ePhotosynthesis: ePhotosynthesis::ValueSetEnum< M, PT > Class Template Reference
ePhotosynthesis::ValueSetEnum< M, PT > Class Template Reference
#include <enums.hpp>
Public Member Functions
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > all
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > static_value_flags
Static Public Member Functions
static std::string error_prefix ()
static std::string getName (const Type &x)
static std::string getName (const Type &x, const std::string &defaultV)
static Type fromName (const std::string &x)
static double getDefault (const Type &x)
static double getDefault (const Type &x, const double &defaultV)
static double getDefaultC3 (const Type &x)
static double getDefaultC3 (const Type &x, const double &defaultV)
static std::string getGlymaid (const Type &x)
static std::string getGlymaid (const Type &x, const std::string &defaultV)
static Type fromGlymaid (const std::string &x)
static Type getAlias (const std::string &x)
static Type getAlias (const std::string &x, const Type &defaultV)
static std::string getDocs (const Type &x)
static std::string getDocs (const Type &x, const std::string &defaultV)
static Type fromDocs (const std::string &x)
static int getValueFlag (const Type &x)
static bool isSkipped (const Type &x)
static void checkSkipped (const Type &x, const std::string &context="")
static void checkNotSkipped (const Type &x, const std::string &context="")
static std::size_t countSkipped ()
static std::size_t countValueFlags ()
static std::vector< Type > listSkipped ()
static void clearSkipped ()
static void clearValueFlags ()
static void addSkipped (const Type &x)
static void addValueFlags (const Type &x, const int &y)
static void removeSkipped (const Type &x)
static void removeValueFlags (const Type &x)
static void addMultipleValueFlags (const std::map< Type, int > &x)
static void removeMultipleValueFlags (const std::map< Type, int > &x)
static int getStaticValueFlag (const Type &x)
static bool isConstant (const Type &x)
static bool isCalculated (const Type &x)
static bool isNonvector (const Type &x)
static bool isResetone (const Type &x)
static bool isInitonce (const Type &x)
static void checkConstant (const Type &x, const std::string &context="")
static void checkCalculated (const Type &x, const std::string &context="")
static void checkNonvector (const Type &x, const std::string &context="")
static void checkResetone (const Type &x, const std::string &context="")
static void checkInitonce (const Type &x, const std::string &context="")
static void checkNotConstant (const Type &x, const std::string &context="")
static void checkNotCalculated (const Type &x, const std::string &context="")
static void checkNotNonvector (const Type &x, const std::string &context="")
static void checkNotResetone (const Type &x, const std::string &context="")
static void checkNotInitonce (const Type &x, const std::string &context="")
static std::size_t countConstant ()
static std::size_t countCalculated ()
static std::size_t countNonvector ()
static std::size_t countResetone ()
static std::size_t countInitonce ()
static std::size_t countStaticValueFlags ()
static std::vector< Type > listConstant ()
static std::vector< Type > listCalculated ()
static std::vector< Type > listNonvector ()
static std::vector< Type > listResetone ()
static std::vector< Type > listInitonce ()
Static Public Attributes
static const MODULE module
static const PARAM_TYPE param_type
static const std::vector< Type > all
static const std::map< Type, std::string > names
static const std::map< Type, double > defaults
static const std::map< Type, double > defaults_C3
static const std::map< Type, std::string > glymaids
static const std::map< std::string, Type > aliases
static const std::map< Type, std::string > docs
static std::map< Type, int > value_flags
static const std::map< Type, int > static_value_flags
Detailed Description
template<MODULE M, PARAM_TYPE PT>
class ePhotosynthesis::ValueSetEnum< M, PT >
Definition at line 28 of file enums.hpp.
Member Function Documentation
addMultipleValueFlags()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::addMultipleValueFlags (const std::map< Type, int > & x) static
Add multiple elements to value_flags if they are not already present
Parameters
[in] x Elements to add
Definition at line 257 of file enums.cpp.
References addValueFlags().
addSkipped()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::addSkipped (const Type & x) static
Add an element to value_flags if it is not already present
Parameters
[in] x Key to add
Definition at line 225 of file enums.cpp.
addValueFlags()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::addValueFlags (const Type & x, const int & y) static
Add an element to value_flags if it is not already present
Parameters
[in] x Key to add
y Value to add for x
Definition at line 237 of file enums.cpp.
Referenced by addMultipleValueFlags().
aliases() [1/73]
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::aliases
Definition at line 104 of file enums_COND.cpp.
aliases() [2/73]
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::aliases
Definition at line 155 of file enums_COND.cpp.
aliases() [3/73]
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::aliases
Definition at line 177 of file enums_COND.cpp.
aliases() [4/73]
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::aliases
Definition at line 199 of file enums_COND.cpp.
aliases() [5/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::aliases
Definition at line 227 of file enums_COND.cpp.
aliases() [6/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::aliases
Definition at line 320 of file enums_COND.cpp.
aliases() [7/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::aliases
Definition at line 401 of file enums_COND.cpp.
aliases() [8/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::aliases
Definition at line 487 of file enums_COND.cpp.
aliases() [9/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::aliases
Definition at line 518 of file enums_COND.cpp.
aliases() [10/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::aliases
Definition at line 540 of file enums_COND.cpp.
aliases() [11/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::aliases
Definition at line 598 of file enums_COND.cpp.
aliases() [12/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::aliases
Definition at line 646 of file enums_COND.cpp.
aliases() [13/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::aliases
Definition at line 685 of file enums_COND.cpp.
aliases() [14/73]
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::aliases
Definition at line 748 of file enums_COND.cpp.
aliases() [15/73]
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::aliases
Definition at line 785 of file enums_COND.cpp.
aliases() [16/73]
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::aliases
Definition at line 817 of file enums_COND.cpp.
aliases() [17/73]
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::aliases
Definition at line 17 of file enums_KE.cpp.
aliases() [18/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::aliases
Definition at line 39 of file enums_KE.cpp.
aliases() [19/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::aliases
Definition at line 61 of file enums_KE.cpp.
aliases() [20/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::aliases
Definition at line 83 of file enums_KE.cpp.
aliases() [21/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::aliases
Definition at line 105 of file enums_KE.cpp.
aliases() [22/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::aliases
Definition at line 157 of file enums_KE.cpp.
aliases() [23/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::aliases
Definition at line 183 of file enums_KE.cpp.
aliases() [24/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::aliases
Definition at line 205 of file enums_KE.cpp.
aliases() [25/73]
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::aliases
Definition at line 227 of file enums_KE.cpp.
aliases() [26/73]
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::aliases
Definition at line 249 of file enums_KE.cpp.
aliases() [27/73]
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::aliases
Definition at line 54 of file enums_MOD.cpp.
aliases() [28/73]
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::aliases
Definition at line 89 of file enums_MOD.cpp.
aliases() [29/73]
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::aliases
Definition at line 111 of file enums_MOD.cpp.
aliases() [30/73]
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::aliases
Definition at line 133 of file enums_MOD.cpp.
aliases() [31/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::aliases
Definition at line 173 of file enums_MOD.cpp.
aliases() [32/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::aliases
Definition at line 217 of file enums_MOD.cpp.
aliases() [33/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::aliases
Definition at line 502 of file enums_MOD.cpp.
aliases() [34/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::aliases
Definition at line 1207 of file enums_MOD.cpp.
aliases() [35/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::aliases
Definition at line 1428 of file enums_MOD.cpp.
aliases() [36/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::aliases
Definition at line 1450 of file enums_MOD.cpp.
aliases() [37/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::aliases
Definition at line 1484 of file enums_MOD.cpp.
aliases() [38/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::aliases
Definition at line 1538 of file enums_MOD.cpp.
aliases() [39/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::aliases
Definition at line 1583 of file enums_MOD.cpp.
aliases() [40/73]
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::aliases
Definition at line 1962 of file enums_MOD.cpp.
aliases() [41/73]
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::aliases
Definition at line 2112 of file enums_MOD.cpp.
aliases() [42/73]
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::aliases
Definition at line 2150 of file enums_MOD.cpp.
aliases() [43/73]
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::aliases
Definition at line 56 of file enums_POOL.cpp.
aliases() [44/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::aliases
Definition at line 110 of file enums_POOL.cpp.
aliases() [45/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::aliases
Definition at line 141 of file enums_POOL.cpp.
aliases() [46/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::aliases
Definition at line 166 of file enums_POOL.cpp.
aliases() [47/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::aliases
Definition at line 188 of file enums_POOL.cpp.
aliases() [48/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::aliases
Definition at line 288 of file enums_POOL.cpp.
aliases() [49/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::aliases
Definition at line 384 of file enums_POOL.cpp.
aliases() [50/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::aliases
Definition at line 424 of file enums_POOL.cpp.
aliases() [51/73]
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::aliases
Definition at line 463 of file enums_POOL.cpp.
aliases() [52/73]
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::aliases
Definition at line 488 of file enums_POOL.cpp.
aliases() [53/73]
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::aliases
Definition at line 131 of file enums_RC.cpp.
aliases() [54/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::aliases
Definition at line 197 of file enums_RC.cpp.
aliases() [55/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::aliases
Definition at line 285 of file enums_RC.cpp.
aliases() [56/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::aliases
Definition at line 503 of file enums_RC.cpp.
aliases() [57/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::aliases
Definition at line 922 of file enums_RC.cpp.
aliases() [58/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::aliases
Definition at line 1082 of file enums_RC.cpp.
aliases() [59/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::aliases
Definition at line 1135 of file enums_RC.cpp.
aliases() [60/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::aliases
Definition at line 1192 of file enums_RC.cpp.
aliases() [61/73]
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::aliases
Definition at line 1393 of file enums_RC.cpp.
aliases() [62/73]
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::aliases
Definition at line 1486 of file enums_RC.cpp.
aliases() [63/73]
const std::map< std::string, typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::aliases
Definition at line 104 of file enums_VARS.cpp.
aliases() [64/73]
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::aliases
Definition at line 113 of file enums_VEL.cpp.
aliases() [65/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::aliases
Definition at line 135 of file enums_VEL.cpp.
aliases() [66/73]
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::aliases
Definition at line 334 of file enums_VEL.cpp.
aliases() [67/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::aliases
Definition at line 437 of file enums_VEL.cpp.
aliases() [68/73]
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::aliases
Definition at line 519 of file enums_VEL.cpp.
aliases() [69/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::aliases
Definition at line 577 of file enums_VEL.cpp.
aliases() [70/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::aliases
Definition at line 608 of file enums_VEL.cpp.
aliases() [71/73]
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::aliases
Definition at line 651 of file enums_VEL.cpp.
aliases() [72/73]
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::aliases
Definition at line 721 of file enums_VEL.cpp.
aliases() [73/73]
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::aliases
Definition at line 783 of file enums_VEL.cpp.
all() [1/73]
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::all
Definition at line 7 of file enums_COND.cpp.
all() [2/73]
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::all
Definition at line 145 of file enums_COND.cpp.
all() [3/73]
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::all
Definition at line 167 of file enums_COND.cpp.
all() [4/73]
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::all
Definition at line 189 of file enums_COND.cpp.
all() [5/73]
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::all
Definition at line 211 of file enums_COND.cpp.
all() [6/73]
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::all
Definition at line 241 of file enums_COND.cpp.
all() [7/73]
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::all
Definition at line 355 of file enums_COND.cpp.
all() [8/73]
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::all
Definition at line 427 of file enums_COND.cpp.
all() [9/73]
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::all
Definition at line 508 of file enums_COND.cpp.
all() [10/73]
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::all
Definition at line 530 of file enums_COND.cpp.
all() [11/73]
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::all
Definition at line 552 of file enums_COND.cpp.
all() [12/73]
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::all
Definition at line 630 of file enums_COND.cpp.
all() [13/73]
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::all
Definition at line 660 of file enums_COND.cpp.
all() [14/73]
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::all
Definition at line 702 of file enums_COND.cpp.
all() [15/73]
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::all
Definition at line 760 of file enums_COND.cpp.
all() [16/73]
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::all
Definition at line 807 of file enums_COND.cpp.
all() [17/73]
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::all
Definition at line 7 of file enums_KE.cpp.
all() [18/73]
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::all
Definition at line 29 of file enums_KE.cpp.
all() [19/73]
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::all
Definition at line 51 of file enums_KE.cpp.
all() [20/73]
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::all
Definition at line 73 of file enums_KE.cpp.
all() [21/73]
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::all
Definition at line 95 of file enums_KE.cpp.
all() [22/73]
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::all
Definition at line 117 of file enums_KE.cpp.
all() [23/73]
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::all
Definition at line 173 of file enums_KE.cpp.
all() [24/73]
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::all
Definition at line 195 of file enums_KE.cpp.
all() [25/73]
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::all
Definition at line 217 of file enums_KE.cpp.
all() [26/73]
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::all
Definition at line 239 of file enums_KE.cpp.
all() [27/73]
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::all
Definition at line 7 of file enums_MOD.cpp.
all() [28/73]
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::all
Definition at line 79 of file enums_MOD.cpp.
all() [29/73]
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::all
Definition at line 101 of file enums_MOD.cpp.
all() [30/73]
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::all
Definition at line 123 of file enums_MOD.cpp.
all() [31/73]
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::all
Definition at line 145 of file enums_MOD.cpp.
all() [32/73]
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::all
Definition at line 197 of file enums_MOD.cpp.
all() [33/73]
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::all
Definition at line 231 of file enums_MOD.cpp.
all() [34/73]
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::all
Definition at line 570 of file enums_MOD.cpp.
all() [35/73]
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::all
Definition at line 1418 of file enums_MOD.cpp.
all() [36/73]
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::all
Definition at line 1440 of file enums_MOD.cpp.
all() [37/73]
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::all
Definition at line 1462 of file enums_MOD.cpp.
all() [38/73]
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::all
Definition at line 1504 of file enums_MOD.cpp.
all() [39/73]
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::all
Definition at line 1562 of file enums_MOD.cpp.
all() [40/73]
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::all
Definition at line 1599 of file enums_MOD.cpp.
all() [41/73]
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::all
Definition at line 2072 of file enums_MOD.cpp.
all() [42/73]
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::all
Definition at line 2140 of file enums_MOD.cpp.
all() [43/73]
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::all
Definition at line 7 of file enums_POOL.cpp.
all() [44/73]
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::all
Definition at line 94 of file enums_POOL.cpp.
all() [45/73]
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::all
Definition at line 122 of file enums_POOL.cpp.
all() [46/73]
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::all
Definition at line 156 of file enums_POOL.cpp.
all() [47/73]
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::all
Definition at line 178 of file enums_POOL.cpp.
all() [48/73]
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::all
Definition at line 200 of file enums_POOL.cpp.
all() [49/73]
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::all
Definition at line 347 of file enums_POOL.cpp.
all() [50/73]
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::all
Definition at line 396 of file enums_POOL.cpp.
all() [51/73]
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::all
Definition at line 441 of file enums_POOL.cpp.
all() [52/73]
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::all
Definition at line 478 of file enums_POOL.cpp.
all() [53/73]
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::all
Definition at line 7 of file enums_RC.cpp.
all() [54/73]
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::all
Definition at line 187 of file enums_RC.cpp.
all() [55/73]
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::all
Definition at line 209 of file enums_RC.cpp.
all() [56/73]
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::all
Definition at line 319 of file enums_RC.cpp.
all() [57/73]
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::all
Definition at line 573 of file enums_RC.cpp.
all() [58/73]
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::all
Definition at line 1033 of file enums_RC.cpp.
all() [59/73]
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::all
Definition at line 1110 of file enums_RC.cpp.
all() [60/73]
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::all
Definition at line 1149 of file enums_RC.cpp.
all() [61/73]
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::all
Definition at line 1215 of file enums_RC.cpp.
all() [62/73]
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::all
Definition at line 1461 of file enums_RC.cpp.
all() [63/73]
const std::vector< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::all
Definition at line 7 of file enums_VARS.cpp.
all() [64/73]
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::all
Definition at line 7 of file enums_VEL.cpp.
all() [65/73]
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::all
Definition at line 125 of file enums_VEL.cpp.
all() [66/73]
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::all
Definition at line 147 of file enums_VEL.cpp.
all() [67/73]
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::all
Definition at line 394 of file enums_VEL.cpp.
all() [68/73]
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::all
Definition at line 449 of file enums_VEL.cpp.
all() [69/73]
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::all
Definition at line 531 of file enums_VEL.cpp.
all() [70/73]
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::all
Definition at line 589 of file enums_VEL.cpp.
all() [71/73]
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::all
Definition at line 620 of file enums_VEL.cpp.
all() [72/73]
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::all
Definition at line 663 of file enums_VEL.cpp.
all() [73/73]
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::all
Definition at line 749 of file enums_VEL.cpp.
checkCalculated()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkCalculated (const Type & x, const std::string & context = "") static
Throw an error if a key is not in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 321 of file enums.cpp.
References error_prefix(), isCalculated(), and names.
checkConstant()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkConstant (const Type & x, const std::string & context = "") static
Throw an error if a key is not in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 315 of file enums.cpp.
References error_prefix(), isConstant(), and names.
checkInitonce()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkInitonce (const Type & x, const std::string & context = "") static
Throw an error if a key is not in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 339 of file enums.cpp.
References error_prefix(), isInitonce(), and names.
checkNonvector()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkNonvector (const Type & x, const std::string & context = "") static
Throw an error if a key is not in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 327 of file enums.cpp.
References error_prefix(), isNonvector(), and names.
checkNotCalculated()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkNotCalculated (const Type & x, const std::string & context = "") static
Throw an error if a key is in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 351 of file enums.cpp.
checkNotConstant()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkNotConstant (const Type & x, const std::string & context = "") static
Throw an error if a key is in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 345 of file enums.cpp.
References isConstant().
checkNotInitonce()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkNotInitonce (const Type & x, const std::string & context = "") static
Throw an error if a key is in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 369 of file enums.cpp.
References error_prefix(), isInitonce(), and names.
checkNotNonvector()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkNotNonvector (const Type & x, const std::string & context = "") static
Throw an error if a key is in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 357 of file enums.cpp.
References error_prefix(), isNonvector(), and names.
checkNotResetone()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkNotResetone (const Type & x, const std::string & context = "") static
Throw an error if a key is in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 363 of file enums.cpp.
References error_prefix(), isResetone(), and names.
checkNotSkipped()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkNotSkipped (const Type & x, const std::string & context = "") static
Throw an error if a key is in value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 181 of file enums.cpp.
checkResetone()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkResetone (const Type & x, const std::string & context = "") static
Throw an error if a key is not in static_value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 333 of file enums.cpp.
References error_prefix(), isResetone(), and names.
checkSkipped()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::checkSkipped (const Type & x, const std::string & context = "") static
Throw an error if a key is not in value_flags
Parameters
[in] x Key to check
[in] context String describing context that should be used in the error message
Definition at line 175 of file enums.cpp.
References isSkipped().
clearSkipped()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::clearSkipped () static
Remove all VALUE_FLAG_SKIPPED flags from value_flags
Definition at line 214 of file enums.cpp.
clearValueFlags()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::clearValueFlags () static
Remove all entries from value_flags
Definition at line 221 of file enums.cpp.
countCalculated()
template<MODULE M, PARAM_TYPE PT> std::size_t ePhotosynthesis::ValueSetEnum< M, PT >::countCalculated () static
Get the number of elements in static_value_flags with STATIC_VALUE_FLAG_CALC set.
Returns
Number of elements with STATIC_VALUE_FLAG_CALC set.
Definition at line 385 of file enums.cpp.
countConstant()
template<MODULE M, PARAM_TYPE PT> std::size_t ePhotosynthesis::ValueSetEnum< M, PT >::countConstant () static
Get the number of elements in static_value_flags with STATIC_VALUE_FLAG_CONST set.
Returns
Number of elements with STATIC_VALUE_FLAG_CONST set.
Definition at line 375 of file enums.cpp.
countInitonce()
template<MODULE M, PARAM_TYPE PT> std::size_t ePhotosynthesis::ValueSetEnum< M, PT >::countInitonce () static
Get the number of elements in static_value_flags with STATIC_VALUE_FLAG_INIT_ONCE set.
Returns
Number of elements with STATIC_VALUE_FLAG_INIT_ONCE set.
Definition at line 415 of file enums.cpp.
References ePhotosynthesis::STATIC_VALUE_FLAG_INIT_ONCE, and static_value_flags.
countNonvector()
template<MODULE M, PARAM_TYPE PT> std::size_t ePhotosynthesis::ValueSetEnum< M, PT >::countNonvector () static
Get the number of elements in static_value_flags with STATIC_VALUE_FLAG_NON_VECTOR set.
Returns
Number of elements with STATIC_VALUE_FLAG_NON_VECTOR set.
Definition at line 395 of file enums.cpp.
References ePhotosynthesis::STATIC_VALUE_FLAG_NON_VECTOR, and static_value_flags.
countResetone()
template<MODULE M, PARAM_TYPE PT> std::size_t ePhotosynthesis::ValueSetEnum< M, PT >::countResetone () static
Get the number of elements in static_value_flags with STATIC_VALUE_FLAG_RESET_ONE set.
Returns
Number of elements with STATIC_VALUE_FLAG_RESET_ONE set.
Definition at line 405 of file enums.cpp.
References ePhotosynthesis::STATIC_VALUE_FLAG_RESET_ONE, and static_value_flags.
countSkipped()
template<MODULE M, PARAM_TYPE PT> std::size_t ePhotosynthesis::ValueSetEnum< M, PT >::countSkipped () static
Get the number of elements in value_flags with VALUE_FLAG_SKIPPED set.
Returns
Number of elements with VALUE_FLAG_SKIPPED set.
Definition at line 187 of file enums.cpp.
countStaticValueFlags()
template<MODULE M, PARAM_TYPE PT> std::size_t ePhotosynthesis::ValueSetEnum< M, PT >::countStaticValueFlags () static
Get the number of elements in static_value_flags.
Returns
Number of elements.
Definition at line 425 of file enums.cpp.
References static_value_flags.
countValueFlags()
template<MODULE M, PARAM_TYPE PT> std::size_t ePhotosynthesis::ValueSetEnum< M, PT >::countValueFlags () static
Get the number of elements in value_flags.
Returns
Number of elements.
Definition at line 197 of file enums.cpp.
References value_flags.
defaults() [1/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::defaults
Definition at line 69 of file enums_COND.cpp.
defaults() [2/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::defaults
Definition at line 149 of file enums_COND.cpp.
defaults() [3/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::defaults
Definition at line 171 of file enums_COND.cpp.
defaults() [4/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::defaults
Definition at line 193 of file enums_COND.cpp.
defaults() [5/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::defaults
Definition at line 219 of file enums_COND.cpp.
defaults() [6/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::defaults
Definition at line 291 of file enums_COND.cpp.
defaults() [7/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::defaults
Definition at line 383 of file enums_COND.cpp.
defaults() [8/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::defaults
Definition at line 463 of file enums_COND.cpp.
defaults() [9/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::defaults
Definition at line 512 of file enums_COND.cpp.
defaults() [10/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::defaults
Definition at line 534 of file enums_COND.cpp.
defaults() [11/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::defaults
Definition at line 580 of file enums_COND.cpp.
defaults() [12/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::defaults
Definition at line 638 of file enums_COND.cpp.
defaults() [13/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::defaults
Definition at line 674 of file enums_COND.cpp.
defaults() [14/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::defaults
Definition at line 724 of file enums_COND.cpp.
defaults() [15/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::defaults
Definition at line 774 of file enums_COND.cpp.
defaults() [16/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::defaults
Definition at line 811 of file enums_COND.cpp.
defaults() [17/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::defaults
Definition at line 11 of file enums_KE.cpp.
defaults() [18/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::defaults
Definition at line 33 of file enums_KE.cpp.
defaults() [19/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::defaults
Definition at line 55 of file enums_KE.cpp.
defaults() [20/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::defaults
Definition at line 77 of file enums_KE.cpp.
defaults() [21/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::defaults
Definition at line 99 of file enums_KE.cpp.
defaults() [22/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::defaults
Definition at line 141 of file enums_KE.cpp.
defaults() [23/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::defaults
Definition at line 177 of file enums_KE.cpp.
defaults() [24/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::defaults
Definition at line 199 of file enums_KE.cpp.
defaults() [25/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::defaults
Definition at line 221 of file enums_KE.cpp.
defaults() [26/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::defaults
Definition at line 243 of file enums_KE.cpp.
defaults() [27/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::defaults
Definition at line 29 of file enums_MOD.cpp.
defaults() [28/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::defaults
Definition at line 83 of file enums_MOD.cpp.
defaults() [29/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::defaults
Definition at line 105 of file enums_MOD.cpp.
defaults() [30/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::defaults
Definition at line 127 of file enums_MOD.cpp.
defaults() [31/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::defaults
Definition at line 161 of file enums_MOD.cpp.
defaults() [32/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::defaults
Definition at line 205 of file enums_MOD.cpp.
defaults() [33/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::defaults
Definition at line 389 of file enums_MOD.cpp.
defaults() [34/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::defaults
Definition at line 924 of file enums_MOD.cpp.
defaults() [35/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::defaults
Definition at line 1422 of file enums_MOD.cpp.
defaults() [36/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::defaults
Definition at line 1444 of file enums_MOD.cpp.
defaults() [37/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::defaults
Definition at line 1474 of file enums_MOD.cpp.
defaults() [38/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::defaults
Definition at line 1524 of file enums_MOD.cpp.
defaults() [39/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::defaults
Definition at line 1572 of file enums_MOD.cpp.
defaults() [40/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::defaults
Definition at line 1781 of file enums_MOD.cpp.
defaults() [41/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::defaults
Definition at line 2096 of file enums_MOD.cpp.
defaults() [42/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::defaults
Definition at line 2144 of file enums_MOD.cpp.
defaults() [43/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::defaults
Definition at line 37 of file enums_POOL.cpp.
defaults() [44/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::defaults
Definition at line 102 of file enums_POOL.cpp.
defaults() [45/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::defaults
Definition at line 132 of file enums_POOL.cpp.
defaults() [46/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::defaults
Definition at line 160 of file enums_POOL.cpp.
defaults() [47/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::defaults
Definition at line 182 of file enums_POOL.cpp.
defaults() [48/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::defaults
Definition at line 256 of file enums_POOL.cpp.
defaults() [49/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::defaults
Definition at line 369 of file enums_POOL.cpp.
defaults() [50/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::defaults
Definition at line 412 of file enums_POOL.cpp.
defaults() [51/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::defaults
Definition at line 453 of file enums_POOL.cpp.
defaults() [52/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::defaults
Definition at line 482 of file enums_POOL.cpp.
defaults() [53/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::defaults
Definition at line 87 of file enums_RC.cpp.
defaults() [54/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::defaults
Definition at line 191 of file enums_RC.cpp.
defaults() [55/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::defaults
Definition at line 257 of file enums_RC.cpp.
defaults() [56/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::defaults
Definition at line 439 of file enums_RC.cpp.
defaults() [57/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::defaults
Definition at line 803 of file enums_RC.cpp.
defaults() [58/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::defaults
Definition at line 1063 of file enums_RC.cpp.
defaults() [59/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::defaults
Definition at line 1124 of file enums_RC.cpp.
defaults() [60/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::defaults
Definition at line 1175 of file enums_RC.cpp.
defaults() [61/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::defaults
Definition at line 1331 of file enums_RC.cpp.
defaults() [62/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::defaults
Definition at line 1475 of file enums_RC.cpp.
defaults() [63/73]
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::defaults
Definition at line 69 of file enums_VARS.cpp.
defaults() [64/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::defaults
Definition at line 75 of file enums_VEL.cpp.
defaults() [65/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::defaults
Definition at line 129 of file enums_VEL.cpp.
defaults() [66/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::defaults
Definition at line 269 of file enums_VEL.cpp.
defaults() [67/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::defaults
Definition at line 420 of file enums_VEL.cpp.
defaults() [68/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::defaults
Definition at line 493 of file enums_VEL.cpp.
defaults() [69/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::defaults
Definition at line 559 of file enums_VEL.cpp.
defaults() [70/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::defaults
Definition at line 599 of file enums_VEL.cpp.
defaults() [71/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::defaults
Definition at line 638 of file enums_VEL.cpp.
defaults() [72/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::defaults
Definition at line 699 of file enums_VEL.cpp.
defaults() [73/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::defaults
Definition at line 769 of file enums_VEL.cpp.
defaults_C3() [1/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::defaults_C3
Definition at line 100 of file enums_COND.cpp.
defaults_C3() [2/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::defaults_C3
Definition at line 151 of file enums_COND.cpp.
defaults_C3() [3/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::defaults_C3
Definition at line 173 of file enums_COND.cpp.
defaults_C3() [4/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::defaults_C3
Definition at line 195 of file enums_COND.cpp.
defaults_C3() [5/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::defaults_C3
Definition at line 223 of file enums_COND.cpp.
defaults_C3() [6/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::defaults_C3
Definition at line 316 of file enums_COND.cpp.
defaults_C3() [7/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::defaults_C3
Definition at line 397 of file enums_COND.cpp.
defaults_C3() [8/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::defaults_C3
Definition at line 481 of file enums_COND.cpp.
defaults_C3() [9/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::defaults_C3
Definition at line 514 of file enums_COND.cpp.
defaults_C3() [10/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::defaults_C3
Definition at line 536 of file enums_COND.cpp.
defaults_C3() [11/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::defaults_C3
Definition at line 594 of file enums_COND.cpp.
defaults_C3() [12/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::defaults_C3
Definition at line 642 of file enums_COND.cpp.
defaults_C3() [13/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::defaults_C3
Definition at line 681 of file enums_COND.cpp.
defaults_C3() [14/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::defaults_C3
Definition at line 735 of file enums_COND.cpp.
defaults_C3() [15/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::defaults_C3
Definition at line 781 of file enums_COND.cpp.
defaults_C3() [16/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::defaults_C3
Definition at line 813 of file enums_COND.cpp.
defaults_C3() [17/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::defaults_C3
Definition at line 13 of file enums_KE.cpp.
defaults_C3() [18/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::defaults_C3
Definition at line 35 of file enums_KE.cpp.
defaults_C3() [19/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::defaults_C3
Definition at line 57 of file enums_KE.cpp.
defaults_C3() [20/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::defaults_C3
Definition at line 79 of file enums_KE.cpp.
defaults_C3() [21/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::defaults_C3
Definition at line 101 of file enums_KE.cpp.
defaults_C3() [22/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::defaults_C3
Definition at line 153 of file enums_KE.cpp.
defaults_C3() [23/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::defaults_C3
Definition at line 179 of file enums_KE.cpp.
defaults_C3() [24/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::defaults_C3
Definition at line 201 of file enums_KE.cpp.
defaults_C3() [25/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::defaults_C3
Definition at line 223 of file enums_KE.cpp.
defaults_C3() [26/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::defaults_C3
Definition at line 245 of file enums_KE.cpp.
defaults_C3() [27/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::defaults_C3
Definition at line 40 of file enums_MOD.cpp.
defaults_C3() [28/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::defaults_C3
Definition at line 85 of file enums_MOD.cpp.
defaults_C3() [29/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::defaults_C3
Definition at line 107 of file enums_MOD.cpp.
defaults_C3() [30/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::defaults_C3
Definition at line 129 of file enums_MOD.cpp.
defaults_C3() [31/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::defaults_C3
Definition at line 169 of file enums_MOD.cpp.
defaults_C3() [32/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::defaults_C3
Definition at line 209 of file enums_MOD.cpp.
defaults_C3() [33/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::defaults_C3
Definition at line 468 of file enums_MOD.cpp.
defaults_C3() [34/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::defaults_C3
Definition at line 1101 of file enums_MOD.cpp.
defaults_C3() [35/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::defaults_C3
Definition at line 1424 of file enums_MOD.cpp.
defaults_C3() [36/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::defaults_C3
Definition at line 1446 of file enums_MOD.cpp.
defaults_C3() [37/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::defaults_C3
Definition at line 1480 of file enums_MOD.cpp.
defaults_C3() [38/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::defaults_C3
Definition at line 1534 of file enums_MOD.cpp.
defaults_C3() [39/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::defaults_C3
Definition at line 1577 of file enums_MOD.cpp.
defaults_C3() [40/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::defaults_C3
Definition at line 1872 of file enums_MOD.cpp.
defaults_C3() [41/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::defaults_C3
Definition at line 2108 of file enums_MOD.cpp.
defaults_C3() [42/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::defaults_C3
Definition at line 2146 of file enums_MOD.cpp.
defaults_C3() [43/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::defaults_C3
Definition at line 52 of file enums_POOL.cpp.
defaults_C3() [44/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::defaults_C3
Definition at line 106 of file enums_POOL.cpp.
defaults_C3() [45/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::defaults_C3
Definition at line 137 of file enums_POOL.cpp.
defaults_C3() [46/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::defaults_C3
Definition at line 162 of file enums_POOL.cpp.
defaults_C3() [47/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::defaults_C3
Definition at line 184 of file enums_POOL.cpp.
defaults_C3() [48/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::defaults_C3
Definition at line 284 of file enums_POOL.cpp.
defaults_C3() [49/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::defaults_C3
Definition at line 380 of file enums_POOL.cpp.
defaults_C3() [50/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::defaults_C3
Definition at line 420 of file enums_POOL.cpp.
defaults_C3() [51/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::defaults_C3
Definition at line 459 of file enums_POOL.cpp.
defaults_C3() [52/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::defaults_C3
Definition at line 484 of file enums_POOL.cpp.
defaults_C3() [53/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::defaults_C3
Definition at line 127 of file enums_RC.cpp.
defaults_C3() [54/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::defaults_C3
Definition at line 193 of file enums_RC.cpp.
defaults_C3() [55/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::defaults_C3
Definition at line 281 of file enums_RC.cpp.
defaults_C3() [56/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::defaults_C3
Definition at line 499 of file enums_RC.cpp.
defaults_C3() [57/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::defaults_C3
Definition at line 918 of file enums_RC.cpp.
defaults_C3() [58/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::defaults_C3
Definition at line 1078 of file enums_RC.cpp.
defaults_C3() [59/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::defaults_C3
Definition at line 1131 of file enums_RC.cpp.
defaults_C3() [60/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::defaults_C3
Definition at line 1188 of file enums_RC.cpp.
defaults_C3() [61/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::defaults_C3
Definition at line 1389 of file enums_RC.cpp.
defaults_C3() [62/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::defaults_C3
Definition at line 1482 of file enums_RC.cpp.
defaults_C3() [63/73]
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::defaults_C3
Definition at line 100 of file enums_VARS.cpp.
defaults_C3() [64/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::defaults_C3
Definition at line 109 of file enums_VEL.cpp.
defaults_C3() [65/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::defaults_C3
Definition at line 131 of file enums_VEL.cpp.
defaults_C3() [66/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::defaults_C3
Definition at line 330 of file enums_VEL.cpp.
defaults_C3() [67/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::defaults_C3
Definition at line 433 of file enums_VEL.cpp.
defaults_C3() [68/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::defaults_C3
Definition at line 515 of file enums_VEL.cpp.
defaults_C3() [69/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::defaults_C3
Definition at line 573 of file enums_VEL.cpp.
defaults_C3() [70/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::defaults_C3
Definition at line 604 of file enums_VEL.cpp.
defaults_C3() [71/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::defaults_C3
Definition at line 647 of file enums_VEL.cpp.
defaults_C3() [72/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::defaults_C3
Definition at line 717 of file enums_VEL.cpp.
defaults_C3() [73/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::defaults_C3
Definition at line 779 of file enums_VEL.cpp.
docs() [1/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::docs
Definition at line 106 of file enums_COND.cpp.
docs() [2/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::docs
Definition at line 157 of file enums_COND.cpp.
docs() [3/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::docs
Definition at line 179 of file enums_COND.cpp.
docs() [4/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::docs
Definition at line 201 of file enums_COND.cpp.
docs() [5/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::docs
Definition at line 229 of file enums_COND.cpp.
docs() [6/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::docs
Definition at line 322 of file enums_COND.cpp.
docs() [7/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::docs
Definition at line 403 of file enums_COND.cpp.
docs() [8/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::docs
Definition at line 489 of file enums_COND.cpp.
docs() [9/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::docs
Definition at line 520 of file enums_COND.cpp.
docs() [10/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::docs
Definition at line 542 of file enums_COND.cpp.
docs() [11/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::docs
Definition at line 600 of file enums_COND.cpp.
docs() [12/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::docs
Definition at line 648 of file enums_COND.cpp.
docs() [13/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::docs
Definition at line 687 of file enums_COND.cpp.
docs() [14/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::docs
Definition at line 750 of file enums_COND.cpp.
docs() [15/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::docs
Definition at line 787 of file enums_COND.cpp.
docs() [16/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::docs
Definition at line 819 of file enums_COND.cpp.
docs() [17/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::docs
Definition at line 19 of file enums_KE.cpp.
docs() [18/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::docs
Definition at line 41 of file enums_KE.cpp.
docs() [19/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::docs
Definition at line 63 of file enums_KE.cpp.
docs() [20/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::docs
Definition at line 85 of file enums_KE.cpp.
docs() [21/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::docs
Definition at line 107 of file enums_KE.cpp.
docs() [22/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::docs
Definition at line 159 of file enums_KE.cpp.
docs() [23/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::docs
Definition at line 185 of file enums_KE.cpp.
docs() [24/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::docs
Definition at line 207 of file enums_KE.cpp.
docs() [25/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::docs
Definition at line 229 of file enums_KE.cpp.
docs() [26/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::docs
Definition at line 251 of file enums_KE.cpp.
docs() [27/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::docs
Definition at line 56 of file enums_MOD.cpp.
docs() [28/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::docs
Definition at line 91 of file enums_MOD.cpp.
docs() [29/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::docs
Definition at line 113 of file enums_MOD.cpp.
docs() [30/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::docs
Definition at line 135 of file enums_MOD.cpp.
docs() [31/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::docs
Definition at line 175 of file enums_MOD.cpp.
docs() [32/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::docs
Definition at line 219 of file enums_MOD.cpp.
docs() [33/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::docs
Definition at line 504 of file enums_MOD.cpp.
docs() [34/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::docs
Definition at line 1209 of file enums_MOD.cpp.
docs() [35/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::docs
Definition at line 1430 of file enums_MOD.cpp.
docs() [36/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::docs
Definition at line 1452 of file enums_MOD.cpp.
docs() [37/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::docs
Definition at line 1486 of file enums_MOD.cpp.
docs() [38/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::docs
Definition at line 1540 of file enums_MOD.cpp.
docs() [39/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::docs
Definition at line 1585 of file enums_MOD.cpp.
docs() [40/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::docs
Definition at line 1964 of file enums_MOD.cpp.
docs() [41/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::docs
Definition at line 2114 of file enums_MOD.cpp.
docs() [42/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::docs
Definition at line 2152 of file enums_MOD.cpp.
docs() [43/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::docs
Definition at line 71 of file enums_POOL.cpp.
docs() [44/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::docs
Definition at line 112 of file enums_POOL.cpp.
docs() [45/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::docs
Definition at line 143 of file enums_POOL.cpp.
docs() [46/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::docs
Definition at line 168 of file enums_POOL.cpp.
docs() [47/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::docs
Definition at line 190 of file enums_POOL.cpp.
docs() [48/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::docs
Definition at line 290 of file enums_POOL.cpp.
docs() [49/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::docs
Definition at line 386 of file enums_POOL.cpp.
docs() [50/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::docs
Definition at line 426 of file enums_POOL.cpp.
docs() [51/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::docs
Definition at line 465 of file enums_POOL.cpp.
docs() [52/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::docs
Definition at line 490 of file enums_POOL.cpp.
docs() [53/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::docs
Definition at line 133 of file enums_RC.cpp.
docs() [54/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::docs
Definition at line 199 of file enums_RC.cpp.
docs() [55/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::docs
Definition at line 287 of file enums_RC.cpp.
docs() [56/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::docs
Definition at line 505 of file enums_RC.cpp.
docs() [57/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::docs
Definition at line 924 of file enums_RC.cpp.
docs() [58/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::docs
Definition at line 1084 of file enums_RC.cpp.
docs() [59/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::docs
Definition at line 1137 of file enums_RC.cpp.
docs() [60/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::docs
Definition at line 1194 of file enums_RC.cpp.
docs() [61/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::docs
Definition at line 1395 of file enums_RC.cpp.
docs() [62/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::docs
Definition at line 1488 of file enums_RC.cpp.
docs() [63/73]
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::docs
Definition at line 114 of file enums_VARS.cpp.
docs() [64/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::docs
Definition at line 115 of file enums_VEL.cpp.
docs() [65/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::docs
Definition at line 137 of file enums_VEL.cpp.
docs() [66/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::docs
Definition at line 336 of file enums_VEL.cpp.
docs() [67/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::docs
Definition at line 439 of file enums_VEL.cpp.
docs() [68/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::docs
Definition at line 521 of file enums_VEL.cpp.
docs() [69/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::docs
Definition at line 579 of file enums_VEL.cpp.
docs() [70/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::docs
Definition at line 610 of file enums_VEL.cpp.
docs() [71/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::docs
Definition at line 653 of file enums_VEL.cpp.
docs() [72/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::docs
Definition at line 723 of file enums_VEL.cpp.
docs() [73/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::docs
Definition at line 785 of file enums_VEL.cpp.
error_prefix()
template<MODULE M, PARAM_TYPE PT> std::string ePhotosynthesis::ValueSetEnum< M, PT >::error_prefix () static
Get a prefix for errors describing the class
Returns
Prefix
Definition at line 9 of file enums.cpp.
References ePhotosynthesis::utils::get_enum_names< MODULE >(), ePhotosynthesis::utils::get_enum_names< PARAM_TYPE >(), module, and param_type.
Referenced by checkCalculated(), checkConstant(), checkInitonce(), checkNonvector(), checkNotInitonce(), checkNotNonvector(), checkNotResetone(), and checkResetone().
fromDocs()
template<MODULE M, PARAM_TYPE PT> ValueSetEnum< M, PT >::Type ePhotosynthesis::ValueSetEnum< M, PT >::fromDocs (const std::string & x) static
Get the enum key corresponding to a docs values
Parameters
[in] x Value to get key for
Returns
Key
Definition at line 148 of file enums.cpp.
References docs.
fromGlymaid()
template<MODULE M, PARAM_TYPE PT> ValueSetEnum< M, PT >::Type ePhotosynthesis::ValueSetEnum< M, PT >::fromGlymaid (const std::string & x) static
Get the enum key corresponding to a glymaid values
Parameters
[in] x Value to get key for
Returns
Key
Definition at line 101 of file enums.cpp.
References glymaids.
fromName()
template<MODULE M, PARAM_TYPE PT> ValueSetEnum< M, PT >::Type ePhotosynthesis::ValueSetEnum< M, PT >::fromName (const std::string & x) static
Get the enum key corresponding to a name values
Parameters
[in] x Value to get key for
Returns
Key
Definition at line 36 of file enums.cpp.
References names.
getAlias() [1/2]
template<MODULE M, PARAM_TYPE PT> ValueSetEnum< M, PT >::Type ePhotosynthesis::ValueSetEnum< M, PT >::getAlias (const std::string & x) static
Get the alias value corresponding to an enum key
Parameters
[in] x Key to get value for
Returns
Value
Definition at line 112 of file enums.cpp.
getAlias() [2/2]
template<MODULE M, PARAM_TYPE PT> static Type ePhotosynthesis::ValueSetEnum< M, PT >::getAlias (const std::string & x, const Type & defaultV) static
Get the alias value corresponding to an enum key
Parameters
[in] x Key to get value for
[in] defaultV Value to return if x is not present
Returns
Value
getDefault() [1/2]
template<MODULE M, PARAM_TYPE PT> static double ePhotosynthesis::ValueSetEnum< M, PT >::getDefault (const Type & x) static
Get the default value corresponding to an enum key
Parameters
[in] x Key to get value for
Returns
Value
getDefault() [2/2]
template<MODULE M, PARAM_TYPE PT> static double ePhotosynthesis::ValueSetEnum< M, PT >::getDefault (const Type & x, const double & defaultV) static
Get the default value corresponding to an enum key
Parameters
[in] x Key to get value for
[in] defaultV Value to return if x is not present
Returns
Value
getDefaultC3() [1/2]
template<MODULE M, PARAM_TYPE PT> static double ePhotosynthesis::ValueSetEnum< M, PT >::getDefaultC3 (const Type & x) static
Get the defaultc3 value corresponding to an enum key
Parameters
[in] x Key to get value for
Returns
Value
getDefaultC3() [2/2]
template<MODULE M, PARAM_TYPE PT> static double ePhotosynthesis::ValueSetEnum< M, PT >::getDefaultC3 (const Type & x, const double & defaultV) static
Get the defaultc3 value corresponding to an enum key
Parameters
[in] x Key to get value for
[in] defaultV Value to return if x is not present
Returns
Value
getDocs() [1/2]
template<MODULE M, PARAM_TYPE PT> static std::string ePhotosynthesis::ValueSetEnum< M, PT >::getDocs (const Type & x) static
Get the docs value corresponding to an enum key
Parameters
[in] x Key to get value for
Returns
Value
getDocs() [2/2]
template<MODULE M, PARAM_TYPE PT> static std::string ePhotosynthesis::ValueSetEnum< M, PT >::getDocs (const Type & x, const std::string & defaultV) static
Get the docs value corresponding to an enum key
Parameters
[in] x Key to get value for
[in] defaultV Value to return if x is not present
Returns
Value
getGlymaid() [1/2]
template<MODULE M, PARAM_TYPE PT> static std::string ePhotosynthesis::ValueSetEnum< M, PT >::getGlymaid (const Type & x) static
Get the glymaid value corresponding to an enum key
Parameters
[in] x Key to get value for
Returns
Value
getGlymaid() [2/2]
template<MODULE M, PARAM_TYPE PT> static std::string ePhotosynthesis::ValueSetEnum< M, PT >::getGlymaid (const Type & x, const std::string & defaultV) static
Get the glymaid value corresponding to an enum key
Parameters
[in] x Key to get value for
[in] defaultV Value to return if x is not present
Returns
Value
getName() [1/2]
template<MODULE M, PARAM_TYPE PT> static std::string ePhotosynthesis::ValueSetEnum< M, PT >::getName (const Type & x) static
Get the name value corresponding to an enum key
Parameters
[in] x Key to get value for
Returns
Value
getName() [2/2]
template<MODULE M, PARAM_TYPE PT> static std::string ePhotosynthesis::ValueSetEnum< M, PT >::getName (const Type & x, const std::string & defaultV) static
Get the name value corresponding to an enum key
Parameters
[in] x Key to get value for
[in] defaultV Value to return if x is not present
Returns
Value
getStaticValueFlag()
template<MODULE M, PARAM_TYPE PT> int ePhotosynthesis::ValueSetEnum< M, PT >::getStaticValueFlag (const Type & x) static
Get the staticvalueflag value corresponding to an enum key
Parameters
[in] x Key to get value for
Returns
Value
Definition at line 271 of file enums.cpp.
References names, and static_value_flags.
getValueFlag()
template<MODULE M, PARAM_TYPE PT> int ePhotosynthesis::ValueSetEnum< M, PT >::getValueFlag (const Type & x) static
Get the valueflag value corresponding to an enum key
Parameters
[in] x Key to get value for
Returns
Value
Definition at line 159 of file enums.cpp.
References names, and value_flags.
glymaids() [1/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::glymaids
Definition at line 102 of file enums_COND.cpp.
glymaids() [2/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::glymaids
Definition at line 153 of file enums_COND.cpp.
glymaids() [3/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::glymaids
Definition at line 175 of file enums_COND.cpp.
glymaids() [4/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::glymaids
Definition at line 197 of file enums_COND.cpp.
glymaids() [5/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::glymaids
Definition at line 225 of file enums_COND.cpp.
glymaids() [6/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::glymaids
Definition at line 318 of file enums_COND.cpp.
glymaids() [7/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::glymaids
Definition at line 399 of file enums_COND.cpp.
glymaids() [8/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::glymaids
Definition at line 485 of file enums_COND.cpp.
glymaids() [9/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::glymaids
Definition at line 516 of file enums_COND.cpp.
glymaids() [10/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::glymaids
Definition at line 538 of file enums_COND.cpp.
glymaids() [11/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::glymaids
Definition at line 596 of file enums_COND.cpp.
glymaids() [12/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::glymaids
Definition at line 644 of file enums_COND.cpp.
glymaids() [13/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::glymaids
Definition at line 683 of file enums_COND.cpp.
glymaids() [14/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::glymaids
Definition at line 746 of file enums_COND.cpp.
glymaids() [15/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::glymaids
Definition at line 783 of file enums_COND.cpp.
glymaids() [16/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::glymaids
Definition at line 815 of file enums_COND.cpp.
glymaids() [17/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::glymaids
Definition at line 15 of file enums_KE.cpp.
glymaids() [18/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::glymaids
Definition at line 37 of file enums_KE.cpp.
glymaids() [19/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::glymaids
Definition at line 59 of file enums_KE.cpp.
glymaids() [20/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::glymaids
Definition at line 81 of file enums_KE.cpp.
glymaids() [21/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::glymaids
Definition at line 103 of file enums_KE.cpp.
glymaids() [22/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::glymaids
Definition at line 155 of file enums_KE.cpp.
glymaids() [23/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::glymaids
Definition at line 181 of file enums_KE.cpp.
glymaids() [24/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::glymaids
Definition at line 203 of file enums_KE.cpp.
glymaids() [25/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::glymaids
Definition at line 225 of file enums_KE.cpp.
glymaids() [26/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::glymaids
Definition at line 247 of file enums_KE.cpp.
glymaids() [27/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::glymaids
Definition at line 48 of file enums_MOD.cpp.
glymaids() [28/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::glymaids
Definition at line 87 of file enums_MOD.cpp.
glymaids() [29/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::glymaids
Definition at line 109 of file enums_MOD.cpp.
glymaids() [30/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::glymaids
Definition at line 131 of file enums_MOD.cpp.
glymaids() [31/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::glymaids
Definition at line 171 of file enums_MOD.cpp.
glymaids() [32/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::glymaids
Definition at line 213 of file enums_MOD.cpp.
glymaids() [33/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::glymaids
Definition at line 492 of file enums_MOD.cpp.
glymaids() [34/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::glymaids
Definition at line 1197 of file enums_MOD.cpp.
glymaids() [35/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::glymaids
Definition at line 1426 of file enums_MOD.cpp.
glymaids() [36/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::glymaids
Definition at line 1448 of file enums_MOD.cpp.
glymaids() [37/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::glymaids
Definition at line 1482 of file enums_MOD.cpp.
glymaids() [38/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::glymaids
Definition at line 1536 of file enums_MOD.cpp.
glymaids() [39/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::glymaids
Definition at line 1581 of file enums_MOD.cpp.
glymaids() [40/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::glymaids
Definition at line 1955 of file enums_MOD.cpp.
glymaids() [41/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::glymaids
Definition at line 2110 of file enums_MOD.cpp.
glymaids() [42/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::glymaids
Definition at line 2148 of file enums_MOD.cpp.
glymaids() [43/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::glymaids
Definition at line 54 of file enums_POOL.cpp.
glymaids() [44/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::glymaids
Definition at line 108 of file enums_POOL.cpp.
glymaids() [45/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::glymaids
Definition at line 139 of file enums_POOL.cpp.
glymaids() [46/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::glymaids
Definition at line 164 of file enums_POOL.cpp.
glymaids() [47/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::glymaids
Definition at line 186 of file enums_POOL.cpp.
glymaids() [48/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::glymaids
Definition at line 286 of file enums_POOL.cpp.
glymaids() [49/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::glymaids
Definition at line 382 of file enums_POOL.cpp.
glymaids() [50/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::glymaids
Definition at line 422 of file enums_POOL.cpp.
glymaids() [51/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::glymaids
Definition at line 461 of file enums_POOL.cpp.
glymaids() [52/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::glymaids
Definition at line 486 of file enums_POOL.cpp.
glymaids() [53/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::glymaids
Definition at line 129 of file enums_RC.cpp.
glymaids() [54/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::glymaids
Definition at line 195 of file enums_RC.cpp.
glymaids() [55/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::glymaids
Definition at line 283 of file enums_RC.cpp.
glymaids() [56/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::glymaids
Definition at line 501 of file enums_RC.cpp.
glymaids() [57/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::glymaids
Definition at line 920 of file enums_RC.cpp.
glymaids() [58/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::glymaids
Definition at line 1080 of file enums_RC.cpp.
glymaids() [59/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::glymaids
Definition at line 1133 of file enums_RC.cpp.
glymaids() [60/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::glymaids
Definition at line 1190 of file enums_RC.cpp.
glymaids() [61/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::glymaids
Definition at line 1391 of file enums_RC.cpp.
glymaids() [62/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::glymaids
Definition at line 1484 of file enums_RC.cpp.
glymaids() [63/73]
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::glymaids
Definition at line 102 of file enums_VARS.cpp.
glymaids() [64/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::glymaids
Definition at line 111 of file enums_VEL.cpp.
glymaids() [65/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::glymaids
Definition at line 133 of file enums_VEL.cpp.
glymaids() [66/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::glymaids
Definition at line 332 of file enums_VEL.cpp.
glymaids() [67/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::glymaids
Definition at line 435 of file enums_VEL.cpp.
glymaids() [68/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::glymaids
Definition at line 517 of file enums_VEL.cpp.
glymaids() [69/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::glymaids
Definition at line 575 of file enums_VEL.cpp.
glymaids() [70/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::glymaids
Definition at line 606 of file enums_VEL.cpp.
glymaids() [71/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::glymaids
Definition at line 649 of file enums_VEL.cpp.
glymaids() [72/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::glymaids
Definition at line 719 of file enums_VEL.cpp.
glymaids() [73/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::glymaids
Definition at line 781 of file enums_VEL.cpp.
isCalculated()
template<MODULE M, PARAM_TYPE PT> bool ePhotosynthesis::ValueSetEnum< M, PT >::isCalculated (const Type & x) static
Check if a key is in static_value_flags
Parameters
[in] x Key to check
Returns
true if x is present, false otherwise
Definition at line 287 of file enums.cpp.
References static_value_flags.
Referenced by checkCalculated().
isConstant()
template<MODULE M, PARAM_TYPE PT> bool ePhotosynthesis::ValueSetEnum< M, PT >::isConstant (const Type & x) static
Check if a key is in static_value_flags
Parameters
[in] x Key to check
Returns
true if x is present, false otherwise
Definition at line 280 of file enums.cpp.
References static_value_flags.
Referenced by checkConstant(), and checkNotConstant().
isInitonce()
template<MODULE M, PARAM_TYPE PT> bool ePhotosynthesis::ValueSetEnum< M, PT >::isInitonce (const Type & x) static
Check if a key is in static_value_flags
Parameters
[in] x Key to check
Returns
true if x is present, false otherwise
Definition at line 308 of file enums.cpp.
References static_value_flags.
Referenced by checkInitonce(), and checkNotInitonce().
isNonvector()
template<MODULE M, PARAM_TYPE PT> bool ePhotosynthesis::ValueSetEnum< M, PT >::isNonvector (const Type & x) static
Check if a key is in static_value_flags
Parameters
[in] x Key to check
Returns
true if x is present, false otherwise
Definition at line 294 of file enums.cpp.
References static_value_flags.
Referenced by checkNonvector(), and checkNotNonvector().
isResetone()
template<MODULE M, PARAM_TYPE PT> bool ePhotosynthesis::ValueSetEnum< M, PT >::isResetone (const Type & x) static
Check if a key is in static_value_flags
Parameters
[in] x Key to check
Returns
true if x is present, false otherwise
Definition at line 301 of file enums.cpp.
References static_value_flags.
Referenced by checkNotResetone(), and checkResetone().
isSkipped()
template<MODULE M, PARAM_TYPE PT> bool ePhotosynthesis::ValueSetEnum< M, PT >::isSkipped (const Type & x) static
Check if a key is in value_flags
Parameters
[in] x Key to check
Returns
true if x is present, false otherwise
Definition at line 168 of file enums.cpp.
References value_flags.
Referenced by checkSkipped().
listCalculated()
template<MODULE M, PARAM_TYPE PT> std::vector< typename ValueSetEnum< M, PT >::Type > ePhotosynthesis::ValueSetEnum< M, PT >::listCalculated () static
Get the set of elements in static_value_flags with STATIC_VALUE_FLAG_CALC set.
Returns
Set of elements.
Definition at line 442 of file enums.cpp.
References ePhotosynthesis::STATIC_VALUE_FLAG_CALC, and static_value_flags.
listConstant()
template<MODULE M, PARAM_TYPE PT> std::vector< typename ValueSetEnum< M, PT >::Type > ePhotosynthesis::ValueSetEnum< M, PT >::listConstant () static
Get the set of elements in static_value_flags with STATIC_VALUE_FLAG_CONST set.
Returns
Set of elements.
Definition at line 431 of file enums.cpp.
References ePhotosynthesis::STATIC_VALUE_FLAG_CONST, and static_value_flags.
listInitonce()
template<MODULE M, PARAM_TYPE PT> std::vector< typename ValueSetEnum< M, PT >::Type > ePhotosynthesis::ValueSetEnum< M, PT >::listInitonce () static
Get the set of elements in static_value_flags with STATIC_VALUE_FLAG_INIT_ONCE set.
Returns
Set of elements.
Definition at line 475 of file enums.cpp.
References ePhotosynthesis::STATIC_VALUE_FLAG_INIT_ONCE, and static_value_flags.
listNonvector()
template<MODULE M, PARAM_TYPE PT> std::vector< typename ValueSetEnum< M, PT >::Type > ePhotosynthesis::ValueSetEnum< M, PT >::listNonvector () static
Get the set of elements in static_value_flags with STATIC_VALUE_FLAG_NON_VECTOR set.
Returns
Set of elements.
Definition at line 453 of file enums.cpp.
References ePhotosynthesis::STATIC_VALUE_FLAG_NON_VECTOR, and static_value_flags.
listResetone()
template<MODULE M, PARAM_TYPE PT> std::vector< typename ValueSetEnum< M, PT >::Type > ePhotosynthesis::ValueSetEnum< M, PT >::listResetone () static
Get the set of elements in static_value_flags with STATIC_VALUE_FLAG_RESET_ONE set.
Returns
Set of elements.
Definition at line 464 of file enums.cpp.
References ePhotosynthesis::STATIC_VALUE_FLAG_RESET_ONE, and static_value_flags.
listSkipped()
template<MODULE M, PARAM_TYPE PT> std::vector< typename ValueSetEnum< M, PT >::Type > ePhotosynthesis::ValueSetEnum< M, PT >::listSkipped () static
Get the set of elements in value_flags with VALUE_FLAG_SKIPPED set.
Returns
Set of elements.
Definition at line 203 of file enums.cpp.
names() [1/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::names
Definition at line 38 of file enums_COND.cpp.
names() [2/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::names
Definition at line 147 of file enums_COND.cpp.
names() [3/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::names
Definition at line 169 of file enums_COND.cpp.
names() [4/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::names
Definition at line 191 of file enums_COND.cpp.
names() [5/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::names
Definition at line 215 of file enums_COND.cpp.
names() [6/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::names
Definition at line 266 of file enums_COND.cpp.
names() [7/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::names
Definition at line 369 of file enums_COND.cpp.
names() [8/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::names
Definition at line 445 of file enums_COND.cpp.
names() [9/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::names
Definition at line 510 of file enums_COND.cpp.
names() [10/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::names
Definition at line 532 of file enums_COND.cpp.
names() [11/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::names
Definition at line 566 of file enums_COND.cpp.
names() [12/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::names
Definition at line 634 of file enums_COND.cpp.
names() [13/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::names
Definition at line 667 of file enums_COND.cpp.
names() [14/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::names
Definition at line 713 of file enums_COND.cpp.
names() [15/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::names
Definition at line 767 of file enums_COND.cpp.
names() [16/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::names
Definition at line 809 of file enums_COND.cpp.
names() [17/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::names
Definition at line 9 of file enums_KE.cpp.
names() [18/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::names
Definition at line 31 of file enums_KE.cpp.
names() [19/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::names
Definition at line 53 of file enums_KE.cpp.
names() [20/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::names
Definition at line 75 of file enums_KE.cpp.
names() [21/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::names
Definition at line 97 of file enums_KE.cpp.
names() [22/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::names
Definition at line 129 of file enums_KE.cpp.
names() [23/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::names
Definition at line 175 of file enums_KE.cpp.
names() [24/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::names
Definition at line 197 of file enums_KE.cpp.
names() [25/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::names
Definition at line 219 of file enums_KE.cpp.
names() [26/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::names
Definition at line 241 of file enums_KE.cpp.
names() [27/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::names
Definition at line 18 of file enums_MOD.cpp.
names() [28/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::names
Definition at line 81 of file enums_MOD.cpp.
names() [29/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::names
Definition at line 103 of file enums_MOD.cpp.
names() [30/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::names
Definition at line 125 of file enums_MOD.cpp.
names() [31/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::names
Definition at line 153 of file enums_MOD.cpp.
names() [32/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::names
Definition at line 201 of file enums_MOD.cpp.
names() [33/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::names
Definition at line 310 of file enums_MOD.cpp.
names() [34/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::names
Definition at line 747 of file enums_MOD.cpp.
names() [35/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::names
Definition at line 1420 of file enums_MOD.cpp.
names() [36/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::names
Definition at line 1442 of file enums_MOD.cpp.
names() [37/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::names
Definition at line 1468 of file enums_MOD.cpp.
names() [38/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::names
Definition at line 1514 of file enums_MOD.cpp.
names() [39/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::names
Definition at line 1567 of file enums_MOD.cpp.
names() [40/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::names
Definition at line 1690 of file enums_MOD.cpp.
names() [41/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::names
Definition at line 2084 of file enums_MOD.cpp.
names() [42/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::names
Definition at line 2142 of file enums_MOD.cpp.
names() [43/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::names
Definition at line 22 of file enums_POOL.cpp.
names() [44/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::names
Definition at line 98 of file enums_POOL.cpp.
names() [45/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::names
Definition at line 127 of file enums_POOL.cpp.
names() [46/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::names
Definition at line 158 of file enums_POOL.cpp.
names() [47/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::names
Definition at line 180 of file enums_POOL.cpp.
names() [48/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::names
Definition at line 228 of file enums_POOL.cpp.
names() [49/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::names
Definition at line 358 of file enums_POOL.cpp.
names() [50/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::names
Definition at line 404 of file enums_POOL.cpp.
names() [51/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::names
Definition at line 447 of file enums_POOL.cpp.
names() [52/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::names
Definition at line 480 of file enums_POOL.cpp.
names() [53/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::names
Definition at line 47 of file enums_RC.cpp.
names() [54/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::names
Definition at line 189 of file enums_RC.cpp.
names() [55/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::names
Definition at line 233 of file enums_RC.cpp.
names() [56/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::names
Definition at line 379 of file enums_RC.cpp.
names() [57/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::names
Definition at line 688 of file enums_RC.cpp.
names() [58/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::names
Definition at line 1048 of file enums_RC.cpp.
names() [59/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::names
Definition at line 1117 of file enums_RC.cpp.
names() [60/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::names
Definition at line 1162 of file enums_RC.cpp.
names() [61/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::names
Definition at line 1273 of file enums_RC.cpp.
names() [62/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::names
Definition at line 1468 of file enums_RC.cpp.
names() [63/73]
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::names
Definition at line 38 of file enums_VARS.cpp.
names() [64/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::names
Definition at line 41 of file enums_VEL.cpp.
names() [65/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::names
Definition at line 127 of file enums_VEL.cpp.
names() [66/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::names
Definition at line 208 of file enums_VEL.cpp.
names() [67/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::names
Definition at line 407 of file enums_VEL.cpp.
names() [68/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::names
Definition at line 471 of file enums_VEL.cpp.
names() [69/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::names
Definition at line 545 of file enums_VEL.cpp.
names() [70/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::names
Definition at line 594 of file enums_VEL.cpp.
names() [71/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::names
Definition at line 629 of file enums_VEL.cpp.
names() [72/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::names
Definition at line 681 of file enums_VEL.cpp.
names() [73/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::names
Definition at line 759 of file enums_VEL.cpp.
removeMultipleValueFlags()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::removeMultipleValueFlags (const std::map< Type, int > & x) static
Remove multiple elements to value_flags if they are not already present
Parameters
[in] x Elements to add
Definition at line 264 of file enums.cpp.
References removeValueFlags().
removeSkipped()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::removeSkipped (const Type & x) static
Remove an element from value_flags
Parameters
[in] x Key to remove
Definition at line 241 of file enums.cpp.
References value_flags.
removeValueFlags()
template<MODULE M, PARAM_TYPE PT> void ePhotosynthesis::ValueSetEnum< M, PT >::removeValueFlags (const Type & x) static
Remove an element from value_flags
Parameters
[in] x Key to remove
Definition at line 249 of file enums.cpp.
Referenced by removeMultipleValueFlags().
static_value_flags() [1/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::static_value_flags
Definition at line 139 of file enums_COND.cpp.
static_value_flags() [2/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::static_value_flags
Definition at line 161 of file enums_COND.cpp.
static_value_flags() [3/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::static_value_flags
Definition at line 183 of file enums_COND.cpp.
static_value_flags() [4/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::static_value_flags
Definition at line 205 of file enums_COND.cpp.
static_value_flags() [5/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::static_value_flags
Definition at line 235 of file enums_COND.cpp.
static_value_flags() [6/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::static_value_flags
Definition at line 349 of file enums_COND.cpp.
static_value_flags() [7/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::static_value_flags
Definition at line 419 of file enums_COND.cpp.
static_value_flags() [8/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::static_value_flags
Definition at line 498 of file enums_COND.cpp.
static_value_flags() [9/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::static_value_flags
Definition at line 524 of file enums_COND.cpp.
static_value_flags() [10/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::static_value_flags
Definition at line 546 of file enums_COND.cpp.
static_value_flags() [11/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::static_value_flags
Definition at line 616 of file enums_COND.cpp.
static_value_flags() [12/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::static_value_flags
Definition at line 654 of file enums_COND.cpp.
static_value_flags() [13/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::static_value_flags
Definition at line 696 of file enums_COND.cpp.
static_value_flags() [14/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::static_value_flags
Definition at line 754 of file enums_COND.cpp.
static_value_flags() [15/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::static_value_flags
Definition at line 796 of file enums_COND.cpp.
static_value_flags() [16/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::static_value_flags
Definition at line 823 of file enums_COND.cpp.
static_value_flags() [17/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::static_value_flags
Definition at line 23 of file enums_KE.cpp.
static_value_flags() [18/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::static_value_flags
Definition at line 45 of file enums_KE.cpp.
static_value_flags() [19/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::static_value_flags
Definition at line 67 of file enums_KE.cpp.
static_value_flags() [20/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::static_value_flags
Definition at line 89 of file enums_KE.cpp.
static_value_flags() [21/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::static_value_flags
Definition at line 111 of file enums_KE.cpp.
static_value_flags() [22/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::static_value_flags
Definition at line 165 of file enums_KE.cpp.
static_value_flags() [23/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::static_value_flags
Definition at line 189 of file enums_KE.cpp.
static_value_flags() [24/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::static_value_flags
Definition at line 211 of file enums_KE.cpp.
static_value_flags() [25/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::static_value_flags
Definition at line 233 of file enums_KE.cpp.
static_value_flags() [26/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::static_value_flags
Definition at line 255 of file enums_KE.cpp.
static_value_flags() [27/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::static_value_flags
Definition at line 69 of file enums_MOD.cpp.
static_value_flags() [28/73]
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::static_value_flags
Definition at line 95 of file enums_MOD.cpp.
static_value_flags() [29/73]
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::static_value_flags
Definition at line 117 of file enums_MOD.cpp.
static_value_flags() [30/73]
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::static_value_flags
Definition at line 139 of file enums_MOD.cpp.
static_value_flags() [31/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::static_value_flags
Definition at line 185 of file enums_MOD.cpp.
static_value_flags() [32/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::static_value_flags
Definition at line 225 of file enums_MOD.cpp.
static_value_flags() [33/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::static_value_flags
Definition at line 551 of file enums_MOD.cpp.
static_value_flags() [34/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::static_value_flags
Definition at line 1370 of file enums_MOD.cpp.
static_value_flags() [35/73]
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::static_value_flags
Definition at line 1434 of file enums_MOD.cpp.
static_value_flags() [36/73]
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::static_value_flags
Definition at line 1456 of file enums_MOD.cpp.
static_value_flags() [37/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::static_value_flags
Definition at line 1494 of file enums_MOD.cpp.
static_value_flags() [38/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::static_value_flags
Definition at line 1552 of file enums_MOD.cpp.
static_value_flags() [39/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::static_value_flags
Definition at line 1591 of file enums_MOD.cpp.
static_value_flags() [40/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::static_value_flags
Definition at line 2054 of file enums_MOD.cpp.
static_value_flags() [41/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::static_value_flags
Definition at line 2128 of file enums_MOD.cpp.
static_value_flags() [42/73]
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::static_value_flags
Definition at line 2156 of file enums_MOD.cpp.
static_value_flags() [43/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::static_value_flags
Definition at line 88 of file enums_POOL.cpp.
static_value_flags() [44/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::static_value_flags
Definition at line 116 of file enums_POOL.cpp.
static_value_flags() [45/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::static_value_flags
Definition at line 150 of file enums_POOL.cpp.
static_value_flags() [46/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::static_value_flags
Definition at line 172 of file enums_POOL.cpp.
static_value_flags() [47/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::static_value_flags
Definition at line 194 of file enums_POOL.cpp.
static_value_flags() [48/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::static_value_flags
Definition at line 318 of file enums_POOL.cpp.
static_value_flags() [49/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::static_value_flags
Definition at line 390 of file enums_POOL.cpp.
static_value_flags() [50/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::static_value_flags
Definition at line 435 of file enums_POOL.cpp.
static_value_flags() [51/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::static_value_flags
Definition at line 472 of file enums_POOL.cpp.
static_value_flags() [52/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::static_value_flags
Definition at line 494 of file enums_POOL.cpp.
static_value_flags() [53/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::static_value_flags
Definition at line 175 of file enums_RC.cpp.
static_value_flags() [54/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::static_value_flags
Definition at line 203 of file enums_RC.cpp.
static_value_flags() [55/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::static_value_flags
Definition at line 313 of file enums_RC.cpp.
static_value_flags() [56/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::static_value_flags
Definition at line 567 of file enums_RC.cpp.
static_value_flags() [57/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::static_value_flags
Definition at line 1027 of file enums_RC.cpp.
static_value_flags() [58/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::static_value_flags
Definition at line 1101 of file enums_RC.cpp.
static_value_flags() [59/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::static_value_flags
Definition at line 1143 of file enums_RC.cpp.
static_value_flags() [60/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::static_value_flags
Definition at line 1209 of file enums_RC.cpp.
static_value_flags() [61/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::static_value_flags
Definition at line 1455 of file enums_RC.cpp.
static_value_flags() [62/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::static_value_flags
Definition at line 1497 of file enums_RC.cpp.
static_value_flags() [63/73]
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::static_value_flags
Definition at line 144 of file enums_VARS.cpp.
static_value_flags() [64/73]
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::static_value_flags
Definition at line 119 of file enums_VEL.cpp.
static_value_flags() [65/73]
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::static_value_flags
Definition at line 141 of file enums_VEL.cpp.
static_value_flags() [66/73]
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::static_value_flags
Definition at line 388 of file enums_VEL.cpp.
static_value_flags() [67/73]
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::static_value_flags
Definition at line 443 of file enums_VEL.cpp.
static_value_flags() [68/73]
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::static_value_flags
Definition at line 525 of file enums_VEL.cpp.
static_value_flags() [69/73]
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::static_value_flags
Definition at line 583 of file enums_VEL.cpp.
static_value_flags() [70/73]
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::static_value_flags
Definition at line 614 of file enums_VEL.cpp.
static_value_flags() [71/73]
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::static_value_flags
Definition at line 657 of file enums_VEL.cpp.
static_value_flags() [72/73]
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::static_value_flags
Definition at line 743 of file enums_VEL.cpp.
static_value_flags() [73/73]
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::static_value_flags
Definition at line 797 of file enums_VEL.cpp.
value_flags() [1/73]
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::value_flags
Definition at line 137 of file enums_COND.cpp.
value_flags() [2/73]
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::value_flags
Definition at line 159 of file enums_COND.cpp.
value_flags() [3/73]
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::value_flags
Definition at line 181 of file enums_COND.cpp.
value_flags() [4/73]
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::value_flags
Definition at line 203 of file enums_COND.cpp.
value_flags() [5/73]
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::value_flags
Definition at line 233 of file enums_COND.cpp.
value_flags() [6/73]
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::value_flags
Definition at line 347 of file enums_COND.cpp.
value_flags() [7/73]
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::value_flags
Definition at line 417 of file enums_COND.cpp.
value_flags() [8/73]
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::value_flags
Definition at line 496 of file enums_COND.cpp.
value_flags() [9/73]
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::value_flags
Definition at line 522 of file enums_COND.cpp.
value_flags() [10/73]
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::value_flags
Definition at line 544 of file enums_COND.cpp.
value_flags() [11/73]
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::value_flags
Definition at line 614 of file enums_COND.cpp.
value_flags() [12/73]
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::value_flags
Definition at line 652 of file enums_COND.cpp.
value_flags() [13/73]
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::value_flags
Definition at line 694 of file enums_COND.cpp.
value_flags() [14/73]
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::value_flags
Definition at line 752 of file enums_COND.cpp.
value_flags() [15/73]
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::value_flags
Definition at line 794 of file enums_COND.cpp.
value_flags() [16/73]
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::value_flags
Definition at line 821 of file enums_COND.cpp.
value_flags() [17/73]
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::value_flags
Definition at line 21 of file enums_KE.cpp.
value_flags() [18/73]
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::value_flags
Definition at line 43 of file enums_KE.cpp.
value_flags() [19/73]
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::value_flags
Definition at line 65 of file enums_KE.cpp.
value_flags() [20/73]
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::value_flags
Definition at line 87 of file enums_KE.cpp.
value_flags() [21/73]
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::value_flags
Definition at line 109 of file enums_KE.cpp.
value_flags() [22/73]
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::value_flags
Definition at line 163 of file enums_KE.cpp.
value_flags() [23/73]
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::value_flags
Definition at line 187 of file enums_KE.cpp.
value_flags() [24/73]
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::value_flags
Definition at line 209 of file enums_KE.cpp.
value_flags() [25/73]
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::value_flags
Definition at line 231 of file enums_KE.cpp.
value_flags() [26/73]
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::value_flags
Definition at line 253 of file enums_KE.cpp.
value_flags() [27/73]
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::value_flags
Definition at line 67 of file enums_MOD.cpp.
value_flags() [28/73]
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::value_flags
Definition at line 93 of file enums_MOD.cpp.
value_flags() [29/73]
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::value_flags
Definition at line 115 of file enums_MOD.cpp.
value_flags() [30/73]
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::value_flags
Definition at line 137 of file enums_MOD.cpp.
value_flags() [31/73]
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::value_flags
Definition at line 183 of file enums_MOD.cpp.
value_flags() [32/73]
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::value_flags
Definition at line 223 of file enums_MOD.cpp.
value_flags() [33/73]
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::value_flags
Definition at line 549 of file enums_MOD.cpp.
value_flags() [34/73]
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::value_flags
Definition at line 1368 of file enums_MOD.cpp.
value_flags() [35/73]
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::value_flags
Definition at line 1432 of file enums_MOD.cpp.
value_flags() [36/73]
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::value_flags
Definition at line 1454 of file enums_MOD.cpp.
value_flags() [37/73]
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::value_flags
Definition at line 1492 of file enums_MOD.cpp.
value_flags() [38/73]
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::value_flags
Definition at line 1550 of file enums_MOD.cpp.
value_flags() [39/73]
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::value_flags
Definition at line 1589 of file enums_MOD.cpp.
value_flags() [40/73]
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::value_flags
Definition at line 2052 of file enums_MOD.cpp.
value_flags() [41/73]
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::value_flags
Definition at line 2126 of file enums_MOD.cpp.
value_flags() [42/73]
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::value_flags
Definition at line 2154 of file enums_MOD.cpp.
value_flags() [43/73]
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::value_flags
Definition at line 86 of file enums_POOL.cpp.
value_flags() [44/73]
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::value_flags
Definition at line 114 of file enums_POOL.cpp.
value_flags() [45/73]
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::value_flags
Definition at line 148 of file enums_POOL.cpp.
value_flags() [46/73]
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::value_flags
Definition at line 170 of file enums_POOL.cpp.
value_flags() [47/73]
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::value_flags
Definition at line 192 of file enums_POOL.cpp.
value_flags() [48/73]
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::value_flags
Definition at line 316 of file enums_POOL.cpp.
value_flags() [49/73]
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::value_flags
Definition at line 388 of file enums_POOL.cpp.
value_flags() [50/73]
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::value_flags
Definition at line 433 of file enums_POOL.cpp.
value_flags() [51/73]
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::value_flags
Definition at line 470 of file enums_POOL.cpp.
value_flags() [52/73]
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::value_flags
Definition at line 492 of file enums_POOL.cpp.
value_flags() [53/73]
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::value_flags
Definition at line 173 of file enums_RC.cpp.
value_flags() [54/73]
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::value_flags
Definition at line 201 of file enums_RC.cpp.
value_flags() [55/73]
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::value_flags
Definition at line 311 of file enums_RC.cpp.
value_flags() [56/73]
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::value_flags
Definition at line 565 of file enums_RC.cpp.
value_flags() [57/73]
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::value_flags
Definition at line 1025 of file enums_RC.cpp.
value_flags() [58/73]
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::value_flags
Definition at line 1099 of file enums_RC.cpp.
value_flags() [59/73]
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::value_flags
Definition at line 1141 of file enums_RC.cpp.
value_flags() [60/73]
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::value_flags
Definition at line 1207 of file enums_RC.cpp.
value_flags() [61/73]
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::value_flags
Definition at line 1453 of file enums_RC.cpp.
value_flags() [62/73]
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::value_flags
Definition at line 1495 of file enums_RC.cpp.
value_flags() [63/73]
std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::value_flags
Definition at line 142 of file enums_VARS.cpp.
value_flags() [64/73]
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::value_flags
Definition at line 117 of file enums_VEL.cpp.
value_flags() [65/73]
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::value_flags
Definition at line 139 of file enums_VEL.cpp.
value_flags() [66/73]
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::value_flags
Definition at line 386 of file enums_VEL.cpp.
value_flags() [67/73]
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::value_flags
Definition at line 441 of file enums_VEL.cpp.
value_flags() [68/73]
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::value_flags
Definition at line 523 of file enums_VEL.cpp.
value_flags() [69/73]
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::value_flags
Definition at line 581 of file enums_VEL.cpp.
value_flags() [70/73]
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::value_flags
Definition at line 612 of file enums_VEL.cpp.
value_flags() [71/73]
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::value_flags
Definition at line 655 of file enums_VEL.cpp.
value_flags() [72/73]
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::value_flags
Definition at line 741 of file enums_VEL.cpp.
value_flags() [73/73]
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::value_flags
Definition at line 795 of file enums_VEL.cpp.
Field Documentation
aliases
template<MODULE M, PARAM_TYPE PT> const std::map<std::string, Type> ePhotosynthesis::ValueSetEnum< M, PT >::aliases static
Aliases for values
Definition at line 42 of file enums.hpp.
Referenced by ePhotosynthesis::Type< MODULE_BF, PARAM_TYPE_COND >::aliases().
all
template<MODULE M, PARAM_TYPE PT> const std::vector<Type> ePhotosynthesis::ValueSetEnum< M, PT >::all static
All enum values
Definition at line 37 of file enums.hpp.
Referenced by ePhotosynthesis::Type< MODULE_BF, PARAM_TYPE_COND >::all().
defaults
template<MODULE M, PARAM_TYPE PT> const std::map<Type, double> ePhotosynthesis::ValueSetEnum< M, PT >::defaults static
Defaults for values
Definition at line 39 of file enums.hpp.
Referenced by ePhotosynthesis::Type< MODULE_BF, PARAM_TYPE_COND >::defaults().
defaults_C3
template<MODULE M, PARAM_TYPE PT> const std::map<Type, double> ePhotosynthesis::ValueSetEnum< M, PT >::defaults_C3 static
Defaults_C3 for values
Definition at line 40 of file enums.hpp.
Referenced by ePhotosynthesis::Type< MODULE_BF, PARAM_TYPE_COND >::defaults_C3().
docs
template<MODULE M, PARAM_TYPE PT> const std::map<Type, std::string> ePhotosynthesis::ValueSetEnum< M, PT >::docs static
Docs for values
Definition at line 43 of file enums.hpp.
Referenced by ePhotosynthesis::Type< MODULE_BF, PARAM_TYPE_COND >::docs(), and fromDocs().
glymaids
template<MODULE M, PARAM_TYPE PT> const std::map<Type, std::string> ePhotosynthesis::ValueSetEnum< M, PT >::glymaids static
Glymaids for values
Definition at line 41 of file enums.hpp.
Referenced by fromGlymaid(), and ePhotosynthesis::Type< MODULE_BF, PARAM_TYPE_COND >::glymaids().
module
template<MODULE M, PARAM_TYPE PT> const MODULE ePhotosynthesis::ValueSetEnum< M, PT >::module static
Definition at line 35 of file enums.hpp.
Referenced by error_prefix().
names
template<MODULE M, PARAM_TYPE PT> const std::map<Type, std::string> ePhotosynthesis::ValueSetEnum< M, PT >::names static
Names for values
Definition at line 38 of file enums.hpp.
Referenced by checkCalculated(), checkConstant(), checkInitonce(), checkNonvector(), checkNotInitonce(), checkNotNonvector(), checkNotResetone(), checkResetone(), fromName(), getStaticValueFlag(), getValueFlag(), and ePhotosynthesis::Type< MODULE_BF, PARAM_TYPE_COND >::names().
param_type
template<MODULE M, PARAM_TYPE PT> const PARAM_TYPE ePhotosynthesis::ValueSetEnum< M, PT >::param_type static
Definition at line 36 of file enums.hpp.
Referenced by error_prefix().
static_value_flags
template<MODULE M, PARAM_TYPE PT> const std::map<Type, int> ePhotosynthesis::ValueSetEnum< M, PT >::static_value_flags static
Static_Value_Flags for values
Definition at line 45 of file enums.hpp.
Referenced by countInitonce(), countNonvector(), countResetone(), countStaticValueFlags(), getStaticValueFlag(), isCalculated(), isConstant(), isInitonce(), isNonvector(), isResetone(), listCalculated(), listConstant(), listInitonce(), listNonvector(), listResetone(), and ePhotosynthesis::Type< MODULE_BF, PARAM_TYPE_COND >::static_value_flags().
value_flags
template<MODULE M, PARAM_TYPE PT> std::map<Type, int> ePhotosynthesis::ValueSetEnum< M, PT >::value_flags static
Value_Flags for values
Definition at line 44 of file enums.hpp.
Referenced by countValueFlags(), getValueFlag(), isSkipped(), removeSkipped(), and ePhotosynthesis::Type< MODULE_BF, PARAM_TYPE_COND >::value_flags().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/enums/enums.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/enums/enums.cpp