ePhotosynthesis: ePhotosynthesis::pool::RROEAPool Class Reference
ePhotosynthesis::pool::RROEAPool Class Reference
#include <RROEAPool.hpp>
Public Member Functions
RROEAPool ()
RROEAPool (const RROEAPool &other)
RROEAPool & operator= (const RROEAPool &other)
Detailed Description
Class for RROEA_Pool data
Definition at line 38 of file RROEAPool.hpp.
Constructor & Destructor Documentation
RROEAPool() [1/2]
ePhotosynthesis::pool::RROEAPool::RROEAPool () inline
Definition at line 41 of file RROEAPool.hpp.
References RROEAPool().
Referenced by operator=(), RROEAPool(), and RROEAPool().
RROEAPool() [2/2]
ePhotosynthesis::pool::RROEAPool::RROEAPool (const RROEAPool & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The RROEAPool object to copy
Definition at line 50 of file RROEAPool.hpp.
References RROEAPool().
Member Function Documentation
operator=()
RROEAPool & ePhotosynthesis::pool::RROEAPool::operator= (const RROEAPool & other) inline
Definition at line 54 of file RROEAPool.hpp.
References RROEAPool().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/pool/RROEAPool.hpp