ePhotosynthesis: ePhotosynthesis::modules::PS Class Reference
ePhotosynthesis::modules::PS Class Reference
#include <PS.hpp>
Static Public Member Functions
static void setParam (const arr &param)
static std::size_t getN ()
Static Private Member Functions
static void _reset (const bool noChildren=false)
Static Private Attributes
static arr Param = {0., 0.}
Detailed Description
Class to for PS related functions and common variables
Definition at line 42 of file PS.hpp.
Member Function Documentation
_reset()
void PS::_reset (const bool noChildren = false) static private
Reset the static member variables to their default values.
Definition at line 607 of file PS_Ini.cpp.
References _reset(), and Param.
Referenced by _reset().
getN()
static std::size_t ePhotosynthesis::modules::PS::getN () inline static
Get the current size of the PS TimeSeries.
Returns
The current size of the TimeSeries.
Definition at line 59 of file PS.hpp.
Referenced by ePhotosynthesis::GenOut().
setParam()
static void ePhotosynthesis::modules::PS::setParam (const arr & param) inline static
Set the initial parameters.
Parameters
param The initial parameters.
Definition at line 50 of file PS.hpp.
References Param, and setParam().
Referenced by setParam().
Field Documentation
Param
arr PS::Param = {0., 0.} static private
Definition at line 183 of file PS.hpp.
Referenced by _reset(), and setParam().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/modules/PS.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/ini/PS_Ini.cpp