ePhotosynthesis: ePhotosynthesis::drivers::trDynaPSDriver Class Reference
ePhotosynthesis::drivers::trDynaPSDriver Class Reference
#include <trDynaPS_Driver.hpp>
Public Member Functions
trDynaPSDriver (Variables *theVars, const double startTime, const double stepSize, const double endTime, const int maxSubsteps, const double atol, const double rtol, const std::size_t para, const double ratio, const bool showWarn=false, const std::vector< std::string > &outVars={})
void setup () override
void getResults () override
Public Member Functions inherited from ePhotosynthesis::drivers::DriverBase< trDynaPSDriver, MODULE_trDynaPS >
void outputParam (const OutputFreq &frequency=OUTPUT_FREQ_NEVER, const std::string &fname_base="", const std::vector< std::string > &vars={}) override
Public Member Functions inherited from ePhotosynthesis::drivers::Driver
arr run ()
void dump (const std::string &filename, const Variables *theVars=nullptr, const ValueSet_t *con=nullptr, const bool is_init=false)
void getOutputVars (Variables *inputVars)
void setOutputVars (const std::vector< std::string > &newVars)
void writeOutputTable (std::ostream &s) const
double getVar (const Variables *inputVars, const std::string &k)
virtual ValueSet_t * currentConditions (realtype *x=nullptr)
virtual arr MB (realtype t, N_Vector u)=0
virtual ~Driver ()
void outputParam (const std::string &fname_init, const std::string &fname_last="", const std::string &fname_step="", const std::vector< std::string > &vars={})
EPHOTO_API const std::map< std::string, double > & getOutput () const
Public Member Functions inherited from ePhotosynthesis::DriverParam
DriverParam ()
DriverParam (const double startTime, const double stepSize, const double endTime, const int maxSubsteps, const double atol, const double rtol, const std::size_t para, const double ratio, const bool showWarn=false, const std::vector< std::string > &outVars={})
Additional Inherited Members
Static Public Member Functions inherited from ePhotosynthesis::drivers::DriverBase< trDynaPSDriver, MODULE_trDynaPS >
static void init (const bool useC3=false)
static void select (const bool x=true)
static void enableC3 (const bool x=true)
static std::string error_prefix ()
Data Fields inherited from ePhotosynthesis::drivers::Driver
arr constraints
std::string fname_vars_init
std::string fname_vars_last
std::string fname_vars_step
std::vector< std::string > param_vars
Data Fields inherited from ePhotosynthesis::DriverParam
double start
double step
double endtime
int maxSubSteps
realtype abstol
realtype reltol
std::size_t ParaNum
double Ratio
std::vector< std::string > outputVars
Static Public Attributes inherited from ePhotosynthesis::drivers::DriverBase< trDynaPSDriver, MODULE_trDynaPS >
static const MODULE module
Static Public Attributes inherited from ePhotosynthesis::drivers::Driver
static EPHOTO_API Variables * inputVars = nullptr
Static Public Attributes inherited from ePhotosynthesis::DriverParam
static EPHOTO_API bool showWarnings = false
Protected Member Functions inherited from ePhotosynthesis::drivers::DriverBase< trDynaPSDriver, MODULE_trDynaPS >
DriverBase (Variables *theVars, const double startTime, const double stepSize, const double endTime, const int maxSubsteps, const double atol, const double rtol, const std::size_t para, const double ratio, const bool showWarn=false, const std::vector< std::string > &outVars={})
Protected Member Functions inherited from ePhotosynthesis::drivers::Driver
Driver (Variables *theVars, const double startTime, const double stepSize, const double endTime, const int maxSubsteps, const double atol, const double rtol, const std::size_t para, const double ratio, const bool showWarn=false, const std::vector< std::string > &outVars={})
Driver (Variables *theVars, const DriverParam &param)
void _dump (realtype t, ValueSet_t *con)
Static Protected Member Functions inherited from ePhotosynthesis::drivers::Driver
static int calculate (realtype t, N_Vector u, N_Vector u_dot, void *user_data)
Protected Attributes inherited from ePhotosynthesis::drivers::Driver
friend CVodeMem
double initialStep
realtype * intermediateRes
arr results
std::map< std::string, double > output
realtype time
CalcData * data
double maxStep
void * cvode_mem
Detailed Description
Class for running trDynaPS with an ODE solver
Definition at line 40 of file trDynaPS_Driver.hpp.
Constructor & Destructor Documentation
trDynaPSDriver()
trDynaPSDriver::trDynaPSDriver (Variables * theVars, const double startTime, const double stepSize, const double endTime, const int maxSubsteps, const double atol, const double rtol, const std::size_t para, const double ratio, const bool showWarn = false, const std::vector< std::string > & outVars = {})
This sets up initial values for the class.
Parameters
[in,out] theVars Instance of the Variables class, which holds global scope variables and intermediate results.
startTime The timestamp to start the solver at. Typically this is 0.
stepSize The optimal step size for the solver to use.
endTime The timestamp to end the calculations.
maxSubsteps The maximum number of sub-iterations to make between steps.
atol The absolute tolerance the ODE solver should use.
rtol The relative tolerance the ODE solver should use.
para Input parameters
ratio Input ratio.
showWarn Whether or not to send solver warnings to stdout. If true then all warning messages are sent. If false, the default, warning messages are not sent, reducing clutter in production output.
outVars Set of variables that should be output by the driver.
Definition at line 41 of file trDynaPS_Drive.cpp.
References ePhotosynthesis::drivers::DriverBase< trDynaPSDriver, MODULE_trDynaPS >::DriverBase(), ePhotosynthesis::drivers::DriverBase< trDynaPSDriver, MODULE_trDynaPS >::init(), ePhotosynthesis::DriverParam::outputVars, and ePhotosynthesis::Variables::useC3.
Member Function Documentation
getResults()
void trDynaPSDriver::getResults () override virtual
Runs the solver one more time on the intermediate results to get the solution at the end time stamp.
Implements ePhotosynthesis::drivers::Driver.
Definition at line 116 of file trDynaPS_Drive.cpp.
References ePhotosynthesis::IniModelCom(), ePhotosynthesis::drivers::Driver::inputVars, ePhotosynthesis::drivers::Driver::intermediateRes, ePhotosynthesis::makeFluxTR(), ePhotosynthesis::drivers::Driver::results, ePhotosynthesis::TargetFunVal(), ePhotosynthesis::drivers::Driver::time, and ePhotosynthesis::zeros().
setup()
void trDynaPSDriver::setup () override virtual
Generate the initial parameter Condition class for the solver to use.
Implements ePhotosynthesis::drivers::Driver.
Definition at line 63 of file trDynaPS_Drive.cpp.
References ePhotosynthesis::drivers::Driver::constraints, ePhotosynthesis::IniModelCom(), ePhotosynthesis::drivers::Driver::inputVars, ePhotosynthesis::ParamSet(), ePhotosynthesis::DriverParam::ParaNum, ePhotosynthesis::DriverParam::Ratio, and ePhotosynthesis::SYSInitial().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/drivers/trDynaPS_Driver.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/drivers/trDynaPS_Drive.cpp