ePhotosynthesis: ePhotosynthesis::drivers Namespace Reference
ePhotosynthesis::drivers Namespace Reference
Data Structures
struct CalcData
class CMDriver
class CVodeMem
class Driver
class DriverBase
class DynaPSDriver
class EPSDriver
class trDynaPSDriver
struct UserData
Functions
UserData * alloc_user_data ()
CalcData * alloc_calc_data ()
EPHOTO_API void select_driver (const DriverType &driverChoice, const bool useC3, const bool x=true)
EPHOTO_API Driver * create_driver (const DriverType &driverChoice, Variables *theVars, const double begintime, const double stepsize, const double stoptime, const int maxSubSteps, const double abstol, const double reltol, const std::size_t para=1, const double ratio=1, const bool showWarn=false, const std::vector< std::string > &outVars={})
EPHOTO_API Driver * create_driver (const DriverType &driverChoice, Variables *theVars, const DriverParam &param)
Variables
template<class T, MODULE M>
const MODULE DriverBase< T, M >::module = M
Function Documentation
alloc_calc_data()
CalcData * ePhotosynthesis::drivers::alloc_calc_data () inline
Create an instance of CalcData.
Returns
New instance of the CalcData structure.
Definition at line 152 of file driver.hpp.
Referenced by ePhotosynthesis::drivers::CVodeMem::cvode_mem_init().
alloc_user_data()
UserData * ePhotosynthesis::drivers::alloc_user_data () inline
Create an instance of UserData
Returns
New instance of the UserData structure.
Definition at line 136 of file driver.hpp.
Referenced by ePhotosynthesis::modules::RedoxReg::_Rate().
create_driver() [1/2]
ePhotosynthesis::drivers::Driver * ePhotosynthesis::drivers::create_driver (const DriverType & driverChoice, Variables * theVars, const double begintime, const double stepsize, const double stoptime, const int maxSubSteps, const double abstol, const double reltol, const std::size_t para = 1, const double ratio = 1, const bool showWarn = false, const std::vector< std::string > & outVars = {})
Definition at line 17 of file drivers.cpp.
References CASE_DRIVER, and SWITCH_DRIVER.
Referenced by ePhotosynthesis::run_simulation().
create_driver() [2/2]
ePhotosynthesis::drivers::Driver * ePhotosynthesis::drivers::create_driver (const DriverType & driverChoice, Variables * theVars, const DriverParam & param)
Definition at line 40 of file drivers.cpp.
References CASE_DRIVER, and SWITCH_DRIVER.
select_driver()
void ePhotosynthesis::drivers::select_driver (const DriverType & driverChoice, const bool useC3, const bool x = true)
Definition at line 5 of file drivers.cpp.
References CASE_DRIVER, and SWITCH_DRIVER.
Referenced by ePhotosynthesis::run_simulation().
Variable Documentation
DriverBase< T, M >::module
template<class T, MODULE M> const MODULE ePhotosynthesis::drivers::DriverBase< T, M >::module = M
Definition at line 438 of file driver.hpp.