ePhotosynthesis: cxxopts::OptionParser Class Reference
cxxopts::OptionParser Class Reference
#include <cxxopts.hpp>
Public Member Functions
OptionParser (const OptionMap &options, const PositionalList &positional, bool allow_unrecognised)
ParseResult parse (int argc, const char *const *argv)
bool consume_positional (const std::string &a, PositionalListIterator &next)
void checked_parse_arg (int argc, const char *const *argv, int &current, const std::shared_ptr< OptionDetails > &value, const std::string &name)
void add_to_option (OptionMap::const_iterator iter, const std::string &option, const std::string &arg)
void parse_option (const std::shared_ptr< OptionDetails > &value, const std::string &name, const std::string &arg="")
void parse_default (const std::shared_ptr< OptionDetails > &details)
Private Member Functions
void finalise_aliases ()
Private Attributes
const OptionMap & m_options
const PositionalList & m_positional
std::vector< KeyValue > m_sequential {}
bool m_allow_unrecognised
ParsedHashMap m_parsed {}
NameHashMap m_keys {}
Detailed Description
Definition at line 1327 of file cxxopts.hpp.
Constructor & Destructor Documentation
OptionParser()
cxxopts::OptionParser::OptionParser (const OptionMap & options, const PositionalList & positional, bool allow_unrecognised) inline
Definition at line 1330 of file cxxopts.hpp.
References m_allow_unrecognised, m_options, and m_positional.
Member Function Documentation
add_to_option()
void cxxopts::OptionParser::add_to_option (OptionMap::const_iterator iter, const std::string & option, const std::string & arg) inline
Definition at line 1825 of file cxxopts.hpp.
References parse_option().
Referenced by consume_positional().
checked_parse_arg()
void cxxopts::OptionParser::checked_parse_arg (int argc, const char *const * argv, int & current, const std::shared_ptr< OptionDetails > & value, const std::string & name) inline
Definition at line 1789 of file cxxopts.hpp.
References parse_option(), cxxopts::throw_or_mimic(), and cxxopts::value().
Referenced by parse().
consume_positional()
bool cxxopts::OptionParser::consume_positional (const std::string & a, PositionalListIterator & next) inline
Definition at line 1832 of file cxxopts.hpp.
References add_to_option(), m_options, m_parsed, m_positional, and cxxopts::throw_or_mimic().
Referenced by parse().
finalise_aliases()
void cxxopts::OptionParser::finalise_aliases () inline private
Definition at line 2052 of file cxxopts.hpp.
References m_keys, m_options, and m_parsed.
Referenced by parse().
parse()
ParseResult cxxopts::OptionParser::parse (int argc, const char *const * argv) inline
Definition at line 1893 of file cxxopts.hpp.
References checked_parse_arg(), consume_positional(), finalise_aliases(), m_allow_unrecognised, m_keys, m_options, m_parsed, m_positional, m_sequential, parse_default(), parse_option(), cxxopts::throw_or_mimic(), and cxxopts::value().
Referenced by cxxopts::Options::parse().
parse_default()
void cxxopts::OptionParser::parse_default (const std::shared_ptr< OptionDetails > & details) inline
Definition at line 1764 of file cxxopts.hpp.
References m_parsed.
Referenced by parse().
parse_option()
void cxxopts::OptionParser::parse_option (const std::shared_ptr< OptionDetails > & value, const std::string & name, const std::string & arg = "") inline
Definition at line 1773 of file cxxopts.hpp.
References m_parsed, m_sequential, and cxxopts::value().
Referenced by add_to_option(), checked_parse_arg(), and parse().
Field Documentation
m_allow_unrecognised
bool cxxopts::OptionParser::m_allow_unrecognised private
Definition at line 1375 of file cxxopts.hpp.
Referenced by OptionParser(), and parse().
m_keys
NameHashMap cxxopts::OptionParser::m_keys {} private
Definition at line 1378 of file cxxopts.hpp.
Referenced by finalise_aliases(), and parse().
m_options
const OptionMap& cxxopts::OptionParser::m_options private
Definition at line 1371 of file cxxopts.hpp.
Referenced by consume_positional(), finalise_aliases(), OptionParser(), and parse().
m_parsed
ParsedHashMap cxxopts::OptionParser::m_parsed {} private
Definition at line 1377 of file cxxopts.hpp.
Referenced by consume_positional(), finalise_aliases(), parse(), parse_default(), and parse_option().
m_positional
const PositionalList& cxxopts::OptionParser::m_positional private
Definition at line 1372 of file cxxopts.hpp.
Referenced by consume_positional(), OptionParser(), and parse().
m_sequential
std::vector<KeyValue> cxxopts::OptionParser::m_sequential {} private
Definition at line 1374 of file cxxopts.hpp.
Referenced by parse(), and parse_option().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/cxxopts.hpp