coverage:
  status:
    project:
      default:   # default is the status check's name, not default settings
        target: auto 
        threshold: 0
        paths: 
          - "src"
          - "bin"
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
