ePhotosynthesis: ePhotosynthesis::conditions::PRCondition Class Reference
ePhotosynthesis::conditions::PRCondition Class Reference
#include <PRCondition.hpp>
Public Member Functions
PRCondition (const arr vec, const std::size_t offset=0)
Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< PRCondition, PS_PRCondition, MODULE_PR >
~ConditionBase () override
void clear ()
void setParent (PS_PRCondition *par) override
Static Public Member Functions
static bool getPS_RuBP ()
static void setPS_RuBP (const bool val)
Static Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< PRCondition, PS_PRCondition, MODULE_PR >
static std::size_t size ()
Static Private Member Functions
static std::size_t _size ()
static void _reset (const bool noChildren=false)
Static Private Attributes
static EPHOTO_API bool PS_RuBP = false
Additional Inherited Members
Data Fields inherited from ePhotosynthesis::conditions::ConditionBase< PRCondition, PS_PRCondition, MODULE_PR >
PS_PRCondition * parent
The parent Condition instance.
Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< PRCondition, PS_PRCondition, MODULE_PR >
ConditionBase ()
ConditionBase (const ConditionBase *const other)
arr _toArray () const override
virtual void _clear ()
void _fromArray (const arr &vec, const std::size_t offset=0) override
Static Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< PRCondition, PS_PRCondition, MODULE_PR >
static void _initStaticMembers ()
Detailed Description
Class for holding the inputs to PR_mb
Definition at line 48 of file PRCondition.hpp.
Constructor & Destructor Documentation
PRCondition()
PRCondition::PRCondition (const arr vec, const std::size_t offset = 0)
Constructor to create an object from the input vector, starting at the given index
Parameters
vec Vector to create the object from
offset The index in vec to start creating the object from
Definition at line 34 of file PRCondition.cpp.
Member Function Documentation
_reset()
static void ePhotosynthesis::conditions::PRCondition::_reset (const bool noChildren = false) inline static private
Reset any static data members to their initial state
Definition at line 77 of file PRCondition.hpp.
References setPS_RuBP().
_size()
static std::size_t ePhotosynthesis::conditions::PRCondition::_size () inline static private
Get the size of the data vector
Returns
The size of the serialized vector.
Definition at line 68 of file PRCondition.hpp.
References _size(), and PS_RuBP.
Referenced by _size().
getPS_RuBP()
static bool ePhotosynthesis::conditions::PRCondition::getPS_RuBP () inline static
Get the value of PS_RuBP
Returns
The current value
Definition at line 61 of file PRCondition.hpp.
References PS_RuBP, and SET_GET_BOOL.
setPS_RuBP()
static void ePhotosynthesis::conditions::PRCondition::setPS_RuBP (const bool val) inline static
Set the value of PS_RuBP
Parameters
val The value to set PS_RuBP to
Definition at line 61 of file PRCondition.hpp.
Referenced by _reset().
Field Documentation
PS_RuBP
bool PRCondition::PS_RuBP = false static private
Definition at line 61 of file PRCondition.hpp.
Referenced by _size(), and getPS_RuBP().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/conditions/PRCondition.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/conditions/PRCondition.cpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/ini/PR_Ini.cpp