ePhotosynthesis: ePhotosynthesis::ValueSet_t Class Reference
ePhotosynthesis::ValueSet_t Class Reference
#include <ValueSet.hpp>
Public Member Functions
virtual ~ValueSet_t ()
virtual bool equals (const ValueSet_t &b0, const bool noChildren=false) const
bool operator== (const ValueSet_t &b) const
bool operator!= (const ValueSet_t &b) const
virtual ValueSet_t * getValueSet ()
virtual std::vector< ValueSet_t ** > & getChildren ()
getChildren
Static Public Member Functions
template<typename T>
static const T & castValueSet (const ValueSet_t &x)
Detailed Description
Untemplated base class to allow storage of mixed value sets in containers.
Definition at line 678 of file ValueSet.hpp.
Constructor & Destructor Documentation
~ValueSet_t()
virtual ePhotosynthesis::ValueSet_t::~ValueSet_t () inline virtual
Definition at line 681 of file ValueSet.hpp.
Member Function Documentation
castValueSet()
template<typename T> static const T & ePhotosynthesis::ValueSet_t::castValueSet (const ValueSet_t & x) inline static
Definition at line 684 of file ValueSet.hpp.
equals()
bool ValueSet_t::equals (const ValueSet_t & b0, const bool noChildren = false) const virtual
Check if another value set is equivalent to this one.
Parameters
b Value set to compare against this one.
noChildren If true, child classes will not be checked.
Reimplemented in ePhotosynthesis::ValueSet< T, U, ID, PT >.
Definition at line 12 of file ValueSet.cpp.
Referenced by operator==().
getChildren()
std::vector< ValueSet_t ** > & ValueSet_t::getChildren () virtual
getChildren
Template class to provide methods for manipulating a set of values used by a model run that can be set via input files.
Template Parameters
T Child class with virtual & static methods.
U Parent class with virtual & static methods.
ID Enum corresponding to the module that the values will be used by.
PT Enum corresponding to the module component that the values will be used by. getChildren
Definition at line 51 of file ValueSet.cpp.
References getChildren().
Referenced by getChildren(), and ePhotosynthesis::Variables::setRecord().
getValueSet()
ValueSet_t * ValueSet_t::getValueSet () virtual
Get a constant ValueSet_t pointer for this instance/class.
Returns
Pointer.
Definition at line 48 of file ValueSet.cpp.
References getValueSet().
Referenced by getValueSet().
operator!=()
bool ValueSet_t::operator!= (const ValueSet_t & b) const
Definition at line 22 of file ValueSet.cpp.
References operator==().
operator==()
bool ValueSet_t::operator== (const ValueSet_t & b) const
Definition at line 19 of file ValueSet.cpp.
References equals().
Referenced by operator!=().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/ValueSet.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/ValueSet.cpp