ePhotosynthesis: ePhotosynthesis::vel::RROEAVel Class Reference
ePhotosynthesis::vel::RROEAVel Class Reference
#include <RROEAVel.hpp>
Public Member Functions
RROEAVel ()
RROEAVel (const RROEAVel &other)
Friends
std::ostream & operator<< (std::ostream &out, const RROEAVel &in)
Detailed Description
Class for holding the results of RROEA_Rate calculations
Definition at line 38 of file RROEAVel.hpp.
Constructor & Destructor Documentation
RROEAVel() [1/2]
ePhotosynthesis::vel::RROEAVel::RROEAVel () inline
Definition at line 41 of file RROEAVel.hpp.
References RROEAVel().
Referenced by operator<<, RROEAVel(), and RROEAVel().
RROEAVel() [2/2]
ePhotosynthesis::vel::RROEAVel::RROEAVel (const RROEAVel & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The RROEAVel object to copy
Definition at line 49 of file RROEAVel.hpp.
References RROEAVel().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const RROEAVel & in) friend
Definition at line 32 of file RROEA_Vel_output.cpp.
References RROEAVel().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/vel/RROEAVel.hpp