ePhotosynthesis: ePhotosynthesis::ValueSetWrapperBase< T > Class Template Reference
ePhotosynthesis::ValueSetWrapperBase< T > Class Template Reference
#include <ValueSet.hpp>
Public Member Functions
ValueSetWrapperBase (T *ptr)
ValueSetWrapperBase (ValueSetWrapperBase &&other)
~ValueSetWrapperBase ()
ValueSetWrapperBase< T > & operator= (ValueSetWrapperBase &&other)
T * operator-> ()
const T * operator-> () const
T & operator* ()
const T & operator* () const
operator bool () const
Private Attributes
T * ptr_
Detailed Description
template<typename T>
class ePhotosynthesis::ValueSetWrapperBase< T >
Wrapper for handling destruction of ValueSet pointers.
Definition at line 824 of file ValueSet.hpp.
Constructor & Destructor Documentation
ValueSetWrapperBase() [1/2]
template<typename T> ValueSetWrapperBase::ValueSetWrapperBase (T * ptr)
Definition at line 162 of file ValueSet.cpp.
References ptr_.
Referenced by operator bool(), operator=(), and ValueSetWrapperBase().
ValueSetWrapperBase() [2/2]
template<typename T> ValueSetWrapperBase::ValueSetWrapperBase (ValueSetWrapperBase< T > && other)
Definition at line 166 of file ValueSet.cpp.
References ptr_, and ValueSetWrapperBase().
~ValueSetWrapperBase()
template<typename T> ValueSetWrapperBase::~ValueSetWrapperBase ()
Definition at line 171 of file ValueSet.cpp.
References ptr_.
Member Function Documentation
operator bool()
template<typename T> ValueSetWrapperBase::operator bool () const
Definition at line 207 of file ValueSet.cpp.
References ptr_, and ValueSetWrapperBase().
operator*() [1/2]
template<typename T> T & ValueSetWrapperBase::operator* ()
Definition at line 199 of file ValueSet.cpp.
References ptr_.
operator*() [2/2]
template<typename T> const T & ValueSetWrapperBase::operator* () const
Definition at line 203 of file ValueSet.cpp.
References ptr_.
operator->() [1/2]
template<typename T> T * ValueSetWrapperBase::operator-> ()
Definition at line 187 of file ValueSet.cpp.
References ptr_.
operator->() [2/2]
template<typename T> const T * ValueSetWrapperBase::operator-> () const
Definition at line 193 of file ValueSet.cpp.
References ptr_.
operator=()
template<typename T> ValueSetWrapperBase< T > & ValueSetWrapperBase::operator= (ValueSetWrapperBase< T > && other)
Definition at line 178 of file ValueSet.cpp.
References ptr_, and ValueSetWrapperBase().
Field Documentation
ptr_
template<typename T> T* ePhotosynthesis::ValueSetWrapperBase< T >::ptr_ private
Definition at line 836 of file ValueSet.hpp.
Referenced by operator bool(), operator*(), operator*(), operator->(), operator->(), operator=(), ValueSetWrapperBase(), ValueSetWrapperBase(), and ~ValueSetWrapperBase().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/ValueSet.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/ValueSet.cpp