ePhotosynthesis: cxxopts::OptionValue Class Reference
cxxopts::OptionValue Class Reference
#include <cxxopts.hpp>
Public Member Functions
void parse (const std::shared_ptr< const OptionDetails > &details, const std::string &text)
void parse_default (const std::shared_ptr< const OptionDetails > &details)
CXXOPTS_NODISCARD size_t count () const noexcept
CXXOPTS_NODISCARD bool has_default () const noexcept
template<typename T>
const T & as () const
Private Member Functions
void ensure_value (const std::shared_ptr< const OptionDetails > &details)
Private Attributes
const std::string * m_long_name = nullptr
std::shared_ptr< Value > m_value {}
size_t m_count = 0
bool m_default = false
Detailed Description
Definition at line 1108 of file cxxopts.hpp.
Member Function Documentation
as()
template<typename T> const T & cxxopts::OptionValue::as () const inline
Definition at line 1150 of file cxxopts.hpp.
References cxxopts::values::abstract_value< T >::get(), m_long_name, m_value, and cxxopts::throw_or_mimic().
count()
CXXOPTS_NODISCARD size_t cxxopts::OptionValue::count () const inline noexcept
Definition at line 1135 of file cxxopts.hpp.
References m_count.
ensure_value()
void cxxopts::OptionValue::ensure_value (const std::shared_ptr< const OptionDetails > & details) inline private
Definition at line 1166 of file cxxopts.hpp.
References m_value.
Referenced by parse(), and parse_default().
has_default()
CXXOPTS_NODISCARD bool cxxopts::OptionValue::has_default () const inline noexcept
Definition at line 1143 of file cxxopts.hpp.
References m_default.
parse()
void cxxopts::OptionValue::parse (const std::shared_ptr< const OptionDetails > & details, const std::string & text) inline
Definition at line 1112 of file cxxopts.hpp.
References ensure_value(), m_count, m_long_name, and m_value.
parse_default()
void cxxopts::OptionValue::parse_default (const std::shared_ptr< const OptionDetails > & details) inline
Definition at line 1125 of file cxxopts.hpp.
References ensure_value(), m_default, m_long_name, and m_value.
Field Documentation
m_count
size_t cxxopts::OptionValue::m_count = 0 private
Definition at line 1179 of file cxxopts.hpp.
Referenced by count(), and parse().
m_default
bool cxxopts::OptionValue::m_default = false private
Definition at line 1180 of file cxxopts.hpp.
Referenced by has_default(), and parse_default().
m_long_name
const std::string* cxxopts::OptionValue::m_long_name = nullptr private
Definition at line 1175 of file cxxopts.hpp.
Referenced by as(), parse(), and parse_default().
m_value
std::shared_ptr<Value> cxxopts::OptionValue::m_value {} private
Definition at line 1178 of file cxxopts.hpp.
Referenced by as(), ensure_value(), parse(), and parse_default().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/cxxopts.hpp