ePhotosynthesis: cxxopts::OptionParseException Class Reference
cxxopts::OptionParseException Class Reference
#include <cxxopts.hpp>
Public Member Functions
OptionParseException (const std::string &message)
Public Member Functions inherited from cxxopts::OptionException
OptionException (std::string message)
CXXOPTS_NODISCARD const char * what () const noexcept override
Detailed Description
Definition at line 368 of file cxxopts.hpp.
Constructor & Destructor Documentation
OptionParseException()
cxxopts::OptionParseException::OptionParseException (const std::string & message) inline explicit
Definition at line 371 of file cxxopts.hpp.
References cxxopts::OptionException::OptionException().
Referenced by cxxopts::argument_incorrect_type::argument_incorrect_type(), cxxopts::missing_argument_exception::missing_argument_exception(), cxxopts::option_not_exists_exception::option_not_exists_exception(), cxxopts::option_not_has_argument_exception::option_not_has_argument_exception(), cxxopts::option_not_present_exception::option_not_present_exception(), cxxopts::option_required_exception::option_required_exception(), cxxopts::option_requires_argument_exception::option_requires_argument_exception(), and cxxopts::option_syntax_exception::option_syntax_exception().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/cxxopts.hpp