ePhotosynthesis: cxxopts Namespace Reference
cxxopts Namespace Reference
Namespaces
namespace values
Data Structures
class argument_incorrect_type
struct HelpGroupDetails
struct HelpOptionDetails
class invalid_option_format_error
class KeyValue
class missing_argument_exception
struct Option
class option_exists_error
class option_has_no_value_exception
class option_not_exists_exception
class option_not_has_argument_exception
class option_not_present_exception
class option_required_exception
class option_requires_argument_exception
class option_syntax_exception
class OptionAdder
class OptionDetails
class OptionException
class OptionParseException
class OptionParser
class Options
class OptionSpecException
class OptionValue
class ParseResult
class Value
Typedefs
typedef std::string String
using ParsedHashMap = std::unordered_map<size_t, OptionValue>
using NameHashMap = std::unordered_map<std::string, size_t>
using OptionMap = std::unordered_map<std::string, std::shared_ptr<OptionDetails>>
using PositionalList = std::vector<std::string>
using PositionalListIterator = PositionalList::const_iterator
Functions
template<typename T>
T toLocalString (T &&t)
size_t stringLength (const String &s)
String & stringAppend (String &s, const String &a)
String & stringAppend (String &s, size_t n, char c)
template<typename Iterator>
String & stringAppend (String &s, Iterator begin, Iterator end)
template<typename T>
std::string toUTF8String (T &&t)
bool empty (const std::string &s)
template<typename T>
void throw_or_mimic (const std::string &text)
template<typename T>
std::shared_ptr< Value > value ()
template<typename T>
std::shared_ptr< Value > value (T &t)
Variables
static constexpr struct cxxopts:: { ... } version
Typedef Documentation
NameHashMap
using cxxopts::NameHashMap = std::unordered_map<std::string, size_t>
Definition at line 1222 of file cxxopts.hpp.
OptionMap
using cxxopts::OptionMap = std::unordered_map<std::string, std::shared_ptr<OptionDetails>>
Definition at line 1323 of file cxxopts.hpp.
ParsedHashMap
using cxxopts::ParsedHashMap = std::unordered_map<size_t, OptionValue>
Definition at line 1221 of file cxxopts.hpp.
PositionalList
using cxxopts::PositionalList = std::vector<std::string>
Definition at line 1324 of file cxxopts.hpp.
PositionalListIterator
using cxxopts::PositionalListIterator = PositionalList::const_iterator
Definition at line 1325 of file cxxopts.hpp.
String
typedef std::string cxxopts::String
Definition at line 218 of file cxxopts.hpp.
Function Documentation
empty()
bool cxxopts::empty (const std::string & s) inline
Definition at line 264 of file cxxopts.hpp.
Referenced by cxxopts::Options::generate_group_help(), and cxxopts::option_has_no_value_exception::option_has_no_value_exception().
stringAppend() [1/3]
String & cxxopts::stringAppend (String & s, const String & a) inline
Definition at line 236 of file cxxopts.hpp.
stringAppend() [2/3]
template<typename Iterator> String & cxxopts::stringAppend (String & s, Iterator begin, Iterator end)
Definition at line 250 of file cxxopts.hpp.
stringAppend() [3/3]
String & cxxopts::stringAppend (String & s, size_t n, char c) inline
Definition at line 243 of file cxxopts.hpp.
stringLength()
size_t cxxopts::stringLength (const String & s) inline
Definition at line 229 of file cxxopts.hpp.
Referenced by cxxopts::Options::help_one_group().
throw_or_mimic()
template<typename T> void cxxopts::throw_or_mimic (const std::string & text)
Definition at line 499 of file cxxopts.hpp.
Referenced by cxxopts::Options::add_one_option(), cxxopts::OptionValue::as(), cxxopts::values::checked_negate(), cxxopts::OptionParser::checked_parse_arg(), cxxopts::OptionParser::consume_positional(), cxxopts::values::integer_parser(), cxxopts::OptionAdder::operator()(), cxxopts::values::detail::SignedCheck< T, true >::operator()(), cxxopts::ParseResult::operator[](), cxxopts::OptionParser::parse(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), and cxxopts::values::stringstream_parser().
toLocalString()
template<typename T> T cxxopts::toLocalString (T && t)
Definition at line 222 of file cxxopts.hpp.
Referenced by cxxopts::Options::add_option(), cxxopts::Options::help(), cxxopts::Options::help_one_group(), and cxxopts::Options::Options().
toUTF8String()
template<typename T> std::string cxxopts::toUTF8String (T && t)
Definition at line 257 of file cxxopts.hpp.
Referenced by cxxopts::Options::help().
value() [1/2]
template<typename T> std::shared_ptr< Value > cxxopts::value ()
Definition at line 996 of file cxxopts.hpp.
Referenced by cxxopts::Options::add_option(), cxxopts::values::detail::check_signed_range(), cxxopts::OptionParser::checked_parse_arg(), cxxopts::Value::default_value(), cxxopts::values::abstract_value< T >::default_value(), cxxopts::Value::implicit_value(), cxxopts::values::abstract_value< T >::implicit_value(), cxxopts::values::integer_parser(), cxxopts::OptionAdder::operator()(), cxxopts::Option::Option(), cxxopts::OptionParser::parse(), cxxopts::OptionParser::parse_option(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), cxxopts::values::parse_value(), and cxxopts::values::stringstream_parser().
value() [2/2]
template<typename T> std::shared_ptr< Value > cxxopts::value (T & t)
Definition at line 1003 of file cxxopts.hpp.
Variable Documentation
[]
struct { ... } cxxopts::version
Initial value:
= {
    CXXOPTS__VERSION_MAJOR,
    CXXOPTS__VERSION_MINOR,
    CXXOPTS__VERSION_PATCH
  }