ePhotosynthesis: ePhotosynthesis::KE::RROEAKE Class Reference
ePhotosynthesis::KE::RROEAKE Class Reference
#include <RROEAKE.hpp>
Public Member Functions
RROEAKE ()
RROEAKE (const RROEAKE &other)
RROEAKE & operator= (const RROEAKE &other)
Detailed Description
Class for RROEA_KE data
Definition at line 38 of file RROEAKE.hpp.
Constructor & Destructor Documentation
RROEAKE() [1/2]
ePhotosynthesis::KE::RROEAKE::RROEAKE () inline
Definition at line 41 of file RROEAKE.hpp.
References RROEAKE().
Referenced by operator=(), RROEAKE(), and RROEAKE().
RROEAKE() [2/2]
ePhotosynthesis::KE::RROEAKE::RROEAKE (const RROEAKE & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The RROEAKE object to copy
Definition at line 49 of file RROEAKE.hpp.
References RROEAKE().
Member Function Documentation
operator=()
RROEAKE & ePhotosynthesis::KE::RROEAKE::operator= (const RROEAKE & other) inline
Definition at line 53 of file RROEAKE.hpp.
References RROEAKE().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/ke/RROEAKE.hpp