ePhotosynthesis: ePhotosynthesis::modules::ModuleBase< T, U, ID > Class Template Reference
ePhotosynthesis::modules::ModuleBase< T, U, ID > Class Template Reference
#include <ModuleBase.hpp>
Public Types
typedef T ModType
typedef U CondType
Static Public Member Functions
static bool compareState (const Variables *theVars1, const Variables *theVars2, const U *con1, const U *con2, const std::map< int, double > &map1, const std::map< int, double > &map2)
static std::string diffState (const Variables *theVars1, const Variables *theVars2, const U *con1, const U *con2, const std::map< int, double > &map1, const std::map< int, double > &map2)
static U * initOrig (Variables *theVars)
static U * initNew (Variables *theVars)
static U * init (Variables *theVars)
static U * initAllValues (Variables *theVars, const bool noDefaults=false)
static arr MB (const double t, const U *condition, Variables *theVars)
static U * MB_con (const double t, const U *condition, Variables *theVars)
static void _select (const bool x=true, const bool noChildren=false)
static void _enableC3 (const bool x=true, const bool noChildren=false)
static void _reset (const bool noChildren=false)
template<typename C>
static void addClass ()
static void initAddedClasses ()
Static Public Attributes
static std::vector< ValueSetClassWrapper > added_classes
Protected Member Functions
ModuleBase ()
Static Protected Member Functions
static void Rate (const double t, const U *condition, Variables *theVars)
static void _initAddedClasses ()
static void _initStaticMembers ()
Static Private Member Functions
static U * _init (Variables *theVars)
static bool _compareState (const Variables *theVars1, const Variables *theVars2, const U *con1, const U *con2, const std::map< int, double > &map1, const std::map< int, double > &map2)
static U * _createCondition (Variables *theVars)
static U * _initOrig (Variables *theVars)
static arr _MB (const double t, const U *con, Variables *theVars)
static U * _MB_con (const double t, const U *con, Variables *theVars)
static void _Rate (const double t, const U *con, Variables *theVars)
Detailed Description
template<class T, class U, MODULE ID = MODULE_NONE>
class ePhotosynthesis::modules::ModuleBase< T, U, ID >
This template class provides a common set of static funtions for every Module subclass. This makes calling the underlying functions more straight forward.
Template Parameters
T The class type to work with
U The condition class associated with this Module
Definition at line 47 of file ModuleBase.hpp.
Member Typedef Documentation
CondType
template<class T, class U, MODULE ID = MODULE_NONE> typedef U ePhotosynthesis::modules::ModuleBase< T, U, ID >::CondType
Definition at line 51 of file ModuleBase.hpp.
ModType
template<class T, class U, MODULE ID = MODULE_NONE> typedef T ePhotosynthesis::modules::ModuleBase< T, U, ID >::ModType
Definition at line 50 of file ModuleBase.hpp.
Constructor & Destructor Documentation
ModuleBase()
template<class T, class U, MODULE ID = MODULE_NONE> ePhotosynthesis::modules::ModuleBase< T, U, ID >::ModuleBase () inline protected
Definition at line 254 of file ModuleBase.hpp.
Member Function Documentation
_compareState()
template<class T, class U, MODULE ID = MODULE_NONE> static bool ePhotosynthesis::modules::ModuleBase< T, U, ID >::_compareState (const Variables * theVars1, const Variables * theVars2, const U * con1, const U * con2, const std::map< int, double > & map1, const std::map< int, double > & map2) inline static private
Definition at line 279 of file ModuleBase.hpp.
References UNUSED.
_createCondition()
template<class T, class U, MODULE ID = MODULE_NONE> static U * ePhotosynthesis::modules::ModuleBase< T, U, ID >::_createCondition (Variables * theVars) inline static private
Function to create a condition for this module.
Parameters
theVars Pointer to the global variables
Returns
A Condition object with values set based on the input
Definition at line 299 of file ModuleBase.hpp.
References UNUSED.
_enableC3()
template<class T, class U, MODULE ID = MODULE_NONE> static void ePhotosynthesis::modules::ModuleBase< T, U, ID >::_enableC3 (const bool x = true, const bool noChildren = false) inline static
Set a flag so that the value set uses or does not use C3 defaults.
Parameters
[in] x true if value set should use C3 defaults, false if it should use non-C3 defaults.
noChildren If true, child classes will not be modified.
Definition at line 211 of file ModuleBase.hpp.
References added_classes.
_init()
template<class T, class U, MODULE ID = MODULE_NONE> static U * ePhotosynthesis::modules::ModuleBase< T, U, ID >::_init (Variables * theVars) inline static private
Function to set the initial state of the Condition class.
Parameters
theVars Pointer to the global variables
Returns
A Condition object with values set based on the input
Definition at line 274 of file ModuleBase.hpp.
References UNUSED.
_initAddedClasses()
template<class T, class U, MODULE ID = MODULE_NONE> static void ePhotosynthesis::modules::ModuleBase< T, U, ID >::_initAddedClasses () inline static protected
Initialized the added classes
Definition at line 366 of file ModuleBase.hpp.
_initOrig()
template<class T, class U, MODULE ID = MODULE_NONE> static U * ePhotosynthesis::modules::ModuleBase< T, U, ID >::_initOrig (Variables * theVars) inline static private
Function to set the initial state of the Condition class. This method initializes the state using the original code.
Parameters
theVars Pointer to the global variables
Returns
A Condition object with values set based on the input
Definition at line 311 of file ModuleBase.hpp.
References UNUSED.
_initStaticMembers()
template<class T, class U, MODULE ID = MODULE_NONE> static void ePhotosynthesis::modules::ModuleBase< T, U, ID >::_initStaticMembers () inline static protected
Perform class specific static member initialization
Definition at line 369 of file ModuleBase.hpp.
References initAddedClasses().
_MB()
template<class T, class U, MODULE ID = MODULE_NONE> static arr ePhotosynthesis::modules::ModuleBase< T, U, ID >::_MB (const double t, const U * con, Variables * theVars) inline static private
Function to calculate the dy/dt values for the Condition at the given time stamp.
Parameters
t The current timestamp
con Condition object giving the input parameters
theVars The global variables
Returns
A vector containing the dy/dt values for this time stamp.
Definition at line 325 of file ModuleBase.hpp.
References UNUSED.
_MB_con()
template<class T, class U, MODULE ID = MODULE_NONE> static U * ePhotosynthesis::modules::ModuleBase< T, U, ID >::_MB_con (const double t, const U * con, Variables * theVars) inline static private
Function to calculate the dy/dt values for the Condition at the given time stamp.
Parameters
t The current timestamp
con Condition object giving the input parameters
theVars The global variables
Returns
A Condition instance containing the dy/dt values for this time stamp.
Definition at line 343 of file ModuleBase.hpp.
References UNUSED.
_Rate()
template<class T, class U, MODULE ID = MODULE_NONE> static void ePhotosynthesis::modules::ModuleBase< T, U, ID >::_Rate (const double t, const U * con, Variables * theVars) inline static private
Calculate the Rates of the module based on the input condition.
Parameters
t The current timestamp
con Condition object giving the input parameters
theVars The global variables
Definition at line 357 of file ModuleBase.hpp.
References UNUSED.
_reset()
template<class T, class U, MODULE ID = MODULE_NONE> static void ePhotosynthesis::modules::ModuleBase< T, U, ID >::_reset (const bool noChildren = false) inline static
Reset the static class members following the destruction of the current driver so that additional runs start with a clean slate.
Parameters
noChildren If true, child classes will not be reset. Common, public interface for the private _reset method.
Definition at line 220 of file ModuleBase.hpp.
References added_classes.
_select()
template<class T, class U, MODULE ID = MODULE_NONE> static void ePhotosynthesis::modules::ModuleBase< T, U, ID >::_select (const bool x = true, const bool noChildren = false) inline static
Select the value set and any children.
Parameters
[in] x true if value set should be selected, false if it should be deselected.
noChildren If true, child classes will not be selected.
Definition at line 202 of file ModuleBase.hpp.
References added_classes.
addClass()
template<class T, class U, MODULE ID = MODULE_NONE> template<typename C> static void ePhotosynthesis::modules::ModuleBase< T, U, ID >::addClass () inline static
Add an associated class to this classes set.
Template Parameters
C Associated class.
Definition at line 236 of file ModuleBase.hpp.
References added_classes.
compareState()
template<class T, class U, MODULE ID = MODULE_NONE> static bool ePhotosynthesis::modules::ModuleBase< T, U, ID >::compareState (const Variables * theVars1, const Variables * theVars2, const U * con1, const U * con2, const std::map< int, double > & map1, const std::map< int, double > & map2) inline static
Definition at line 53 of file ModuleBase.hpp.
References compareState().
Referenced by compareState(), and init().
diffState()
template<class T, class U, MODULE ID = MODULE_NONE> static std::string ePhotosynthesis::modules::ModuleBase< T, U, ID >::diffState (const Variables * theVars1, const Variables * theVars2, const U * con1, const U * con2, const std::map< int, double > & map1, const std::map< int, double > & map2) inline static
Definition at line 72 of file ModuleBase.hpp.
References ePhotosynthesis::Variables::max_field_width_all(), and ePhotosynthesis::Variables::max_value_width_all().
Referenced by init().
init()
template<class T, class U, MODULE ID = MODULE_NONE> static U * ePhotosynthesis::modules::ModuleBase< T, U, ID >::init (Variables * theVars) inline static
Common, public interface for the private init function.
Parameters
theVars The main Variables instance.
Returns
A pointer to the associated Condition class.
Definition at line 113 of file ModuleBase.hpp.
References compareState(), ePhotosynthesis::Variables::deepcopy(), diffState(), ERROR_VALUE_SET, initNew(), and initOrig().
initAddedClasses()
template<class T, class U, MODULE ID = MODULE_NONE> static void ePhotosynthesis::modules::ModuleBase< T, U, ID >::initAddedClasses () inline static
Initialize the set of added classes.
Common, public interface for the private _initAddedClasses function.
Definition at line 245 of file ModuleBase.hpp.
References added_classes.
Referenced by _initStaticMembers().
initAllValues()
template<class T, class U, MODULE ID = MODULE_NONE> static U * ePhotosynthesis::modules::ModuleBase< T, U, ID >::initAllValues (Variables * theVars, const bool noDefaults = false) inline static
Function to initialize the value set pointers and set values to defaults.
Parameters
theVars Pointer to the global variables
noDefaults If true, the value pointers will be initialized, but the default values will not be assigned to those values.
Returns
A Condition object with values set based on the input
Definition at line 154 of file ModuleBase.hpp.
References ePhotosynthesis::Variables::initParam().
Referenced by initNew(), and initOrig().
initNew()
template<class T, class U, MODULE ID = MODULE_NONE> static U * ePhotosynthesis::modules::ModuleBase< T, U, ID >::initNew (Variables * theVars) inline static
Definition at line 101 of file ModuleBase.hpp.
References initAllValues().
Referenced by init().
initOrig()
template<class T, class U, MODULE ID = MODULE_NONE> static U * ePhotosynthesis::modules::ModuleBase< T, U, ID >::initOrig (Variables * theVars) inline static
Definition at line 95 of file ModuleBase.hpp.
References initAllValues().
Referenced by init().
MB()
template<class T, class U, MODULE ID = MODULE_NONE> static arr ePhotosynthesis::modules::ModuleBase< T, U, ID >::MB (const double t, const U * condition, Variables * theVars) inline static
Common, public interface for the private differential calculation function
Parameters
t The current timestamp.
condition The input Condition class.
theVars The main Variables instance.
Returns
A vector of doubles containing the dy/dt values for each member of the input Condition.
Definition at line 177 of file ModuleBase.hpp.
References DEBUG_MESSAGE.
MB_con()
template<class T, class U, MODULE ID = MODULE_NONE> static U * ePhotosynthesis::modules::ModuleBase< T, U, ID >::MB_con (const double t, const U * condition, Variables * theVars) inline static
Common, public interface for the private differential calculation function
Parameters
t The current timestamp.
condition The input Condition class.
theVars The main Variables instance.
Returns
A pointer to an associated Condition class containing the dy/dt values for each member of the input Condition.
Definition at line 193 of file ModuleBase.hpp.
References DEBUG_MESSAGE.
Rate()
template<class T, class U, MODULE ID = MODULE_NONE> static void ePhotosynthesis::modules::ModuleBase< T, U, ID >::Rate (const double t, const U * condition, Variables * theVars) inline static protected
Common interface for the private rate calculation function.
Parameters
t The current timestamp.
condition The input Condition class.
theVars The main Variables instance.
Definition at line 263 of file ModuleBase.hpp.
Field Documentation
added_classes
template<class T, class U, MODULE ID = MODULE_NONE> std::vector<ValueSetClassWrapper> ePhotosynthesis::modules::ModuleBase< T, U, ID >::added_classes static
Wrappers for value set classes associated with this module
Definition at line 251 of file ModuleBase.hpp.
Referenced by _enableC3(), _reset(), _select(), addClass(), and initAddedClasses().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/modules/ModuleBase.hpp