ePhotosynthesis: ePhotosynthesis::conditions::CMCondition Class Reference
ePhotosynthesis::conditions::CMCondition Class Reference
#include <CMCondition.hpp>
Public Member Functions
CMCondition (EPSCondition *par=nullptr)
~CMCondition ()
CMCondition (const arr &vec, const std::size_t offset=0)
CMCondition (realtype *x)
CMCondition (PS_PRCondition *pother, SUCSCondition *sother)
Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >
~ConditionBase () override
void clear ()
void setParent (EPSCondition *par) override
Data Fields
PS_PRCondition * PS_PR_con = nullptr
SUCSCondition * SUCS_con = nullptr
Data Fields inherited from ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >
EPSCondition * parent
The parent Condition instance.
Static Private Member Functions
static std::size_t _size ()
Additional Inherited Members
Static Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >
static std::size_t size ()
Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >
ConditionBase ()
ConditionBase (const ConditionBase *const other)
arr _toArray () const override
virtual void _clear ()
void _fromArray (const arr &vec, const std::size_t offset=0) override
Static Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >
static void _initStaticMembers ()
Detailed Description
Class for holding the inputs to CM_mb
Definition at line 46 of file CMCondition.hpp.
Constructor & Destructor Documentation
CMCondition() [1/4]
ePhotosynthesis::conditions::CMCondition::CMCondition (EPSCondition * par = nullptr) inline
Definition at line 49 of file CMCondition.hpp.
References CMCondition(), PS_PR_con, ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >::setParent(), and SUCS_con.
Referenced by CMCondition().
~CMCondition()
ePhotosynthesis::conditions::CMCondition::~CMCondition () inline
Definition at line 53 of file CMCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >::_clear().
CMCondition() [2/4]
CMCondition::CMCondition (const arr & vec, const std::size_t offset = 0)
Constructor to create an object from the input vector, starting at the given index
Parameters
vec Vector to create the object from
offset The index in vec to start creating the object from
Definition at line 34 of file CMCondition.cpp.
CMCondition() [3/4]
CMCondition::CMCondition (realtype * x)
Constructor to create an object from the input pointer
Parameters
x The pointer to get the data from
Definition at line 39 of file CMCondition.cpp.
References realtype.
CMCondition() [4/4]
CMCondition::CMCondition (PS_PRCondition * pother, SUCSCondition * sother)
Constructor to create an object from the contained classes
Parameters
pother A PS_PRCondition object to incorporate
sother A SUCSCondition object to incorporate
Definition at line 44 of file CMCondition.cpp.
References ePhotosynthesis::conditions::ConditionBase< T, U, ID >::parent, PS_PR_con, and SUCS_con.
Member Function Documentation
_size()
static std::size_t ePhotosynthesis::conditions::CMCondition::_size () inline static private
Get the size of the data vector
Returns
The size of the serialized vector.
Definition at line 89 of file CMCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >::size().
Field Documentation
PS_PR_con
PS_PRCondition* ePhotosynthesis::conditions::CMCondition::PS_PR_con = nullptr
Definition at line 80 of file CMCondition.hpp.
Referenced by CMCondition(), and CMCondition().
SUCS_con
SUCSCondition* ePhotosynthesis::conditions::CMCondition::SUCS_con = nullptr
Definition at line 81 of file CMCondition.hpp.
Referenced by CMCondition(), and CMCondition().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/conditions/CMCondition.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/conditions/CMCondition.cpp