ePhotosynthesis: ePhotosynthesis::conditions::PS_PRCondition Class Reference
ePhotosynthesis::conditions::PS_PRCondition Class Reference
#include <PS_PRCondition.hpp>
Public Member Functions
PS_PRCondition (CMCondition *par=nullptr)
~PS_PRCondition () override
PS_PRCondition (PSCondition *sother, PRCondition *rother)
PS_PRCondition (const arr &vec, const std::size_t offset=0)
Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< PS_PRCondition, CMCondition, MODULE_PS_PR >
~ConditionBase () override
void clear ()
void setParent (CMCondition *par) override
Data Fields
PSCondition * PS_con = nullptr
PRCondition * PR_con = nullptr
Data Fields inherited from ePhotosynthesis::conditions::ConditionBase< PS_PRCondition, CMCondition, MODULE_PS_PR >
CMCondition * parent
The parent Condition instance.
Static Private Member Functions
static std::size_t _size ()
Additional Inherited Members
Static Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< PS_PRCondition, CMCondition, MODULE_PS_PR >
static std::size_t size ()
Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< PS_PRCondition, CMCondition, MODULE_PS_PR >
ConditionBase ()
ConditionBase (const ConditionBase *const other)
arr _toArray () const override
virtual void _clear ()
void _fromArray (const arr &vec, const std::size_t offset=0) override
Static Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< PS_PRCondition, CMCondition, MODULE_PS_PR >
static void _initStaticMembers ()
Detailed Description
Class to hold inputs to PS_PR_mb
Definition at line 46 of file PS_PRCondition.hpp.
Constructor & Destructor Documentation
PS_PRCondition() [1/3]
ePhotosynthesis::conditions::PS_PRCondition::PS_PRCondition (CMCondition * par = nullptr) inline
Definition at line 49 of file PS_PRCondition.hpp.
References PR_con, PS_con, PS_PRCondition(), and ePhotosynthesis::conditions::ConditionBase< PS_PRCondition, CMCondition, MODULE_PS_PR >::setParent().
Referenced by PS_PRCondition().
~PS_PRCondition()
ePhotosynthesis::conditions::PS_PRCondition::~PS_PRCondition () inline override
Definition at line 54 of file PS_PRCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< PS_PRCondition, CMCondition, MODULE_PS_PR >::_clear().
PS_PRCondition() [2/3]
PS_PRCondition::PS_PRCondition (PSCondition * sother, PRCondition * rother)
Constructor to create an object from the contained classes
Parameters
sother A PSCon object to incorporate
rother A PRCon object to incorporate
Definition at line 36 of file PS_PRCondition.cpp.
References ePhotosynthesis::conditions::ConditionBase< T, U, ID >::parent, PR_con, and PS_con.
PS_PRCondition() [3/3]
PS_PRCondition::PS_PRCondition (const arr & vec, const std::size_t offset = 0)
Constructor to create an object from the input vector, starting at the given index
Parameters
vec Vector to create the object from
offset The index in vec to start creating the object from
Definition at line 52 of file PS_PRCondition.cpp.
Member Function Documentation
_size()
static std::size_t ePhotosynthesis::conditions::PS_PRCondition::_size () inline static private
Get the size of the data vector
Returns
The size of the serialized vector.
Definition at line 83 of file PS_PRCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >::size().
Field Documentation
PR_con
PRCondition* ePhotosynthesis::conditions::PS_PRCondition::PR_con = nullptr
Definition at line 75 of file PS_PRCondition.hpp.
Referenced by PS_PRCondition(), and PS_PRCondition().
PS_con
PSCondition* ePhotosynthesis::conditions::PS_PRCondition::PS_con = nullptr
Definition at line 74 of file PS_PRCondition.hpp.
Referenced by PS_PRCondition(), and PS_PRCondition().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/conditions/PS_PRCondition.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/conditions/PS_PRCondition.cpp