ePhotosynthesis: ePhotosynthesis::drivers::CVodeMem Class Reference
ePhotosynthesis::drivers::CVodeMem Class Reference
#include <CVodeMem.hpp>
Public Member Functions
~CVodeMem ()
CVodeMem (const CVodeMem &)=delete
CVodeMem (CVodeMem &&)=delete
CVodeMem & operator= (const CVodeMem &)=delete
CVodeMem & operator= (CVodeMem &&)=delete
void cvode_mem_init (Driver *driver, realtype t0, N_Vector y)
void cvode_mem_free ()
Static Public Member Functions
static CVodeMem & create ()
Private Member Functions
CVodeMem ()
Private Attributes
bool initialized
void * _cvode_mem
CalcData * data
Detailed Description
Definition at line 11 of file CVodeMem.hpp.
Constructor & Destructor Documentation
~CVodeMem()
CVodeMem::~CVodeMem ()
Definition at line 71 of file CVodeMem.cpp.
References _cvode_mem, data, and initialized.
CVodeMem() [1/3]
ePhotosynthesis::drivers::CVodeMem::CVodeMem (const CVodeMem &) delete
References CVodeMem().
Referenced by create(), CVodeMem(), CVodeMem(), operator=(), and operator=().
CVodeMem() [2/3]
ePhotosynthesis::drivers::CVodeMem::CVodeMem (CVodeMem &&) delete
References CVodeMem().
CVodeMem() [3/3]
ePhotosynthesis::drivers::CVodeMem::CVodeMem () inline private
Definition at line 40 of file CVodeMem.hpp.
References _cvode_mem, data, and initialized.
Member Function Documentation
create()
static CVodeMem & ePhotosynthesis::drivers::CVodeMem::create () inline static
This is a singleton class the initializes an interacts with the ODE solver. This class sets all the memory allocations and stepping parameters.
Definition at line 17 of file CVodeMem.hpp.
References CVodeMem().
Referenced by ePhotosynthesis::drivers::Driver::run(), and ePhotosynthesis::drivers::Driver::~Driver().
cvode_mem_free()
void CVodeMem::cvode_mem_free ()
Destroy the ODE solver.
Definition at line 62 of file CVodeMem.cpp.
References _cvode_mem, data, and initialized.
Referenced by ePhotosynthesis::drivers::Driver::~Driver().
cvode_mem_init()
void CVodeMem::cvode_mem_init (Driver * driver, realtype t0, N_Vector y)
Initialize the ODE solver using the given Driver instance.
Parameters
driver Instance of Driver, containing the setpping and solving parameters.
t0 The first timestamp to run the calculations at.
y Specialized data vector containing the inputs for the solver.
Definition at line 11 of file CVodeMem.cpp.
References _cvode_mem, ePhotosynthesis::DriverParam::abstol, ePhotosynthesis::drivers::alloc_calc_data(), ePhotosynthesis::drivers::Driver::calculate(), ePhotosynthesis::drivers::Driver::cvode_mem, data, ePhotosynthesis::drivers::Driver::data, initialized, ePhotosynthesis::drivers::Driver::maxStep, ePhotosynthesis::DriverParam::maxSubSteps, realtype, ePhotosynthesis::DriverParam::reltol, and ePhotosynthesis::DriverParam::showWarnings.
Referenced by ePhotosynthesis::drivers::Driver::run().
operator=() [1/2]
CVodeMem & ePhotosynthesis::drivers::CVodeMem::operator= (const CVodeMem &) delete
References CVodeMem().
operator=() [2/2]
CVodeMem & ePhotosynthesis::drivers::CVodeMem::operator= (CVodeMem &&) delete
References CVodeMem(), and realtype.
Field Documentation
_cvode_mem
void* ePhotosynthesis::drivers::CVodeMem::_cvode_mem private
Definition at line 46 of file CVodeMem.hpp.
Referenced by cvode_mem_free(), cvode_mem_init(), CVodeMem(), and ~CVodeMem().
data
CalcData* ePhotosynthesis::drivers::CVodeMem::data private
Definition at line 47 of file CVodeMem.hpp.
Referenced by cvode_mem_free(), cvode_mem_init(), CVodeMem(), and ~CVodeMem().
initialized
bool ePhotosynthesis::drivers::CVodeMem::initialized private
Definition at line 45 of file CVodeMem.hpp.
Referenced by cvode_mem_free(), cvode_mem_init(), CVodeMem(), and ~CVodeMem().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/drivers/CVodeMem.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/drivers/CVodeMem.cpp