ePhotosynthesis: ePhotosynthesis::pool::SUCSPool Class Reference
ePhotosynthesis::pool::SUCSPool Class Reference
#include <SUCSPool.hpp>
Public Member Functions
SUCSPool ()
SUCSPool (const SUCSPool &other)
SUCSPool & operator= (const SUCSPool &other)
Detailed Description
Class for SUCS_Pool data
Definition at line 38 of file SUCSPool.hpp.
Constructor & Destructor Documentation
SUCSPool() [1/2]
ePhotosynthesis::pool::SUCSPool::SUCSPool () inline
Definition at line 41 of file SUCSPool.hpp.
References SUCSPool().
Referenced by operator=(), SUCSPool(), and SUCSPool().
SUCSPool() [2/2]
ePhotosynthesis::pool::SUCSPool::SUCSPool (const SUCSPool & other) inline
Definition at line 45 of file SUCSPool.hpp.
References SUCSPool().
Member Function Documentation
operator=()
SUCSPool & ePhotosynthesis::pool::SUCSPool::operator= (const SUCSPool & other) inline
Definition at line 49 of file SUCSPool.hpp.
References SUCSPool().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/pool/SUCSPool.hpp