ePhotosynthesis: ePhotosynthesis::vel::FIVel Class Reference
ePhotosynthesis::vel::FIVel Class Reference
#include <FIVel.hpp>
Public Member Functions
FIVel ()
FIVel (const FIVel &other)
Friends
std::ostream & operator<< (std::ostream &out, const FIVel &in)
Detailed Description
Class for holding the results of the FI_Rate calculations
Definition at line 38 of file FIVel.hpp.
Constructor & Destructor Documentation
FIVel() [1/2]
ePhotosynthesis::vel::FIVel::FIVel () inline
Definition at line 41 of file FIVel.hpp.
References FIVel().
Referenced by FIVel(), FIVel(), and operator<<.
FIVel() [2/2]
ePhotosynthesis::vel::FIVel::FIVel (const FIVel & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The FIVel object to copy
Definition at line 49 of file FIVel.hpp.
References FIVel().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const FIVel & in) friend
Definition at line 32 of file FI_Vel_output.cpp.
References FIVel().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/vel/FIVel.hpp