ePhotosynthesis: ePhotosynthesis::RC::BFRC Class Reference
ePhotosynthesis::RC::BFRC Class Reference
#include <BFRC.hpp>
Public Member Functions
BFRC ()
BFRC (const BFRC &other)
BFRC & operator= (const BFRC &other)
Detailed Description
Class for holding BF_RC data
Definition at line 38 of file BFRC.hpp.
Constructor & Destructor Documentation
BFRC() [1/2]
ePhotosynthesis::RC::BFRC::BFRC () inline
Definition at line 41 of file BFRC.hpp.
References BFRC().
Referenced by BFRC(), BFRC(), and operator=().
BFRC() [2/2]
ePhotosynthesis::RC::BFRC::BFRC (const BFRC & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The BFRC object to copy
Definition at line 49 of file BFRC.hpp.
References BFRC().
Member Function Documentation
operator=()
BFRC & ePhotosynthesis::RC::BFRC::operator= (const BFRC & other) inline
Definition at line 53 of file BFRC.hpp.
References BFRC().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/rc/BFRC.hpp