ePhotosynthesis: cxxopts::OptionException Class Reference
cxxopts::OptionException Class Reference
#include <cxxopts.hpp>
Public Member Functions
OptionException (std::string message)
CXXOPTS_NODISCARD const char * what () const noexcept override
Private Attributes
std::string m_message
Detailed Description
Definition at line 338 of file cxxopts.hpp.
Constructor & Destructor Documentation
OptionException()
cxxopts::OptionException::OptionException (std::string message) inline explicit
Definition at line 341 of file cxxopts.hpp.
References m_message.
Referenced by cxxopts::option_has_no_value_exception::option_has_no_value_exception(), cxxopts::OptionParseException::OptionParseException(), and cxxopts::OptionSpecException::OptionSpecException().
Member Function Documentation
what()
CXXOPTS_NODISCARD const char * cxxopts::OptionException::what () const inline override noexcept
Definition at line 348 of file cxxopts.hpp.
References m_message.
Field Documentation
m_message
std::string cxxopts::OptionException::m_message private
Definition at line 354 of file cxxopts.hpp.
Referenced by OptionException(), and what().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/cxxopts.hpp