ePhotosynthesis: ePhotosynthesis::RC::RROEARC Class Reference
ePhotosynthesis::RC::RROEARC Class Reference
#include <RROEARC.hpp>
Public Member Functions
RROEARC ()
RROEARC (const RROEARC &other)
RROEARC & operator= (const RROEARC &other)
Detailed Description
Class for RROEA_RC data
Definition at line 38 of file RROEARC.hpp.
Constructor & Destructor Documentation
RROEARC() [1/2]
ePhotosynthesis::RC::RROEARC::RROEARC () inline
Definition at line 41 of file RROEARC.hpp.
References RROEARC().
Referenced by operator=(), RROEARC(), and RROEARC().
RROEARC() [2/2]
ePhotosynthesis::RC::RROEARC::RROEARC (const RROEARC & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The RROEARC object to copy
Definition at line 49 of file RROEARC.hpp.
References RROEARC().
Member Function Documentation
operator=()
RROEARC & ePhotosynthesis::RC::RROEARC::operator= (const RROEARC & other) inline
Definition at line 53 of file RROEARC.hpp.
References RROEARC().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/rc/RROEARC.hpp