ePhotosynthesis: ePhotosynthesis::RC::FIRC Class Reference
ePhotosynthesis::RC::FIRC Class Reference
#include <FIRC.hpp>
Public Member Functions
FIRC ()
FIRC (const FIRC &other)
FIRC & operator= (const FIRC &other)
Detailed Description
Definition at line 36 of file FIRC.hpp.
Constructor & Destructor Documentation
FIRC() [1/2]
ePhotosynthesis::RC::FIRC::FIRC () inline
Definition at line 39 of file FIRC.hpp.
References FIRC().
Referenced by FIRC(), FIRC(), and operator=().
FIRC() [2/2]
ePhotosynthesis::RC::FIRC::FIRC (const FIRC & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The FIRC object to copy
Definition at line 48 of file FIRC.hpp.
References FIRC().
Member Function Documentation
operator=()
FIRC & ePhotosynthesis::RC::FIRC::operator= (const FIRC & other) inline
Definition at line 52 of file FIRC.hpp.
References FIRC().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/rc/FIRC.hpp