ePhotosynthesis: ePhotosynthesis::pool::FIBFPool Class Reference
ePhotosynthesis::pool::FIBFPool Class Reference
#include <FIBFPool.hpp>
Public Member Functions
FIBFPool ()
FIBFPool (const FIBFPool &other)
FIBFPool & operator= (const FIBFPool &other)
Detailed Description
Class for FIBF_Pool data
Definition at line 38 of file FIBFPool.hpp.
Constructor & Destructor Documentation
FIBFPool() [1/2]
ePhotosynthesis::pool::FIBFPool::FIBFPool () inline
Definition at line 41 of file FIBFPool.hpp.
References FIBFPool().
Referenced by FIBFPool(), FIBFPool(), and operator=().
FIBFPool() [2/2]
ePhotosynthesis::pool::FIBFPool::FIBFPool (const FIBFPool & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The FIBFPool object to copy
Definition at line 50 of file FIBFPool.hpp.
References FIBFPool().
Member Function Documentation
operator=()
FIBFPool & ePhotosynthesis::pool::FIBFPool::operator= (const FIBFPool & other) inline
Definition at line 54 of file FIBFPool.hpp.
References FIBFPool().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/pool/FIBFPool.hpp