ePhotosynthesis: ePhotosynthesis::ValueSetStatic< T, U, ID, PT > Class Template Reference
ePhotosynthesis::ValueSetStatic< T, U, ID, PT > Class Template Reference
#include <ValueSet.hpp>
Public Types
typedef ValueSetStatic< T, U, ID, PT > ValueSetClass
Public Types inherited from ePhotosynthesis::ValueSetBase< T, U, ID, PT >
enum VS_FLAGS : int {
VS_FLAG_SELECTED = 0x00000001 , VS_FLAG_DEFAULTS_C3 = 0x00000002 , VS_FLAG_DEFAULTS_EDITED = 0x00000004 , VS_FLAG_INIT_DEFAULTS = 0x00000008 ,
VS_FLAG_INIT_POINTERS = 0x00000010 , VS_FLAG_INIT_VALUES = 0x00000020 , VS_FLAG_INIT_STATIC = 0x00000040 , VS_FLAG_INIT_CHILDREN = 0x00000080
}
typedef T ThisClass
typedef U ThisParent
typedef ValueSetBase< T, U, ID, PT > BaseClass
typedef ValueSetEnum< ID, PT > EnumBaseClass
typedef EnumBaseClass::Type EnumType
typedef EnumBaseClass EnumClass
typedef Value< BaseClass > ValueType
typedef std::map< EnumType, double * >::iterator iterator
typedef std::map< EnumType, double * >::const_iterator const_iterator
typedef _valueSetStaticMember< T > StaticMemberClass
Static Public Member Functions
static const ValueSet_t * getValueSet ()
static std::map< int, double > getValueMap (const bool preinit=false)
static void setValueMap (const std::map< int, double > &map, const bool setinit=false, const bool preinit=false)
static void initMembers (const bool noChildren=false)
static void resetValues (const bool noChildren=false)
static bool initialized ()
static void initValues (const bool noDefaults=false, const bool force=false, const bool noChildren=false)
static void initMemberPointers (const bool noChildren=false)
static void initStaticMembers (const bool noChildren=false)
static ValueSet_t * newInstance (ValueSet_t *par=nullptr)
static std::map< std::string, double * > getPointerMap ()
static iterator begin ()
static iterator end ()
static std::size_t max_value_width (bool noChildren=false)
static std::string diff (const ValueSet_t &other, std::size_t padKeys=0, std::size_t padVals=0, bool includePrefixes=false, bool noChildren=false)
static std::ostream & print (std::ostream &out, const uint tab=0, std::size_t pad=0, bool includePrefixes=false, bool includeSkipped=false, const std::vector< std::string > &skip_keys={}, const std::map< std::string, std::string > &key_aliases={}, bool noChildren=false)
static void check (const EnumType k, const std::string &context="")
static void update_values (const std::map< EnumType, double > &new_values, const std::string &context="", bool allow_extras=false, bool no_missing=false, bool no_constants=false, bool no_skipped=false)
static void update_values (const std::string &filename, const std::string &context="", bool allow_extras=false, bool no_missing=false, bool no_constants=false, bool no_skipped=false)
static void setPreInit (const EnumType &k, const double &v)
static void set (const EnumType &k, const double &v)
static void set (const std::string &name, const double &v, const bool &isGlymaID=false)
static void set (const int &k, const double &v)
static void setFromEnzymeAct (const EnumType k, const std::map< std::string, double > &EnzymeAct)
static double get (const EnumType &k)
static double get (const std::string &name, const bool &isGlymaID=false)
static double get (const int &k)
static void insertOrig (const EnumType k, double *v, const std::string &context="")
static void reset (const bool noChildren=false)
static std::size_t sizeArray ()
static arr toArray ()
static void fromArray (const arr &vec, const std::size_t offset=0)
template<typename C>
static void addChildClass ()
Static Public Member Functions inherited from ePhotosynthesis::ValueSetBase< T, U, ID, PT >
static ValueSetClass_t * getValueSetClass ()
static EnumType int2key (const int &k)
static int key2int (const EnumType &k)
template<typename V>
static std::map< EnumType, V > int2key (const std::map< int, V > &map)
static bool inArrays (const EnumType k)
template<typename K, typename V>
static std::size_t field_width_value_map (const std::map< K, V > &vals, bool includePrefixes=false)
template<typename K, typename V>
static std::size_t value_width_value_map (const std::map< K, V > &vals)
static std::size_t max_field_width (bool noChildren=false)
static std::size_t max_default_value_width (bool noChildren=false)
static std::ostream & print_value (const double &val, std::ostream &out, bool show_pointers=false)
static std::ostream & print_value (const double *val, std::ostream &out, bool show_pointers=false)
template<typename V>
static std::string string_value (V const val, bool show_pointers=false)
static std::string getTabs (const uint tab=0)
template<typename V>
static std::ostream & print_value (const EnumType &key, V const &val, std::ostream &out, const uint tab=0, std::size_t pad=0, bool includePrefixes=false, bool includeSkipped=false, const std::vector< std::string > &skip_keys={}, const std::map< std::string, std::string > &key_aliases={}, bool show_pointers=false, std::string iname="")
template<typename V>
static std::ostream & print_value (const std::string &name, V const &val, std::ostream &out, const uint tab=0, std::size_t pad=0, bool includePrefixes=false, bool includeSkipped=false, const std::vector< std::string > &skip_keys={}, const std::map< std::string, std::string > &key_aliases={}, bool show_pointers=false, std::string iname="")
template<typename V>
static std::ostream & print_value_map (const std::map< EnumType, V > &vals, std::ostream &out, const uint tab=0, std::size_t pad=0, bool includePrefixes=false, bool includeSkipped=false, const std::vector< std::string > &skip_keys={}, const std::map< std::string, std::string > &key_aliases={}, bool show_pointers=false)
template<typename V>
static std::string to_string_with_precision (V const a_value, const int n=COMPARE_PRECISION)
static bool valuesEqual (const double &a, const double &b)
static bool valuesEqual (const double *a, const double *b)
static bool valuesEqual (const double &a, const double *b)
static bool valuesEqual (const double *a, const double &b)
static bool valuesEqual (const ValueType &a, const ValueType &b)
static bool valuesEqual (const ValueType &a, const double &b)
static bool valuesEqual (const ValueType &a, const double *b)
static bool valuesEqual (const double &a, const ValueType &b)
static bool valuesEqual (const double *a, const ValueType &b)
static std::string valueString (const ValueType &a)
static std::string valueString (const double &a)
static std::string valueString (const double *a)
static std::string valuePointerString (const double &a)
static std::string valuePointerString (const double *a)
static std::string valuePointerString (const ValueType &a)
static void valueSet (double &dst, const double &src, const std::string &context="")
static void valueSet (double &dst, const double *src, const std::string &context="")
static void valueSet (double *dst, const double &src, const std::string &context="")
static void valueSet (double *dst, const double *src, const std::string &context="")
template<typename V>
static void valueSet (ValueType &dst, V const &src, const std::string &context="")
static double valueGet (const double *x)
static double valueGet (const double &x)
static double valueGet (const ValueType &x)
static void insertValue (std::map< EnumType, double * > &valsDst, const EnumType &k, const double *src, const std::string &context="")
static void insertValue (std::map< EnumType, double > &valsDst, const EnumType &k, const double &src, const std::string &context="")
static void insertValue (std::map< EnumType, double > &valsDst, const EnumType &k, const double *src, const std::string &context="")
static void insertValue (std::map< EnumType, double * > &, const EnumType &k, const double &, const std::string &context="")
template<typename V>
static void insertValue (std::map< EnumType, ValueType > &valsDst, const EnumType &k, V const &src, const std::string &context="")
static void compareValues (const EnumType k, const double &a, const double &b, const std::string &context="")
template<typename V>
static void check_value_map (const std::map< EnumType, V > &vals, const std::string &context="")
template<typename V>
static void check_value_map (const std::map< EnumType, V > &vals, const EnumType k, const std::string &context="")
template<typename V>
static void remove_skipped (std::map< EnumType, V > &vals, const std::string &context="")
static std::map< std::string, double * > get_pointer_map (std::map< EnumType, double * > vals)
template<typename K, typename VSrc, typename VDst>
static std::string diff_value_maps (const std::map< K, VDst > &valsDst, const std::map< K, VSrc > &valsSrc, std::size_t padKeys=0, std::size_t padVals=0, bool includePrefixes=false)
template<typename VSrc, typename VDst>
static bool compare_value_maps (const std::map< EnumType, VDst > &valsDst, const std::map< EnumType, VSrc > &valsSrc, const std::string &context="")
template<typename VSrc, typename VDst>
static bool compare_value_maps (const std::map< int, VDst > &valsDst, const std::map< int, VSrc > &valsSrc, const std::string &context="")
template<typename VSrc, typename VDst>
static void check_value_maps (std::map< EnumType, VDst > &valsDst, const std::map< EnumType, VSrc > &valsSrc, const std::string &context="", bool ignore_extras=false, bool ignore_missing=false, bool ignore_constants=false)
template<typename VSrc, typename VDst>
static void copy_value_map (std::map< EnumType, VDst > &valsDst, const std::map< EnumType, VSrc > &valsSrc, const std::string &context="", bool ignore_extras=false, bool ignore_missing=false, bool ignore_constants=false, bool ignore_skipped=false, bool ignore_initonce=false)
template<typename V>
static void copy_value_map (std::map< EnumType, V > &vals, const std::string &filename, const std::string &context="", bool ignore_extras=false, bool ignore_missing=false, bool ignore_constants=false, bool ignore_skipped=false, bool ignore_initonce=false)
template<typename VSrc, typename VDst>
static void update_value_map (std::map< EnumType, VDst > &valsDst, const std::map< EnumType, VSrc > &valsSrc, const std::string &context="", bool allow_extras=false, bool no_missing=false, bool no_constants=false, bool no_skipped=false)
template<typename V>
static void update_value_map (std::map< EnumType, V > &vals, const std::string &filename, const std::string &context="", bool allow_extras=false, bool no_missing=false, bool no_constants=false, bool no_skipped=false)
template<typename V>
static std::map< int, double > export_value_map (const std::map< EnumType, V > &vals, const std::string &context="")
static void import_value_map (std::map< EnumType, double * > &dst, const std::map< int, double > &src, const std::string &context="")
static void import_value_map (std::map< EnumType, double > &dst, const std::map< int, double > &src, const std::string &context)
template<typename V>
static void init_value_map (std::map< EnumType, V > &vals, const bool isinit=false)
static void checkDefaults (const std::string &context="")
static MODULE get_module ()
static PARAM_TYPE get_param_type ()
static const std::vector< PARAM_TYPE > & get_parameter_types ()
static void initDefaults ()
static void initDefaults (const bool useC3, const std::string &filename="", const bool force=false, const bool noChildren=false)
static std::string getName (const int &k)
static std::string getName (const std::string &k)
template<typename K>
static std::string getNameWithPrefix (const K &k)
static std::string getAliasedName (const std::string &name)
static EnumType fromNameWithAliases (const std::string &name, bool isGlymaID=false)
static int fromNameWithAliasesInt (const std::string &name, bool isGlymaID=false)
static bool has (const std::string &name, const bool &isGlymaID=false)
static bool hasGlymaID (const std::string &name)
static void setDefault (const EnumType &k, const double &v, const bool dontPreserve=false)
static void setDefault (const std::string &k, const double &v, const bool &isGlymaID=false, const bool dontPreserve=false)
static void setDefault (const int &k, const double &v, const bool dontPreserve=false)
static double getDefault (const EnumType &x)
static double getDefault (const std::string &x, const bool &isGlymaID=false)
static double getDefault (const int &k)
static double getDefault (const EnumType &x, const double &defaultV)
static std::string getDocs (const std::string &name, const bool &isGlymaID=false)
static std::string getDocs (const int &k)
template<typename V>
static ValueType get_value (std::map< EnumType, V > &vals, const EnumType k, const std::string &context="[]: ")
static const double & get_value_const (const std::map< EnumType, double > &vals, const EnumType k, const std::string &context="")
static const double & get_value_const (const std::map< EnumType, double * > &vals, const EnumType k, const std::string &context="")
static const double & get_value_const (const std::map< EnumType, ValueType > &vals, const EnumType k, const std::string &context="")
static void set_value (std::map< EnumType, double > &vals, const EnumType k, const double v, const std::string &context="")
static void set_value (std::map< EnumType, double * > &vals, const EnumType k, const double v, const std::string &context="")
static void set_value (std::map< EnumType, ValueType > &vals, const EnumType k, const double v, const std::string &context="")
template<typename V>
static void set_value_from_EnzymeAct (std::map< EnumType, V > &vals, const EnumType k, const std::map< std::string, double > &EnzymeAct)
static double *& get_value_orig (std::map< EnumType, double * > &vals, const EnumType k, const std::string &context="[]: ")
static void insert_value_orig (std::map< EnumType, double * > &vals, const EnumType k, double *v, const std::string &context="")
static void set_value_orig (std::map< EnumType, double * > &vals, const EnumType k, double *v)
template<typename V>
static void reset_value_map (std::map< EnumType, V > &vals)
template<typename V>
static void value_map_toArray (const std::map< EnumType, V > &vals, arr &out)
template<typename V>
static void value_map_fromArray (std::map< EnumType, V > &vals, const arr &vec, const std::size_t offset=0)
static std::size_t memberCount (const bool noChildren=false)
static std::string memberState (const bool noChildren=false)
template<typename C>
static void addChildClass ()
static void initChildClasses (const bool noChildren=false)
static void initStaticMembers (const bool noChildren=false)
static bool selected ()
static void select (const bool x=true, const bool noChildren=false)
static void checkSelected ()
static bool hasChildren ()
static bool usesC3 ()
static void enableC3 (const bool x=true, const bool noChildren=false)
static void reset (const bool noChildren=false)
static std::size_t size ()
Static Public Member Functions inherited from ePhotosynthesis::ValueSetEnum< ID, PT >
static std::string error_prefix ()
static std::string getName (const Type &x)
static std::string getName (const Type &x, const std::string &defaultV)
static Type fromName (const std::string &x)
static double getDefault (const Type &x)
static double getDefault (const Type &x, const double &defaultV)
static double getDefaultC3 (const Type &x)
static double getDefaultC3 (const Type &x, const double &defaultV)
static std::string getGlymaid (const Type &x)
static std::string getGlymaid (const Type &x, const std::string &defaultV)
static Type fromGlymaid (const std::string &x)
static Type getAlias (const std::string &x)
static Type getAlias (const std::string &x, const Type &defaultV)
static std::string getDocs (const Type &x)
static std::string getDocs (const Type &x, const std::string &defaultV)
static Type fromDocs (const std::string &x)
static int getValueFlag (const Type &x)
static bool isSkipped (const Type &x)
static void checkSkipped (const Type &x, const std::string &context="")
static void checkNotSkipped (const Type &x, const std::string &context="")
static std::size_t countSkipped ()
static std::size_t countValueFlags ()
static std::vector< Type > listSkipped ()
static void clearSkipped ()
static void clearValueFlags ()
static void addSkipped (const Type &x)
static void addValueFlags (const Type &x, const int &y)
static void removeSkipped (const Type &x)
static void removeValueFlags (const Type &x)
static void addMultipleValueFlags (const std::map< Type, int > &x)
static void removeMultipleValueFlags (const std::map< Type, int > &x)
static int getStaticValueFlag (const Type &x)
static bool isConstant (const Type &x)
static bool isCalculated (const Type &x)
static bool isNonvector (const Type &x)
static bool isResetone (const Type &x)
static bool isInitonce (const Type &x)
static void checkConstant (const Type &x, const std::string &context="")
static void checkCalculated (const Type &x, const std::string &context="")
static void checkNonvector (const Type &x, const std::string &context="")
static void checkResetone (const Type &x, const std::string &context="")
static void checkInitonce (const Type &x, const std::string &context="")
static void checkNotConstant (const Type &x, const std::string &context="")
static void checkNotCalculated (const Type &x, const std::string &context="")
static void checkNotNonvector (const Type &x, const std::string &context="")
static void checkNotResetone (const Type &x, const std::string &context="")
static void checkNotInitonce (const Type &x, const std::string &context="")
static std::size_t countConstant ()
static std::size_t countCalculated ()
static std::size_t countNonvector ()
static std::size_t countResetone ()
static std::size_t countInitonce ()
static std::size_t countStaticValueFlags ()
static std::vector< Type > listConstant ()
static std::vector< Type > listCalculated ()
static std::vector< Type > listNonvector ()
static std::vector< Type > listResetone ()
static std::vector< Type > listInitonce ()
static std::string error_prefix ()
static std::string getName (const Type &x)
static std::string getName (const Type &x, const std::string &defaultV)
static Type fromName (const std::string &x)
static double getDefault (const Type &x)
static double getDefault (const Type &x, const double &defaultV)
static double getDefaultC3 (const Type &x)
static double getDefaultC3 (const Type &x, const double &defaultV)
static std::string getGlymaid (const Type &x)
static std::string getGlymaid (const Type &x, const std::string &defaultV)
static Type fromGlymaid (const std::string &x)
static Type getAlias (const std::string &x)
static Type getAlias (const std::string &x, const Type &defaultV)
static std::string getDocs (const Type &x)
static std::string getDocs (const Type &x, const std::string &defaultV)
static Type fromDocs (const std::string &x)
static int getValueFlag (const Type &x)
static bool isSkipped (const Type &x)
static void checkSkipped (const Type &x, const std::string &context="")
static void checkNotSkipped (const Type &x, const std::string &context="")
static std::size_t countSkipped ()
static std::size_t countValueFlags ()
static std::vector< Type > listSkipped ()
static void clearSkipped ()
static void clearValueFlags ()
static void addSkipped (const Type &x)
static void addValueFlags (const Type &x, const int &y)
static void removeSkipped (const Type &x)
static void removeValueFlags (const Type &x)
static void addMultipleValueFlags (const std::map< Type, int > &x)
static void removeMultipleValueFlags (const std::map< Type, int > &x)
static int getStaticValueFlag (const Type &x)
static bool isConstant (const Type &x)
static bool isCalculated (const Type &x)
static bool isNonvector (const Type &x)
static bool isResetone (const Type &x)
static bool isInitonce (const Type &x)
static void checkConstant (const Type &x, const std::string &context="")
static void checkCalculated (const Type &x, const std::string &context="")
static void checkNonvector (const Type &x, const std::string &context="")
static void checkResetone (const Type &x, const std::string &context="")
static void checkInitonce (const Type &x, const std::string &context="")
static void checkNotConstant (const Type &x, const std::string &context="")
static void checkNotCalculated (const Type &x, const std::string &context="")
static void checkNotNonvector (const Type &x, const std::string &context="")
static void checkNotResetone (const Type &x, const std::string &context="")
static void checkNotInitonce (const Type &x, const std::string &context="")
static std::size_t countConstant ()
static std::size_t countCalculated ()
static std::size_t countNonvector ()
static std::size_t countResetone ()
static std::size_t countInitonce ()
static std::size_t countStaticValueFlags ()
static std::vector< Type > listConstant ()
static std::vector< Type > listCalculated ()
static std::vector< Type > listNonvector ()
static std::vector< Type > listResetone ()
static std::vector< Type > listInitonce ()
Static Protected Member Functions
static void _initMembers ()
static void _resetValues ()
static void _initValues ()
static std::string _diff (std::size_t padKeys=0, std::size_t padVals=0, bool includePrefixes=false, bool noChildren=false)
static std::ostream & _print (std::ostream &out, const uint tab=0, std::size_t pad=0, bool includePrefixes=false, bool includeSkipped=false, const std::vector< std::string > &skip_keys={}, const std::map< std::string, std::string > &key_aliases={}, bool noChildren=false)
static void _initMemberPointers ()
static std::size_t _sizeArray ()
static arr _toArray ()
static void _fromArray (const arr &vec, const std::size_t offset=0)
Static Protected Member Functions inherited from ePhotosynthesis::ValueSetBase< T, U, ID, PT >
static void _initDefaults ()
static void _initChildClasses ()
static void _initStaticMembers ()
static void _select (const bool=true, const bool=false)
static void _enableC3 (const bool=true, const bool=false)
static void _reset (const bool=false)
static std::size_t _size ()
Static Private Attributes
static std::map< EnumType, double * > values
static std::map< EnumType, double > preinit_values
Additional Inherited Members
Public Member Functions inherited from ePhotosynthesis::ValueSetBase< T, U, ID, PT >
INHERIT_METHOD_ENUM (EnumBaseClass)
Public Member Functions inherited from ePhotosynthesis::ValueSetEnum< ID, PT >
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > all
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > all
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > all
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > all
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > all
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > all
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > all
const std::vector< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > all
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > all
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > all
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > names
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > defaults
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > defaults_C3
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > glymaids
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > aliases
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > aliases
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > docs
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > docs
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > value_flags
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > static_value_flags
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > static_value_flags
Static Public Attributes inherited from ePhotosynthesis::ValueSetEnum< ID, PT >
static const MODULE module
static const PARAM_TYPE param_type
static const std::vector< Type > all
static const std::map< Type, std::string > names
static const std::map< Type, double > defaults
static const std::map< Type, double > defaults_C3
static const std::map< Type, std::string > glymaids
static const std::map< std::string, Type > aliases
static const std::map< Type, std::string > docs
static std::map< Type, int > value_flags
static const std::map< Type, int > static_value_flags
static const MODULE module
static const PARAM_TYPE param_type
static const std::vector< Type > all
static const std::map< Type, std::string > names
static const std::map< Type, double > defaults
static const std::map< Type, double > defaults_C3
static const std::map< Type, std::string > glymaids
static const std::map< std::string, Type > aliases
static const std::map< Type, std::string > docs
static std::map< Type, int > value_flags
static const std::map< Type, int > static_value_flags
Static Protected Attributes inherited from ePhotosynthesis::ValueSetBase< T, U, ID, PT >
static int static_flags
static std::map< EnumType, double > defaults
static std::map< EnumType, double * > static_values
static std::vector< ValueSetClassWrapper > child_classes
static const uint tab_size = 2
Detailed Description
template<class T, class U, MODULE ID, PARAM_TYPE PT>
class ePhotosynthesis::ValueSetStatic< T, U, ID, PT >
Template class to provide methods for manipulating a set of static class values used by a model run that can be set via input files.
Template Parameters
T Child class with virtual & static methods.
U Parent class with virtual & static methods.
ID Enum corresponding to the module that the values will be used by.
PT Enum corresponding to the module component that the values will be used by.
Definition at line 2627 of file ValueSet.hpp.
Member Typedef Documentation
ValueSetClass
template<class T, class U, MODULE ID, PARAM_TYPE PT> typedef ValueSetStatic<T, U, ID, PT> ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::ValueSetClass
Definition at line 2629 of file ValueSet.hpp.
Member Function Documentation
_diff()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static std::string ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::_diff (std::size_t padKeys = 0, std::size_t padVals = 0, bool includePrefixes = false, bool noChildren = false) inline static protected
Definition at line 2836 of file ValueSet.hpp.
References UNUSED.
_fromArray()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::_fromArray (const arr & vec, const std::size_t offset = 0) static protected
_initMemberPointers()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::_initMemberPointers () inline static protected
Definition at line 2853 of file ValueSet.hpp.
_initMembers()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::_initMembers () inline static protected
Definition at line 2833 of file ValueSet.hpp.
_initValues()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::_initValues () inline static protected
Definition at line 2835 of file ValueSet.hpp.
_print()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static std::ostream & ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::_print (std::ostream & out, const uint tab = 0, std::size_t pad = 0, bool includePrefixes = false, bool includeSkipped = false, const std::vector< std::string > & skip_keys = {}, const std::map< std::string, std::string > & key_aliases = {}, bool noChildren = false) static protected
_resetValues()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::_resetValues () inline static protected
Definition at line 2834 of file ValueSet.hpp.
_sizeArray()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static std::size_t ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::_sizeArray () static protected
_toArray()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static arr ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::_toArray () static protected
addChildClass()
template<class T, class U, MODULE ID, PARAM_TYPE PT> template<typename C> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::addChildClass () inline static
Add a child class to this classes set.
Template Parameters
C Child class.
Definition at line 2823 of file ValueSet.hpp.
References ePhotosynthesis::ValueSetBase< T, U, ID, PT >::child_classes.
begin()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static iterator ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::begin () static
Get the iterator pointing to the start of the value set
References begin().
Referenced by begin().
check()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::check (const EnumType k, const std::string & context = "") static
Throw an error if a key is not present in the set.
Parameters
k Key to check.
context String to prefix the error message with.
diff()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static std::string ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::diff (const ValueSet_t & other, std::size_t padKeys = 0, std::size_t padVals = 0, bool includePrefixes = false, bool noChildren = false) static
Get the diff between this an another value set.
Parameters
other Value set to compare against.
padKeys Number of characters that key names should be padded to fill.
padVals Number of characters that values should be padded to fill.
includePrefixes If true, the module & parameter type prefixes will be added to the member names.
noChildren If true, children of composite sets will not be displayed.
Returns
String diff.
References diff().
Referenced by diff().
end()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static iterator ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::end () static
Get the iterator pointing to the end of the value set
References end().
Referenced by end().
fromArray()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::fromArray (const arr & vec, const std::size_t offset = 0) static
Update the values in the set from an array.
Parameters
vec Array to update values from.
offset Index in vec to start from.
get() [1/3]
template<class T, class U, MODULE ID, PARAM_TYPE PT> static double ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::get (const EnumType & k) static
Get the value associated with a key.
Parameters
k Key to get value for.
Returns
Value.
get() [2/3]
template<class T, class U, MODULE ID, PARAM_TYPE PT> static double ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::get (const int & k) static
Get the value associated with a key.
Parameters
k Key to get value for.
Returns
Value.
get() [3/3]
template<class T, class U, MODULE ID, PARAM_TYPE PT> static double ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::get (const std::string & name, const bool & isGlymaID = false) static
Get the value associated with a key.
Parameters
name String representation of key to get value for.
[in] isGlymaID If true, k is a GlymaID.
Returns
Value
getPointerMap()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static std::map< std::string, double * > ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::getPointerMap () static
Get the map containing pointers to the static class members.
Returns
Map between member names and pointers to static class members.
References getPointerMap().
Referenced by getPointerMap().
getValueMap()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static std::map< int, double > ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::getValueMap (const bool preinit = false) static
Get a copy of the value in the set.
Parameters
[in] preinit If true, the values in preinit_values will be returned.
Returns
Map of values in the value set.
References getValueMap().
Referenced by getValueMap().
getValueSet()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static const ValueSet_t * ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::getValueSet () static
Get a constant ValueSet_t pointer for this instance/class.
Returns
Pointer.
References getValueSet().
Referenced by getValueSet().
initialized()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static bool ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::initialized () static
Check if the value set has been initialized.
Returns
true if the value set has been initialized, false otherwise.
References initialized().
Referenced by initialized().
initMemberPointers()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::initMemberPointers (const bool noChildren = false) static
Initialize the map containing pointers to instance members. Common, public interface for the private _initMemberPointers method.
Parameters
noChildren If true, child classes will not be initialized.
References initMemberPointers().
Referenced by initMemberPointers().
initMembers()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::initMembers (const bool noChildren = false) static
Initialize the members in the instance. This should be overriden by child classes with a method that adds pointers to values. Common, public interface for the private _initMembers method.
Parameters
noChildren If true, child classes will not be initialized.
References initMembers().
Referenced by initMembers().
initStaticMembers()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::initStaticMembers (const bool noChildren = false) static
Initialize the static class members including child classes.
Parameters
noChildren If true, child classes will not be initialized. Common, public interface for the private _initStaticMembers method.
References initStaticMembers().
Referenced by initStaticMembers().
initValues()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::initValues (const bool noDefaults = false, const bool force = false, const bool noChildren = false) static
Initialize the values to the default values if they have not already been initialized, minus any values that are skipped. Common, public interface for the private _initValues method.
Parameters
noDefaults If true, the value pointers will be initialized, but the default values will not be assigned to those values.
force If true, initialize the values even if they have already been initialized.
noChildren If true, child classes will not be initialized.
References initValues().
Referenced by initValues().
insertOrig()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::insertOrig (const EnumType k, double * v, const std::string & context = "") static
Add a value reference for the given key.
Parameters
k Key to update value for.
v New value pointer for key.
context String providing context for error messages.
max_value_width()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static std::size_t ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::max_value_width (bool noChildren = false) static
Get the constant iterator pointing to the start of the value set
Get the maximum width of the values in the value set.
Parameters
noChildren If true, children won't be included when determining the maximum value width.
Returns
Maximum value width.
References max_value_width().
Referenced by max_value_width().
newInstance()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static ValueSet_t * ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::newInstance (ValueSet_t * par = nullptr) static
Disabled method to create an instance of the class.
References newInstance().
Referenced by newInstance().
print()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static std::ostream & ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::print (std::ostream & out, const uint tab = 0, std::size_t pad = 0, bool includePrefixes = false, bool includeSkipped = false, const std::vector< std::string > & skip_keys = {}, const std::map< std::string, std::string > & key_aliases = {}, bool noChildren = false) static
Display the values in the set. Common, public interface for the private _print method.
Parameters
out Output stream.
tab Number of tabs to prefix each line in the output with.
pad Number of characters that key names should be padded to fill.
includePrefixes If true, the module & parameter type prefixes will be added to the member names.
includeSkipped If true, skipped keys will be output.
noChildren If true, children of composite sets will not be displayed.
skip_keys Key strings to skip in output.
key_aliases String aliases to use for keys.
Returns
Output stream.
References print().
Referenced by print().
reset()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::reset (const bool noChildren = false) static
Reset the static class members following the destruction of the current driver so that additional runs start with a clean slate.
Parameters
noChildren If true, child classes will not be reset. Common, public interface for the private _reset method.
resetValues()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::resetValues (const bool noChildren = false) static
Reset the values so that they can be re-initialized.
Parameters
noChildren If true, child classes will not be initialized.
References resetValues().
Referenced by resetValues().
set() [1/3]
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::set (const EnumType & k, const double & v) static
Update the value associated with a key.
Parameters
k Key to update value for.
v New value for key.
set() [2/3]
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::set (const int & k, const double & v) static
Update the value associated with a key.
Parameters
k Key to update value for.
v New value for key.
set() [3/3]
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::set (const std::string & name, const double & v, const bool & isGlymaID = false) static
Update the value associated with a key.
Parameters
k Key to update value for.
v New value for key.
[in] isGlymaID If true, k is a GlymaID.
setFromEnzymeAct()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::setFromEnzymeAct (const EnumType k, const std::map< std::string, double > & EnzymeAct) static
Update the value associated with a key in the value set from a map containing enzyme activity values.
Parameters
k Key to update value for.
EnzymeAct Enzyme activities.
setPreInit()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::setPreInit (const EnumType & k, const double & v) static
Record a value set before the value set is initialized so it can be ensured once the values are initialized.
Parameters
k Key to update value for.
v New value for key.
setValueMap()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::setValueMap (const std::map< int, double > & map, const bool setinit = false, const bool preinit = false) static
Set the values from a map.
Parameters
[in] map Value map to update values from.
[in] setinit If true, set the flag indicating that the value set is initialized.
[in] preinit If true, the values in preinit_values will be updated. preinit & setinit cannot both be true.
References setValueMap().
Referenced by setValueMap().
sizeArray()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static std::size_t ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::sizeArray () static
Get the number of values in the set that would be included in an array produced by toArray.
Returns
Value count.
toArray()
template<class T, class U, MODULE ID, PARAM_TYPE PT> static arr ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::toArray () static
Get the values in an array ordering based on key order.
Returns
Values array.
update_values() [1/2]
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::update_values (const std::map< EnumType, double > & new_values, const std::string & context = "", bool allow_extras = false, bool no_missing = false, bool no_constants = false, bool no_skipped = false) static
Add values to the set.
Parameters
new_values New values to add to the set.
context String providing context for error messages.
allow_extras If true, extra values in new_values that are not in the set will be allowed.
no_missing If true, an error will be raised if there are values in the set that are not in new_values.
no_constants If true, an error will be raised if there are constant values in new_values that differ from the values in the set.
no_skipped If true, an error will be raised if there are skipped values in new_values.
update_values() [2/2]
template<class T, class U, MODULE ID, PARAM_TYPE PT> static void ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::update_values (const std::string & filename, const std::string & context = "", bool allow_extras = false, bool no_missing = false, bool no_constants = false, bool no_skipped = false) static
Add values to the set by reading a parameter file.
Parameters
filename File containing values to add to the set.
context String providing context for error messages.
allow_extras If true, extra values in the file that are not in the set will be allowed.
no_missing If true, an error will be raised if there are values in the set that are not in the file.
no_constants If true, an error will be raised if there are constant values in the file that differ from the values in the set.
no_skipped If true, an error will be raised if there are skipped values in the file.
Field Documentation
preinit_values
template<class T, class U, MODULE ID, PARAM_TYPE PT> std::map<EnumType, double> ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::preinit_values static private
Value set pre-initialization
Definition at line 2829 of file ValueSet.hpp.
values
template<class T, class U, MODULE ID, PARAM_TYPE PT> std::map<EnumType, double*> ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::values static private
Values in the set.
Definition at line 2828 of file ValueSet.hpp.
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/ValueSet.hpp