ePhotosynthesis: cxxopts::ParseResult Class Reference
cxxopts::ParseResult Class Reference
#include <cxxopts.hpp>
Public Member Functions
ParseResult ()
ParseResult (const ParseResult &)=default
ParseResult (NameHashMap &&keys, ParsedHashMap &&values, std::vector< KeyValue > sequential, std::vector< std::string > &&unmatched_args)
ParseResult & operator= (ParseResult &&)=default
ParseResult & operator= (const ParseResult &)=default
size_t count (const std::string &o) const
const OptionValue & operator[] (const std::string &option) const
const std::vector< KeyValue > & arguments () const
const std::vector< std::string > & unmatched () const
Private Attributes
NameHashMap m_keys {}
ParsedHashMap m_values {}
std::vector< KeyValue > m_sequential {}
std::vector< std::string > m_unmatched {}
Detailed Description
Definition at line 1223 of file cxxopts.hpp.
Constructor & Destructor Documentation
ParseResult() [1/3]
cxxopts::ParseResult::ParseResult () inline
Definition at line 1227 of file cxxopts.hpp.
Referenced by operator=(), operator=(), and ParseResult().
ParseResult() [2/3]
cxxopts::ParseResult::ParseResult (const ParseResult &) default
References ParseResult().
ParseResult() [3/3]
cxxopts::ParseResult::ParseResult (NameHashMap && keys, ParsedHashMap && values, std::vector< KeyValue > sequential, std::vector< std::string > && unmatched_args) inline
Definition at line 1231 of file cxxopts.hpp.
References m_keys, m_sequential, m_unmatched, and m_values.
Member Function Documentation
arguments()
const std::vector< KeyValue > & cxxopts::ParseResult::arguments () const inline
Definition at line 1282 of file cxxopts.hpp.
References m_sequential.
count()
size_t cxxopts::ParseResult::count (const std::string & o) const inline
Definition at line 1243 of file cxxopts.hpp.
References m_keys, and m_values.
operator=() [1/2]
ParseResult & cxxopts::ParseResult::operator= (const ParseResult &) default
References ParseResult().
operator=() [2/2]
ParseResult & cxxopts::ParseResult::operator= (ParseResult &&) default
References ParseResult().
operator[]()
const OptionValue & cxxopts::ParseResult::operator[] (const std::string & option) const inline
Definition at line 1262 of file cxxopts.hpp.
References m_keys, m_values, and cxxopts::throw_or_mimic().
unmatched()
const std::vector< std::string > & cxxopts::ParseResult::unmatched () const inline
Definition at line 1288 of file cxxopts.hpp.
References m_unmatched.
Field Documentation
m_keys
NameHashMap cxxopts::ParseResult::m_keys {} private
Definition at line 1294 of file cxxopts.hpp.
Referenced by count(), operator[](), and ParseResult().
m_sequential
std::vector<KeyValue> cxxopts::ParseResult::m_sequential {} private
Definition at line 1296 of file cxxopts.hpp.
Referenced by arguments(), and ParseResult().
m_unmatched
std::vector<std::string> cxxopts::ParseResult::m_unmatched {} private
Definition at line 1297 of file cxxopts.hpp.
Referenced by ParseResult(), and unmatched().
m_values
ParsedHashMap cxxopts::ParseResult::m_values {} private
Definition at line 1295 of file cxxopts.hpp.
Referenced by count(), operator[](), and ParseResult().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/cxxopts.hpp