ePhotosynthesis: ePhotosynthesis::vel::SUCSVel Class Reference
ePhotosynthesis::vel::SUCSVel Class Reference
#include <SUCSVel.hpp>
Public Member Functions
SUCSVel ()
SUCSVel (const SUCSVel &other)
Friends
std::ostream & operator<< (std::ostream &out, const SUCSVel &in)
Detailed Description
Class for holding the results of SUCS_Rate calculations
Definition at line 38 of file SUCSVel.hpp.
Constructor & Destructor Documentation
SUCSVel() [1/2]
ePhotosynthesis::vel::SUCSVel::SUCSVel () inline
Definition at line 41 of file SUCSVel.hpp.
References SUCSVel().
Referenced by operator<<, SUCSVel(), and SUCSVel().
SUCSVel() [2/2]
ePhotosynthesis::vel::SUCSVel::SUCSVel (const SUCSVel & other) inline
Definition at line 44 of file SUCSVel.hpp.
References SUCSVel().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const SUCSVel & in) friend
Definition at line 32 of file SUCS_Vel_output.cpp.
References SUCSVel().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/vel/SUCSVel.hpp