ePhotosynthesis: ePhotosynthesis::pool::FIPool Class Reference
ePhotosynthesis::pool::FIPool Class Reference
#include <FIPool.hpp>
Public Member Functions
FIPool ()
FIPool (const FIPool &other)
Detailed Description
Class for hoplding FI_Pool data
Definition at line 38 of file FIPool.hpp.
Constructor & Destructor Documentation
FIPool() [1/2]
ePhotosynthesis::pool::FIPool::FIPool () inline
Definition at line 41 of file FIPool.hpp.
References FIPool().
Referenced by FIPool(), and FIPool().
FIPool() [2/2]
ePhotosynthesis::pool::FIPool::FIPool (const FIPool & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The FIPool object to copy
Definition at line 50 of file FIPool.hpp.
References FIPool().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/pool/FIPool.hpp