ePhotosynthesis: ePhotosynthesis::vel::RedoxRegVel Class Reference
ePhotosynthesis::vel::RedoxRegVel Class Reference
#include <RedoxRegVel.hpp>
Public Member Functions
RedoxRegVel ()
RedoxRegVel (const RedoxRegVel &other)
Friends
std::ostream & operator<< (std::ostream &out, const RedoxRegVel &in)
Detailed Description
Class for holding the results of RedoxReg_Rate calculations
Definition at line 38 of file RedoxRegVel.hpp.
Constructor & Destructor Documentation
RedoxRegVel() [1/2]
ePhotosynthesis::vel::RedoxRegVel::RedoxRegVel () inline
Definition at line 41 of file RedoxRegVel.hpp.
References RedoxRegVel().
Referenced by operator<<, RedoxRegVel(), and RedoxRegVel().
RedoxRegVel() [2/2]
ePhotosynthesis::vel::RedoxRegVel::RedoxRegVel (const RedoxRegVel & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The RedoxRegVel object to copy
Definition at line 49 of file RedoxRegVel.hpp.
References RedoxRegVel().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const RedoxRegVel & in) friend
Definition at line 32 of file RedoxReg_Vel_output.cpp.
References RedoxRegVel().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/vel/RedoxRegVel.hpp