ePhotosynthesis: ePhotosynthesis::conditions::EPSCondition Class Reference
ePhotosynthesis::conditions::EPSCondition Class Reference
#include <EPSCondition.hpp>
Public Member Functions
EPSCondition (RACondition *par=nullptr)
~EPSCondition () override
EPSCondition (realtype *x)
EPSCondition (FIBFCondition *fother, CMCondition *cother)
EPSCondition (const arr &vec, const std::size_t offset=0)
Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< EPSCondition, RACondition, MODULE_EPS >
~ConditionBase () override
void clear ()
void setParent (RACondition *par) override
Data Fields
CMCondition * CM_con = nullptr
FIBFCondition * FIBF_con = nullptr
Data Fields inherited from ePhotosynthesis::conditions::ConditionBase< EPSCondition, RACondition, MODULE_EPS >
RACondition * parent
The parent Condition instance.
Static Private Member Functions
static std::size_t _size ()
Additional Inherited Members
Static Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< EPSCondition, RACondition, MODULE_EPS >
static std::size_t size ()
Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< EPSCondition, RACondition, MODULE_EPS >
ConditionBase ()
ConditionBase (const ConditionBase *const other)
arr _toArray () const override
virtual void _clear ()
void _fromArray (const arr &vec, const std::size_t offset=0) override
Static Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< EPSCondition, RACondition, MODULE_EPS >
static void _initStaticMembers ()
Detailed Description
Class for holding the inputs to EPS_mb
Definition at line 45 of file EPSCondition.hpp.
Constructor & Destructor Documentation
EPSCondition() [1/4]
ePhotosynthesis::conditions::EPSCondition::EPSCondition (RACondition * par = nullptr) inline
Definition at line 48 of file EPSCondition.hpp.
References CM_con, EPSCondition(), FIBF_con, and ePhotosynthesis::conditions::ConditionBase< EPSCondition, RACondition, MODULE_EPS >::setParent().
Referenced by EPSCondition().
~EPSCondition()
ePhotosynthesis::conditions::EPSCondition::~EPSCondition () inline override
Definition at line 52 of file EPSCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< EPSCondition, RACondition, MODULE_EPS >::_clear().
EPSCondition() [2/4]
EPSCondition::EPSCondition (realtype * x)
Constructor to create an object from the input pointer
Parameters
x The pointer to get the data from
Definition at line 34 of file EPSCondition.cpp.
References realtype.
EPSCondition() [3/4]
EPSCondition::EPSCondition (FIBFCondition * fother, CMCondition * cother)
Constructor to create an object from the contained classes
Parameters
fother A FIBFCondition object to incorporate
cother A CMCondition object to incorporate
Definition at line 39 of file EPSCondition.cpp.
References CM_con, FIBF_con, and ePhotosynthesis::conditions::ConditionBase< T, U, ID >::parent.
EPSCondition() [4/4]
EPSCondition::EPSCondition (const arr & vec, const std::size_t offset = 0)
Constructor to create an object from the input vector, starting at the given index
Parameters
vec Vector to create the object from
offset The index in vec to start creating the object from
Definition at line 55 of file EPSCondition.cpp.
Member Function Documentation
_size()
static std::size_t ePhotosynthesis::conditions::EPSCondition::_size () inline static private
Get the size of the data vector
Returns
The size of the serialized vector.
Definition at line 88 of file EPSCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< CMCondition, EPSCondition, MODULE_CM >::size(), and ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >::size().
Field Documentation
CM_con
CMCondition* ePhotosynthesis::conditions::EPSCondition::CM_con = nullptr
Definition at line 79 of file EPSCondition.hpp.
Referenced by EPSCondition(), and EPSCondition().
FIBF_con
FIBFCondition* ePhotosynthesis::conditions::EPSCondition::FIBF_con = nullptr
Definition at line 80 of file EPSCondition.hpp.
Referenced by ePhotosynthesis::modules::RedoxReg::_Rate(), EPSCondition(), and EPSCondition().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/conditions/EPSCondition.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/conditions/EPSCondition.cpp