ePhotosynthesis: ePhotosynthesis::conditions::DynaPSCondition Class Reference
ePhotosynthesis::conditions::DynaPSCondition Class Reference
#include <DynaPSCondition.hpp>
Public Member Functions
DynaPSCondition (trDynaPSCondition *par=nullptr)
~DynaPSCondition () override
DynaPSCondition (realtype *x)
DynaPSCondition (RACondition *rother, XanCycleCondition *xother)
DynaPSCondition (const arr &vec, const std::size_t offset=0)
Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >
~ConditionBase () override
void clear ()
void setParent (trDynaPSCondition *par) override
Data Fields
RACondition * RA_con = nullptr
XanCycleCondition * XanCycle_con = nullptr
Data Fields inherited from ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >
trDynaPSCondition * parent
The parent Condition instance.
Static Private Member Functions
static std::size_t _size ()
Additional Inherited Members
Static Public Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >
static std::size_t size ()
Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >
ConditionBase ()
ConditionBase (const ConditionBase *const other)
arr _toArray () const override
virtual void _clear ()
void _fromArray (const arr &vec, const std::size_t offset=0) override
Static Protected Member Functions inherited from ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >
static void _initStaticMembers ()
Detailed Description
Class for holding inputs to DynaPS_mb
Definition at line 46 of file DynaPSCondition.hpp.
Constructor & Destructor Documentation
DynaPSCondition() [1/4]
ePhotosynthesis::conditions::DynaPSCondition::DynaPSCondition (trDynaPSCondition * par = nullptr) inline
Definition at line 49 of file DynaPSCondition.hpp.
References DynaPSCondition(), RA_con, ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >::setParent(), and XanCycle_con.
Referenced by DynaPSCondition().
~DynaPSCondition()
ePhotosynthesis::conditions::DynaPSCondition::~DynaPSCondition () inline override
Definition at line 54 of file DynaPSCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >::_clear().
DynaPSCondition() [2/4]
DynaPSCondition::DynaPSCondition (realtype * x)
Constructor to create an object from the input pointer
Parameters
x The pointer to get the data from
Definition at line 34 of file DynaPSCondition.cpp.
References realtype.
DynaPSCondition() [3/4]
DynaPSCondition::DynaPSCondition (RACondition * rother, XanCycleCondition * xother)
Constructor to create an object from the contained classes
Parameters
rother A RACondition object to incorporate
xother A XanCycleCondition object to incorporate
Definition at line 39 of file DynaPSCondition.cpp.
References ePhotosynthesis::conditions::ConditionBase< T, U, ID >::parent, ePhotosynthesis::conditions::RACondition::parentRedoxReg, RA_con, and XanCycle_con.
DynaPSCondition() [4/4]
DynaPSCondition::DynaPSCondition (const arr & vec, const std::size_t offset = 0)
Constructor to create an object from the input vector, starting at the given index
Parameters
vec Vector to create the object from
offset The index in vec to start creating the object from
Definition at line 55 of file DynaPSCondition.cpp.
Member Function Documentation
_size()
static std::size_t ePhotosynthesis::conditions::DynaPSCondition::_size () inline static private
Get the size of the data vector
Returns
The size of the serialized vector.
Definition at line 90 of file DynaPSCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >::size().
Field Documentation
RA_con
RACondition* ePhotosynthesis::conditions::DynaPSCondition::RA_con = nullptr
Definition at line 81 of file DynaPSCondition.hpp.
Referenced by DynaPSCondition(), and DynaPSCondition().
XanCycle_con
XanCycleCondition* ePhotosynthesis::conditions::DynaPSCondition::XanCycle_con = nullptr
Definition at line 82 of file DynaPSCondition.hpp.
Referenced by DynaPSCondition(), and DynaPSCondition().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/conditions/DynaPSCondition.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/conditions/DynaPSCondition.cpp