ePhotosynthesis: ePhotosynthesis::Variables Class Reference
ePhotosynthesis::Variables Class Reference
#include <Variables.hpp>
Public Member Functions
Variables ()
~Variables ()
Variables (const Variables *other)
Variables (const Variables &other)
EPHOTO_API void finalizeInputs ()
EPHOTO_API Variables * deepcopy () const
bool equals (const ValueSet_t &b, const bool noChildren=false) const override
void setRecord (const ValueSet_t *x, std::map< MODULE, const ValueSet_t * > &conditions)
void setRecord (const ValueSet_t *x)
void setRecord (ValueSet_t *x, std::map< MODULE, ValueSet_t * > &conditions)
void dump (const std::string &filename, const bool includeSkipped=false, const std::vector< MODULE > &skip_modules={}, const std::vector< PARAM_TYPE > &skip_param_types={}, const std::vector< std::string > &skip_keys={}, const std::map< std::string, std::string > &key_aliases={}, const std::map< MODULE, const ValueSet_t * > &conditions={}, const std::vector< std::string > &subset={}) const
std::ostream & dump (std::ostream &out, const bool includeSkipped=false, const std::vector< MODULE > &skip_modules={}, const std::vector< PARAM_TYPE > &skip_param_types={}, const std::vector< std::string > &skip_keys={}, const std::map< std::string, std::string > &key_aliases={}, const std::map< MODULE, const ValueSet_t * > &conditions={}, const std::vector< std::string > &subset={}) const
std::ostream & dump (const MODULE &module, const PARAM_TYPE &param_type, std::ostream &out, std::size_t pad, const bool includeSkipped=false, const std::vector< MODULE > &skip_modules={}, const std::vector< PARAM_TYPE > &skip_param_types={}, const std::vector< std::string > &skip_keys={}, const std::map< std::string, std::string > &key_aliases={}, const std::map< MODULE, const ValueSet_t * > &conditions={}) const
EPHOTO_API void initParam (const MODULE &mod, const PARAM_TYPE &pt, const bool noDefaults=false, const bool force=false, ValueSet_t *value_set=nullptr)
EPHOTO_API std::size_t max_value_width_all () const
EPHOTO_API void setControlVar (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name, const int &value)
EPHOTO_API int getControlVar (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name) const
EPHOTO_API void setVar (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name, const double &value, const bool &isGlymaID=false)
EPHOTO_API void setVar (const MODULE &mod, const PARAM_TYPE &pt, const int &key, const double &value)
EPHOTO_API void setVar (const std::string &k, const double &value, const bool &isGlymaID=false)
EPHOTO_API double getVar (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name, const bool &isGlymaID=false) const
EPHOTO_API double getVar (const MODULE &mod, const PARAM_TYPE &pt, const int &key) const
EPHOTO_API double getVar (const std::string &k, const bool &isGlymaID=false) const
ValueSet_t * getValueSet (const MODULE &mod, const PARAM_TYPE &pt=PARAM_TYPE_MOD, const bool no_error_on_invalid=false, const std::map< MODULE, ValueSet_t * > &conditions={}, const std::string &error_context="")
const ValueSet_t * getValueSet (const MODULE &mod, const PARAM_TYPE &pt=PARAM_TYPE_MOD, const bool no_error_on_invalid=false, const std::map< MODULE, const ValueSet_t * > &conditions={}, const std::string &error_context="") const
EPHOTO_API void readParam (const std::string &fname)
EPHOTO_API void readParam (const std::string &fname, std::map< std::string, std::string > &inputs)
EPHOTO_API void readEnzymeAct (const std::string &fname)
EPHOTO_API void readGRN (const std::string &fname)
VARS_INST_APPLY_TO_MEMBERS (DO_MEMBERS)
Static Public Member Functions
static EPHOTO_API void initAllDefaults (const bool useC3=false)
static EPHOTO_API void initDefaults (const MODULE &module, const PARAM_TYPE &param_type, const bool useC3=false, const std::string &filename="", const bool force=true)
static EPHOTO_API bool isSelected (const MODULE &mod, const PARAM_TYPE &pt)
static EPHOTO_API std::size_t max_field_width_all ()
static EPHOTO_API std::string parseVar (const std::string &k, MODULE &mod, PARAM_TYPE &pt, const bool &isGlymaID=false, const bool &use_1st_match=false, const bool &allow_no_match=false, bool *controlVar=nullptr)
static EPHOTO_API bool hasVar (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name, const bool &isGlymaID=false, bool *controlVar=nullptr)
static EPHOTO_API bool hasVar (const std::string &name, const bool &isGlymaID=false, bool *controlVar=nullptr)
static EPHOTO_API bool isControlVar (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name)
static EPHOTO_API std::string getControlDocs (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name)
static EPHOTO_API std::string getControlAlias (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name)
static EPHOTO_API int getKey (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name, const bool &isGlymaID=false)
static EPHOTO_API double getDefault (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name, const bool &isGlymaID=false)
static EPHOTO_API double getDefault (const MODULE &mod, const PARAM_TYPE &pt, const int &key)
static EPHOTO_API double getDefault (const std::string &k, const bool &isGlymaID=false)
static EPHOTO_API void setDefault (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name, const double &value, const bool &isGlymaID=false)
static EPHOTO_API void setDefault (const MODULE &mod, const PARAM_TYPE &pt, const int &key, const double &value)
static EPHOTO_API void setDefault (const std::string &k, const double &value, const bool &isGlymaID=false)
static EPHOTO_API std::string getDocs (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name, const bool &isGlymaID=false)
static EPHOTO_API std::string getDocs (const MODULE &mod, const PARAM_TYPE &pt, const int &key)
static EPHOTO_API std::string getDocs (const std::string &k, const bool &isGlymaID=false)
static EPHOTO_API std::vector< PARAM_TYPE > getParamTypes (const MODULE &mod, const bool for_instance=false, const bool include_cond=false, const std::map< MODULE, const ValueSet_t * > &conditions={})
static ValueSetClass_t * getModule (const MODULE &mod, const bool no_error_on_invalid=false, const std::string &error_context="")
static ValueSetClass_t * getValueSetClass (const MODULE &mod, const PARAM_TYPE &pt=PARAM_TYPE_MOD, const bool no_error_on_invalid=false, const std::string &error_context="")
static EPHOTO_API void updateParam (std::map< std::string, std::string > &inputs, Variables *theVars=nullptr, const std::string &context="updateParam")
static EPHOTO_API void readDefaults (const std::string &fname)
static EPHOTO_API void readDefaults (const std::string &fname, std::map< std::string, std::string > &inputs)
Data Fields
bool inputsFinalized = false
bool record = false
int GP = 0
int GRNC = 0
int GRNT = 0
int PAR_in_Wpm2 = 0
int VolRatioStCyto = 1
int RUBISCOMETHOD = 1
std::map< std::string, double > EnzymeAct
arr VfactorCp = zeros(33)
arr VfactorT = ones(28)
arr FluxTR = {}
TimeSeries< std::vector< double > > CO2A = TimeSeries<std::vector<double> > ()
std::vector< arr > RedoxReg_MP
bool useC3 = false
Protected Member Functions
void __copyMembers (const Variables &other) override
std::string _diff (const Variables &other, std::size_t padKeys=0, std::size_t padVals=0, bool includePrefixes=false, bool noChildren=false) const override
Static Protected Member Functions
static void _initStaticMembers ()
Static Private Member Functions
static void setDefaultControlVar (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name, const int &value)
static int getDefaultControlVar (const MODULE &mod, const PARAM_TYPE &pt, const std::string &name)
static void _readParam (const std::string &fname, std::map< std::string, std::string > &inputs, Variables *theVars=nullptr, const std::string &context="_readParam")
Friends
EPHOTO_API friend std::ostream & operator<< (std::ostream &out, const Variables *in)
Detailed Description
Structure to hold global variables
Definition at line 86 of file Variables.hpp.
Constructor & Destructor Documentation
Variables() [1/3]
Variables::Variables ()
Construct a new variables instance for a given sundials context
Definition at line 98 of file Variables.cpp.
References useC3.
Referenced by __copyMembers(), _diff(), _readParam(), deepcopy(), equals(), getValueSet(), operator<<, updateParam(), Variables(), and Variables().
~Variables()
Variables::~Variables ()
Destructor
Definition at line 108 of file Variables.cpp.
Variables() [2/3]
Variables::Variables (const Variables * other)
Copy constructor for a pointer to another variables instance. Some variables are not included in the default copy (e.g. alfa, fc, lightParam, CO2A, RedoxReg_MP, module *_Param values, & rates). To include these, use deepcopy.
Parameters
[in] other Variables instance to copy.
Definition at line 111 of file Variables.cpp.
References Variables().
Variables() [3/3]
Variables::Variables (const Variables & other)
Copy constructor. Some variables are not included in the default copy (e.g. alfa, fc, lightParam, CO2A, RedoxReg_MP, module *_Param values, & rates). To include these, use deepcopy.
Parameters
[in] other Variables instance to copy.
Definition at line 104 of file Variables.cpp.
References Variables().
Member Function Documentation
__copyMembers()
void Variables::__copyMembers (const Variables & other) override protected
Copy additional members. Some variables are not included in the default copy (e.g. alfa, fc, lightParam, CO2A, RedoxReg_MP, module *_Param values, & rates). To include these, use deepcopy.
Parameters
[in] other Variables instance to copy.
Definition at line 114 of file Variables.cpp.
References DO_MEMBERS, EnzymeAct, FluxTR, GP, GRNC, GRNT, inputsFinalized, PAR_in_Wpm2, record, RUBISCOMETHOD, useC3, Variables(), VARS_INST_APPLY_TO_MEMBERS, VfactorCp, VfactorT, and VolRatioStCyto.
_diff()
std::string Variables::_diff (const Variables & other, std::size_t padKeys = 0, std::size_t padVals = 0, bool includePrefixes = false, bool noChildren = false) const override protected
Get the diff between this an another value set.
Parameters
other Value set to compare against.
padKeys Number of characters that key names should be padded to fill.
padVals Number of characters that values should be padded to fill.
includePrefixes If true, the module & parameter type prefixes will be added to the member names.
noChildren If true, children of composite sets will not be displayed.
Returns
String diff.
Definition at line 199 of file Variables.cpp.
References FITER, Variables(), and VARS_ITER_MACRO_INST.
_initStaticMembers()
void Variables::_initStaticMembers () static protected
Definition at line 61 of file Variables.cpp.
_readParam()
void Variables::_readParam (const std::string & fname, std::map< std::string, std::string > & inputs, Variables * theVars = nullptr, const std::string & context = "_readParam") static private
Definition at line 1042 of file Variables.cpp.
References ePhotosynthesis::readFile(), updateParam(), and Variables().
Referenced by readDefaults(), readDefaults(), readParam(), and readParam().
deepcopy()
Variables * Variables::deepcopy () const
Create a deep copy of this instance including variables excluded from a default copy.
Returns
New instance with all parameters copied.
Definition at line 174 of file Variables.cpp.
References CO2A, DO_MEMBERS, DO_MOD, EXPAND, FOR_EACH, RedoxReg_MP, Variables(), VARS_INST_APPLY_TO_MEMBERS, and VARS_INST_MODULES.
Referenced by ePhotosynthesis::drivers::Driver::dump(), ePhotosynthesis::modules::ModuleBase< T, U, ID >::init(), and ePhotosynthesis::run_simulation().
dump() [1/3]
std::ostream & Variables::dump (const MODULE & module, const PARAM_TYPE & param_type, std::ostream & out, std::size_t pad, const bool includeSkipped = false, const std::vector< MODULE > & skip_modules = {}, const std::vector< PARAM_TYPE > & skip_param_types = {}, const std::vector< std::string > & skip_keys = {}, const std::map< std::string, std::string > & key_aliases = {}, const std::map< MODULE, const ValueSet_t * > & conditions = {}) const
Serialize parameters for a single value set to an output stream.
Parameters
[in] module ID for module that should be serialized.
[in] param_type ID for parameter type that should be serialized.
[in,out] out Output stream.
pad Number of characters that key names should be padded to fill.
[in] includeSkipped If true, skipped keys will be output.
[in] skip_modules Vector of IDs for modules that should not be serialized.
[in] skip_param_types Vector of IDs for parameter types that should not be serialized.
[in] skip_keys Key strings to skip in output.
[in] key_aliases String aliases to use for keys.
[in] conditions Map of conditions for composite modules that are not stored on Variables instances.
Returns
Updated output stream.
Definition at line 401 of file Variables.cpp.
References GET_VALUE_SET, isSelected(), ePhotosynthesis::ValueSetEnum< M, PT >::module, and ePhotosynthesis::ValueSetEnum< M, PT >::param_type.
dump() [2/3]
void Variables::dump (const std::string & filename, const bool includeSkipped = false, const std::vector< MODULE > & skip_modules = {}, const std::vector< PARAM_TYPE > & skip_param_types = {}, const std::vector< std::string > & skip_keys = {}, const std::map< std::string, std::string > & key_aliases = {}, const std::map< MODULE, const ValueSet_t * > & conditions = {}, const std::vector< std::string > & subset = {}) const
Serialize all parameters attached to this instance to a file.
Parameters
[in] filename Name of file where parameters should be written.
[in] includeSkipped If true, skipped keys will be output.
[in] skip_modules Vector of IDs for modules that should not be serialized.
[in] skip_param_types Vector of IDs for parameter types that should not be serialized.
[in] skip_keys Key strings to skip in output.
[in] key_aliases String aliases to use for keys.
[in] conditions Map of conditions for composite modules that are not stored on Variables instances.
[in] subset Subset of parameters to output.
Definition at line 339 of file Variables.cpp.
References dump().
Referenced by ePhotosynthesis::drivers::Driver::dump(), and dump().
dump() [3/3]
std::ostream & Variables::dump (std::ostream & out, const bool includeSkipped = false, const std::vector< MODULE > & skip_modules = {}, const std::vector< PARAM_TYPE > & skip_param_types = {}, const std::vector< std::string > & skip_keys = {}, const std::map< std::string, std::string > & key_aliases = {}, const std::map< MODULE, const ValueSet_t * > & conditions = {}, const std::vector< std::string > & subset = {}) const
Serialize all parameters attached to this instance to an output stream.
Parameters
[in,out] out Output stream.
[in] includeSkipped If true, skipped keys will be output.
[in] skip_modules Vector of IDs for modules that should not be serialized.
[in] skip_param_types Vector of IDs for parameter types that should not be serialized.
[in] skip_keys Key strings to skip in output.
[in] key_aliases String aliases to use for keys.
[in] conditions Map of conditions for composite modules that are not stored on Variables instances.
[in] subset Subset of parameters to output.
Returns
Updated output stream.
Definition at line 353 of file Variables.cpp.
References FITER, getControlVar(), getValueSetClass(), max_field_width_all(), parseVar(), and VARS_ITER_MACRO_COND.
equals()
bool Variables::equals (const ValueSet_t & b, const bool noChildren = false) const override
Check if another value set is equivalent to this one.
Parameters
b Value set to compare against this one.
noChildren If true, child classes will not be checked.
Definition at line 215 of file Variables.cpp.
References CHECK, CHECK_COM, CO2A, EnzymeAct, EXPAND, FITER, FluxTR, FOR_EACH, GP, GRNC, GRNT, inputsFinalized, PAR_in_Wpm2, record, RedoxReg_MP, RUBISCOMETHOD, useC3, Variables(), VARS_INST_CONNECTIONS, VARS_ITER_MACRO_COND, VfactorCp, VfactorT, and VolRatioStCyto.
finalizeInputs()
void Variables::finalizeInputs ()
Finalize variables read from input including any unit changes.
Definition at line 148 of file Variables.cpp.
References inputsFinalized, PAR_in_Wpm2, and useC3.
Referenced by ePhotosynthesis::drivers::Driver::Driver().
getControlAlias()
std::string Variables::getControlAlias (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name) static
Get the aliased version of a control variable name.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
Returns
Aliased control variable name.
Definition at line 692 of file Variables.cpp.
Referenced by parseVar().
getControlDocs()
std::string Variables::getControlDocs (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name) static
Get the documentation string for a control variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
Returns
Variable doc string.
Definition at line 700 of file Variables.cpp.
References ePhotosynthesis::utils::enum_key2string(), and ERROR_VALUE_SET.
Referenced by getDocs(), and getDocs().
getControlVar()
int Variables::getControlVar (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name) const
Get the value of a control variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
Returns
Variable value.
Definition at line 668 of file Variables.cpp.
References CHECK_CONTROL_MOD, CONTROL_Variables, ePhotosynthesis::utils::enum_key2string(), ERROR_VALUE_SET, EVAL, EXPAND, FOR_EACH, and SET_CONTROL.
Referenced by dump(), getVar(), and getVar().
getDefault() [1/3]
double Variables::getDefault (const MODULE & mod, const PARAM_TYPE & pt, const int & key) static
Get the default value for a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] key Key identifying the variable.
Definition at line 785 of file Variables.cpp.
References GET_VALUE_SET_CLASS.
getDefault() [2/3]
double Variables::getDefault (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name, const bool & isGlymaID = false) static
Get the default value for a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Definition at line 778 of file Variables.cpp.
References GET_VALUE_SET_CLASS.
Referenced by getDefault().
getDefault() [3/3]
double Variables::getDefault (const std::string & k, const bool & isGlymaID = false) static
Set the default value for a variable in a value set.
Parameters
[in] k String identifying the variable.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Definition at line 789 of file Variables.cpp.
References getDefault(), getDefaultControlVar(), and parseVar().
getDefaultControlVar()
int Variables::getDefaultControlVar (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name) static private
Get the default value of a control variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
Returns
Variable default value.
Definition at line 739 of file Variables.cpp.
References ePhotosynthesis::utils::enum_key2string(), and ERROR_VALUE_SET.
Referenced by getDefault().
getDocs() [1/3]
std::string Variables::getDocs (const MODULE & mod, const PARAM_TYPE & pt, const int & key) static
Get the documentation string for a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] key Key identifying the variable.
Returns
Variable doc string.
Definition at line 887 of file Variables.cpp.
References GET_VALUE_SET_CLASS, ePhotosynthesis::ValueSetEnum< M, PT >::module, and ePhotosynthesis::ValueSetEnum< M, PT >::param_type.
getDocs() [2/3]
std::string Variables::getDocs (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name, const bool & isGlymaID = false) static
Get the documentation string for a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Returns
Variable doc string.
Definition at line 878 of file Variables.cpp.
References GET_VALUE_SET_CLASS, getControlDocs(), isControlVar(), ePhotosynthesis::ValueSetEnum< M, PT >::module, and ePhotosynthesis::ValueSetEnum< M, PT >::param_type.
Referenced by getDocs().
getDocs() [3/3]
std::string Variables::getDocs (const std::string & k, const bool & isGlymaID = false) static
Get the documentation string for a variable in a value set.
Parameters
[in] k String identifying the variable.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Returns
Variable doc string.
Definition at line 892 of file Variables.cpp.
References getControlDocs(), getDocs(), and parseVar().
getKey()
int Variables::getKey (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name, const bool & isGlymaID = false) static
Get the integer key for a value set variable.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Returns
Variable key.
Definition at line 773 of file Variables.cpp.
References GET_VALUE_SET_CLASS.
getModule()
ValueSetClass_t * Variables::getModule (const MODULE & mod, const bool no_error_on_invalid = false, const std::string & error_context = "") static
Get a ValueSetClass_t instance for a module that can be used to call virtual methods.
Parameters
[in] mod Module ID.
[in] no_error_on_invalid If true, no error will be thrown if the combination of mod & pt are unrecognized.
[in] error_context String providing context for errors.
Returns
Pointer to ValueSetClass_t instance.
Definition at line 926 of file Variables.cpp.
References getValueSetClass().
Referenced by getParamTypes().
getParamTypes()
std::vector< PARAM_TYPE > Variables::getParamTypes (const MODULE & mod, const bool for_instance = false, const bool include_cond = false, const std::map< MODULE, const ValueSet_t * > & conditions = {}) static
Get the set of parameters types for a module.
Parameters
[in] mod Module ID.
[in] for_instance If true, parameter types that do not have instances in Variables will be excluded.
[in] include_cond If true, local copies of conditions will be included.
[in] conditions Map of conditions for composite modules that are not stored on Variables instances.
Definition at line 904 of file Variables.cpp.
References getModule(), ePhotosynthesis::ValueSetEnum< M, PT >::all, ePhotosynthesis::ValueSetEnum< M, PT >::module, and VARS_INST_IS_MODULE.
getValueSet() [1/2]
const ValueSet_t * Variables::getValueSet (const MODULE & mod, const PARAM_TYPE & pt = PARAM_TYPE_MOD, const bool no_error_on_invalid = false, const std::map< MODULE, const ValueSet_t * > & conditions = {}, const std::string & error_context = "") const
Get a constant ValueSet_t* instance for a value set that can be used to call virtual methods.
Parameters
[in] mod Module associated with the value set.
[in] pt Parameter type associated with the value set.
[in] no_error_on_invalid If true, no error will be thrown if the combination of mod & pt are unrecognized.
[in] conditions Map of conditions for composite modules that are not stored on Variables instances.
[in] error_context String providing context for errors.
Returns
Constant pointer to ValueSet_t instance.
Definition at line 970 of file Variables.cpp.
References ePhotosynthesis::utils::enum_key2string(), ERROR_VALUE_SET, getValueSet(), MOD2PT_COND, MOD2PT_NO_COND, SWITCH_MOD, SWITCH_MOD_AND_PT, VARS_CLASS_MODULES, VARS_INST_CALL, VARS_INST_CALL_STATIC, VARS_INST_MODULES, and VARS_RETURN_CALL.
getValueSet() [2/2]
ValueSet_t * Variables::getValueSet (const MODULE & mod, const PARAM_TYPE & pt = PARAM_TYPE_MOD, const bool no_error_on_invalid = false, const std::map< MODULE, ValueSet_t * > & conditions = {}, const std::string & error_context = "")
Get a ValueSet_t* instance for a value set that can be used to call virtual methods.
Parameters
[in] mod Module associated with the value set.
[in] pt Parameter type associated with the value set.
[in] no_error_on_invalid If true, no error will be thrown if the combination of mod & pt are unrecognized.
[in] conditions Map of conditions for composite modules that are not stored on Variables instances.
[in] error_context String providing context for errors.
Returns
Pointer to ValueSet_t instance.
Definition at line 959 of file Variables.cpp.
References Variables().
Referenced by getValueSet().
getValueSetClass()
ValueSetClass_t * Variables::getValueSetClass (const MODULE & mod, const PARAM_TYPE & pt = PARAM_TYPE_MOD, const bool no_error_on_invalid = false, const std::string & error_context = "") static
Get a constant ValueSetClass_t instance for a value set that can be used to call static methods.
Parameters
[in] mod Module associated with the value set.
[in] pt Parameter type associated with the value set.
[in] no_error_on_invalid If true, no error will be thrown if the combination of mod & pt are unrecognized.
[in] error_context String providing context for errors.
Returns
Pointer to ValueSetClass_t instance.
Definition at line 932 of file Variables.cpp.
References ePhotosynthesis::utils::enum_key2string(), ERROR_VALUE_SET, getValueSetClass(), MOD2PT, SWITCH_MOD, SWITCH_MOD_AND_PT, VARS_CLASS_CALL, VARS_CLASS_CALL_STATIC, VARS_CLASS_MODULES, and VARS_RETURN_CALL.
Referenced by dump(), getModule(), getValueSetClass(), and hasVar().
getVar() [1/3]
double Variables::getVar (const MODULE & mod, const PARAM_TYPE & pt, const int & key) const
Get the value of a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] key Key identifying the variable.
Returns
Variable value.
Definition at line 861 of file Variables.cpp.
References GET_VALUE_SET, ePhotosynthesis::ValueSetEnum< M, PT >::module, and ePhotosynthesis::ValueSetEnum< M, PT >::param_type.
getVar() [2/3]
double Variables::getVar (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name, const bool & isGlymaID = false) const
Get the value of a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Returns
Variable value.
Definition at line 852 of file Variables.cpp.
References GET_VALUE_SET, getControlVar(), isControlVar(), ePhotosynthesis::ValueSetEnum< M, PT >::module, and ePhotosynthesis::ValueSetEnum< M, PT >::param_type.
Referenced by getVar().
getVar() [3/3]
double Variables::getVar (const std::string & k, const bool & isGlymaID = false) const
Get the value of a variable in a value set.
Parameters
[in] k String identifying the variable.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Returns
Variable value.
Definition at line 866 of file Variables.cpp.
References getControlVar(), getVar(), and parseVar().
hasVar() [1/2]
bool Variables::hasVar (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name, const bool & isGlymaID = false, bool * controlVar = nullptr) static
Check if a value set has a variable that matches the provided string.
Parameters
[in] mod Module associated with the value set that should be checked.
[in] pt Parameter type associated with the value set that should be checked.
[in] name String to check against variables in the value set.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
[in] controlVar If provided, the target will be set to true if the string refers to a control parameter and false otherwise. If not provided and k is a control parameter, an error will be raised.
Returns
true if the variable is part of the value set, false otherwise.
Definition at line 748 of file Variables.cpp.
References getValueSetClass(), and isControlVar().
Referenced by hasVar(), and parseVar().
hasVar() [2/2]
bool Variables::hasVar (const std::string & name, const bool & isGlymaID = false, bool * controlVar = nullptr) static
Check if there is a variable that matches the provided string.
Parameters
[in] name String to check against variables.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
[in] controlVar If provided, the target will be set to true if the string refers to a control parameter and false otherwise. If not provided and k is a control parameter, an error will be raised.
Returns
true if the variable is part of a value set, false otherwise.
Definition at line 762 of file Variables.cpp.
References hasVar(), and parseVar().
initAllDefaults()
void Variables::initAllDefaults (const bool useC3 = false) static
Initialize the default values for all value sets selected by the current driver.
Parameters
useC3 If true, C3 defaults should be used.
Definition at line 439 of file Variables.cpp.
References initDefaults(), useC3, and VARS_ITER_ALL_CLASS.
initDefaults()
void Variables::initDefaults (const MODULE & module, const PARAM_TYPE & param_type, const bool useC3 = false, const std::string & filename = "", const bool force = true) static
Initialize the default values for a value set.
Parameters
module Value set module.
param_type Value set parameter type.
useC3 If true, C3 defaults should be used.
filename Full path to a file containing values that should be used as defaults in the value set.
force If true, the defaults will be initialized reguardless of if the value set is selected by the current driver or not. If false, a warning will be generated when the value set is not selected and the defaults will not be initialized.
Definition at line 442 of file Variables.cpp.
References ePhotosynthesis::utils::enum_key2string(), GET_VALUE_SET_CLASS, INFO_VALUE_SET, isSelected(), and useC3.
Referenced by initAllDefaults().
initParam()
void Variables::initParam (const MODULE & mod, const PARAM_TYPE & pt, const bool noDefaults = false, const bool force = false, ValueSet_t * value_set = nullptr)
Initialize the parameters for a value set.
Parameters
mod Value set module.
pt Value set parameter type.
noDefaults If true, the value pointers will be initialized, but the default values will not be assigned to those values.
force If true, initialize the values even if they have already been initialized.
value_set Pointer to the value set that should be initialized if different than the default version attached to Variables.
Definition at line 432 of file Variables.cpp.
References GET_VALUE_SET, GET_VALUE_SET_CLASS, and useC3.
Referenced by ePhotosynthesis::modules::ModuleBase< T, U, ID >::initAllValues().
isControlVar()
bool Variables::isControlVar (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name) static
Check if a string matches a control parameter.
Parameters
[in] mod Module associated with the value set that should be checked.
[in] pt Parameter type associated with the value set that should be checked.
[in] name String to check against control parameters.
Returns
true if the variable is a control parameter, false otherwise.
Definition at line 619 of file Variables.cpp.
References CHECK_CONTROL, CHECK_CONTROL_MOD, CONTROL_Variables, EVAL, EXPAND, and FOR_EACH.
Referenced by getDocs(), getVar(), hasVar(), setDefault(), and setVar().
isSelected()
bool Variables::isSelected (const MODULE & mod, const PARAM_TYPE & pt) static
Check if a value set is selected by the current driver.
Parameters
[in] mod Module type of value set to check.
[in] pt Parameter type of value set to check.
Returns
true if the value set is selected, false otherwise.
Definition at line 465 of file Variables.cpp.
References GET_VALUE_SET_CLASS.
Referenced by dump(), initDefaults(), and parseVar().
max_field_width_all()
std::size_t Variables::max_field_width_all () static
Get the maximum field width of all selected value sets for use in aligning field names.
Returns
Maximum field width.
Definition at line 469 of file Variables.cpp.
References MAX_WIDTH, and VARS_ITER_MACRO_CLASS.
Referenced by ePhotosynthesis::modules::ModuleBase< T, U, ID >::diffState(), and dump().
max_value_width_all()
std::size_t Variables::max_value_width_all () const
Get the maximum value width of all selected value sets for use in aligning values.
Returns
Maximum value width.
Definition at line 480 of file Variables.cpp.
References ePhotosynthesis::ALL_MODULE, GET_VALUE_SET_CLASS, MAX_WIDTH, and VARS_ITER_MACRO.
Referenced by ePhotosynthesis::modules::ModuleBase< T, U, ID >::diffState().
parseVar()
std::string Variables::parseVar (const std::string & k, MODULE & mod, PARAM_TYPE & pt, const bool & isGlymaID = false, const bool & use_1st_match = false, const bool & allow_no_match = false, bool * controlVar = nullptr) static
Parse a variable string, checking if there is a prefix containing information on the module and/or parameter type associated with the value set that the variable belongs to. If this information is not provided, all value sets will be checked.
Parameters
[in] k String to parse.
[out] mod Module that the variable was determined to belong to.
[out] pt Parameter type that the variable was determined to belong to.
[in] isGlymaID If true, k is assumed to contain a GlymaID instead of a variable name.
[in] use_1st_match If true, the first variable matching the provided string will be returned. If false and there is more than one match, an error will be thrown.
[in] allow_no_match If true, an empty string will be returned if there is not match.
[in] controlVar If provided, the target will be set to true if the string refers to a control parameter and false otherwise. If not provided and k is a control parameter, an error will be raised.
Returns
Variable name extracted from k.
Definition at line 499 of file Variables.cpp.
References ePhotosynthesis::ALL_MODULE, ePhotosynthesis::ALL_PARAM_TYPE, ePhotosynthesis::utils::enum_key2string(), ePhotosynthesis::utils::enum_string2key(), ERROR_VALUE_SET, GET_VALUE_SET_CLASS, getControlAlias(), hasVar(), INFO_VALUE_SET, and isSelected().
Referenced by dump(), getDefault(), getDocs(), getVar(), hasVar(), setDefault(), setVar(), and updateParam().
readDefaults() [1/2]
void Variables::readDefaults (const std::string & fname) static
Read default parameters from a file.
Parameters
[in] fname File to read.
Definition at line 1167 of file Variables.cpp.
References _readParam().
readDefaults() [2/2]
void Variables::readDefaults (const std::string & fname, std::map< std::string, std::string > & inputs) static
Read default parameters from a file, checking for duplicates
Parameters
[in] fname File to read.
[in,out] inputs Map that read variables should be checked against for duplicates and copied into.
Definition at line 1171 of file Variables.cpp.
References _readParam().
readEnzymeAct()
void Variables::readEnzymeAct (const std::string & fname)
Read Enzyme activities from a file.
Parameters
[in] File to read.
Definition at line 1121 of file Variables.cpp.
References EnzymeAct, and ePhotosynthesis::readFile().
Referenced by ePhotosynthesis::run_simulation().
readGRN()
void Variables::readGRN (const std::string & fname)
Read genetic regulatory network expression data from a file.
Parameters
[in] File to read.
Definition at line 1127 of file Variables.cpp.
References ePhotosynthesis::glymaID_order, GRNC, ePhotosynthesis::readFile(), and VfactorCp.
Referenced by ePhotosynthesis::run_simulation().
readParam() [1/2]
void Variables::readParam (const std::string & fname)
Read parameters from a file.
Parameters
[in] fname File to read.
Definition at line 1175 of file Variables.cpp.
References _readParam().
Referenced by ePhotosynthesis::run_simulation().
readParam() [2/2]
void Variables::readParam (const std::string & fname, std::map< std::string, std::string > & inputs)
Read parameters from a file, checking for duplicates
Parameters
[in] fname File to read.
[in,out] inputs Map that read variables should be checked against for duplicates and copied into.
Definition at line 1179 of file Variables.cpp.
References _readParam().
setControlVar()
void Variables::setControlVar (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name, const int & value)
Set the value for a control variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
[in] value The new value.
Definition at line 641 of file Variables.cpp.
References CHECK_CONTROL_MOD, CONTROL_Variables, ePhotosynthesis::utils::enum_key2string(), ERROR_VALUE_SET, EVAL, EXPAND, FOR_EACH, and SET_CONTROL.
Referenced by setVar(), setVar(), and updateParam().
setDefault() [1/3]
void Variables::setDefault (const MODULE & mod, const PARAM_TYPE & pt, const int & key, const double & value) static
Set the default value for a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] key Key identifying the variable.
[in] value The new default value.
Definition at line 809 of file Variables.cpp.
References GET_VALUE_SET_CLASS.
setDefault() [2/3]
void Variables::setDefault (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name, const double & value, const bool & isGlymaID = false) static
Set the default value for a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
[in] value The new default value.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Definition at line 801 of file Variables.cpp.
References GET_VALUE_SET_CLASS, isControlVar(), and setDefaultControlVar().
Referenced by setDefault(), and updateParam().
setDefault() [3/3]
void Variables::setDefault (const std::string & k, const double & value, const bool & isGlymaID = false) static
Set the default value for a variable in a value set.
Parameters
[in] k String identifying the variable.
[in] value The new default value.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Definition at line 813 of file Variables.cpp.
References parseVar(), setDefault(), and setDefaultControlVar().
setDefaultControlVar()
void Variables::setDefaultControlVar (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name, const int & value) static private
Set the default value for a control variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
[in] value The new default value.
Definition at line 731 of file Variables.cpp.
References ePhotosynthesis::utils::enum_key2string(), and ERROR_VALUE_SET.
Referenced by setDefault(), setDefault(), and updateParam().
setRecord() [1/3]
void Variables::setRecord (const ValueSet_t * x)
Definition at line 1028 of file Variables.cpp.
References setRecord().
setRecord() [2/3]
void Variables::setRecord (const ValueSet_t * x, std::map< MODULE, const ValueSet_t * > & conditions)
Record a value set by copying it into this set of Variables.
Parameters
[in] x Value set to record.
[in] conditions Map that conditions for composite modules that are not stored on Variables instances should be added to.
Definition at line 1009 of file Variables.cpp.
References DO_ASSIGN, ePhotosynthesis::ValueSet_t::getChildren(), INST_MOD_PT_PAIRS, setRecord(), and SWITCH_MOD_AND_PT_PAIRS.
Referenced by ePhotosynthesis::drivers::Driver::dump(), setRecord(), setRecord(), and setRecord().
setRecord() [3/3]
void Variables::setRecord (ValueSet_t * x, std::map< MODULE, ValueSet_t * > & conditions)
Definition at line 1032 of file Variables.cpp.
References setRecord().
setVar() [1/3]
void Variables::setVar (const MODULE & mod, const PARAM_TYPE & pt, const int & key, const double & value)
Set the value for a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] key Key identifying the variable.
[in] value The new value.
Definition at line 835 of file Variables.cpp.
References GET_VALUE_SET, ePhotosynthesis::ValueSetEnum< M, PT >::module, and ePhotosynthesis::ValueSetEnum< M, PT >::param_type.
setVar() [2/3]
void Variables::setVar (const MODULE & mod, const PARAM_TYPE & pt, const std::string & name, const double & value, const bool & isGlymaID = false)
Set the value for a variable in a value set.
Parameters
[in] mod Module associated with the value set that the variable is part of.
[in] pt Parameter type associated with the value set that the variable is part of.
[in] name String identifying the variable.
[in] value The new value.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Definition at line 825 of file Variables.cpp.
References GET_VALUE_SET, isControlVar(), setControlVar(), ePhotosynthesis::ValueSetEnum< M, PT >::module, and ePhotosynthesis::ValueSetEnum< M, PT >::param_type.
Referenced by setVar(), and updateParam().
setVar() [3/3]
void Variables::setVar (const std::string & k, const double & value, const bool & isGlymaID = false)
Set the value for a variable in a value set.
Parameters
[in] k String identifying the variable.
[in] value The new value.
[in] isGlymaID If true, name will be treated as a GlymaID. If false, name will be treated as the variable name.
Definition at line 840 of file Variables.cpp.
References parseVar(), setControlVar(), and setVar().
updateParam()
void Variables::updateParam (std::map< std::string, std::string > & inputs, Variables * theVars = nullptr, const std::string & context = "updateParam") static
Update the default parameters from a map.
Parameters
[in,out] inputs Map of parameters that should be added.
[in] theVars Variable instance that should be updated.
[in] context String providing context for errors.
Definition at line 1052 of file Variables.cpp.
References ePhotosynthesis::utils::enum_key2string(), parseVar(), setControlVar(), setDefault(), setDefaultControlVar(), setVar(), ePhotosynthesis::utils::str_endswith(), and Variables().
Referenced by _readParam(), and ePhotosynthesis::run_simulation().
VARS_INST_APPLY_TO_MEMBERS()
ePhotosynthesis::Variables::VARS_INST_APPLY_TO_MEMBERS (DO_MEMBERS)
References DO_MEMBERS.
Friends And Related Symbol Documentation
operator<<
EPHOTO_API friend std::ostream & operator<< (std::ostream & out, const Variables * in) friend
Serialization operator.
Parameters
[in,out] out Output stream.
[in] in Instance to serialize.
Returns
Updated output stream.
References Variables().
Field Documentation
CO2A
TimeSeries<std::vector<double> > ePhotosynthesis::Variables::CO2A = TimeSeries<std::vector<double> > ()
Definition at line 834 of file Variables.hpp.
Referenced by deepcopy(), equals(), and ePhotosynthesis::GenOut().
EnzymeAct
std::map<std::string, double> ePhotosynthesis::Variables::EnzymeAct
Map of enzyme activity levels used when GP == 0
Definition at line 826 of file Variables.hpp.
Referenced by __copyMembers(), equals(), and readEnzymeAct().
FluxTR
arr ePhotosynthesis::Variables::FluxTR = {}
Definition at line 832 of file Variables.hpp.
Referenced by __copyMembers(), equals(), ePhotosynthesis::makeFluxTR(), and ePhotosynthesis::operator<<().
GP
int ePhotosynthesis::Variables::GP = 0
Definition at line 814 of file Variables.hpp.
Referenced by __copyMembers(), equals(), and ePhotosynthesis::operator<<().
GRNC
int ePhotosynthesis::Variables::GRNC = 0
Control parameter; if 1, VfactorCp values will be used to scale enzyme activities in the PS, PR, & SUCS modules when CO2 > 0
Definition at line 815 of file Variables.hpp.
Referenced by __copyMembers(), equals(), ePhotosynthesis::operator<<(), and readGRN().
GRNT
int ePhotosynthesis::Variables::GRNT = 0
Control parameter; if 1, VfactorT values will be used to scale enzyme activities in the PS, PR, & SUCS modules when T > 25
Definition at line 816 of file Variables.hpp.
Referenced by __copyMembers(), equals(), and ePhotosynthesis::operator<<().
inputsFinalized
bool ePhotosynthesis::Variables::inputsFinalized = false
Definition at line 812 of file Variables.hpp.
Referenced by __copyMembers(), equals(), finalizeInputs(), and ePhotosynthesis::operator<<().
PAR_in_Wpm2
int ePhotosynthesis::Variables::PAR_in_Wpm2 = 0
Control parameter; if 1, the input TestLi will be taken to be in units of W/m**2
Definition at line 817 of file Variables.hpp.
Referenced by __copyMembers(), equals(), finalizeInputs(), and ePhotosynthesis::operator<<().
record
bool ePhotosynthesis::Variables::record = false
Definition at line 813 of file Variables.hpp.
Referenced by __copyMembers(), ePhotosynthesis::modules::RedoxReg::_Rate(), equals(), ePhotosynthesis::GenOut(), ePhotosynthesis::operator<<(), ePhotosynthesis::run_simulation(), and ePhotosynthesis::TargetFunVal().
RedoxReg_MP
std::vector<arr> ePhotosynthesis::Variables::RedoxReg_MP
Definition at line 835 of file Variables.hpp.
Referenced by ePhotosynthesis::modules::RedoxReg::_Rate(), deepcopy(), and equals().
RUBISCOMETHOD
int ePhotosynthesis::Variables::RUBISCOMETHOD = 1
Definition at line 823 of file Variables.hpp.
Referenced by __copyMembers(), equals(), and ePhotosynthesis::operator<<().
useC3
bool ePhotosynthesis::Variables::useC3 = false
Definition at line 853 of file Variables.hpp.
Referenced by __copyMembers(), ePhotosynthesis::drivers::CMDriver::CMDriver(), ePhotosynthesis::Condition(), ePhotosynthesis::drivers::Driver::dump(), ePhotosynthesis::drivers::DynaPSDriver::DynaPSDriver(), ePhotosynthesis::drivers::EPSDriver::EPSDriver(), equals(), finalizeInputs(), initAllDefaults(), initDefaults(), initParam(), ePhotosynthesis::operator<<(), ePhotosynthesis::run_simulation(), ePhotosynthesis::drivers::trDynaPSDriver::trDynaPSDriver(), and Variables().
VfactorCp
arr ePhotosynthesis::Variables::VfactorCp = zeros(33)
Definition at line 828 of file Variables.hpp.
Referenced by __copyMembers(), equals(), ePhotosynthesis::operator<<(), and readGRN().
VfactorT
arr ePhotosynthesis::Variables::VfactorT = ones(28)
Definition at line 829 of file Variables.hpp.
Referenced by __copyMembers(), equals(), and ePhotosynthesis::operator<<().
VolRatioStCyto
int ePhotosynthesis::Variables::VolRatioStCyto = 1
Control parameter; If 1, the ratio between the volume of the stroma and cytosol is 1, otherwise it will be 4.0/9.0. This factor is used to scale rates for the photorespiration (PR) reactions.
Definition at line 818 of file Variables.hpp.
Referenced by __copyMembers(), equals(), ePhotosynthesis::makeFluxTR(), ePhotosynthesis::operator<<(), and ePhotosynthesis::TargetFunVal().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/Variables.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/Variables.cpp