ePhotosynthesis: ePhotosynthesis::conditions::trDynaPSCondition Class Reference
ePhotosynthesis::conditions::trDynaPSCondition Class Reference
#include <trDynaPSCondition.hpp>
Public Member Functions
trDynaPSCondition ()
~trDynaPSCondition () override
trDynaPSCondition (DynaPSCondition *dother, RROEACondition *rother)
trDynaPSCondition (const arr &vec, const std::size_t offset=0)
trDynaPSCondition (realtype *x)
Data Fields
RROEACondition * RROEA_con = nullptr
DynaPSCondition * DynaPS_con = nullptr
Static Private Member Functions
static std::size_t _size ()
Detailed Description
Class for holding inputs to trDynaPS_mb
Definition at line 45 of file trDynaPSCondition.hpp.
Constructor & Destructor Documentation
trDynaPSCondition() [1/4]
ePhotosynthesis::conditions::trDynaPSCondition::trDynaPSCondition () inline
Definition at line 48 of file trDynaPSCondition.hpp.
References DynaPS_con, RROEA_con, and trDynaPSCondition().
Referenced by trDynaPSCondition().
~trDynaPSCondition()
ePhotosynthesis::conditions::trDynaPSCondition::~trDynaPSCondition () inline override
Definition at line 52 of file trDynaPSCondition.hpp.
trDynaPSCondition() [2/4]
trDynaPSCondition::trDynaPSCondition (DynaPSCondition * dother, RROEACondition * rother)
Constructor to create an object from the contained classes
Parameters
dother A DynaPSCon object to incorporate
rother A RROEACon object to incorporate
Definition at line 34 of file trDynaPSCondition.cpp.
References DynaPS_con, ePhotosynthesis::conditions::ConditionBase< T, U, ID >::parent, and RROEA_con.
trDynaPSCondition() [3/4]
trDynaPSCondition::trDynaPSCondition (const arr & vec, const std::size_t offset = 0)
Constructor to create an object from the input vector, starting at the given index
Parameters
vec Vector to create the object from
offset The index in vec to start creating the object from
Definition at line 50 of file trDynaPSCondition.cpp.
trDynaPSCondition() [4/4]
trDynaPSCondition::trDynaPSCondition (realtype * x)
Constructor to create an object from the input pointer
Parameters
x The pointer to get the data from
Definition at line 55 of file trDynaPSCondition.cpp.
References realtype.
Member Function Documentation
_size()
static std::size_t ePhotosynthesis::conditions::trDynaPSCondition::_size () inline static private
Get the size of the data vector
Returns
The size of the serialized vector.
Definition at line 88 of file trDynaPSCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >::size(), and ePhotosynthesis::conditions::ConditionBase< RROEACondition, trDynaPSCondition, MODULE_RROEA >::size().
Field Documentation
DynaPS_con
DynaPSCondition* ePhotosynthesis::conditions::trDynaPSCondition::DynaPS_con = nullptr
Definition at line 80 of file trDynaPSCondition.hpp.
Referenced by trDynaPSCondition(), and trDynaPSCondition().
RROEA_con
RROEACondition* ePhotosynthesis::conditions::trDynaPSCondition::RROEA_con = nullptr
Definition at line 79 of file trDynaPSCondition.hpp.
Referenced by trDynaPSCondition(), and trDynaPSCondition().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/conditions/trDynaPSCondition.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/conditions/trDynaPSCondition.cpp