ePhotosynthesis: ePhotosynthesis::conditions::RedoxRegCondition Class Reference
ePhotosynthesis::conditions::RedoxRegCondition Class Reference
#include <RedoxRegCondition.hpp>
Public Member Functions
RedoxRegCondition ()
~RedoxRegCondition () override
RedoxRegCondition (RACondition *rother, double thio=0.)
RedoxRegCondition (const arr &vec, const std::size_t offset=0)
Data Fields
RACondition * RA_con = nullptr
Static Private Member Functions
static std::size_t _size ()
Detailed Description
Class for holding the inputs to RedoxReg_mb
Definition at line 50 of file RedoxRegCondition.hpp.
Constructor & Destructor Documentation
RedoxRegCondition() [1/3]
ePhotosynthesis::conditions::RedoxRegCondition::RedoxRegCondition () inline
Definition at line 53 of file RedoxRegCondition.hpp.
References RA_con, and RedoxRegCondition().
Referenced by RedoxRegCondition().
~RedoxRegCondition()
ePhotosynthesis::conditions::RedoxRegCondition::~RedoxRegCondition () inline override
Definition at line 57 of file RedoxRegCondition.hpp.
RedoxRegCondition() [2/3]
RedoxRegCondition::RedoxRegCondition (RACondition * rother, double thio = 0.)
Constructor to create an object from the contained classes
Parameters
rother A RACon object to incorporate
thio
Definition at line 34 of file RedoxRegCondition.cpp.
References ePhotosynthesis::conditions::ConditionBase< T, U, ID >::parent, ePhotosynthesis::conditions::RACondition::parentRedoxReg, and RA_con.
RedoxRegCondition() [3/3]
RedoxRegCondition::RedoxRegCondition (const arr & vec, const std::size_t offset = 0)
Constructor to create an object from the input vector, starting at the given index
Parameters
vec Vector to create the object from
offset The index in vec to start creating the object from
Definition at line 48 of file RedoxRegCondition.cpp.
Member Function Documentation
_size()
static std::size_t ePhotosynthesis::conditions::RedoxRegCondition::_size () inline static private
Get the size of the data vector
Returns
The size of the serialized vector.
Definition at line 89 of file RedoxRegCondition.hpp.
References ePhotosynthesis::conditions::ConditionBase< DynaPSCondition, trDynaPSCondition, MODULE_DynaPS >::size().
Field Documentation
RA_con
RACondition* ePhotosynthesis::conditions::RedoxRegCondition::RA_con = nullptr
Definition at line 77 of file RedoxRegCondition.hpp.
Referenced by ePhotosynthesis::modules::RedoxReg::_Rate(), RedoxRegCondition(), and RedoxRegCondition().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/conditions/RedoxRegCondition.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/conditions/RedoxRegCondition.cpp