ePhotosynthesis: ePhotosynthesis Namespace Reference
ePhotosynthesis Namespace Reference
Namespaces
namespace COND
namespace conditions
namespace drivers
namespace KE
namespace MOD
namespace modules
namespace POOL
namespace pool
namespace python
namespace RC
namespace utils
namespace VARS
namespace VEL
namespace vel
Data Structures
class _valueSetStaticMember
class DriverParam
struct enum_helper_inv
struct enum_helper_inv< ENUM_ALL_VARS >
struct enum_helper_inv< ENUM_BF_COND >
struct enum_helper_inv< ENUM_BF_KE >
struct enum_helper_inv< ENUM_BF_MOD >
struct enum_helper_inv< ENUM_BF_POOL >
struct enum_helper_inv< ENUM_BF_RC >
struct enum_helper_inv< ENUM_BF_VEL >
struct enum_helper_inv< ENUM_CM_COND >
struct enum_helper_inv< ENUM_CM_MOD >
struct enum_helper_inv< ENUM_DynaPS_COND >
struct enum_helper_inv< ENUM_DynaPS_MOD >
struct enum_helper_inv< ENUM_EPS_COND >
struct enum_helper_inv< ENUM_EPS_MOD >
struct enum_helper_inv< ENUM_FI_COND >
struct enum_helper_inv< ENUM_FI_KE >
struct enum_helper_inv< ENUM_FI_MOD >
struct enum_helper_inv< ENUM_FI_POOL >
struct enum_helper_inv< ENUM_FI_RC >
struct enum_helper_inv< ENUM_FI_VEL >
struct enum_helper_inv< ENUM_FIBF_COND >
struct enum_helper_inv< ENUM_FIBF_KE >
struct enum_helper_inv< ENUM_FIBF_MOD >
struct enum_helper_inv< ENUM_FIBF_POOL >
struct enum_helper_inv< ENUM_FIBF_RC >
struct enum_helper_inv< ENUM_FIBF_VEL >
struct enum_helper_inv< ENUM_PR_COND >
struct enum_helper_inv< ENUM_PR_KE >
struct enum_helper_inv< ENUM_PR_MOD >
struct enum_helper_inv< ENUM_PR_POOL >
struct enum_helper_inv< ENUM_PR_RC >
struct enum_helper_inv< ENUM_PR_VEL >
struct enum_helper_inv< ENUM_PS_COND >
struct enum_helper_inv< ENUM_PS_KE >
struct enum_helper_inv< ENUM_PS_MOD >
struct enum_helper_inv< ENUM_PS_POOL >
struct enum_helper_inv< ENUM_PS_PR_COND >
struct enum_helper_inv< ENUM_PS_PR_MOD >
struct enum_helper_inv< ENUM_PS_RC >
struct enum_helper_inv< ENUM_PS_VEL >
struct enum_helper_inv< ENUM_RA_COND >
struct enum_helper_inv< ENUM_RA_MOD >
struct enum_helper_inv< ENUM_RedoxReg_COND >
struct enum_helper_inv< ENUM_RedoxReg_KE >
struct enum_helper_inv< ENUM_RedoxReg_MOD >
struct enum_helper_inv< ENUM_RedoxReg_POOL >
struct enum_helper_inv< ENUM_RedoxReg_RC >
struct enum_helper_inv< ENUM_RedoxReg_VEL >
struct enum_helper_inv< ENUM_RROEA_COND >
struct enum_helper_inv< ENUM_RROEA_KE >
struct enum_helper_inv< ENUM_RROEA_MOD >
struct enum_helper_inv< ENUM_RROEA_POOL >
struct enum_helper_inv< ENUM_RROEA_RC >
struct enum_helper_inv< ENUM_RROEA_VEL >
struct enum_helper_inv< ENUM_RuACT_COND >
struct enum_helper_inv< ENUM_RuACT_KE >
struct enum_helper_inv< ENUM_RuACT_MOD >
struct enum_helper_inv< ENUM_RuACT_POOL >
struct enum_helper_inv< ENUM_RuACT_RC >
struct enum_helper_inv< ENUM_RuACT_VEL >
struct enum_helper_inv< ENUM_SUCS_COND >
struct enum_helper_inv< ENUM_SUCS_KE >
struct enum_helper_inv< ENUM_SUCS_MOD >
struct enum_helper_inv< ENUM_SUCS_POOL >
struct enum_helper_inv< ENUM_SUCS_RC >
struct enum_helper_inv< ENUM_SUCS_VEL >
struct enum_helper_inv< ENUM_trDynaPS_COND >
struct enum_helper_inv< ENUM_trDynaPS_MOD >
struct enum_helper_inv< ENUM_XanCycle_COND >
struct enum_helper_inv< ENUM_XanCycle_KE >
struct enum_helper_inv< ENUM_XanCycle_MOD >
struct enum_helper_inv< ENUM_XanCycle_POOL >
struct enum_helper_inv< ENUM_XanCycle_RC >
struct enum_helper_inv< ENUM_XanCycle_VEL >
class TimeSeries
class Value
class ValueSet
class ValueSet_t
class ValueSetBase
class ValueSetClass_t
class ValueSetClassType
class ValueSetEnum
class ValueSetStatic
class ValueSetStaticClassType
class ValueSetWrapperBase
class Variables
Typedefs
typedef std::vector< double > arr
typedef ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type ENUM_BF_COND
typedef ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type ENUM_CM_COND
typedef ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type ENUM_DynaPS_COND
typedef ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type ENUM_EPS_COND
typedef ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type ENUM_FIBF_COND
typedef ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type ENUM_FI_COND
typedef ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type ENUM_PR_COND
typedef ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type ENUM_PS_COND
typedef ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type ENUM_PS_PR_COND
typedef ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type ENUM_RA_COND
typedef ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type ENUM_RROEA_COND
typedef ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type ENUM_RedoxReg_COND
typedef ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type ENUM_RuACT_COND
typedef ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type ENUM_SUCS_COND
typedef ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type ENUM_XanCycle_COND
typedef ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type ENUM_trDynaPS_COND
typedef ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type ENUM_BF_KE
typedef ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type ENUM_FIBF_KE
typedef ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type ENUM_FI_KE
typedef ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type ENUM_PR_KE
typedef ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type ENUM_PS_KE
typedef ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type ENUM_RROEA_KE
typedef ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type ENUM_RedoxReg_KE
typedef ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type ENUM_RuACT_KE
typedef ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type ENUM_SUCS_KE
typedef ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type ENUM_XanCycle_KE
typedef ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type ENUM_BF_MOD
typedef ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type ENUM_CM_MOD
typedef ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type ENUM_DynaPS_MOD
typedef ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type ENUM_EPS_MOD
typedef ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type ENUM_FIBF_MOD
typedef ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type ENUM_FI_MOD
typedef ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type ENUM_PR_MOD
typedef ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type ENUM_PS_MOD
typedef ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type ENUM_PS_PR_MOD
typedef ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type ENUM_RA_MOD
typedef ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type ENUM_RROEA_MOD
typedef ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type ENUM_RedoxReg_MOD
typedef ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type ENUM_RuACT_MOD
typedef ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type ENUM_SUCS_MOD
typedef ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type ENUM_XanCycle_MOD
typedef ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type ENUM_trDynaPS_MOD
typedef ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type ENUM_BF_POOL
typedef ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type ENUM_FIBF_POOL
typedef ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type ENUM_FI_POOL
typedef ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type ENUM_PR_POOL
typedef ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type ENUM_PS_POOL
typedef ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type ENUM_RROEA_POOL
typedef ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type ENUM_RedoxReg_POOL
typedef ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type ENUM_RuACT_POOL
typedef ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type ENUM_SUCS_POOL
typedef ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type ENUM_XanCycle_POOL
typedef ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type ENUM_BF_RC
typedef ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type ENUM_FIBF_RC
typedef ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type ENUM_FI_RC
typedef ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type ENUM_PR_RC
typedef ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type ENUM_PS_RC
typedef ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type ENUM_RROEA_RC
typedef ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type ENUM_RedoxReg_RC
typedef ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type ENUM_RuACT_RC
typedef ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type ENUM_SUCS_RC
typedef ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type ENUM_XanCycle_RC
typedef ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type ENUM_ALL_VARS
typedef ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type ENUM_BF_VEL
typedef ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type ENUM_FIBF_VEL
typedef ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type ENUM_FI_VEL
typedef ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type ENUM_PR_VEL
typedef ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type ENUM_PS_VEL
typedef ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type ENUM_RROEA_VEL
typedef ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type ENUM_RedoxReg_VEL
typedef ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type ENUM_RuACT_VEL
typedef ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type ENUM_SUCS_VEL
typedef ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type ENUM_XanCycle_VEL
typedef ValueSetWrapperBase< ValueSet_t > ValueSetWrapper
typedef ValueSetWrapperBase< ValueSetClass_t > ValueSetClassWrapper
Enumerations
enum DriverType : int { None , MEMBERS_DRIVER }
enum OutputFreq : int { OUTPUT_FREQ_NEVER , OUTPUT_FREQ_FIRST , OUTPUT_FREQ_FIRST_AND_LAST , OUTPUT_FREQ_STEPS }
enum MODULE : int { MEMBERS_MODULE }
enum PARAM_TYPE : int { MEMBERS_PARAM }
enum VALUE_FLAG : int { VALUE_FLAG_NONE = 0x00000000 , VALUE_FLAG_SKIPPED = 0x00000001 , VALUE_FLAG_MAX = 0x00000002 }
enum STATIC_VALUE_FLAG : int {
STATIC_VALUE_FLAG_NONE = 0x00000000 , STATIC_VALUE_FLAG_CONST = 0x00000001 , STATIC_VALUE_FLAG_CALC = 0x00000002 , STATIC_VALUE_FLAG_NON_VECTOR = 0x00000004 ,
STATIC_VALUE_FLAG_RESET_ONE = 0x00000008 , STATIC_VALUE_FLAG_INIT_ONCE = 0x00000010 , STATIC_VALUE_FLAG_MAX = 0x00000020
}
Functions
FORWARD_DECLARE_CONDITION (BF)
FORWARD_DECLARE_CONDITION (CM)
FORWARD_DECLARE_CONDITION (DynaPS)
FORWARD_DECLARE_CONDITION (EPS)
FORWARD_DECLARE_CONDITION (FIBF)
FORWARD_DECLARE_CONDITION (FI)
FORWARD_DECLARE_CONDITION (PR)
FORWARD_DECLARE_CONDITION (PS_PR)
FORWARD_DECLARE_CONDITION (PS)
FORWARD_DECLARE_CONDITION (RA)
FORWARD_DECLARE_CONDITION_TOP (RedoxReg)
FORWARD_DECLARE_CONDITION (RROEA)
FORWARD_DECLARE_CONDITION (RuACT)
FORWARD_DECLARE_CONDITION (SUCS)
FORWARD_DECLARE_CONDITION_TOP (trDynaPS)
FORWARD_DECLARE_CONDITION (XanCycle)
arr ones (const std::size_t length)
[SET_GET_BOOL_MODULE]
arr zeros (const std::size_t length)
void report (arr values)
FORWARD_DECLARE_DRIVER (CM)
FORWARD_DECLARE_DRIVER (DynaPS)
FORWARD_DECLARE_DRIVER (EPS)
FORWARD_DECLARE_DRIVER (trDynaPS)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_BF_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_CM_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_DynaPS_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_EPS_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FIBF_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FI_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PR_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PS_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PS_PR_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RA_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RROEA_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RedoxReg_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RuACT_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_SUCS_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_XanCycle_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_trDynaPS_COND &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_BF_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FIBF_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FI_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PR_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PS_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RROEA_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RedoxReg_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RuACT_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_SUCS_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_XanCycle_KE &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_BF_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_CM_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_DynaPS_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_EPS_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FIBF_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FI_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PR_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PS_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PS_PR_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RA_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RROEA_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RedoxReg_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RuACT_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_SUCS_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_XanCycle_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_trDynaPS_MOD &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_BF_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FIBF_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FI_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PR_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PS_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RROEA_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RedoxReg_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RuACT_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_SUCS_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_XanCycle_POOL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_BF_RC &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FIBF_RC &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FI_RC &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PR_RC &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PS_RC &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RROEA_RC &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RedoxReg_RC &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RuACT_RC &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_SUCS_RC &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_XanCycle_RC &x)
template<typename T>
std::ostream & operator<< (std::ostream &out, const std::vector< T > &x)
template<typename T1, typename T2>
std::ostream & operator<< (std::ostream &out, const std::map< T1, T2 > &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_ALL_VARS &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_BF_VEL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FIBF_VEL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_FI_VEL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PR_VEL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_PS_VEL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RROEA_VEL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RedoxReg_VEL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_RuACT_VEL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_SUCS_VEL &x)
EPHOTO_API std::ostream & operator<< (std::ostream &out, const ENUM_XanCycle_VEL &x)
EPHOTO_API std::map< std::string, double > run_simulation (Variables *&theVars, const DriverType driverChoice, const double &begintime=0.0, const double &stoptime=5000.0, const double &stepsize=1.0, const int &maxSubSteps=750, const double &abstol=1e-5, const double &reltol=1e-4, const std::string &outputFile="", const std::vector< std::string > &outputVars={}, int outputParam=0, const std::string &outputParamBase="", const std::vector< std::string > &outputParamVars={})
Run a simulation.
EPHOTO_API std::map< std::string, double > run_simulation (DriverType driverChoice, const double &begintime=0.0, const double &stoptime=5000.0, const double &stepsize=1.0, const int &maxSubSteps=750, const double &abstol=1e-5, const double &reltol=1e-4, std::map< std::string, std::string > inputs={}, bool useC3=false, const std::string &evnFile="", const std::string &atpcostFile="", const std::string &enzymeFile="", const std::string &grnFile="", const std::string &outputFile="", const std::vector< std::string > &outputVars={}, const int &outputParam=0, const std::string &outputParamBase="", const std::vector< std::string > &outputParamVars={}, ushort dbglvl=0, const bool debugDelta=false, const bool debugInternal=false, const bool &record=false, Variables *theVars=nullptr)
Run a simulation.
void Condition (double t, Variables *theVars)
void GenOut (double t, Variables *theVars)
void IniModelCom (Variables *theVars)
void ParamSet (Variables *theVars)
void SYSInitial (Variables *theVars)
double TargetFunVal (const Variables *theVars)
void makeFluxTR (Variables *theVars)
EPHOTO_API void readFile (const std::string &filename, std::map< std::string, std::string > &mapper)
EPHOTO_API void readFile (const std::string &filename, std::map< std::string, double > &mapper, bool enzymes=false)
FORWARD_DECLARE_MODULE (BF)
FORWARD_DECLARE_MODULE_DRIVER (CM)
FORWARD_DECLARE_MODULE_DRIVER (DynaPS)
FORWARD_DECLARE_MODULE_DRIVER (EPS)
FORWARD_DECLARE_MODULE (FI)
FORWARD_DECLARE_MODULE_COMPOSITE (FIBF)
FORWARD_DECLARE_MODULE (PR)
FORWARD_DECLARE_MODULE (PS)
FORWARD_DECLARE_MODULE_COMPOSITE (PS_PR)
FORWARD_DECLARE_MODULE_COMPOSITE (RA)
FORWARD_DECLARE_MODULE_COMPOSITE (RedoxReg)
FORWARD_DECLARE_MODULE (RROEA)
FORWARD_DECLARE_MODULE (RuACT)
FORWARD_DECLARE_MODULE (SUCS)
FORWARD_DECLARE_MODULE_TOP (trDynaPS)
FORWARD_DECLARE_MODULE (XanCycle)
EPHOTO_API Variables * create_Variables ()
Factory for creating Variables.
EPHOTO_API void destroy_Variables (Variables *&theVars)
Utility for destroying Variables.
EPHOTO_API std::ostream & operator<< (std::ostream &out, const Variables *in)
INSTANTIATE_FUNCTIONS ((CLASS_VARS(ValueSetBase)), VSB)
INSTANTIATE_FUNCTIONS ((CLASS_VARS(ValueSetBase)), VS)
EVAL (FOR_EACH_GENERIC(EXPLICIT_TEMPLATE_INSTANTIATION_COND_DEFERED, CALL_WITH_EMPTY_ARGS_DEFER, SEP_SEMICOLON,(), MEMBER_NAMES_MODULE))
EVAL (FOR_EACH_GENERIC(EXPLICIT_TEMPLATE_INSTANTIATION_MOD_DEFERED, CALL_WITH_EMPTY_ARGS_DEFER, SEP_SEMICOLON,(), MEMBER_NAMES_MODULE))
EVAL (FOR_EACH_GENERIC(EXPLICIT_TEMPLATE_INSTANTIATION_PAIR_DEFERED, CALL_WITH_EMPTY_ARGS_DEFER, SEP_SEMICOLON,(), INST_MOD_PT_PAIRS_NO_COND))
Variables
static std::vector< std::string > glymaID_order
template<MODULE M, PARAM_TYPE PT>
const MODULE ValueSetEnum< M, PT >::module = M
template<MODULE M, PARAM_TYPE PT>
const PARAM_TYPE ValueSetEnum< M, PT >::param_type = PT
template<MODULE M, PARAM_TYPE PT>
const std::vector< typename ValueSetEnum< M, PT >::Type > ValueSetEnum< M, PT >::all = {}
template<MODULE M, PARAM_TYPE PT>
const std::map< typename ValueSetEnum< M, PT >::Type, std::string > ValueSetEnum< M, PT >::names = {}
template<MODULE M, PARAM_TYPE PT>
const std::map< typename ValueSetEnum< M, PT >::Type, double > ValueSetEnum< M, PT >::defaults = {}
template<MODULE M, PARAM_TYPE PT>
const std::map< typename ValueSetEnum< M, PT >::Type, double > ValueSetEnum< M, PT >::defaults_C3 = {}
template<MODULE M, PARAM_TYPE PT>
const std::map< typename ValueSetEnum< M, PT >::Type, std::string > ValueSetEnum< M, PT >::glymaids = {}
template<MODULE M, PARAM_TYPE PT>
const std::map< std::string, typename ValueSetEnum< M, PT >::Type > ValueSetEnum< M, PT >::aliases = {}
template<MODULE M, PARAM_TYPE PT>
const std::map< typename ValueSetEnum< M, PT >::Type, std::string > ValueSetEnum< M, PT >::docs = {}
template<MODULE M, PARAM_TYPE PT>
std::map< typename ValueSetEnum< M, PT >::Type, int > ValueSetEnum< M, PT >::value_flags = {}
template<MODULE M, PARAM_TYPE PT>
const std::map< typename ValueSetEnum< M, PT >::Type, int > ValueSetEnum< M, PT >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::docs
template<>
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::docs
template<>
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::docs
template<>
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::docs
template<>
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::defaults_C3
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::docs
template<>
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::defaults_C3
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::all
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::names
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::docs
template<>
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, double > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, std::string > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::Type, int > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::static_value_flags = {}
static const std::vector< MODULE > ALL_MODULE
static const std::vector< PARAM_TYPE > ALL_PARAM_TYPE
static const std::vector< VALUE_FLAG > ALL_VALUE_FLAG
static const std::vector< STATIC_VALUE_FLAG > ALL_STATIC_VALUE_FLAG
template<>
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::defaults_C3
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::glymaids
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::defaults_C3
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::glymaids
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::defaults_C3
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::glymaids
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::defaults_C3
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::glymaids
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::defaults_C3
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::defaults_C3
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::glymaids
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::all
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::names
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::docs
template<>
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, double > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, std::string > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::Type, int > ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::aliases
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::docs
template<>
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::docs
template<>
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::docs
template<>
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::all
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::names
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::docs
template<>
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::all
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::names
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::docs
template<>
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::all
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::names
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::docs
template<>
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::all
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::names
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::docs
template<>
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::docs
template<>
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::all
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::names
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::docs
template<>
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::all
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::names
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::docs
template<>
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::all
template<>
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::names
template<>
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, double > ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type > ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::aliases
template<>
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, std::string > ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::docs
template<>
std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::Type, int > ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::static_value_flags
template<>
const std::vector< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::all = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::names = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::defaults = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::docs
template<>
std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::docs = {}
template<>
std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::docs
template<>
std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::static_value_flags = {}
template<>
const std::vector< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::all
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::names
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::defaults
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, double > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::defaults_C3 = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::glymaids = {}
template<>
const std::map< std::string, typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::aliases = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, std::string > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::docs
template<>
std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::value_flags = {}
template<>
const std::map< typename ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::Type, int > ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::static_value_flags = {}
template<class T, class U, MODULE ID, PARAM_TYPE PT>
int ValueSetBase< T, U, ID, PT >::static_flags = 0
template<class T, class U, MODULE ID, PARAM_TYPE PT>
std::map< typename ValueSetBase< T, U, ID, PT >::EnumType, double > ValueSetBase< T, U, ID, PT >::defaults = {}
template<class T, class U, MODULE ID, PARAM_TYPE PT>
std::map< typename ValueSetBase< T, U, ID, PT >::EnumType, double * > ValueSetBase< T, U, ID, PT >::static_values = {}
template<class T, class U, MODULE ID, PARAM_TYPE PT>
std::vector< ValueSetClassWrapper > ValueSetBase< T, U, ID, PT >::child_classes = {}
template<class T, class U, MODULE ID, PARAM_TYPE PT>
std::map< typename ValueSetStatic< T, U, ID, PT >::EnumType, double * > ValueSetStatic< T, U, ID, PT >::values = {}
template<class T, class U, MODULE ID, PARAM_TYPE PT>
std::map< typename ValueSetStatic< T, U, ID, PT >::EnumType, double > ValueSetStatic< T, U, ID, PT >::preinit_values = {}
Typedef Documentation
arr
typedef std::vector<double> ePhotosynthesis::arr
The common flat data structure in this code.
Definition at line 83 of file definitions.hpp.
ENUM_ALL_VARS
typedef ValueSetEnum<MODULE_ALL,PARAM_TYPE_VARS>::Type ePhotosynthesis::ENUM_ALL_VARS
Definition at line 13 of file enums_VARS.hpp.
ENUM_BF_COND
typedef ValueSetEnum<MODULE_BF,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_BF_COND
Definition at line 13 of file enums_COND.hpp.
ENUM_BF_KE
typedef ValueSetEnum<MODULE_BF,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_BF_KE
Definition at line 13 of file enums_KE.hpp.
ENUM_BF_MOD
typedef ValueSetEnum<MODULE_BF,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_BF_MOD
Definition at line 13 of file enums_MOD.hpp.
ENUM_BF_POOL
typedef ValueSetEnum<MODULE_BF,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_BF_POOL
Definition at line 13 of file enums_POOL.hpp.
ENUM_BF_RC
typedef ValueSetEnum<MODULE_BF,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_BF_RC
Definition at line 13 of file enums_RC.hpp.
ENUM_BF_VEL
typedef ValueSetEnum<MODULE_BF,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_BF_VEL
Definition at line 13 of file enums_VEL.hpp.
ENUM_CM_COND
typedef ValueSetEnum<MODULE_CM,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_CM_COND
Definition at line 51 of file enums_COND.hpp.
ENUM_CM_MOD
typedef ValueSetEnum<MODULE_CM,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_CM_MOD
Definition at line 51 of file enums_MOD.hpp.
ENUM_DynaPS_COND
typedef ValueSetEnum<MODULE_DynaPS,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_DynaPS_COND
Definition at line 89 of file enums_COND.hpp.
ENUM_DynaPS_MOD
typedef ValueSetEnum<MODULE_DynaPS,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_DynaPS_MOD
Definition at line 89 of file enums_MOD.hpp.
ENUM_EPS_COND
typedef ValueSetEnum<MODULE_EPS,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_EPS_COND
Definition at line 127 of file enums_COND.hpp.
ENUM_EPS_MOD
typedef ValueSetEnum<MODULE_EPS,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_EPS_MOD
Definition at line 127 of file enums_MOD.hpp.
ENUM_FI_COND
typedef ValueSetEnum<MODULE_FI,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_FI_COND
Definition at line 203 of file enums_COND.hpp.
ENUM_FI_KE
typedef ValueSetEnum<MODULE_FI,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_FI_KE
Definition at line 89 of file enums_KE.hpp.
ENUM_FI_MOD
typedef ValueSetEnum<MODULE_FI,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_FI_MOD
Definition at line 203 of file enums_MOD.hpp.
ENUM_FI_POOL
typedef ValueSetEnum<MODULE_FI,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_FI_POOL
Definition at line 89 of file enums_POOL.hpp.
ENUM_FI_RC
typedef ValueSetEnum<MODULE_FI,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_FI_RC
Definition at line 89 of file enums_RC.hpp.
ENUM_FI_VEL
typedef ValueSetEnum<MODULE_FI,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_FI_VEL
Definition at line 89 of file enums_VEL.hpp.
ENUM_FIBF_COND
typedef ValueSetEnum<MODULE_FIBF,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_FIBF_COND
Definition at line 165 of file enums_COND.hpp.
ENUM_FIBF_KE
typedef ValueSetEnum<MODULE_FIBF,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_FIBF_KE
Definition at line 51 of file enums_KE.hpp.
ENUM_FIBF_MOD
typedef ValueSetEnum<MODULE_FIBF,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_FIBF_MOD
Definition at line 165 of file enums_MOD.hpp.
ENUM_FIBF_POOL
typedef ValueSetEnum<MODULE_FIBF,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_FIBF_POOL
Definition at line 51 of file enums_POOL.hpp.
ENUM_FIBF_RC
typedef ValueSetEnum<MODULE_FIBF,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_FIBF_RC
Definition at line 51 of file enums_RC.hpp.
ENUM_FIBF_VEL
typedef ValueSetEnum<MODULE_FIBF,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_FIBF_VEL
Definition at line 51 of file enums_VEL.hpp.
ENUM_PR_COND
typedef ValueSetEnum<MODULE_PR,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_PR_COND
Definition at line 241 of file enums_COND.hpp.
ENUM_PR_KE
typedef ValueSetEnum<MODULE_PR,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_PR_KE
Definition at line 127 of file enums_KE.hpp.
ENUM_PR_MOD
typedef ValueSetEnum<MODULE_PR,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_PR_MOD
Definition at line 241 of file enums_MOD.hpp.
ENUM_PR_POOL
typedef ValueSetEnum<MODULE_PR,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_PR_POOL
Definition at line 127 of file enums_POOL.hpp.
ENUM_PR_RC
typedef ValueSetEnum<MODULE_PR,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_PR_RC
Definition at line 127 of file enums_RC.hpp.
ENUM_PR_VEL
typedef ValueSetEnum<MODULE_PR,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_PR_VEL
Definition at line 127 of file enums_VEL.hpp.
ENUM_PS_COND
typedef ValueSetEnum<MODULE_PS,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_PS_COND
Definition at line 279 of file enums_COND.hpp.
ENUM_PS_KE
typedef ValueSetEnum<MODULE_PS,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_PS_KE
Definition at line 165 of file enums_KE.hpp.
ENUM_PS_MOD
typedef ValueSetEnum<MODULE_PS,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_PS_MOD
Definition at line 279 of file enums_MOD.hpp.
ENUM_PS_POOL
typedef ValueSetEnum<MODULE_PS,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_PS_POOL
Definition at line 165 of file enums_POOL.hpp.
ENUM_PS_PR_COND
typedef ValueSetEnum<MODULE_PS_PR,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_PS_PR_COND
Definition at line 317 of file enums_COND.hpp.
ENUM_PS_PR_MOD
typedef ValueSetEnum<MODULE_PS_PR,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_PS_PR_MOD
Definition at line 317 of file enums_MOD.hpp.
ENUM_PS_RC
typedef ValueSetEnum<MODULE_PS,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_PS_RC
Definition at line 165 of file enums_RC.hpp.
ENUM_PS_VEL
typedef ValueSetEnum<MODULE_PS,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_PS_VEL
Definition at line 165 of file enums_VEL.hpp.
ENUM_RA_COND
typedef ValueSetEnum<MODULE_RA,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_RA_COND
Definition at line 355 of file enums_COND.hpp.
ENUM_RA_MOD
typedef ValueSetEnum<MODULE_RA,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_RA_MOD
Definition at line 355 of file enums_MOD.hpp.
ENUM_RedoxReg_COND
typedef ValueSetEnum<MODULE_RedoxReg,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_RedoxReg_COND
Definition at line 431 of file enums_COND.hpp.
ENUM_RedoxReg_KE
typedef ValueSetEnum<MODULE_RedoxReg,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_RedoxReg_KE
Definition at line 241 of file enums_KE.hpp.
ENUM_RedoxReg_MOD
typedef ValueSetEnum<MODULE_RedoxReg,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_RedoxReg_MOD
Definition at line 431 of file enums_MOD.hpp.
ENUM_RedoxReg_POOL
typedef ValueSetEnum<MODULE_RedoxReg,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_RedoxReg_POOL
Definition at line 241 of file enums_POOL.hpp.
ENUM_RedoxReg_RC
typedef ValueSetEnum<MODULE_RedoxReg,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_RedoxReg_RC
Definition at line 241 of file enums_RC.hpp.
ENUM_RedoxReg_VEL
typedef ValueSetEnum<MODULE_RedoxReg,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_RedoxReg_VEL
Definition at line 241 of file enums_VEL.hpp.
ENUM_RROEA_COND
typedef ValueSetEnum<MODULE_RROEA,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_RROEA_COND
Definition at line 393 of file enums_COND.hpp.
ENUM_RROEA_KE
typedef ValueSetEnum<MODULE_RROEA,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_RROEA_KE
Definition at line 203 of file enums_KE.hpp.
ENUM_RROEA_MOD
typedef ValueSetEnum<MODULE_RROEA,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_RROEA_MOD
Definition at line 393 of file enums_MOD.hpp.
ENUM_RROEA_POOL
typedef ValueSetEnum<MODULE_RROEA,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_RROEA_POOL
Definition at line 203 of file enums_POOL.hpp.
ENUM_RROEA_RC
typedef ValueSetEnum<MODULE_RROEA,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_RROEA_RC
Definition at line 203 of file enums_RC.hpp.
ENUM_RROEA_VEL
typedef ValueSetEnum<MODULE_RROEA,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_RROEA_VEL
Definition at line 203 of file enums_VEL.hpp.
ENUM_RuACT_COND
typedef ValueSetEnum<MODULE_RuACT,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_RuACT_COND
Definition at line 469 of file enums_COND.hpp.
ENUM_RuACT_KE
typedef ValueSetEnum<MODULE_RuACT,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_RuACT_KE
Definition at line 279 of file enums_KE.hpp.
ENUM_RuACT_MOD
typedef ValueSetEnum<MODULE_RuACT,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_RuACT_MOD
Definition at line 469 of file enums_MOD.hpp.
ENUM_RuACT_POOL
typedef ValueSetEnum<MODULE_RuACT,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_RuACT_POOL
Definition at line 279 of file enums_POOL.hpp.
ENUM_RuACT_RC
typedef ValueSetEnum<MODULE_RuACT,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_RuACT_RC
Definition at line 279 of file enums_RC.hpp.
ENUM_RuACT_VEL
typedef ValueSetEnum<MODULE_RuACT,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_RuACT_VEL
Definition at line 279 of file enums_VEL.hpp.
ENUM_SUCS_COND
typedef ValueSetEnum<MODULE_SUCS,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_SUCS_COND
Definition at line 507 of file enums_COND.hpp.
ENUM_SUCS_KE
typedef ValueSetEnum<MODULE_SUCS,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_SUCS_KE
Definition at line 317 of file enums_KE.hpp.
ENUM_SUCS_MOD
typedef ValueSetEnum<MODULE_SUCS,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_SUCS_MOD
Definition at line 507 of file enums_MOD.hpp.
ENUM_SUCS_POOL
typedef ValueSetEnum<MODULE_SUCS,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_SUCS_POOL
Definition at line 317 of file enums_POOL.hpp.
ENUM_SUCS_RC
typedef ValueSetEnum<MODULE_SUCS,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_SUCS_RC
Definition at line 317 of file enums_RC.hpp.
ENUM_SUCS_VEL
typedef ValueSetEnum<MODULE_SUCS,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_SUCS_VEL
Definition at line 317 of file enums_VEL.hpp.
ENUM_trDynaPS_COND
typedef ValueSetEnum<MODULE_trDynaPS,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_trDynaPS_COND
Definition at line 583 of file enums_COND.hpp.
ENUM_trDynaPS_MOD
typedef ValueSetEnum<MODULE_trDynaPS,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_trDynaPS_MOD
Definition at line 583 of file enums_MOD.hpp.
ENUM_XanCycle_COND
typedef ValueSetEnum<MODULE_XanCycle,PARAM_TYPE_COND>::Type ePhotosynthesis::ENUM_XanCycle_COND
Definition at line 545 of file enums_COND.hpp.
ENUM_XanCycle_KE
typedef ValueSetEnum<MODULE_XanCycle,PARAM_TYPE_KE>::Type ePhotosynthesis::ENUM_XanCycle_KE
Definition at line 355 of file enums_KE.hpp.
ENUM_XanCycle_MOD
typedef ValueSetEnum<MODULE_XanCycle,PARAM_TYPE_MOD>::Type ePhotosynthesis::ENUM_XanCycle_MOD
Definition at line 545 of file enums_MOD.hpp.
ENUM_XanCycle_POOL
typedef ValueSetEnum<MODULE_XanCycle,PARAM_TYPE_POOL>::Type ePhotosynthesis::ENUM_XanCycle_POOL
Definition at line 355 of file enums_POOL.hpp.
ENUM_XanCycle_RC
typedef ValueSetEnum<MODULE_XanCycle,PARAM_TYPE_RC>::Type ePhotosynthesis::ENUM_XanCycle_RC
Definition at line 355 of file enums_RC.hpp.
ENUM_XanCycle_VEL
typedef ValueSetEnum<MODULE_XanCycle,PARAM_TYPE_VEL>::Type ePhotosynthesis::ENUM_XanCycle_VEL
Definition at line 355 of file enums_VEL.hpp.
ValueSetClassWrapper
typedef ValueSetWrapperBase<ValueSetClass_t> ePhotosynthesis::ValueSetClassWrapper
Definition at line 840 of file ValueSet.hpp.
ValueSetWrapper
typedef ValueSetWrapperBase<ValueSet_t> ePhotosynthesis::ValueSetWrapper
Definition at line 839 of file ValueSet.hpp.
Enumeration Type Documentation
DriverType
enum ePhotosynthesis::DriverType : int
Enumerator
None
MEMBERS_DRIVER
Definition at line 41 of file driver.hpp.
MODULE
enum ePhotosynthesis::MODULE : int
Enumerator
MEMBERS_MODULE
Definition at line 62 of file enums_helpers.hpp.
OutputFreq
enum ePhotosynthesis::OutputFreq : int
Enumerator
OUTPUT_FREQ_NEVER
OUTPUT_FREQ_FIRST
OUTPUT_FREQ_FIRST_AND_LAST
OUTPUT_FREQ_STEPS
Definition at line 45 of file driver.hpp.
PARAM_TYPE
enum ePhotosynthesis::PARAM_TYPE : int
Enumerator
MEMBERS_PARAM
Definition at line 110 of file enums_helpers.hpp.
STATIC_VALUE_FLAG
enum ePhotosynthesis::STATIC_VALUE_FLAG : int
Enumerator
STATIC_VALUE_FLAG_NONE
STATIC_VALUE_FLAG_CONST
STATIC_VALUE_FLAG_CALC
STATIC_VALUE_FLAG_NON_VECTOR
STATIC_VALUE_FLAG_RESET_ONE
STATIC_VALUE_FLAG_INIT_ONCE
STATIC_VALUE_FLAG_MAX
Definition at line 183 of file enums_helpers.hpp.
VALUE_FLAG
enum ePhotosynthesis::VALUE_FLAG : int
Enumerator
VALUE_FLAG_NONE
VALUE_FLAG_SKIPPED
VALUE_FLAG_MAX
Definition at line 151 of file enums_helpers.hpp.
Function Documentation
Condition()
void ePhotosynthesis::Condition (double t, Variables * theVars)
Set some initial global variables
Parameters
t The current timestamp
[in,out] theVars The global variables
Definition at line 38 of file Condition.cpp.
References ePhotosynthesis::Variables::useC3.
create_Variables()
ePhotosynthesis::Variables * ePhotosynthesis::create_Variables ()
Factory for creating Variables.
Returns
Pointer to new Variables instance.
Definition at line 39 of file Variables.cpp.
destroy_Variables()
void ePhotosynthesis::destroy_Variables (ePhotosynthesis::Variables *& theVars)
Utility for destroying Variables.
Parameters
[in] theVars Variables instance to destroy.
Definition at line 43 of file Variables.cpp.
EVAL() [1/3]
ePhotosynthesis::EVAL (FOR_EACH_GENERIC(EXPLICIT_TEMPLATE_INSTANTIATION_COND_DEFERED, CALL_WITH_EMPTY_ARGS_DEFER, SEP_SEMICOLON,(), MEMBER_NAMES_MODULE))
References CALL_WITH_EMPTY_ARGS_DEFER, EXPLICIT_TEMPLATE_INSTANTIATION_COND_DEFERED, MEMBER_NAMES_MODULE, and SEP_SEMICOLON.
EVAL() [2/3]
ePhotosynthesis::EVAL (FOR_EACH_GENERIC(EXPLICIT_TEMPLATE_INSTANTIATION_MOD_DEFERED, CALL_WITH_EMPTY_ARGS_DEFER, SEP_SEMICOLON,(), MEMBER_NAMES_MODULE))
References CALL_WITH_EMPTY_ARGS_DEFER, EXPLICIT_TEMPLATE_INSTANTIATION_MOD_DEFERED, MEMBER_NAMES_MODULE, and SEP_SEMICOLON.
EVAL() [3/3]
ePhotosynthesis::EVAL (FOR_EACH_GENERIC(EXPLICIT_TEMPLATE_INSTANTIATION_PAIR_DEFERED, CALL_WITH_EMPTY_ARGS_DEFER, SEP_SEMICOLON,(), INST_MOD_PT_PAIRS_NO_COND))
References CALL_WITH_EMPTY_ARGS_DEFER, EXPLICIT_TEMPLATE_INSTANTIATION_PAIR_DEFERED, INST_MOD_PT_PAIRS_NO_COND, and SEP_SEMICOLON.
FORWARD_DECLARE_CONDITION() [1/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (BF)
FORWARD_DECLARE_CONDITION() [2/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (CM)
FORWARD_DECLARE_CONDITION() [3/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (DynaPS)
FORWARD_DECLARE_CONDITION() [4/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (EPS)
FORWARD_DECLARE_CONDITION() [5/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (FI)
FORWARD_DECLARE_CONDITION() [6/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (FIBF)
FORWARD_DECLARE_CONDITION() [7/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (PR)
FORWARD_DECLARE_CONDITION() [8/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (PS)
FORWARD_DECLARE_CONDITION() [9/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (PS_PR)
FORWARD_DECLARE_CONDITION() [10/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (RA)
FORWARD_DECLARE_CONDITION() [11/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (RROEA)
FORWARD_DECLARE_CONDITION() [12/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (RuACT)
FORWARD_DECLARE_CONDITION() [13/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (SUCS)
FORWARD_DECLARE_CONDITION() [14/14]
ePhotosynthesis::FORWARD_DECLARE_CONDITION (XanCycle)
FORWARD_DECLARE_CONDITION_TOP() [1/2]
ePhotosynthesis::FORWARD_DECLARE_CONDITION_TOP (RedoxReg)
FORWARD_DECLARE_CONDITION_TOP() [2/2]
ePhotosynthesis::FORWARD_DECLARE_CONDITION_TOP (trDynaPS)
FORWARD_DECLARE_DRIVER() [1/4]
ePhotosynthesis::FORWARD_DECLARE_DRIVER (CM)
FORWARD_DECLARE_DRIVER() [2/4]
ePhotosynthesis::FORWARD_DECLARE_DRIVER (DynaPS)
FORWARD_DECLARE_DRIVER() [3/4]
ePhotosynthesis::FORWARD_DECLARE_DRIVER (EPS)
FORWARD_DECLARE_DRIVER() [4/4]
ePhotosynthesis::FORWARD_DECLARE_DRIVER (trDynaPS)
FORWARD_DECLARE_MODULE() [1/8]
ePhotosynthesis::FORWARD_DECLARE_MODULE (BF)
FORWARD_DECLARE_MODULE() [2/8]
ePhotosynthesis::FORWARD_DECLARE_MODULE (FI)
FORWARD_DECLARE_MODULE() [3/8]
ePhotosynthesis::FORWARD_DECLARE_MODULE (PR)
FORWARD_DECLARE_MODULE() [4/8]
ePhotosynthesis::FORWARD_DECLARE_MODULE (PS)
FORWARD_DECLARE_MODULE() [5/8]
ePhotosynthesis::FORWARD_DECLARE_MODULE (RROEA)
FORWARD_DECLARE_MODULE() [6/8]
ePhotosynthesis::FORWARD_DECLARE_MODULE (RuACT)
FORWARD_DECLARE_MODULE() [7/8]
ePhotosynthesis::FORWARD_DECLARE_MODULE (SUCS)
FORWARD_DECLARE_MODULE() [8/8]
ePhotosynthesis::FORWARD_DECLARE_MODULE (XanCycle)
FORWARD_DECLARE_MODULE_COMPOSITE() [1/4]
ePhotosynthesis::FORWARD_DECLARE_MODULE_COMPOSITE (FIBF)
FORWARD_DECLARE_MODULE_COMPOSITE() [2/4]
ePhotosynthesis::FORWARD_DECLARE_MODULE_COMPOSITE (PS_PR)
FORWARD_DECLARE_MODULE_COMPOSITE() [3/4]
ePhotosynthesis::FORWARD_DECLARE_MODULE_COMPOSITE (RA)
FORWARD_DECLARE_MODULE_COMPOSITE() [4/4]
ePhotosynthesis::FORWARD_DECLARE_MODULE_COMPOSITE (RedoxReg)
FORWARD_DECLARE_MODULE_DRIVER() [1/3]
ePhotosynthesis::FORWARD_DECLARE_MODULE_DRIVER (CM)
FORWARD_DECLARE_MODULE_DRIVER() [2/3]
ePhotosynthesis::FORWARD_DECLARE_MODULE_DRIVER (DynaPS)
FORWARD_DECLARE_MODULE_DRIVER() [3/3]
ePhotosynthesis::FORWARD_DECLARE_MODULE_DRIVER (EPS)
FORWARD_DECLARE_MODULE_TOP()
ePhotosynthesis::FORWARD_DECLARE_MODULE_TOP (trDynaPS)
GenOut()
void ePhotosynthesis::GenOut (double t, Variables * theVars)
Generate output
Parameters
t The current timestamp
[in,out] theVars The global variables
Definition at line 35 of file GenOut.cpp.
References ePhotosynthesis::Variables::CO2A, ePhotosynthesis::modules::PS::getN(), ePhotosynthesis::TimeSeries< T >::insert(), ePhotosynthesis::Variables::record, and zeros().
IniModelCom()
void ePhotosynthesis::IniModelCom (Variables * theVars)
Set some initial global variables
Parameters
[in,out] theVars The global variables
Definition at line 32 of file IniModelCom.cpp.
Referenced by ePhotosynthesis::drivers::CMDriver::getResults(), ePhotosynthesis::drivers::DynaPSDriver::getResults(), ePhotosynthesis::drivers::EPSDriver::getResults(), ePhotosynthesis::drivers::trDynaPSDriver::getResults(), ePhotosynthesis::drivers::CMDriver::setup(), ePhotosynthesis::drivers::DynaPSDriver::setup(), ePhotosynthesis::drivers::EPSDriver::setup(), and ePhotosynthesis::drivers::trDynaPSDriver::setup().
INSTANTIATE_FUNCTIONS() [1/2]
ePhotosynthesis::INSTANTIATE_FUNCTIONS ((CLASS_VARS(ValueSetBase)) , VS)
INSTANTIATE_FUNCTIONS() [2/2]
ePhotosynthesis::INSTANTIATE_FUNCTIONS ((CLASS_VARS(ValueSetBase)) , VSB)
makeFluxTR()
void ePhotosynthesis::makeFluxTR (Variables * theVars)
Definition at line 121 of file GenOut.cpp.
References ePhotosynthesis::Variables::FluxTR, ePhotosynthesis::Variables::VolRatioStCyto, and zeros().
Referenced by ePhotosynthesis::drivers::DynaPSDriver::getResults(), and ePhotosynthesis::drivers::trDynaPSDriver::getResults().
ones()
arr ePhotosynthesis::ones (const std::size_t length) inline
[SET_GET_BOOL_MODULE]
Helper function to initialize a vector of 1's of the given length.
Parameters
length The size of the vector to return
Returns
A vector of 1's, with the input size.
Definition at line 259 of file definitions.hpp.
operator<<() [1/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_ALL_VARS & x)
Definition at line 167 of file enums_VARS.cpp.
operator<<() [2/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_BF_COND & x)
Definition at line 140 of file enums_COND.cpp.
operator<<() [3/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_BF_KE & x)
Definition at line 24 of file enums_KE.cpp.
operator<<() [4/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_BF_MOD & x)
Definition at line 74 of file enums_MOD.cpp.
operator<<() [5/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_BF_POOL & x)
Definition at line 89 of file enums_POOL.cpp.
operator<<() [6/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_BF_RC & x)
Definition at line 182 of file enums_RC.cpp.
operator<<() [7/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_BF_VEL & x)
Definition at line 120 of file enums_VEL.cpp.
operator<<() [8/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_CM_COND & x)
Definition at line 162 of file enums_COND.cpp.
operator<<() [9/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_CM_MOD & x)
Definition at line 96 of file enums_MOD.cpp.
operator<<() [10/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_DynaPS_COND & x)
Definition at line 184 of file enums_COND.cpp.
operator<<() [11/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_DynaPS_MOD & x)
Definition at line 118 of file enums_MOD.cpp.
operator<<() [12/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_EPS_COND & x)
Definition at line 206 of file enums_COND.cpp.
operator<<() [13/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_EPS_MOD & x)
Definition at line 140 of file enums_MOD.cpp.
operator<<() [14/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FI_COND & x)
Definition at line 350 of file enums_COND.cpp.
operator<<() [15/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FI_KE & x)
Definition at line 68 of file enums_KE.cpp.
operator<<() [16/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FI_MOD & x)
Definition at line 226 of file enums_MOD.cpp.
operator<<() [17/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FI_POOL & x)
Definition at line 151 of file enums_POOL.cpp.
operator<<() [18/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FI_RC & x)
Definition at line 314 of file enums_RC.cpp.
operator<<() [19/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FI_VEL & x)
Definition at line 389 of file enums_VEL.cpp.
operator<<() [20/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FIBF_COND & x)
Definition at line 236 of file enums_COND.cpp.
operator<<() [21/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FIBF_KE & x)
Definition at line 46 of file enums_KE.cpp.
operator<<() [22/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FIBF_MOD & x)
Definition at line 192 of file enums_MOD.cpp.
operator<<() [23/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FIBF_POOL & x)
Definition at line 117 of file enums_POOL.cpp.
operator<<() [24/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FIBF_RC & x)
Definition at line 204 of file enums_RC.cpp.
operator<<() [25/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_FIBF_VEL & x)
Definition at line 142 of file enums_VEL.cpp.
operator<<() [26/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PR_COND & x)
Definition at line 422 of file enums_COND.cpp.
operator<<() [27/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PR_KE & x)
Definition at line 90 of file enums_KE.cpp.
operator<<() [28/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PR_MOD & x)
Definition at line 565 of file enums_MOD.cpp.
operator<<() [29/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PR_POOL & x)
Definition at line 173 of file enums_POOL.cpp.
operator<<() [30/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PR_RC & x)
Definition at line 568 of file enums_RC.cpp.
operator<<() [31/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PR_VEL & x)
Definition at line 444 of file enums_VEL.cpp.
operator<<() [32/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PS_COND & x)
Definition at line 503 of file enums_COND.cpp.
operator<<() [33/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PS_KE & x)
Definition at line 112 of file enums_KE.cpp.
operator<<() [34/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PS_MOD & x)
Definition at line 1413 of file enums_MOD.cpp.
operator<<() [35/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PS_POOL & x)
Definition at line 195 of file enums_POOL.cpp.
operator<<() [36/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PS_PR_COND & x)
Definition at line 525 of file enums_COND.cpp.
operator<<() [37/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PS_PR_MOD & x)
Definition at line 1435 of file enums_MOD.cpp.
operator<<() [38/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PS_RC & x)
Definition at line 1028 of file enums_RC.cpp.
operator<<() [39/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_PS_VEL & x)
Definition at line 526 of file enums_VEL.cpp.
operator<<() [40/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RA_COND & x)
Definition at line 547 of file enums_COND.cpp.
operator<<() [41/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RA_MOD & x)
Definition at line 1457 of file enums_MOD.cpp.
operator<<() [42/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RedoxReg_COND & x)
Definition at line 655 of file enums_COND.cpp.
operator<<() [43/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RedoxReg_KE & x)
Definition at line 190 of file enums_KE.cpp.
operator<<() [44/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RedoxReg_MOD & x)
Definition at line 1557 of file enums_MOD.cpp.
operator<<() [45/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RedoxReg_POOL & x)
Definition at line 391 of file enums_POOL.cpp.
operator<<() [46/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RedoxReg_RC & x)
Definition at line 1144 of file enums_RC.cpp.
operator<<() [47/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RedoxReg_VEL & x)
Definition at line 615 of file enums_VEL.cpp.
operator<<() [48/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RROEA_COND & x)
Definition at line 625 of file enums_COND.cpp.
operator<<() [49/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RROEA_KE & x)
Definition at line 168 of file enums_KE.cpp.
operator<<() [50/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RROEA_MOD & x)
Definition at line 1499 of file enums_MOD.cpp.
operator<<() [51/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RROEA_POOL & x)
Definition at line 342 of file enums_POOL.cpp.
operator<<() [52/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RROEA_RC & x)
Definition at line 1105 of file enums_RC.cpp.
operator<<() [53/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RROEA_VEL & x)
Definition at line 584 of file enums_VEL.cpp.
operator<<() [54/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RuACT_COND & x)
Definition at line 697 of file enums_COND.cpp.
operator<<() [55/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RuACT_KE & x)
Definition at line 212 of file enums_KE.cpp.
operator<<() [56/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RuACT_MOD & x)
Definition at line 1594 of file enums_MOD.cpp.
operator<<() [57/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RuACT_POOL & x)
Definition at line 436 of file enums_POOL.cpp.
operator<<() [58/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RuACT_RC & x)
Definition at line 1210 of file enums_RC.cpp.
operator<<() [59/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_RuACT_VEL & x)
Definition at line 658 of file enums_VEL.cpp.
operator<<() [60/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_SUCS_COND & x)
Definition at line 755 of file enums_COND.cpp.
operator<<() [61/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_SUCS_KE & x)
Definition at line 234 of file enums_KE.cpp.
operator<<() [62/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_SUCS_MOD & x)
Definition at line 2067 of file enums_MOD.cpp.
operator<<() [63/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_SUCS_POOL & x)
Definition at line 473 of file enums_POOL.cpp.
operator<<() [64/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_SUCS_RC & x)
Definition at line 1456 of file enums_RC.cpp.
operator<<() [65/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_SUCS_VEL & x)
Definition at line 744 of file enums_VEL.cpp.
operator<<() [66/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_trDynaPS_COND & x)
Definition at line 824 of file enums_COND.cpp.
operator<<() [67/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_trDynaPS_MOD & x)
Definition at line 2157 of file enums_MOD.cpp.
operator<<() [68/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_XanCycle_COND & x)
Definition at line 802 of file enums_COND.cpp.
operator<<() [69/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_XanCycle_KE & x)
Definition at line 256 of file enums_KE.cpp.
operator<<() [70/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_XanCycle_MOD & x)
Definition at line 2135 of file enums_MOD.cpp.
operator<<() [71/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_XanCycle_POOL & x)
Definition at line 495 of file enums_POOL.cpp.
operator<<() [72/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_XanCycle_RC & x)
Definition at line 1498 of file enums_RC.cpp.
operator<<() [73/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const ENUM_XanCycle_VEL & x)
Definition at line 798 of file enums_VEL.cpp.
operator<<() [74/76]
template<typename T1, typename T2> std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const std::map< T1, T2 > & x)
Definition at line 248 of file enums_utils.hpp.
References ePhotosynthesis::utils::print_string().
operator<<() [75/76]
template<typename T> std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const std::vector< T > & x)
Definition at line 244 of file enums_utils.hpp.
References ePhotosynthesis::utils::print_string().
operator<<() [76/76]
std::ostream & ePhotosynthesis::operator<< (std::ostream & out, const Variables * in)
Serialization operator.
Parameters
[in,out] out Output stream.
[in] in Instance to serialize.
Returns
Updated output stream.
Definition at line 255 of file Variables.cpp.
References DO_COND, DO_CONN, DO_PARAM, DO_RATIO, DO_VEL, EXPAND, ePhotosynthesis::Variables::FluxTR, FOR_EACH, ePhotosynthesis::Variables::GP, ePhotosynthesis::Variables::GRNC, ePhotosynthesis::Variables::GRNT, ePhotosynthesis::Variables::inputsFinalized, ePhotosynthesis::Variables::PAR_in_Wpm2, ePhotosynthesis::Variables::record, ePhotosynthesis::Variables::RUBISCOMETHOD, ePhotosynthesis::Variables::useC3, VARS_INST_CONNECTIONS, VARS_INST_MODULES, ePhotosynthesis::Variables::VfactorCp, ePhotosynthesis::Variables::VfactorT, and ePhotosynthesis::Variables::VolRatioStCyto.
ParamSet()
void ePhotosynthesis::ParamSet (Variables * theVars)
Set parameters
Parameters
[in,out] theVars The global variables
Definition at line 31 of file ParamSet.cpp.
References zeros().
Referenced by ePhotosynthesis::drivers::trDynaPSDriver::setup().
readFile() [1/2]
void ePhotosynthesis::readFile (const std::string & filename, std::map< std::string, double > & mapper, bool enzymes = false)
Overloaded utility function to read a text file and convert it to a map. The input text file must be formatted with key/value pairs, one pair per line, and white space between the key and value. This overloaded version works where the values are double type.
Parameters
filename The name of the file to open and read.
[in,out] mapper The std::map to put the contents of the file into
[in] enzymes If True, the inputs are scales like enzymes.
Exceptions
std::runtime_error If the opening of the file fails.
Definition at line 164 of file Condition.cpp.
References ePhotosynthesis::utils::str_split_whitespace().
readFile() [2/2]
void ePhotosynthesis::readFile (const std::string & filename, std::map< std::string, std::string > & mapper)
Overloaded utility function to read a text file and convert it to a map. The input text file must be formatted with key/value pairs, one pair per line, and white space between the key and value. This overloaded version works where the values are std::string type.
Parameters
filename The name of the file to open and read.
[in,out] mapper The std::map to put the contents of the file into
Exceptions
std::runtime_error If the opening of the file fails.
Definition at line 141 of file Condition.cpp.
References ePhotosynthesis::utils::str_split_whitespace().
Referenced by ePhotosynthesis::Variables::_readParam(), ePhotosynthesis::Variables::readEnzymeAct(), and ePhotosynthesis::Variables::readGRN().
report()
void ePhotosynthesis::report (arr values) inline
Definition at line 400 of file definitions.hpp.
References ValueSetStatic< T, U, ID, PT >::values.
run_simulation() [1/2]
std::map< std::string, double > ePhotosynthesis::run_simulation (DriverType driverChoice, const double & begintime = 0.0, const double & stoptime = 5000.0, const double & stepsize = 1.0, const int & maxSubSteps = 750, const double & abstol = 1e-5, const double & reltol = 1e-4, std::map< std::string, std::string > inputs = {}, bool useC3 = false, const std::string & evnFile = "", const std::string & atpcostFile = "", const std::string & enzymeFile = "", const std::string & grnFile = "", const std::string & outputFile = "", const std::vector< std::string > & outputVars = {}, const int & outputParam = 0, const std::string & outputParamBase = "", const std::vector< std::string > & outputParamVars = {}, ushort dbglvl = 0, const bool debugDelta = false, const bool debugInternal = false, const bool & record = false, Variables * theVars = nullptr)
Run a simulation.
Parameters
[in] driverChoice Driver that should be used to run the simulation. Valid values are: 1 - trDynaPS (default): PS, PR, FI, BF, SUCS, RuACT, XanCycle, RROEA 2 - DynaPS: PS, PR, FI, BF, SUCS, XanCycle 3 - CM: PS, PR, SUCS 4 - EPS: PS, PR, FI, BF, SUCS
[in] inputs Map between variable names and values that they should be set to.
[in] begintime The starting time for the calculations.
[in] stoptime The time to stop calculations.
[in] stepsize The step size to use in the calculations.
[in] maxSubSteps The maximum number of iterations at each time step.
[in] abstol Absolute tolerance for calculations.
[in] reltol Relative tolerance for calculations.
[in] useC3 Use the C3 model, automatically set to true for the EPS driver.
[in] evnFile The full path to the file containing environmental parameters.
[in] atpcostFile The full path to the file containing the ATP cost.
[in] enzymeFile The full path to the file containing enzyme activities.
[in] grnFile The full path to the file containing transcription factor ratios for relevant enzymes.
[in] outputFile Full path to the text file where outputs should be saved.
[in] outputVars Vector of the names of variables that should be output to outputFile at the end of a simulation. Variables for modules, equilibirium constants, etc. can be specified by including the C++ scope of the variable. (e.g. MOD:BF:cATPsyn would output the concentration of ATP synthase). If not provided the output variables will be determined by the driver.
[in] outputParam Control for how often model parameters should be output during the course of the simulation. Choices are: 0 - (default) Don't output parameters during the run. 1 - Output the initial parameter values. 2 - Output the initial and final parameter values. 3 - Output the parameter values for each step in addition to the initial and final values.
[in] outputParamBase Base name for files parameter values should be output to at times through the run as specified by outputParam.
[in] outputParamVars Vector of the names of variables that should be output at the times during the run indicated by outputParam. If not provided, all variables will be output.
[in] dbglvl Debug level.
[in] debugDelta Debug deltas.
[in] debugInternal Debug internals.
[in] record Record output values for all steps (this can significantly slow the program).
[in] theVars Variables instance containing some parameters for the simulation. It will be updated with variables passed as arguments and read from provided input files. This instance will be deleted at the end of the simulation.
Returns
Map of variables names and values at the end of the simulation.
Definition at line 191 of file ePhotosynthesis.cpp.
References ePhotosynthesis::Variables::readEnzymeAct(), ePhotosynthesis::Variables::readGRN(), ePhotosynthesis::Variables::readParam(), ePhotosynthesis::Variables::record, run_simulation(), ePhotosynthesis::drivers::select_driver(), ePhotosynthesis::Variables::updateParam(), and ePhotosynthesis::Variables::useC3.
run_simulation() [2/2]
std::map< std::string, double > ePhotosynthesis::run_simulation (Variables *& theVars, const DriverType driverChoice, const double & begintime = 0.0, const double & stoptime = 5000.0, const double & stepsize = 1.0, const int & maxSubSteps = 750, const double & abstol = 1e-5, const double & reltol = 1e-4, const std::string & outputFile = "", const std::vector< std::string > & outputVars = {}, int outputParam = 0, const std::string & outputParamBase = "", const std::vector< std::string > & outputParamVars = {})
Run a simulation.
Parameters
[in,out] theVars Variables instance containing parameters for the simulation. The results of the simulation will also be stored here at the end of the simulation.
[in] driverChoice Driver that should be used to run the simulation. Valid values are: 1 - trDynaPS (default): PS, PR, FI, BF, SUCS, RuACT, XanCycle, RROEA 2 - DynaPS: PS, PR, FI, BF, SUCS, XanCycle 3 - CM: PS, PR, SUCS 4 - EPS: PS, PR, FI, BF, SUCS
[in] begintime The starting time for the calculations.
[in] stoptime The time to stop calculations.
[in] stepsize The step size to use in the calculations.
[in] maxSubSteps The maximum number of iterations at each time step.
[in] abstol Absolute tolerance for calculations.
[in] reltol Relative tolerance for calculations.
[in] outputFile Full path to the text file where outputs should be saved.
[in] outputVars Vector of the names of variables that should be output to outputFile at the end of a simulation. Variables for modules, equilibirium constants, etc. can be specified by including the C++ scope of the variable. (e.g. MOD:BF:cATPsyn would output the concentration of ATP synthase). If not provided the output variables will be determined by the driver.
[in] outputParam Control for how often model parameters should be output during the course of the simulation. Choices are: 0 - (default) Don't output parameters during the run. 1 - Output the initial parameter values. 2 - Output the initial and final parameter values. 3 - Output the parameter values for each step in addition to the initial and final values.
[in] outputParamBase Base name for files parameter values should be output to at times through the run as specified by outputParam.
[in] outputParamVars Vector of the names of variables that should be output at the times during the run indicated by outputParam. If not provided, all variables will be output.
Returns
Map of variables names and values at the end of the simulation.
Definition at line 73 of file ePhotosynthesis.cpp.
References ePhotosynthesis::drivers::create_driver(), ePhotosynthesis::Variables::deepcopy(), ePhotosynthesis::drivers::Driver::getOutput(), ePhotosynthesis::drivers::Driver::inputVars, ePhotosynthesis::drivers::Driver::output, ePhotosynthesis::drivers::Driver::outputParam(), ePhotosynthesis::drivers::Driver::run(), ePhotosynthesis::drivers::Driver::setOutputVars(), and ePhotosynthesis::drivers::Driver::writeOutputTable().
Referenced by run_simulation().
SYSInitial()
void ePhotosynthesis::SYSInitial (Variables * theVars)
Set some initial global variables
Parameters
[in,out] theVars The global variables
Definition at line 37 of file SYSInitial.cpp.
Referenced by ePhotosynthesis::drivers::DynaPSDriver::setup(), ePhotosynthesis::drivers::EPSDriver::setup(), and ePhotosynthesis::drivers::trDynaPSDriver::setup().
TargetFunVal()
double ePhotosynthesis::TargetFunVal (const Variables * theVars)
Definition at line 32 of file TargetFunVal.cpp.
References ePhotosynthesis::Variables::record, and ePhotosynthesis::Variables::VolRatioStCyto.
Referenced by ePhotosynthesis::drivers::CMDriver::getResults(), ePhotosynthesis::drivers::DynaPSDriver::getResults(), ePhotosynthesis::drivers::EPSDriver::getResults(), ePhotosynthesis::drivers::trDynaPSDriver::getResults(), and ePhotosynthesis::drivers::Driver::getVar().
zeros()
arr ePhotosynthesis::zeros (const std::size_t length) inline
Helper function to initialize a vector of 0's of the given length.
Parameters
length The size of the vector to return
Returns
A vector of 0's, with the input size.
Definition at line 267 of file definitions.hpp.
Referenced by DEFINE_MODULE_COMPOSITE(), GenOut(), ePhotosynthesis::drivers::DynaPSDriver::getResults(), ePhotosynthesis::drivers::EPSDriver::getResults(), ePhotosynthesis::drivers::trDynaPSDriver::getResults(), makeFluxTR(), ParamSet(), and ePhotosynthesis::drivers::DynaPSDriver::setup().
Variable Documentation
ALL_MODULE
const std::vector<MODULE> ePhotosynthesis::ALL_MODULE static
Initial value:
= {
    MODULE_BF      ,
    MODULE_CM      ,
    MODULE_DynaPS  ,
    MODULE_EPS     ,
    MODULE_FIBF    ,
    MODULE_FI      ,
    MODULE_PR      ,
    MODULE_PS      ,
    MODULE_PS_PR   ,
    MODULE_RA      ,
    MODULE_RROEA   ,
    MODULE_RedoxReg,
    MODULE_RuACT   ,
    MODULE_SUCS    ,
    MODULE_XanCycle,
    MODULE_trDynaPS,
    MODULE_ALL
  }
All enum values
Definition at line 65 of file enums_helpers.hpp.
Referenced by ePhotosynthesis::Variables::max_value_width_all(), and ePhotosynthesis::Variables::parseVar().
ALL_PARAM_TYPE
const std::vector<PARAM_TYPE> ePhotosynthesis::ALL_PARAM_TYPE static
Initial value:
= {
    PARAM_TYPE_COND,
    PARAM_TYPE_POOL,
    PARAM_TYPE_KE  ,
    PARAM_TYPE_MOD ,
    PARAM_TYPE_RC  ,
    PARAM_TYPE_VARS,
    PARAM_TYPE_VEL
  }
All enum values
Definition at line 113 of file enums_helpers.hpp.
Referenced by ePhotosynthesis::Variables::parseVar().
ALL_STATIC_VALUE_FLAG
const std::vector<STATIC_VALUE_FLAG> ePhotosynthesis::ALL_STATIC_VALUE_FLAG static
Initial value:
= {
    STATIC_VALUE_FLAG_CONST     ,
    STATIC_VALUE_FLAG_CALC      ,
    STATIC_VALUE_FLAG_NON_VECTOR,
    STATIC_VALUE_FLAG_RESET_ONE ,
    STATIC_VALUE_FLAG_INIT_ONCE
  }
All enum values
Definition at line 192 of file enums_helpers.hpp.
ALL_VALUE_FLAG
const std::vector<VALUE_FLAG> ePhotosynthesis::ALL_VALUE_FLAG static
Initial value:
= {
    VALUE_FLAG_SKIPPED
  }
All enum values
Definition at line 156 of file enums_helpers.hpp.
glymaID_order
std::vector<std::string> ePhotosynthesis::glymaID_order static
Definition at line 85 of file definitions.hpp.
Referenced by ePhotosynthesis::Variables::readGRN().
ValueSetBase< T, U, ID, PT >::child_classes
template<class T, class U, MODULE ID, PARAM_TYPE PT> std::vector<ValueSetClassWrapper> ePhotosynthesis::ValueSetBase< T, U, ID, PT >::child_classes = {}
Definition at line 2162 of file ValueSet.hpp.
ValueSetBase< T, U, ID, PT >::defaults
template<class T, class U, MODULE ID, PARAM_TYPE PT> std::map<typename ValueSetBase<T, U, ID, PT>::EnumType, double> ePhotosynthesis::ValueSetBase< T, U, ID, PT >::defaults = {}
Definition at line 2154 of file ValueSet.hpp.
ValueSetBase< T, U, ID, PT >::static_flags
template<class T, class U, MODULE ID, PARAM_TYPE PT> int ePhotosynthesis::ValueSetBase< T, U, ID, PT >::static_flags = 0
Definition at line 2150 of file ValueSet.hpp.
ValueSetBase< T, U, ID, PT >::static_values
template<class T, class U, MODULE ID, PARAM_TYPE PT> std::map<typename ValueSetBase<T, U, ID, PT>::EnumType, double*> ePhotosynthesis::ValueSetBase< T, U, ID, PT >::static_values = {}
Definition at line 2158 of file ValueSet.hpp.
ValueSetEnum< M, PT >::aliases
template<MODULE M, PARAM_TYPE PT> const std::map<std::string, typename ValueSetEnum<M, PT>::Type> ePhotosynthesis::ValueSetEnum< M, PT >::aliases = {}
Definition at line 404 of file enums.hpp.
ValueSetEnum< M, PT >::all
template<MODULE M, PARAM_TYPE PT> const std::vector<typename ValueSetEnum<M, PT>::Type> ePhotosynthesis::ValueSetEnum< M, PT >::all = {}
Definition at line 394 of file enums.hpp.
Referenced by ePhotosynthesis::Variables::getParamTypes().
ValueSetEnum< M, PT >::defaults
template<MODULE M, PARAM_TYPE PT> const std::map<typename ValueSetEnum<M, PT>::Type, double> ePhotosynthesis::ValueSetEnum< M, PT >::defaults = {}
Definition at line 398 of file enums.hpp.
ValueSetEnum< M, PT >::defaults_C3
template<MODULE M, PARAM_TYPE PT> const std::map<typename ValueSetEnum<M, PT>::Type, double> ePhotosynthesis::ValueSetEnum< M, PT >::defaults_C3 = {}
Definition at line 400 of file enums.hpp.
ValueSetEnum< M, PT >::docs
template<MODULE M, PARAM_TYPE PT> const std::map<typename ValueSetEnum<M, PT>::Type, std::string> ePhotosynthesis::ValueSetEnum< M, PT >::docs = {}
Definition at line 406 of file enums.hpp.
ValueSetEnum< M, PT >::glymaids
template<MODULE M, PARAM_TYPE PT> const std::map<typename ValueSetEnum<M, PT>::Type, std::string> ePhotosynthesis::ValueSetEnum< M, PT >::glymaids = {}
Definition at line 402 of file enums.hpp.
ValueSetEnum< M, PT >::module
template<MODULE M, PARAM_TYPE PT> const MODULE ePhotosynthesis::ValueSetEnum< M, PT >::module = M
Definition at line 390 of file enums.hpp.
Referenced by ePhotosynthesis::Variables::dump(), ePhotosynthesis::Variables::getDocs(), ePhotosynthesis::Variables::getDocs(), ePhotosynthesis::Variables::getParamTypes(), ePhotosynthesis::Variables::getVar(), ePhotosynthesis::Variables::getVar(), ePhotosynthesis::Variables::setVar(), and ePhotosynthesis::Variables::setVar().
ValueSetEnum< M, PT >::names
template<MODULE M, PARAM_TYPE PT> const std::map<typename ValueSetEnum<M, PT>::Type, std::string> ePhotosynthesis::ValueSetEnum< M, PT >::names = {}
Definition at line 396 of file enums.hpp.
ValueSetEnum< M, PT >::param_type
template<MODULE M, PARAM_TYPE PT> const PARAM_TYPE ePhotosynthesis::ValueSetEnum< M, PT >::param_type = PT
Definition at line 392 of file enums.hpp.
Referenced by ePhotosynthesis::Variables::dump(), ePhotosynthesis::Variables::getDocs(), ePhotosynthesis::Variables::getDocs(), ePhotosynthesis::Variables::getVar(), ePhotosynthesis::Variables::getVar(), ePhotosynthesis::Variables::setVar(), and ePhotosynthesis::Variables::setVar().
ValueSetEnum< M, PT >::static_value_flags
template<MODULE M, PARAM_TYPE PT> const std::map<typename ValueSetEnum<M, PT>::Type, int> ePhotosynthesis::ValueSetEnum< M, PT >::static_value_flags = {}
Definition at line 410 of file enums.hpp.
ValueSetEnum< M, PT >::value_flags
template<MODULE M, PARAM_TYPE PT> std::map<typename ValueSetEnum<M, PT>::Type, int> ePhotosynthesis::ValueSetEnum< M, PT >::value_flags = {}
Definition at line 408 of file enums.hpp.
ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::Type> ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::aliases
Initial value:
= {
    {"ATPCost"           , ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestATPCost},
    {"CO2"               , ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_in     },
    {"Air_CO2"           , ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_in     },
    {"PAR"               , ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi     },
    {"Radiation_PAR"     , ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi     },
    {"Temp"              , ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Tp         },
    {"WeatherTemperature", ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Tp         }
  }
Definition at line 26 of file enums_VARS.hpp.
ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::all
template<> const std::vector<typename ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::Type> ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::all
Initial value:
= {
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)AVR              ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)HPR              ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)O2               ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_cond         ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)GLight           ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)O2_cond          ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS12ratio        ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)ADP              ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Pi               ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestATPCost      ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_in           ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi_Wps       ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi           ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS2BF_Pi         ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS_PR_Param      ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Tp               ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alfa             ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)fc               ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)lightParam       ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha1           ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha2           ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCI       ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCII      ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSI        ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSIIcore   ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIIantennaSize  ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIantennaSize   ,
    ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)ProteinTotalRatio
  }
Definition at line 16 of file enums_VARS.hpp.
ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)AVR              , 30.0 },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)HPR              , 4.66 },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)O2               , 210.0},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_cond         , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)GLight           , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)O2_cond          , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS12ratio        , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)ADP              , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Pi               , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestATPCost      , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_in           , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi_Wps       , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi           , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS2BF_Pi         , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS_PR_Param      , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Tp               , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alfa             , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)fc               , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)lightParam       , 0.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha1           , 1.205},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha2           , 2.06 },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCI       , 6.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCII      , 13.0 },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSI        , 1.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSIIcore   , 1.0  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIIantennaSize  , 37.0 },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIantennaSize   , 95.0 },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)ProteinTotalRatio, 0.973}
  }
Definition at line 20 of file enums_VARS.hpp.
ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::defaults_C3 = {}
Definition at line 22 of file enums_VARS.hpp.
ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::docs
template<> const std::map<typename ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)AVR              , "[CONST] The conversion factor between volume and area (micromole per meter square per second and milimole per liter per second)."},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)HPR              , "[CONST]"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)O2               , "[CONST] Seems to be unused currently"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_cond         , "[CALC] Intercellular CO2 in umoles m^{-3}, calculated from air CO2 (CO2_in)"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS12ratio        , "[CALC] Calcualted from input_PSI & input_PSIIcore in SYSInitial"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Pi               , "[CALC] Pi used when useC3 is true and EPS module selected"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestATPCost      , "[ALIASES={ATPCost}] Extra ATP cost when useC3 is false (in units per area)"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_in           , "[CALC,ALIASES={CO2,Air_CO2}] Air CO2 concentration in ppm"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi_Wps       , "[CALC] Light intensity (in units of W s^{-1})"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi           , "[CALC,ALIASES={PAR,Radiation_PAR}] Light intensity (in units of umoles m^{-2} s^{-1})"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS2BF_Pi         , "Pi Shared by PS & BF modules when useC3 is false and EPS module is selected"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS_PR_Param      , "Seems to unused currently"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Tp               , "[ALIASES={Temp,WeatherTemperature}] Temperature"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alfa             , "[CONST] Used for scaling light (*= alpha * (1 - fc))"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)fc               , "[CONST] Used for scaling light (*= alpha * (1 - fc))"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)lightParam       , "[CALC]"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha1           , "[CONST] originally 1.205 in C++ code, 1 for Matlab equivalent"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha2           , "[CONST] originally 2.06 in C++ code, 1 for Matlab equivalent"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCI       , "[CONST] Used to set FIBF::ChlPSI in SYSInitial"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCII      , "[CONST] Used to set FIBF::ChlT in SYSInitial"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSI        , "[CONST] Used to set FIBF::ChlPSI & PS12ratio in SYSInitial"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSIIcore   , "[CONST] Used to set FIBF::ChlT2, FIBF::ChlT & PS12ratio in SYSInitial"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIIantennaSize  , "[CONST] Used to set FIBF::ChlT2 & FIBF::ChlT in SYSInitial"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIantennaSize   , "[CONST] Used to set FIBF::ChlPSI in SYSInitial"},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)ProteinTotalRatio, "[CONST] Scaling factor for CM GRN expression levels"}
  }
Definition at line 28 of file enums_VARS.hpp.
ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::glymaids = {}
Definition at line 24 of file enums_VARS.hpp.
ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::names
template<> const std::map<typename ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::names
Initial value:
= {
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)AVR              , "AVR"              },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)HPR              , "HPR"              },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)O2               , "O2"               },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_cond         , "CO2_cond"         },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)GLight           , "GLight"           },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)O2_cond          , "O2_cond"          },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS12ratio        , "PS12ratio"        },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)ADP              , "ADP"              },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Pi               , "Pi"               },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestATPCost      , "TestATPCost"      },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_in           , "CO2_in"           },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi_Wps       , "TestLi_Wps"       },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi           , "TestLi"           },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS2BF_Pi         , "PS2BF_Pi"         },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS_PR_Param      , "PS_PR_Param"      },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Tp               , "Tp"               },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alfa             , "alfa"             },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)fc               , "fc"               },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)lightParam       , "lightParam"       },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha1           , "alpha1"           },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha2           , "alpha2"           },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCI       , "input_LHCI"       },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCII      , "input_LHCII"      },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSI        , "input_PSI"        },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSIIcore   , "input_PSIIcore"   },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIIantennaSize  , "PSIIantennaSize"  },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIantennaSize   , "PSIantennaSize"   },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)ProteinTotalRatio, "ProteinTotalRatio"}
  }
Definition at line 18 of file enums_VARS.hpp.
ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)AVR              , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)HPR              , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)O2               , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_cond         , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PS12ratio        , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)Pi               , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)CO2_in           , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi_Wps       , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)TestLi           , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alfa             , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)fc               , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)lightParam       , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha1           , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)alpha2           , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCI       , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_LHCII      , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSI        , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)input_PSIIcore   , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIIantennaSize  , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)PSIantennaSize   , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::SCOPED_ENUM_TYPE(Type)ProteinTotalRatio, (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 32 of file enums_VARS.hpp.
ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_ALL, PARAM_TYPE_VARS>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_ALL, PARAM_TYPE_VARS >::value_flags = {}
Definition at line 30 of file enums_VARS.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::aliases = {}
Definition at line 26 of file enums_COND.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPHr  ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytc1  ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPo   ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPoQH2,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QHsemi ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytbL  ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qi     ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Q      ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytbH  ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qn     ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qr     ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QH2    ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytc2  ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P700   ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ADP    ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATP    ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Ks     ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Mgs    ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Cls    ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Aip    ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)U      ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)An     ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Fdn    ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)BFHs   ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)BFHl   ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PHs    ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PHl    ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)NADPH
  }
Definition at line 16 of file enums_COND.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPHr  , 0.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytc1  , 1.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPo   , 1.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPoQH2, 0.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QHsemi , 0.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytbL  , 1.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qi     , 0.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Q      , 1.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytbH  , 1.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qn     , 0.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qr     , 0.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QH2    , 5.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytc2  , 1.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P700   , 0.5    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ADP    , 0.82   },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATP    , 0.68   },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Ks     , 10.0   },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Mgs    , 5.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Cls    , 1.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Aip    , 0.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)U      , 0.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)An     , 0.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Fdn    , 0.3    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)BFHs   , 19.0001},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)BFHl   , 19.0001},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PHs    , 7.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PHl    , 7.0    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)NADPH  , 0.21   }
  }
Definition at line 20 of file enums_COND.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 22 of file enums_COND.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPHr  , "The reduced ion sulfer protein (ISPH); unit: micromole per m2"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytc1  , "The oxidized state of cytc1; unit: micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPo   , "The oxidized ion sulfer protein (ISP); unit: micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPoQH2, "The complex of oxidized ion sulfer protein and reduced quinone; unit: micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QHsemi , "Semiquinone; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytbL  , "The oxidized cytbL; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qi     , "The binding Quinone; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Q      , "Quinone; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytbH  , "The oxidized form of cytbH; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qn     , "Q-; unit: micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qr     , "The reduced quinone Q2-; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QH2    , "The reduced quinone PQH2; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytc2  , "oxidized cytc2; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P700   , "The reduced state of P700, including both P700 and excited P700; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ADP    , "ADP in stroma, from the earlier photorespiration model; mmol l-1"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATP    , "ATP in stroma, from the photorespiration model; mmol l-1"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Ks     , "K ions in stroma, mM, from the literature; mmol l-1; 90 might be an default;"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Mgs    , "Mg ions in stroma, mM, from the literature of the ion estimate"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Cls    , "Cl ions in stroma, mM, from the literature of the ion estimate"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Aip    , "The number of photons in peripheral antenna; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)U      , "The number of photons in core antenna; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)An     , "The reduced electron acceptor in PSI; micromole per meter square"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Fdn    , "The reduced ferrodoxin; micromole per meter square leaf area"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)BFHs   , "The protonated buffer species  and free proton together in stroma; mmol l-1; The value follows Laisk and Walker, 1989. But they did not give reference about the source of this number.; default 25"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)BFHl   , "The protonated buffer species and free proton together in lumen; mmol l-1; The value follows Laisk and Walker, 1989. But they did not give reference about the source of this number. ; default 5"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PHs    , "The PH value of the stroma"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PHl    , "The PH value of the lumen"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)NADPH  , "The NADPH concentration in stroma, Unit: mmol l-1;"}
  }
Definition at line 28 of file enums_COND.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::glymaids = {}
Definition at line 24 of file enums_COND.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPHr  , "ISPHr"  },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytc1  , "cytc1"  },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPo   , "ISPo"   },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ISPoQH2, "ISPoQH2"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QHsemi , "QHsemi" },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytbL  , "cytbL"  },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qi     , "Qi"     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Q      , "Q"      },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytbH  , "cytbH"  },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qn     , "Qn"     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Qr     , "Qr"     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QH2    , "QH2"    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)cytc2  , "cytc2"  },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P700   , "P700"   },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ADP    , "ADP"    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATP    , "ATP"    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Ks     , "Ks"     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Mgs    , "Mgs"    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Cls    , "Cls"    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Aip    , "Aip"    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)U      , "U"      },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)An     , "An"     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Fdn    , "Fdn"    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)BFHs   , "BFHs"   },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)BFHl   , "BFHl"   },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PHs    , "PHs"    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PHl    , "PHl"    },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)NADPH  , "NADPH"  }
  }
Definition at line 18 of file enums_COND.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 32 of file enums_COND.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_COND >::value_flags = {}
Definition at line 30 of file enums_COND.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_BF, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::aliases = {}
Definition at line 26 of file enums_KE.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::all = {}
Definition at line 16 of file enums_KE.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::defaults = {}
Definition at line 20 of file enums_KE.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 22 of file enums_KE.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::docs = {}
Definition at line 28 of file enums_KE.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::glymaids = {}
Definition at line 24 of file enums_KE.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::names = {}
Definition at line 18 of file enums_KE.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::static_value_flags = {}
Definition at line 32 of file enums_KE.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_KE >::value_flags = {}
Definition at line 30 of file enums_KE.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::aliases = {}
Definition at line 26 of file enums_MOD.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::all
Initial value:
= {
    ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cATPsyn     ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)CPSi        ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cNADPHsyn   ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)EPS_ATP_Rate,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)_Pi         ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)PMODTEM     ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RT          ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)DeltaGo
  }
Definition at line 16 of file enums_MOD.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cATPsyn     , 0.0     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)CPSi        , 0.0     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cNADPHsyn   , 0.0     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)EPS_ATP_Rate, 0.0     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)_Pi         , 0.9     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)PMODTEM     , 1.0     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RT          , 2477.572},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)DeltaGo     , 30543.2 }
  }
Definition at line 20 of file enums_MOD.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::defaults_C3
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cATPsyn     , 1.0},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)CPSi        , 1.0},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cNADPHsyn   , 1.0},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)EPS_ATP_Rate, 0.0},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)_Pi         , 0.9}
  }
Definition at line 22 of file enums_MOD.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cATPsyn     , "[GLYMAID=Glyma.13G204800] cATPsyn=1.0447;%1.01866 WY201803"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)CPSi        , "[GLYMAID=Glyma.10G042000] CPSi=1.0131;% 1.0237 WY201803"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cNADPHsyn   , "[GLYMAID=Glyma.09G024100] cNADPHsyn=1.094468408;%1.0388 WY201803"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)EPS_ATP_Rate, "Indicate in the beginning there is no ATP synthesis activity."},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)_Pi         , "Phosphate in stroma"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)PMODTEM     , "[CONST] ?; Used to scale RC parameters PK, PMg, & PCl"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RT          , "[CONST] 8.314 * 298.; Gas constant and the temperature. Used to calculate RC parameters KE8, KE9 & KE11"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)DeltaGo     , "[CONST] 7.3 * 4184; The free energy change for ATP synthesis from ADP and Pi; Used to calculate KE11"}
  }
Definition at line 28 of file enums_MOD.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::glymaids
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cATPsyn  , "Glyma.13G204800"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)CPSi     , "Glyma.10G042000"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cNADPHsyn, "Glyma.09G024100"}
  }
Definition at line 24 of file enums_MOD.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::names
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cATPsyn     , "cATPsyn"     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)CPSi        , "CPSi"        },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cNADPHsyn   , "cNADPHsyn"   },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)EPS_ATP_Rate, "EPS_ATP_Rate"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)_Pi         , "_Pi"         },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)PMODTEM     , "PMODTEM"     },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RT          , "RT"          },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)DeltaGo     , "DeltaGo"     }
  }
Definition at line 18 of file enums_MOD.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)PMODTEM, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RT     , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)DeltaGo, (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 32 of file enums_MOD.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 30 of file enums_MOD.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::aliases
Initial value:
= {
    {"Tcyt"  , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_d},
    {"Tcytc2", ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_f},
    {"TK"    , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_U},
    {"TMg"   , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_A},
    {"TCl"   , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_d},
    {"TFd"   , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_f},
    {"TA"    , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k1  },
    {"TQ"    , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k_r1},
    {"BFTs"  , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kz  },
    {"BFTl"  , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k12 },
    {"P700T" , ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k23 },
    {"NADPHT", ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k30 }
  }
Definition at line 26 of file enums_POOL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::all
Initial value:
= {
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_d,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_f,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_U,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_A,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_d,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_f,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k1  ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k_r1,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kz  ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k12 ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k23 ,
    ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k30
  }
Definition at line 16 of file enums_POOL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_d, 1.0 },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_f, 1.0 },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_U, 20.0},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_A, 10.0},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_d, 2.0 },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_f, 1.0 },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k1  , 1.0 },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k_r1, 8.0 },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kz  , 38.0},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k12 , 38.0},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k23 , 1.0 },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k30 , 1.0 }
  }
Definition at line 20 of file enums_POOL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 22 of file enums_POOL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_d, "[ALIASES={Tcyt}] The total amount of cytbH or cytbL; Unit: micromole m-2 leaf area"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_f, "[ALIASES={Tcytc2}] The total amount of cytc; Unit: micromole m-2 leaf area"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_U, "[ALIASES={TK}] The total concentration of K in both stroma and lumen. Unit: mmol l-1. In this model, it was assumed that the total concentration of K, and Mg and Cl as well, is constant."},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_A, "[ALIASES={TMg}] The total concentration of Mg in both stroma and lumen. Unit: mmol l-1. In this model, it was assumed that the total concentration of Mg, and K and Cl as well, is constant."},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_d, "[ALIASES={TCl}] The total concentration of Cl in both stroma and lumen. Unit: mmol l-1. In this model, it was assumed that the total concentration of Cl in both stroma and lumen is constant."},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_f, "[ALIASES={TFd}] The total concentration of Ferrodoxin"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k1  , "[ALIASES={TA}] The total concentration of the primary electron acceptor of PSI; Unit: micromole m-2 leaf area"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k_r1, "[ALIASES={TQ}] The total concentration of plastoquinone in thylakoid membrane. ; Unit: micromole m-2 leaf area"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kz  , "[ALIASES={BFTs}] The total concentration of buffer in stroma; unit: mmol per liter"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k12 , "[ALIASES={BFTl}] The total concentration of buffer in lumen; unit: mmol per liter"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k23 , "[ALIASES={P700T}] The total number of P700; unit: micromole m-2 leaf area"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k30 , "[ALIASES={NADPHT}]   The total concentration of NADPH in stroma; 1 is an guessed value;"}
  }
Definition at line 28 of file enums_POOL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 24 of file enums_POOL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_d, "kA_d"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_f, "kA_f"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kA_U, "kA_U"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_A, "kU_A"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_d, "kU_d"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kU_f, "kU_f"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k1  , "k1"  },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k_r1, "k_r1"},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)kz  , "kz"  },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k12 , "k12" },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k23 , "k23" },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)k30 , "k30" }
  }
Definition at line 18 of file enums_POOL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::static_value_flags = {}
Definition at line 32 of file enums_POOL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 30 of file enums_POOL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::aliases = {}
Definition at line 26 of file enums_RC.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::all
Definition at line 16 of file enums_RC.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::defaults
Definition at line 20 of file enums_RC.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 22 of file enums_RC.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::docs
Definition at line 28 of file enums_RC.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::glymaids = {}
Definition at line 24 of file enums_RC.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::names
Definition at line 18 of file enums_RC.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)KE8    , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)KE9    , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Em_IPS , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Em_Cytf, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Em_PG  , (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 32 of file enums_RC.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_RC >::value_flags = {}
Definition at line 30 of file enums_RC.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_BF, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::aliases = {}
Definition at line 26 of file enums_VEL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::all
Definition at line 16 of file enums_VEL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::defaults
Definition at line 20 of file enums_VEL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 22 of file enums_VEL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::docs = {}
Definition at line 28 of file enums_VEL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 24 of file enums_VEL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::names
Definition at line 18 of file enums_VEL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 32 of file enums_VEL.hpp.
ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_BF, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_BF, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 30 of file enums_VEL.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_CM, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::aliases = {}
Definition at line 64 of file enums_COND.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::all = {}
Definition at line 54 of file enums_COND.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::defaults = {}
Definition at line 58 of file enums_COND.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 60 of file enums_COND.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::docs = {}
Definition at line 66 of file enums_COND.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::glymaids = {}
Definition at line 62 of file enums_COND.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::names = {}
Definition at line 56 of file enums_COND.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 70 of file enums_COND.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_COND >::value_flags = {}
Definition at line 68 of file enums_COND.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_CM, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::aliases = {}
Definition at line 64 of file enums_MOD.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::all = {}
Definition at line 54 of file enums_MOD.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::defaults = {}
Definition at line 58 of file enums_MOD.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 60 of file enums_MOD.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::docs = {}
Definition at line 66 of file enums_MOD.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 62 of file enums_MOD.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::names = {}
Definition at line 56 of file enums_MOD.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::static_value_flags = {}
Definition at line 70 of file enums_MOD.hpp.
ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_CM, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_CM, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 68 of file enums_MOD.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::aliases = {}
Definition at line 102 of file enums_COND.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::all = {}
Definition at line 92 of file enums_COND.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::defaults = {}
Definition at line 96 of file enums_COND.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 98 of file enums_COND.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::docs = {}
Definition at line 104 of file enums_COND.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::glymaids = {}
Definition at line 100 of file enums_COND.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::names = {}
Definition at line 94 of file enums_COND.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 108 of file enums_COND.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_COND >::value_flags = {}
Definition at line 106 of file enums_COND.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::aliases = {}
Definition at line 102 of file enums_MOD.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::all = {}
Definition at line 92 of file enums_MOD.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::defaults = {}
Definition at line 96 of file enums_MOD.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 98 of file enums_MOD.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::docs = {}
Definition at line 104 of file enums_MOD.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 100 of file enums_MOD.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::names = {}
Definition at line 94 of file enums_MOD.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::static_value_flags = {}
Definition at line 108 of file enums_MOD.hpp.
ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_DynaPS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_DynaPS, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 106 of file enums_MOD.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::aliases = {}
Definition at line 140 of file enums_COND.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::all = {}
Definition at line 130 of file enums_COND.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::defaults = {}
Definition at line 134 of file enums_COND.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 136 of file enums_COND.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::docs = {}
Definition at line 142 of file enums_COND.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::glymaids = {}
Definition at line 138 of file enums_COND.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::names = {}
Definition at line 132 of file enums_COND.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 146 of file enums_COND.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_COND >::value_flags = {}
Definition at line 144 of file enums_COND.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::aliases = {}
Definition at line 140 of file enums_MOD.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::all = {}
Definition at line 130 of file enums_MOD.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::defaults = {}
Definition at line 134 of file enums_MOD.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 136 of file enums_MOD.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::docs = {}
Definition at line 142 of file enums_MOD.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 138 of file enums_MOD.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::names = {}
Definition at line 132 of file enums_MOD.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::static_value_flags = {}
Definition at line 146 of file enums_MOD.hpp.
ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_EPS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_EPS, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 144 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::aliases = {}
Definition at line 216 of file enums_COND.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)A         ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)U         ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680ePheo ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680pPheon,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680pPheo ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680Pheon ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Yz        ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S1T       ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S2T       ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S3T       ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S0T       ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S1Tp      ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S2Tp      ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S3Tp      ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S0Tp      ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQB      ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQB     ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQBn     ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQBn    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQB2n    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQB2n   ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PQn
  }
Definition at line 206 of file enums_COND.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)A         , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)U         , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680ePheo , 1  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680pPheon, 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680pPheo , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680Pheon , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Yz        , 1  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S1T       , 0.8},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S2T       , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S3T       , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S0T       , 0.2},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S1Tp      , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S2Tp      , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S3Tp      , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S0Tp      , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQB      , 1  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQB     , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQBn     , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQBn    , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQB2n    , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQB2n   , 0  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PQn       , 5  }
  }
Definition at line 210 of file enums_COND.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 212 of file enums_COND.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)A         , "The concentration of excitons in the peripheral antenna"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)U         , "The concentration fo excitons in the core antenna"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680ePheo , "The concentration of the P680Pheo; QF add"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680pPheon, "The concentration for the P680+ Pheo-"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680pPheo , "The concentration of P680+ Pheo"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680Pheon , "The concentration of P680Pheo-"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Yz        , "The concentration of reduced tyrosine; --unused"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S1T       , "The concentration of S1 in combination with reduced tyrosine"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S2T       , "The concentration of S2 in combination with reduced tyrosine"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S3T       , "The concentration of S3 in combination with reduced tyrosine"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S0T       , "The concentration of S0 in combination with reduced tyrosine"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S1Tp      , "The concentration of S1 in combination with oxidized tyrosine"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S2Tp      , "The concentration of S2 in combination with oxidized tyrosine"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S3Tp      , "The concentration of S3 in combination with oxidized tyrosine"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S0Tp      , "The concentration of S0 in combination with oxidized tyrosine"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQB      , "The concentration of [QAQB]"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQB     , "The concentration of [QA-QB]"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQBn     , "The concentration of [QAQB-]"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQBn    , "The concentration of [QA-QB-]"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQB2n    , "The concentration of [QAQB2-]"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQB2n   , "The concentration of [QA-QB2-]"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PQn       , "The concentration of reduced PQ, i.e. PQH2;"}
  }
Definition at line 218 of file enums_COND.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::glymaids = {}
Definition at line 214 of file enums_COND.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)A         , "A"         },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)U         , "U"         },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680ePheo , "P680ePheo" },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680pPheon, "P680pPheon"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680pPheo , "P680pPheo" },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)P680Pheon , "P680Pheon" },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Yz        , "Yz"        },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S1T       , "S1T"       },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S2T       , "S2T"       },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S3T       , "S3T"       },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S0T       , "S0T"       },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S1Tp      , "S1Tp"      },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S2Tp      , "S2Tp"      },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S3Tp      , "S3Tp"      },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S0Tp      , "S0Tp"      },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQB      , "QAQB"      },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQB     , "QAnQB"     },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQBn     , "QAQBn"     },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQBn    , "QAnQBn"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAQB2n    , "QAQB2n"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)QAnQB2n   , "QAnQB2n"   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PQn       , "PQn"       }
  }
Definition at line 208 of file enums_COND.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 222 of file enums_COND.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_COND >::value_flags = {}
Definition at line 220 of file enums_COND.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FI, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::aliases = {}
Definition at line 102 of file enums_KE.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::all = {}
Definition at line 92 of file enums_KE.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::defaults = {}
Definition at line 96 of file enums_KE.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 98 of file enums_KE.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::docs = {}
Definition at line 104 of file enums_KE.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::glymaids = {}
Definition at line 100 of file enums_KE.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::names = {}
Definition at line 94 of file enums_KE.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::static_value_flags = {}
Definition at line 108 of file enums_KE.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_KE >::value_flags = {}
Definition at line 106 of file enums_KE.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::aliases = {}
Definition at line 216 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::all
Initial value:
= {
    ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cpsii
  }
Definition at line 206 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cpsii, 0.0}
  }
Definition at line 210 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::defaults_C3
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cpsii, 1.0}
  }
Definition at line 212 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cpsii, "[GLYMAID=Glyma.01G095900]"}
  }
Definition at line 218 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::glymaids
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cpsii, "Glyma.01G095900"}
  }
Definition at line 214 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::names
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)cpsii, "cpsii"}
  }
Definition at line 208 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::static_value_flags = {}
Definition at line 222 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 220 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::aliases = {}
Definition at line 102 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::all
Initial value:
= {
    ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)QBt,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PQT
  }
Definition at line 92 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)QBt, 1},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PQT, 8}
  }
Definition at line 96 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 98 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)QBt, "The total concentration of Qb site;"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PQT, "The total concentration of PQ;"}
  }
Definition at line 104 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 100 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)QBt, "QBt"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PQT, "PQT"}
  }
Definition at line 94 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::static_value_flags = {}
Definition at line 108 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 106 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::aliases = {}
Definition at line 102 of file enums_RC.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::all
Initial value:
= {
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_d    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_f    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_U    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_A    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_d    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_f    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k1      ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_r1    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kz      ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k12     ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k23     ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k30     ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k01     ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k2      ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kAB1    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kBA1    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kAB2    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kBA2    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k3      ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_r3    ,
    ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_pq_oxy
  }
Definition at line 92 of file enums_RC.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_d    , 2e8   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_f    , 1.26e6},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_U    , 1.0e10},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_A    , 1.0e10},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_d    , 2e8   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_f    , 1.26e6},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k1      , 2.5e11},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_r1    , 3e8   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kz      , 5e6   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k12     , 30000 },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k23     , 10000 },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k30     , 3000  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k01     , 500   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k2      , 2e9   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kAB1    , 2500  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kBA1    , 200   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kAB2    , 3300  },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kBA2    , 250   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k3      , 800   },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_r3    , 80    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_pq_oxy, 500   }
  }
Definition at line 96 of file enums_RC.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 98 of file enums_RC.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_d    , "The rate constant of heat dissipation from peripheral antenna Lazar (1999), 0.25~1 *10^(9)"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_f    , "The rate constant of fluorescence emission from peripheral antenna Lazar 1999, with a lifetime of 5 ns at closed reaction center"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_U    , "The rate constant of exciton transfer from periphral antenna to core antenna Reference needed, a guess"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_A    , "The rate constant of exciton transfer from core antenna to peripheral antenna Reference needed, a guess"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_d    , "The rate constant of heat emission from core antenna"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_f    , "The rate constant of fluorescence emission from core antenna"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k1      , "The rate constant of primary charge separation for open reaction center"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_r1    , "The rate constant of charge recombination for open reactoin center"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kz      , "The rate constant of the Tyrosine oxidation Lazar (1999); 3.8~50 * 10^6"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k12     , "The rate constant of the S1 to S2 transition Lazar (1999); 0.667~33.3 * 10^3"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k23     , "The rate constant of the S2 to S3 transition Lazar (1999); 0.667~33.3 * 10^3"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k30     , "The rate constant of the S3 to S0 transition Lazar (1999); 0.667~33.3 * 10^3"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k01     , "The rate constant of the S0 to S1 transition Lazar (1999); 0.667~33.3 * 10^3"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k2      , "The rate constant of the QA reduction by Pheo- Lazar (1999); 2~2.3 * 10^9"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kAB1    , "The rate constant of QAQB-->QAQB- Lazar (1999); 2.5~5 * 10^3"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kBA1    , "The rate constant of the QAQB- -->QAQB Lazar (1999)"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kAB2    , "The rate constant of the QAQB- --> QAQB2- Lazar (1999); 1.25~3.33 * 10^3"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kBA2    , "The rate constant of the QAQB2- --> QAQB- Lazar (1999), or same as kAB2 depend on the equilibium constant"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k3      , "The rate constant of the exchange of PQ and QBH2 Lazar (1999),0.12~1 for the fast PQ pool, or 3~8 for the slow recycling PQ pool"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_r3    , "The rate constant of the exchange of QB and PQH2 Lazar (1999), since the equilibrium constant is 1 (205 in Lazar, 1999)"},
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_pq_oxy, "The rate constant of the PQH2 oxidation Lazar (1999),50~500"}
  }
Definition at line 104 of file enums_RC.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::glymaids = {}
Definition at line 100 of file enums_RC.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::names
Initial value:
= {
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_d    , "kA_d"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_f    , "kA_f"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kA_U    , "kA_U"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_A    , "kU_A"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_d    , "kU_d"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kU_f    , "kU_f"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k1      , "k1"      },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_r1    , "k_r1"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kz      , "kz"      },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k12     , "k12"     },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k23     , "k23"     },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k30     , "k30"     },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k01     , "k01"     },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k2      , "k2"      },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kAB1    , "kAB1"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kBA1    , "kBA1"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kAB2    , "kAB2"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kBA2    , "kBA2"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k3      , "k3"      },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_r3    , "k_r3"    },
    {ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k_pq_oxy, "k_pq_oxy"}
  }
Definition at line 94 of file enums_RC.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::static_value_flags = {}
Definition at line 108 of file enums_RC.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_RC >::value_flags = {}
Definition at line 106 of file enums_RC.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FI, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::aliases = {}
Definition at line 102 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::all
Definition at line 92 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::defaults
Definition at line 96 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 98 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::docs
Definition at line 104 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 100 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::names
Definition at line 94 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 108 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FI, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FI, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 106 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::aliases = {}
Definition at line 178 of file enums_COND.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)kd
  }
Definition at line 168 of file enums_COND.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)kd, 0.5e8}
  }
Definition at line 172 of file enums_COND.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 174 of file enums_COND.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)kd, "The initialization of the initial rate constant for heat dissipation"}
  }
Definition at line 180 of file enums_COND.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::glymaids = {}
Definition at line 176 of file enums_COND.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)kd, "kd"}
  }
Definition at line 170 of file enums_COND.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 184 of file enums_COND.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_COND >::value_flags = {}
Definition at line 182 of file enums_COND.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::aliases = {}
Definition at line 64 of file enums_KE.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::all = {}
Definition at line 54 of file enums_KE.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::defaults = {}
Definition at line 58 of file enums_KE.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 60 of file enums_KE.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::docs = {}
Definition at line 66 of file enums_KE.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::glymaids = {}
Definition at line 62 of file enums_KE.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::names = {}
Definition at line 56 of file enums_KE.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::static_value_flags = {}
Definition at line 70 of file enums_KE.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_KE >::value_flags = {}
Definition at line 68 of file enums_KE.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::aliases = {}
Definition at line 178 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::all
Initial value:
= {
    ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlPSI     ,
    ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT       ,
    ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT2      ,
    ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQ ,
    ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQa
  }
Definition at line 168 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlPSI     , 0.0},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT       , 0.0},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT2      , 0.0},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQ , 0.0},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQa, 0.0}
  }
Definition at line 172 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 174 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlPSI     , "[CALC, INIT_ONCE]"},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT       , "[CALC, INIT_ONCE]"},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT2      , "[CALC, INIT_ONCE]"},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQ , "[CALC, INIT_ONCE]"},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQa, "[CALC, INIT_ONCE]"}
  }
Definition at line 180 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 176 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::names
Initial value:
= {
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlPSI     , "ChlPSI"     },
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT       , "ChlT"       },
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT2      , "ChlT2"      },
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQ , "FIBF2FI_PQ" },
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQa, "FIBF2FI_PQa"}
  }
Definition at line 170 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlPSI     , (STATIC_VALUE_FLAG_CALC | STATIC_VALUE_FLAG_INIT_ONCE)},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT       , (STATIC_VALUE_FLAG_CALC | STATIC_VALUE_FLAG_INIT_ONCE)},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ChlT2      , (STATIC_VALUE_FLAG_CALC | STATIC_VALUE_FLAG_INIT_ONCE)},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQ , (STATIC_VALUE_FLAG_CALC | STATIC_VALUE_FLAG_INIT_ONCE)},
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FIBF2FI_PQa, (STATIC_VALUE_FLAG_CALC | STATIC_VALUE_FLAG_INIT_ONCE)}
  }
Definition at line 184 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 182 of file enums_MOD.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::aliases = {}
Definition at line 64 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::all
Initial value:
= {
    ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PQT
  }
Definition at line 54 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PQT, 8.0}
  }
Definition at line 58 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 60 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::docs = {}
Definition at line 66 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 62 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PQT, "PQT"}
  }
Definition at line 56 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::static_value_flags = {}
Definition at line 70 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 68 of file enums_POOL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::aliases = {}
Definition at line 64 of file enums_RC.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::all = {}
Definition at line 54 of file enums_RC.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::defaults = {}
Definition at line 58 of file enums_RC.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 60 of file enums_RC.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::docs = {}
Definition at line 66 of file enums_RC.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::glymaids = {}
Definition at line 62 of file enums_RC.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::names = {}
Definition at line 56 of file enums_RC.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::static_value_flags = {}
Definition at line 70 of file enums_RC.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_RC >::value_flags = {}
Definition at line 68 of file enums_RC.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::aliases = {}
Definition at line 64 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::all = {}
Definition at line 54 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::defaults = {}
Definition at line 58 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 60 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::docs = {}
Definition at line 66 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 62 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::names = {}
Definition at line 56 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 70 of file enums_VEL.hpp.
ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_FIBF, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_FIBF, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 68 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::aliases = {}
Definition at line 254 of file enums_COND.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCEA ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCA  ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGCA ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCAc ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GOAc ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SERc ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GLYc ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HPRc ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCEAc,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v131
  }
Definition at line 244 of file enums_COND.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCEA , 0.1812},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCA  , 0.36  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGCA , 0.0029},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCAc , 0.36  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GOAc , 0.028 },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SERc , 7.5   },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GLYc , 1.8   },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HPRc , 0.0035},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCEAc, 0.1812},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP , 2.0   },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v131, 0.0   }
  }
Definition at line 248 of file enums_COND.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 250 of file enums_COND.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCEA , "Glycerate in chloroplast; derived based on V113"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCA  , "Derived from radioactive labelling experiment; assume equal concenatration inside and outshide chloroplast"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGCA , "Phosphoglycolate in chloroplast derived based on the Km112; orignal value is : 0.0029;"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCAc , "See the note for GCA."},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GOAc , "Glyoxylate in cytosol; 0.028; EXPERIMENTAL DATA;"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SERc , "Serine in cytosol; 7.5 original value"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GLYc , "Glycine in cytosol; 1.8 original vlaue"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HPRc , "HydroxylPyruvate; derived from equation 123;"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCEAc, "Glycerate in cytosol; assume at equilibrium with GCEA initially."},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP , "RuBP concentration"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v131, "[CONST, NON_VECTOR] ?"}
  }
Definition at line 256 of file enums_COND.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::glymaids = {}
Definition at line 252 of file enums_COND.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCEA , "GCEA" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCA  , "GCA"  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGCA , "PGCA" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCAc , "GCAc" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GOAc , "GOAc" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SERc , "SERc" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GLYc , "GLYc" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HPRc , "HPRc" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GCEAc, "GCEAc"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP , "RuBP" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v131, "_v131"}
  }
Definition at line 246 of file enums_COND.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v131, (STATIC_VALUE_FLAG_CONST | STATIC_VALUE_FLAG_NON_VECTOR)}
  }
Definition at line 260 of file enums_COND.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_COND >::value_flags = {}
Definition at line 258 of file enums_COND.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PR, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::aliases = {}
Definition at line 140 of file enums_KE.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::all = {}
Definition at line 130 of file enums_KE.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::defaults = {}
Definition at line 134 of file enums_KE.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 136 of file enums_KE.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::docs = {}
Definition at line 142 of file enums_KE.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::glymaids = {}
Definition at line 138 of file enums_KE.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::names = {}
Definition at line 132 of file enums_KE.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::static_value_flags = {}
Definition at line 146 of file enums_KE.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_KE >::value_flags = {}
Definition at line 144 of file enums_KE.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::aliases = {}
Definition at line 254 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::all
Definition at line 244 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::defaults
Definition at line 248 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::defaults_C3
Initial value:
= {
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)PR_ADP    , 0.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)PR_ATP    , 0.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)KI124     , 2.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)KM1312    , 0.075},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)KI1312    , 0.015},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)KM1012    , 0.2  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)KI1012    , 0.22 },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor112, 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor113, 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor121, 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor122, 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor123, 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor124, 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor131, 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vf_T131   , 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vf_T113   , 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vf_T123   , 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vf_T121   , 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vf_T122   , 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vf_T112   , 1.0  },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)PGA       , 2.4  }
  }
Definition at line 250 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::docs
Definition at line 256 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::glymaids
Initial value:
= {
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor112, "Glyma.09G015500"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor113, "Glyma.15G012500"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor121, "Glyma.06G017900"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor122, "Glyma.08G302600"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor123, "Glyma.09G255200"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor124, "Glyma.01G026700"},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor131, "Glyma.13G222300"}
  }
Definition at line 252 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::names
Definition at line 246 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)V111   , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)KI124  , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)KM1312 , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)KI1312 , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_112, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_113, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_121, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_122, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_123, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_124, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_131, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)CE     , (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 260 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 258 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PR, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::aliases = {}
Definition at line 140 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::all = {}
Definition at line 130 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::defaults = {}
Definition at line 134 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 136 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::docs = {}
Definition at line 142 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 138 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::names = {}
Definition at line 132 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::static_value_flags = {}
Definition at line 146 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 144 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PR, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::aliases = {}
Definition at line 140 of file enums_RC.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::all
Definition at line 130 of file enums_RC.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::defaults
Definition at line 134 of file enums_RC.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 136 of file enums_RC.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::docs
Definition at line 142 of file enums_RC.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::glymaids = {}
Definition at line 138 of file enums_RC.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::names
Definition at line 132 of file enums_RC.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::static_value_flags = {}
Definition at line 146 of file enums_RC.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_RC >::value_flags = {}
Definition at line 144 of file enums_RC.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::aliases = {}
Definition at line 140 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::all
Initial value:
= {
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v111 ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v112 ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v113 ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v121 ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v122 ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v123 ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v124 ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v131 ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v1in ,
    ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v2out
  }
Definition at line 130 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v111 , 0.0},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v112 , 0.0},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v113 , 0.0},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v121 , 0.0},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v122 , 0.0},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v123 , 0.0},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v124 , 0.0},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v131 , 0.0},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v1in , 0.0},
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v2out, 0.0}
  }
Definition at line 134 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 136 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::docs = {}
Definition at line 142 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 138 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v111 , "v111" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v112 , "v112" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v113 , "v113" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v121 , "v121" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v122 , "v122" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v123 , "v123" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v124 , "v124" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v131 , "v131" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v1in , "v1in" },
    {ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v2out, "v2out"}
  }
Definition at line 132 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 146 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PR, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PR, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 144 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::aliases = {}
Definition at line 292 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGA ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)DPGA,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)T3P ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ADPG,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBP ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)E4P ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S7P ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SBP ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATP ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HexP,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PenP,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_Pi ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_ADP,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v1
  }
Definition at line 282 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP, 2.000 },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGA , 2.400 },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)DPGA, 0.0011},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)T3P , 0.5   },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ADPG, 0.005 },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBP , 0.670 },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)E4P , 0.050 },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S7P , 2.000 },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SBP , 0.300 },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATP , 0.68  },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HexP, 2.2   },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PenP, 0.25  },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_Pi , 0.0   },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_ADP, 0.0   },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v1 , 0.0   }
  }
Definition at line 286 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::defaults_C3
Initial value:
= {
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ADPG, 0.0}
  }
Definition at line 288 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ADPG, "(0.0 with C3)"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_Pi , "[CONST, NON_VECTOR] ?"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_ADP, "[CONST, NON_VECTOR] ?"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v1 , "[CONST, NON_VECTOR] ?"}
  }
Definition at line 294 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::glymaids = {}
Definition at line 290 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP, "RuBP"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGA , "PGA" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)DPGA, "DPGA"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)T3P , "T3P" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ADPG, "ADPG"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBP , "FBP" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)E4P , "E4P" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)S7P , "S7P" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SBP , "SBP" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATP , "ATP" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HexP, "HexP"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PenP, "PenP"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_Pi , "_Pi" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_ADP, "_ADP"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v1 , "_v1" }
  }
Definition at line 284 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_Pi , (STATIC_VALUE_FLAG_CONST | STATIC_VALUE_FLAG_NON_VECTOR)},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_ADP, (STATIC_VALUE_FLAG_CONST | STATIC_VALUE_FLAG_NON_VECTOR)},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)_v1 , (STATIC_VALUE_FLAG_CONST | STATIC_VALUE_FLAG_NON_VECTOR)}
  }
Definition at line 298 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_COND >::value_flags = {}
Definition at line 296 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PS, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::aliases = {}
Definition at line 178 of file enums_KE.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::all = {}
Definition at line 168 of file enums_KE.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::defaults = {}
Definition at line 172 of file enums_KE.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 174 of file enums_KE.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::docs = {}
Definition at line 180 of file enums_KE.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::glymaids = {}
Definition at line 176 of file enums_KE.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::names = {}
Definition at line 170 of file enums_KE.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::static_value_flags = {}
Definition at line 184 of file enums_KE.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_KE >::value_flags = {}
Definition at line 182 of file enums_KE.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::aliases = {}
Definition at line 292 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::all
Definition at line 282 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::defaults
Definition at line 286 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::defaults_C3
Definition at line 288 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::docs
Definition at line 294 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::glymaids
Initial value:
= {
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor1 , "Glyma.19G046800"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor2 , "Glyma.08G165500"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor3 , "Glyma.04G015900"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor5 , "Glyma.10G268500"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor7 , "Glyma.10G293500"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor13, "Glyma.19G089100"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor23, "Glyma.17G015600"}
  }
Definition at line 290 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::names
Definition at line 284 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::static_value_flags
Definition at line 298 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 296 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PS, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::aliases = {}
Definition at line 178 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::all = {}
Definition at line 168 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::defaults = {}
Definition at line 172 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 174 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::docs = {}
Definition at line 180 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 176 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::names = {}
Definition at line 170 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::static_value_flags = {}
Definition at line 184 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 182 of file enums_POOL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PS, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::aliases = {}
Definition at line 178 of file enums_RC.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::all
Definition at line 168 of file enums_RC.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::defaults
Definition at line 172 of file enums_RC.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 174 of file enums_RC.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::docs
Definition at line 180 of file enums_RC.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::glymaids = {}
Definition at line 176 of file enums_RC.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::names
Definition at line 170 of file enums_RC.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::static_value_flags = {}
Definition at line 184 of file enums_RC.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_RC >::value_flags = {}
Definition at line 182 of file enums_RC.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::aliases = {}
Definition at line 178 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::all
Initial value:
= {
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v1 ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v2 ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v3 ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v4 ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v5 ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v6 ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v7 ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v8 ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v9 ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v10,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v13,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v16,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v23,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v31,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v32,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v33,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Pi ,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v24,
    ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v25
  }
Definition at line 168 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v1 , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v2 , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v3 , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v4 , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v5 , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v6 , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v7 , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v8 , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v9 , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v10, 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v13, 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v16, 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v23, 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v31, 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v32, 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v33, 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Pi , 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v24, 0.0},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v25, 0.0}
  }
Definition at line 172 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 174 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::docs = {}
Definition at line 180 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 176 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v1 , "v1" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v2 , "v2" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v3 , "v3" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v4 , "v4" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v5 , "v5" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v6 , "v6" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v7 , "v7" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v8 , "v8" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v9 , "v9" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v10, "v10"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v13, "v13"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v16, "v16"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v23, "v23"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v31, "v31"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v32, "v32"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v33, "v33"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Pi , "Pi" },
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v24, "v24"},
    {ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v25, "v25"}
  }
Definition at line 170 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 184 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PS, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 182 of file enums_VEL.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::aliases = {}
Definition at line 330 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::all = {}
Definition at line 320 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::defaults = {}
Definition at line 324 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 326 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::docs = {}
Definition at line 332 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::glymaids = {}
Definition at line 328 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::names = {}
Definition at line 322 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 336 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_COND >::value_flags = {}
Definition at line 334 of file enums_COND.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::aliases = {}
Definition at line 330 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::all = {}
Definition at line 320 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::defaults = {}
Definition at line 324 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 326 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::docs = {}
Definition at line 332 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 328 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::names = {}
Definition at line 322 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::static_value_flags = {}
Definition at line 336 of file enums_MOD.hpp.
ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_PS_PR, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_PS_PR, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 334 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RA, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::aliases = {}
Definition at line 368 of file enums_COND.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::all = {}
Definition at line 358 of file enums_COND.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::defaults = {}
Definition at line 362 of file enums_COND.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 364 of file enums_COND.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::docs = {}
Definition at line 370 of file enums_COND.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::glymaids = {}
Definition at line 366 of file enums_COND.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::names = {}
Definition at line 360 of file enums_COND.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 374 of file enums_COND.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_COND >::value_flags = {}
Definition at line 372 of file enums_COND.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RA, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::aliases = {}
Definition at line 368 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::all = {}
Definition at line 358 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::defaults = {}
Definition at line 362 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 364 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::docs = {}
Definition at line 370 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 366 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::names = {}
Definition at line 360 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::static_value_flags = {}
Definition at line 374 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RA, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RA, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 372 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::aliases = {}
Definition at line 444 of file enums_COND.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Thion
  }
Definition at line 434 of file enums_COND.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Thion, 0.25}
  }
Definition at line 438 of file enums_COND.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 440 of file enums_COND.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Thion, "This is a wild guess"}
  }
Definition at line 446 of file enums_COND.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::glymaids = {}
Definition at line 442 of file enums_COND.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Thion, "Thion"}
  }
Definition at line 436 of file enums_COND.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 450 of file enums_COND.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_COND >::value_flags = {}
Definition at line 448 of file enums_COND.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::aliases = {}
Definition at line 254 of file enums_KE.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::all = {}
Definition at line 244 of file enums_KE.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::defaults = {}
Definition at line 248 of file enums_KE.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 250 of file enums_KE.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::docs = {}
Definition at line 256 of file enums_KE.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::glymaids = {}
Definition at line 252 of file enums_KE.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::names = {}
Definition at line 246 of file enums_KE.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::static_value_flags = {}
Definition at line 260 of file enums_KE.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_KE >::value_flags = {}
Definition at line 258 of file enums_KE.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::aliases = {}
Definition at line 444 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::all
Initial value:
= {
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX6 ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX9 ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX13,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX16,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Fd_Thio_ET     ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ThioT          ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Thio_Oxidation
  }
Definition at line 434 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX6 , 0.0  },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX9 , 0.0  },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX13, 0.0  },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX16, 0.0  },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Fd_Thio_ET     , 500.0},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ThioT          , 0.5  },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Thio_Oxidation , 0.1  }
  }
Definition at line 438 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 440 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX6 , "Taken from PS::V6"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX9 , "Taken from PS::V9"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX13, "Taken from PS::V13"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX16, "Taken from PS::V16"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Fd_Thio_ET     , "[CONST]"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ThioT          , "[CONST]"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Thio_Oxidation , "[CONST]"}
  }
Definition at line 446 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 442 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX6 , "RedoxReg_VMAX6" },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX9 , "RedoxReg_VMAX9" },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX13, "RedoxReg_VMAX13"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)RedoxReg_VMAX16, "RedoxReg_VMAX16"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Fd_Thio_ET     , "Fd_Thio_ET"     },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ThioT          , "ThioT"          },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Thio_Oxidation , "Thio_Oxidation" }
  }
Definition at line 436 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Fd_Thio_ET    , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ThioT         , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Thio_Oxidation, (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 450 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 448 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::aliases = {}
Definition at line 254 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::all
Initial value:
= {
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase_Coeff,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase0     ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase_Coeff,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase0     ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK_Coeff   ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK0        ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase_Coeff,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase0
  }
Definition at line 244 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase_Coeff, -0.305},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase0     , 0.5   },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase_Coeff, -0.3  },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase0     , 0.5   },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK_Coeff   , -0.295},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK0        , 0.5   },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase_Coeff, -0.28 },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase0     , 0.5   }
  }
Definition at line 248 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 250 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::docs = {}
Definition at line 256 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 252 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase_Coeff, "FBPase_Coeff"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase0     , "FBPase0"     },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase_Coeff, "SBPase_Coeff"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase0     , "SBPase0"     },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK_Coeff   , "PRK_Coeff"   },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK0        , "PRK0"        },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase_Coeff, "ATPase_Coeff"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase0     , "ATPase0"     }
  }
Definition at line 246 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::static_value_flags = {}
Definition at line 260 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 258 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::aliases = {}
Definition at line 254 of file enums_RC.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::all
Initial value:
= {
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Fd_Thio_ET    ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ThioT         ,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Thio_Oxidation,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Thion0
  }
Definition at line 244 of file enums_RC.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Fd_Thio_ET    , 500 },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ThioT         , 0.5 },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Thio_Oxidation, 0.1 },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Thion0        , 0.25}
  }
Definition at line 248 of file enums_RC.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 250 of file enums_RC.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Thion0, "This is a wild guess"}
  }
Definition at line 256 of file enums_RC.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::glymaids = {}
Definition at line 252 of file enums_RC.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Fd_Thio_ET    , "Fd_Thio_ET"    },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ThioT         , "ThioT"         },
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Thio_Oxidation, "Thio_Oxidation"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Thion0        , "Thion0"        }
  }
Definition at line 246 of file enums_RC.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::static_value_flags = {}
Definition at line 260 of file enums_RC.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_RC >::value_flags = {}
Definition at line 258 of file enums_RC.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::aliases = {}
Definition at line 254 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::all
Initial value:
= {
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vred,
    ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vox
  }
Definition at line 244 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vred, 0.0},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vox , 0.0}
  }
Definition at line 248 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 250 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::docs = {}
Definition at line 256 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 252 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vred, "Vred"},
    {ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vox , "Vox" }
  }
Definition at line 246 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 260 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RedoxReg, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RedoxReg, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 258 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::aliases = {}
Definition at line 406 of file enums_COND.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GAPDH ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SBPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PRK   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPGPP,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)MDH   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Thio  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Fd    ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuACT ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Coeff
  }
Definition at line 396 of file enums_COND.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GAPDH , 1.0972130787798991e-08},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBPase, 4.309416074121956e-08 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SBPase, 2.1645021645021643e-07},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PRK   , 6.097560975609756e-08 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPase, 2e-08                 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPGPP, 4.7619047619047623e-07},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)MDH   , 0.0                   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Thio  , 0.081                 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Fd    , 0.081                 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuACT , 0.0056                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Coeff , 0.3                   }
  }
Definition at line 400 of file enums_COND.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 402 of file enums_COND.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GAPDH , "[CALC] Calculated from Pool & Coeff The initial concentration of active GAPDH; *=V3; SA = 620.0, mw = 147000.0, PS::V3"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBPase, "[CALC] Calculated from Pool & Coeff The initial concentration of active FBPase; *=V6; SA = 119.0, mw = 195000.0, PS::V6"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SBPase, "[CALC] Calculated from Pool & Coeff The initial concentration of active SBPase; *=V9; SA = 70.0, mw = 66000.0, PS::V9"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PRK   , "[CALC] Calculated from Pool & Coeff The initial concentration of active PRK; *=V13; SA = 410.0, mw = 40000.0 PS::V13"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPase, "[CALC] Calculated from Pool & Coeff The initial concentration of active ATPase; *=V16; SA = 100.0, mw = 500000.0 PS::V16"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPGPP, "[CALC] Calculated from Pool & Coeff The initial concentration of active ATPGPP; *=V23; SA = 10.0, mw = 210000.0 PS::V23"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)MDH   , "The initial concentration of active MDH; Not set from Pool like previous variables"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Thio  , "The initial concentration of reduced thioredoxin; scaled by Coeff"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Fd    , "The initial concentration of reduced ferrodoxin; scaled by Coeff"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuACT , "The initial concentration of active Rubisco activase; scaled by Coeff"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Coeff , "[CONST, NON_VECTOR] Used to scale Thio, Fd, & RuACT and calculate GAPDH, FBPase, SBPase, PRK, ATPase, ATPGPP from Pool values"}
  }
Definition at line 408 of file enums_COND.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::glymaids = {}
Definition at line 404 of file enums_COND.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GAPDH , "GAPDH" },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBPase, "FBPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SBPase, "SBPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PRK   , "PRK"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPase, "ATPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPGPP, "ATPGPP"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)MDH   , "MDH"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Thio  , "Thio"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Fd    , "Fd"    },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuACT , "RuACT" },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Coeff , "Coeff" }
  }
Definition at line 398 of file enums_COND.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)GAPDH , (STATIC_VALUE_FLAG_CALC)                                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBPase, (STATIC_VALUE_FLAG_CALC)                                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SBPase, (STATIC_VALUE_FLAG_CALC)                                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PRK   , (STATIC_VALUE_FLAG_CALC)                                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPase, (STATIC_VALUE_FLAG_CALC)                                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ATPGPP, (STATIC_VALUE_FLAG_CALC)                                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Coeff , (STATIC_VALUE_FLAG_CONST | STATIC_VALUE_FLAG_NON_VECTOR)}
  }
Definition at line 412 of file enums_COND.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_COND >::value_flags = {}
Definition at line 410 of file enums_COND.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::aliases = {}
Definition at line 216 of file enums_KE.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::all
Initial value:
= {
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2FBPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2SBPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2PRK   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2ATPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2RuACT ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2GAPDH ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2MDH   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2ATPGPP,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEeFd2Thio
  }
Definition at line 206 of file enums_KE.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2FBPase, 0.311167869},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2SBPase, 0.459194309},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2PRK   , 0.677638775},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2ATPase, 1.0        },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2RuACT , 0.677638775},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2GAPDH , 0.044461692},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2MDH   , 0.044461692},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2ATPGPP, 1.0        },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEeFd2Thio, 24776.0    }
  }
Definition at line 210 of file enums_KE.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 212 of file enums_KE.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2ATPase, "[CONST] 2.177727336 was set in code, but not used"}
  }
Definition at line 218 of file enums_KE.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::glymaids = {}
Definition at line 214 of file enums_KE.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2FBPase, "KEe2FBPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2SBPase, "KEe2SBPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2PRK   , "KEe2PRK"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2ATPase, "KEe2ATPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2RuACT , "KEe2RuACT" },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2GAPDH , "KEe2GAPDH" },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2MDH   , "KEe2MDH"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2ATPGPP, "KEe2ATPGPP"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEeFd2Thio, "KEeFd2Thio"}
  }
Definition at line 208 of file enums_KE.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::SCOPED_ENUM_TYPE(Type)KEe2ATPase, (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 222 of file enums_KE.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_KE >::value_flags = {}
Definition at line 220 of file enums_KE.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::aliases = {}
Definition at line 406 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::all
Initial value:
= {
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)SC  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)fc16,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FC
  }
Definition at line 396 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)SC  , 1.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)fc16, 1.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FC  , 1.0}
  }
Definition at line 400 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 402 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)SC  , "[CONST] Used to scale PS module parameters V3, V6, V9, V13, V16, & V23 if RROEA is used without EPS"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)fc16, "[CONST] Used to scale PS module parameter V16 if RROEA is used without EPS"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FC  , "[CONST] Used to scale PS module parameters V9 & V23 if RROEA is used without EPS"}
  }
Definition at line 408 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 404 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)SC  , "SC"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)fc16, "fc16"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FC  , "FC"  }
  }
Definition at line 398 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)SC  , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)fc16, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)FC  , (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 412 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 410 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::aliases = {}
Definition at line 216 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::all
Initial value:
= {
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)GAPDH    ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK      ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPGPP   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH      ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ThioT    ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FdT      ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)RuACTT   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_GAPDH ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_FBPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_SBPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_PRK   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPGPP,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_MDH   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_GAPDH ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_FBPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_SBPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_PRK   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPase,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPGPP,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_MDH   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH_Vmax
  }
Definition at line 206 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)GAPDH    , 1.0972130787798991e-08},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase   , 4.309416074121956e-08 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase   , 2.1645021645021643e-07},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK      , 6.097560975609756e-08 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase   , 2e-08                 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPGPP   , 4.7619047619047623e-07},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH      , 6.24687656171914e-08  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ThioT    , 0.081                 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FdT      , 0.081                 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)RuACTT   , 0.0056                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_GAPDH , 620                   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_FBPase, 119                   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_SBPase, 70                    },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_PRK   , 410                   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPase, 100                   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPGPP, 10                    },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_MDH   , 184                   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_GAPDH , 147000                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_FBPase, 195000                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_SBPase, 66000                 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_PRK   , 40000                 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPase, 500000                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPGPP, 210000                },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_MDH   , 87000                 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH_Vmax , 2.0                   }
  }
Definition at line 210 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 212 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)GAPDH    , "[CALC] The initial concentration of active GAPDH; *=V3; SA = 620.0, mw = 147000.0, PS::V3"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase   , "[CALC] The initial concentration of active FBPase; *=V6; SA = 119.0, mw = 195000.0, PS::V6"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase   , "[CALC] The initial concentration of active SBPase; *=V9; SA = 70.0, mw = 66000.0, PS::V9"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK      , "[CALC] The initial concentration of active PRK; *=V13; SA = 410.0, mw = 40000.0 PS::V13"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase   , "[CALC] The initial concentration of active ATPase; *=V16; SA = 100.0, mw = 500000.0 PS::V16"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPGPP   , "[CALC] The initial concentration of active ATPGPP; *=V23; SA = 10.0, mw = 210000.0 PS::V23"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH      , "[CALC] The initial concentration of active MDH; *=MDH_Vmax; SA = 184.0, mw = 87000.0; MDH_Vmax = 2 value is assumed, but no literature to support. Needs to be fixed."},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FdT      , "Comes from BF if used with RROEA_EPS"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_GAPDH , "[CONST] Used w/ mw_GAPDH to calculate GAPDH from PS::V3; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_FBPase, "[CONST] Used w/ mw_FBPase to calculate FBPase from PS::V6; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_SBPase, "[CONST] Used w/ mw_SBPase to calculate SBPase from PS::V9; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_PRK   , "[CONST] Used w/ mw_PRK to calculate PRK from PS::V13; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPase, "[CONST] Used w/ mw_ATPase to calculate ATPase from PS::V16; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPGPP, "[CONST] Used w/ mw_ATPGPP to calculate ATPGPP from PS::V16; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_MDH   , "[CONST] Used w/ MDH_Vmax & mw_MDH to calculate MDH; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_GAPDH , "[CONST] Used w/ SA_GAPDH to calculate GAPDH from PS::V3; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_FBPase, "[CONST] Used w/ SA_FBPase to calculate FBPase from PS::V6; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_SBPase, "[CONST] Used w/ SA_SBPase to calculate SBPase from PS::V9; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_PRK   , "[CONST] Used w/ SA_PRK to calculate PRK from PS::V13; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPase, "[CONST] Used w/ SA_ATPase to calculate ATPase from PS::V16; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPGPP, "[CONST] Used w/ SA_ATPGPP to calculate ATPGPP from PS::V16; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_MDH   , "[CONST] Used w/ MDH_Vmax & SA_MDH to calculate MDH; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH_Vmax , "[CONST] This value is assumed and there is no literature about it. Need to be fixed.; Used w/ SA_MDH & mw_MDH to calculate MDH; = Vmax * 1000.0 * 60.0 / SA_var / mw_var"}
  }
Definition at line 218 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 214 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)GAPDH    , "GAPDH"    },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase   , "FBPase"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase   , "SBPase"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK      , "PRK"      },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase   , "ATPase"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPGPP   , "ATPGPP"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH      , "MDH"      },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ThioT    , "ThioT"    },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FdT      , "FdT"      },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)RuACTT   , "RuACTT"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_GAPDH , "SA_GAPDH" },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_FBPase, "SA_FBPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_SBPase, "SA_SBPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_PRK   , "SA_PRK"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPase, "SA_ATPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPGPP, "SA_ATPGPP"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_MDH   , "SA_MDH"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_GAPDH , "mw_GAPDH" },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_FBPase, "mw_FBPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_SBPase, "mw_SBPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_PRK   , "mw_PRK"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPase, "mw_ATPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPGPP, "mw_ATPGPP"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_MDH   , "mw_MDH"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH_Vmax , "MDH_Vmax" }
  }
Definition at line 208 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)GAPDH    , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)FBPase   , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SBPase   , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PRK      , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPase   , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATPGPP   , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH      , (STATIC_VALUE_FLAG_CALC) },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_GAPDH , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_FBPase, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_SBPase, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_PRK   , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPase, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_ATPGPP, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)SA_MDH   , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_GAPDH , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_FBPase, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_SBPase, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_PRK   , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPase, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_ATPGPP, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)mw_MDH   , (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)MDH_Vmax , (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 222 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 220 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::aliases = {}
Definition at line 216 of file enums_RC.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::all
Initial value:
= {
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2GAPDH   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2MDH     ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2FBPase  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2SBPase  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2PRK     ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2ATPase  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2RubACT  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2Fd      ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)keFd2Thio  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)keFd2Calvin,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2ATPGPP  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Coeff
  }
Definition at line 206 of file enums_RC.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2GAPDH   , 22.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2MDH     , 20.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2FBPase  , 1.38},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2SBPase  , 1.65},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2PRK     , 59.8},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2ATPase  , 1.0 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2RubACT  , 6.35},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2Fd      , 18.5},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)keFd2Thio  , 10  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)keFd2Calvin, 7   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2ATPGPP  , 6.3 },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Coeff      , 1.0 }
  }
Definition at line 210 of file enums_RC.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 212 of file enums_RC.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2GAPDH   , "*= Coeff / 60; The rate constant of electron transfer to GAPDH. From literature."},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2MDH     , "*= Coeff / 60; The rate constant of electront transfer to MDH, this rate is totally ASSUMED."},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2FBPase  , "*= Coeff / 60; The rate constant of electron transfer from thioredoxin to FBPase."},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2SBPase  , "*= Coeff / 60; The rate constant of electron tranfer from thioredoxin to SBPase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2PRK     , "*= Coeff / 60; The rate constant of electron transfer from thioredoxin to PRK, Phosphoribulase kinase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2ATPase  , "[CONST] The rate constant of electron transfer to ATPase; This was constant in the code"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2RubACT  , "*= Coeff / 60; The rate constant of electron transfer from thioredoxin to Rubisco activase"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2Fd      , "*= Coeff; The rate constant of electron transfer to fe"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)keFd2Thio  , "*= Coeff; The rate constant of electron transfer from fd to thio"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)keFd2Calvin, "*= Coeff; The rate constant of electron transfer from fd to Calvin cycle"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2ATPGPP  , "*= Coeff / 60; The rate constant of electron transfer to ATPGPP"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Coeff      , "[CONST] Used to scale electron transfer rate constants (with the exception of ke2ATPase)"}
  }
Definition at line 218 of file enums_RC.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::glymaids = {}
Definition at line 214 of file enums_RC.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2GAPDH   , "ke2GAPDH"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2MDH     , "ke2MDH"     },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2FBPase  , "ke2FBPase"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2SBPase  , "ke2SBPase"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2PRK     , "ke2PRK"     },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2ATPase  , "ke2ATPase"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2RubACT  , "ke2RubACT"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2Fd      , "ke2Fd"      },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)keFd2Thio  , "keFd2Thio"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)keFd2Calvin, "keFd2Calvin"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2ATPGPP  , "ke2ATPGPP"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Coeff      , "Coeff"      }
  }
Definition at line 208 of file enums_RC.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ke2ATPase, (STATIC_VALUE_FLAG_CONST)},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Coeff    , (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 222 of file enums_RC.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_RC >::value_flags = {}
Definition at line 220 of file enums_RC.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::aliases = {}
Definition at line 216 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::all
Initial value:
= {
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2GAPDH   ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2FBPase  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2SBPase  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2PRK     ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2ATPase  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2ATPGPP  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2MDH     ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2Fd      ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)veFd2Thio  ,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)veFd2Calvin,
    ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2RuACT
  }
Definition at line 206 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2GAPDH   , 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2FBPase  , 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2SBPase  , 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2PRK     , 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2ATPase  , 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2ATPGPP  , 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2MDH     , 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2Fd      , 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)veFd2Thio  , 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)veFd2Calvin, 0.0},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2RuACT   , 0.0}
  }
Definition at line 210 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 212 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::docs = {}
Definition at line 218 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 214 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2GAPDH   , "ve2GAPDH"   },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2FBPase  , "ve2FBPase"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2SBPase  , "ve2SBPase"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2PRK     , "ve2PRK"     },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2ATPase  , "ve2ATPase"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2ATPGPP  , "ve2ATPGPP"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2MDH     , "ve2MDH"     },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2Fd      , "ve2Fd"      },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)veFd2Thio  , "veFd2Thio"  },
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)veFd2Calvin, "veFd2Calvin"},
    {ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)ve2RuACT   , "ve2RuACT"   }
  }
Definition at line 208 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 222 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RROEA, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 220 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::aliases = {}
Definition at line 482 of file enums_COND.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ER  ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Eaf ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ECMR,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP
  }
Definition at line 472 of file enums_COND.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ER  , 0.20},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Eaf , 0.20},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ECMR, 0.8 },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP, 2.0 }
  }
Definition at line 476 of file enums_COND.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 478 of file enums_COND.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ER  , "The concentration of inactive ER"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Eaf , "The total concentration of E, EC, AND ECM"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ECMR, "The concentration of ECMR"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP, "The concentration of ECMR"}
  }
Definition at line 484 of file enums_COND.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::glymaids = {}
Definition at line 480 of file enums_COND.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ER  , "ER"  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Eaf , "Eaf" },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ECMR, "ECMR"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)RuBP, "RuBP"}
  }
Definition at line 474 of file enums_COND.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 488 of file enums_COND.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_COND >::value_flags = {}
Definition at line 486 of file enums_COND.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::aliases = {}
Definition at line 292 of file enums_KE.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::all = {}
Definition at line 282 of file enums_KE.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::defaults = {}
Definition at line 286 of file enums_KE.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 288 of file enums_KE.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::docs = {}
Definition at line 294 of file enums_KE.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::glymaids = {}
Definition at line 290 of file enums_KE.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::names = {}
Definition at line 284 of file enums_KE.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::static_value_flags = {}
Definition at line 298 of file enums_KE.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_KE >::value_flags = {}
Definition at line 296 of file enums_KE.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::aliases = {}
Definition at line 482 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::all
Initial value:
= {
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)activase,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)factor
  }
Definition at line 472 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)activase, 80.0},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)factor  , 1.0 }
  }
Definition at line 476 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::defaults_C3
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)activase, 80.0}
  }
Definition at line 478 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)factor, "[CONST] Factor used to scale RuACT condition parameters ER, Eaf & ECMR and RuACT pool parameter ET; was previously 0.224/0.3 in comments"}
  }
Definition at line 484 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 480 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)activase, "activase"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)factor  , "factor"  }
  }
Definition at line 474 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)factor, (STATIC_VALUE_FLAG_CONST)}
  }
Definition at line 488 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 486 of file enums_MOD.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::aliases = {}
Definition at line 292 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::all
Initial value:
= {
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ET ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)Rac,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)C  ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)O  ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)M
  }
Definition at line 282 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ET , 1.2   },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)Rac, 0.0056},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)C  , 0.012 },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)O  , 0.260 },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)M  , 5.0   }
  }
Definition at line 286 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 288 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ET , "The total concentraiton of E, ER, EC, ECM, ECMR , mM;"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)Rac, "The concentration of the activase, mM"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)C  , "mM"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)O  , "mM"}
  }
Definition at line 294 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 290 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ET , "ET" },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)Rac, "Rac"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)C  , "C"  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)O  , "O"  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)M  , "M"  }
  }
Definition at line 284 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::static_value_flags = {}
Definition at line 298 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 296 of file enums_POOL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::aliases = {}
Definition at line 292 of file enums_RC.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::all
Initial value:
= {
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k1 ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kn1,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)km1,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Ke2,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Ke3,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k6 ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kc ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ko ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k7 ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kr
  }
Definition at line 282 of file enums_RC.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k1 , 0.006  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kn1, 1.6e-3 },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)km1, 20e-6  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Ke2, 0.1    },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Ke3, 1.600  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k6 , 2.5    },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kc , 0.016  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ko , 0.448  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k7 , 10.0   },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kr , 20.0e-3}
  }
Definition at line 286 of file enums_RC.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 288 of file enums_RC.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k1 , "The rate constant of the activation of the Rubisco bound with RuBP. This step is associated with the ARubisco theVars->activase content or activity;"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kn1, "The rate constant of E inactivation by binding of RuBP; Lazar 1999, with a lifetime of 5 ns at closed reaction center"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)km1, "The michaelis menton constant for RuBP with E."},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Ke2, "Data from Mate et al 1996. Unit: micormolar; Reference needed, a guess"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Ke3, "Data from Mate et al 1996. Unit: micormolar;"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k6 , "micromolar per meter square per second, transfered to unit"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kc , "Michaelis menton constant for CO2"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ko , "Michaelis menton constant for O2"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k7 , "The rate constant for ecm to ecmr"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kr , "The apparaent michaelis menton constant for RuBP"}
  }
Definition at line 294 of file enums_RC.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::glymaids = {}
Definition at line 290 of file enums_RC.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k1 , "k1" },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kn1, "kn1"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)km1, "km1"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Ke2, "Ke2"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)Ke3, "Ke3"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k6 , "k6" },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kc , "kc" },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)ko , "ko" },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)k7 , "k7" },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kr , "kr" }
  }
Definition at line 284 of file enums_RC.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::static_value_flags = {}
Definition at line 298 of file enums_RC.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_RC >::value_flags = {}
Definition at line 296 of file enums_RC.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::aliases = {}
Definition at line 292 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::all
Initial value:
= {
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v1  ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vn1 ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v7  ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vn7 ,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v6_1,
    ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v6_2
  }
Definition at line 282 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v1  , 0.0},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vn1 , 0.0},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v7  , 0.0},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vn7 , 0.0},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v6_1, 0.0},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v6_2, 0.0}
  }
Definition at line 286 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 288 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::docs = {}
Definition at line 294 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 290 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v1  , "v1"  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vn1 , "vn1" },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v7  , "v7"  },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vn7 , "vn7" },
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v6_1, "v6_1"},
    {ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v6_2, "v6_2"}
  }
Definition at line 284 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 298 of file enums_VEL.hpp.
ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_RuACT, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_RuACT, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 296 of file enums_VEL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::aliases = {}
Definition at line 520 of file enums_COND.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)T3Pc  ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBPc  ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HexPc ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)F26BPc,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)UDPGc ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SUCP  ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SUC   ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGAc
  }
Definition at line 510 of file enums_COND.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)T3Pc  , 2.0   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBPc  , 2.0   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HexPc , 5.8   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)F26BPc, 7.8e-6},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)UDPGc , 0.57  },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SUCP  , 0.0   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SUC   , 0.0   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGAc  , 0.5   }
  }
Definition at line 514 of file enums_COND.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::defaults_C3
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)T3Pc  , 2.3   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBPc  , 2.0   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HexPc , 5.8   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)F26BPc, 7.8e-6},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)UDPGc , 0.57  },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SUCP  , 0.0   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SUC   , 0.0   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGAc  , 0.0   }
  }
Definition at line 516 of file enums_COND.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::docs = {}
Definition at line 522 of file enums_COND.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::glymaids = {}
Definition at line 518 of file enums_COND.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)T3Pc  , "T3Pc"  },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)FBPc  , "FBPc"  },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)HexPc , "HexPc" },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)F26BPc, "F26BPc"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)UDPGc , "UDPGc" },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SUCP  , "SUCP"  },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)SUC   , "SUC"   },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)PGAc  , "PGAc"  }
  }
Definition at line 512 of file enums_COND.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 526 of file enums_COND.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_COND >::value_flags = {}
Definition at line 524 of file enums_COND.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::aliases = {}
Definition at line 330 of file enums_KE.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::all = {}
Definition at line 320 of file enums_KE.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::defaults = {}
Definition at line 324 of file enums_KE.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 326 of file enums_KE.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::docs = {}
Definition at line 332 of file enums_KE.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::glymaids = {}
Definition at line 328 of file enums_KE.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::names = {}
Definition at line 322 of file enums_KE.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::static_value_flags = {}
Definition at line 336 of file enums_KE.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_KE >::value_flags = {}
Definition at line 334 of file enums_KE.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::aliases = {}
Definition at line 520 of file enums_MOD.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::all
Definition at line 510 of file enums_MOD.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::defaults
Definition at line 514 of file enums_MOD.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::defaults_C3
Definition at line 516 of file enums_MOD.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::docs
Definition at line 522 of file enums_MOD.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::glymaids
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor52, "Glyma.16G168000"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor56, "Glyma.06G323700"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor57, "Glyma.10G086600"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vfactor59, "Glyma.11G169700"}
  }
Definition at line 518 of file enums_MOD.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::names
Definition at line 512 of file enums_MOD.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)KI583      , (STATIC_VALUE_FLAG_CONST)    },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)SUCS2PS_Pic, (STATIC_VALUE_FLAG_INIT_ONCE)},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vmatpf     , (STATIC_VALUE_FLAG_CONST)    },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_51     , (STATIC_VALUE_FLAG_CONST)    },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_52     , (STATIC_VALUE_FLAG_CONST)    },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_55     , (STATIC_VALUE_FLAG_CONST)    },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_56     , (STATIC_VALUE_FLAG_CONST)    },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_57     , (STATIC_VALUE_FLAG_CONST)    },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Q10_58     , (STATIC_VALUE_FLAG_CONST)    },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)SC         , (STATIC_VALUE_FLAG_CONST)    },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)SC1        , (STATIC_VALUE_FLAG_CONST)    }
  }
Definition at line 526 of file enums_MOD.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 524 of file enums_MOD.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::aliases = {}
Definition at line 330 of file enums_POOL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::all
Initial value:
= {
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATc,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)UTc,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PTc
  }
Definition at line 320 of file enums_POOL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATc, 1.0 },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)UTc, 1.5 },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PTc, 15.0}
  }
Definition at line 324 of file enums_POOL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 326 of file enums_POOL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATc, "mM"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)UTc, "mM"}
  }
Definition at line 332 of file enums_POOL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 328 of file enums_POOL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)ATc, "ATc"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)UTc, "UTc"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::SCOPED_ENUM_TYPE(Type)PTc, "PTc"}
  }
Definition at line 322 of file enums_POOL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::static_value_flags = {}
Definition at line 336 of file enums_POOL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 334 of file enums_POOL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::aliases = {}
Definition at line 330 of file enums_RC.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::all
Definition at line 320 of file enums_RC.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::defaults
Definition at line 324 of file enums_RC.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 326 of file enums_RC.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::docs
Definition at line 332 of file enums_RC.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::glymaids = {}
Definition at line 328 of file enums_RC.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::names
Definition at line 322 of file enums_RC.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::static_value_flags = {}
Definition at line 336 of file enums_RC.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_RC >::value_flags = {}
Definition at line 334 of file enums_RC.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::aliases = {}
Definition at line 330 of file enums_VEL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::all
Initial value:
= {
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v51     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v52     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v55     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v56     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v57     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v58     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v59     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v60     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v61     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v62     ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vdhap_in,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vgap_in ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vpga_in ,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vpga_use,
    ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vatpf
  }
Definition at line 320 of file enums_VEL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v51     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v52     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v55     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v56     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v57     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v58     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v59     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v60     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v61     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v62     , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vdhap_in, 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vgap_in , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vpga_in , 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vpga_use, 0.0},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vatpf   , 0.0}
  }
Definition at line 324 of file enums_VEL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 326 of file enums_VEL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v51     , "DHAP+GAP --FBP"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v52     , "FBP --F6P + Pi"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v55     , "G1P+UTP --OPOP+UDPG"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v56     , "UDPG+F6P--SUCP + UDP"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v57     , "SUCP--Pi + SUC"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v58     , "F26BP--F6P + Pi"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v59     , "F6P + ATP --ADP + F26BP"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v60     , "ATP+UDP --UTP + ADP"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v61     , "POPO --2PO"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v62     , "SUC SINK"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vdhap_in, "DHAP IN"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vgap_in , "GAP Export from chloroplast"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vpga_in , "PGA export from chloroplast"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vpga_use, "PGA utilisation in chloroplast"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vatpf   , "ATP synthesis rate"}
  }
Definition at line 332 of file enums_VEL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 328 of file enums_VEL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v51     , "v51"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v52     , "v52"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v55     , "v55"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v56     , "v56"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v57     , "v57"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v58     , "v58"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v59     , "v59"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v60     , "v60"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v61     , "v61"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)v62     , "v62"     },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vdhap_in, "vdhap_in"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vgap_in , "vgap_in" },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vpga_in , "vpga_in" },
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vpga_use, "vpga_use"},
    {ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)vatpf   , "vatpf"   }
  }
Definition at line 322 of file enums_VEL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 336 of file enums_VEL.hpp.
ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_SUCS, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_SUCS, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 334 of file enums_VEL.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::aliases = {}
Definition at line 596 of file enums_COND.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::all = {}
Definition at line 586 of file enums_COND.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::defaults = {}
Definition at line 590 of file enums_COND.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 592 of file enums_COND.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::docs = {}
Definition at line 598 of file enums_COND.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::glymaids = {}
Definition at line 594 of file enums_COND.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::names = {}
Definition at line 588 of file enums_COND.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::static_value_flags = {}
Definition at line 602 of file enums_COND.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_COND >::value_flags = {}
Definition at line 600 of file enums_COND.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::aliases = {}
Definition at line 596 of file enums_MOD.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::all = {}
Definition at line 586 of file enums_MOD.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::defaults = {}
Definition at line 590 of file enums_MOD.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 592 of file enums_MOD.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::docs = {}
Definition at line 598 of file enums_MOD.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 594 of file enums_MOD.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::names = {}
Definition at line 588 of file enums_MOD.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::static_value_flags = {}
Definition at line 602 of file enums_MOD.hpp.
ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_trDynaPS, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_trDynaPS, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 600 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::aliases = {}
Definition at line 558 of file enums_COND.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::all
template<> const std::vector<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::all
Initial value:
= {
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Vx ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Ax ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Zx ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ABA
  }
Definition at line 548 of file enums_COND.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Vx , 160.0},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Ax , 10.0 },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Zx , 5.0  },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ABA, 1.0  }
  }
Definition at line 552 of file enums_COND.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::defaults_C3 = {}
Definition at line 554 of file enums_COND.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::docs
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Vx , "[CALC] * 0.37; The concentration of Violozanthin"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Ax , "[CALC] * 0.37; The concentration of Anthrozanthin"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Zx , "[CALC] * 0.37; The concentration of Zeaznthin"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ABA, "[CALC] The concentration of ABA"}
  }
Definition at line 560 of file enums_COND.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::glymaids = {}
Definition at line 556 of file enums_COND.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::names
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::names
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Vx , "Vx" },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Ax , "Ax" },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Zx , "Zx" },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ABA, "ABA"}
  }
Definition at line 550 of file enums_COND.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Vx , (STATIC_VALUE_FLAG_CALC)},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Ax , (STATIC_VALUE_FLAG_CALC)},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)Zx , (STATIC_VALUE_FLAG_CALC)},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::SCOPED_ENUM_TYPE(Type)ABA, (STATIC_VALUE_FLAG_CALC)}
  }
Definition at line 564 of file enums_COND.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_COND>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_COND >::value_flags = {}
Definition at line 562 of file enums_COND.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::aliases = {}
Definition at line 368 of file enums_KE.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::all
template<> const std::vector<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_KE>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::all = {}
Definition at line 358 of file enums_KE.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::defaults = {}
Definition at line 362 of file enums_KE.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_KE>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::defaults_C3 = {}
Definition at line 364 of file enums_KE.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::docs
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::docs = {}
Definition at line 370 of file enums_KE.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::glymaids = {}
Definition at line 366 of file enums_KE.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::names
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_KE>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::names = {}
Definition at line 360 of file enums_KE.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::static_value_flags = {}
Definition at line 374 of file enums_KE.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_KE>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_KE >::value_flags = {}
Definition at line 372 of file enums_KE.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::aliases = {}
Definition at line 558 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::all
template<> const std::vector<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::all
Initial value:
= {
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kva                 ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kaz                 ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kza                 ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kav                 ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vx_                 ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Ax_                 ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Zx_                 ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ABA_                ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)XanCycle2FIBF_Xstate
  }
Definition at line 548 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kva                 , 0.163},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kaz                 , 0.691},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kza                 , 0.119},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kav                 , 0.119},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vx_                 , 160.0},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Ax_                 , 10.0 },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Zx_                 , 5.0  },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ABA_                , 1.0  },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)XanCycle2FIBF_Xstate, 0.0  }
  }
Definition at line 552 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::defaults_C3 = {}
Definition at line 554 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::docs
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kva                 , "/=60; Ruth Frommolt et a; 2001; Planta"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kaz                 , "/=60; Ruth Frommolt et a; 2001; Planta"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kza                 , "/=60; Ruth Frommolt et a; 2001; Planta"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kav                 , "/=60; Ruth Frommolt et a; 2001; Planta. This is not given in the paper. Therefore, teh value is really an educated guess."},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vx_                 , "[CONST, INIT_ONCE] The concentration of Violozanthin"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Ax_                 , "[CONST, INIT_ONCE] The concentration of Anthrozanthin"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Zx_                 , "[CONST, INIT_ONCE] The concentration of Zeaznthin"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ABA_                , "[CONST, INIT_ONCE] The concentration of ABA"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)XanCycle2FIBF_Xstate, "[CALC] Calculated"}
  }
Definition at line 560 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::glymaids = {}
Definition at line 556 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::names
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::names
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kva                 , "kva"                 },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kaz                 , "kaz"                 },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kza                 , "kza"                 },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)kav                 , "kav"                 },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vx_                 , "Vx_"                 },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Ax_                 , "Ax_"                 },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Zx_                 , "Zx_"                 },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ABA_                , "ABA_"                },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)XanCycle2FIBF_Xstate, "XanCycle2FIBF_Xstate"}
  }
Definition at line 550 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::static_value_flags
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Vx_                 , (STATIC_VALUE_FLAG_CONST | STATIC_VALUE_FLAG_INIT_ONCE)},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Ax_                 , (STATIC_VALUE_FLAG_CONST | STATIC_VALUE_FLAG_INIT_ONCE)},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)Zx_                 , (STATIC_VALUE_FLAG_CONST | STATIC_VALUE_FLAG_INIT_ONCE)},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)ABA_                , (STATIC_VALUE_FLAG_CONST | STATIC_VALUE_FLAG_INIT_ONCE)},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::SCOPED_ENUM_TYPE(Type)XanCycle2FIBF_Xstate, (STATIC_VALUE_FLAG_CALC)                               }
  }
Definition at line 564 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_MOD>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_MOD >::value_flags = {}
Definition at line 562 of file enums_MOD.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::aliases = {}
Definition at line 368 of file enums_POOL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_POOL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::all = {}
Definition at line 358 of file enums_POOL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::defaults = {}
Definition at line 362 of file enums_POOL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_POOL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::defaults_C3 = {}
Definition at line 364 of file enums_POOL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::docs = {}
Definition at line 370 of file enums_POOL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::glymaids = {}
Definition at line 366 of file enums_POOL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::names
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_POOL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::names = {}
Definition at line 360 of file enums_POOL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::static_value_flags = {}
Definition at line 374 of file enums_POOL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_POOL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_POOL >::value_flags = {}
Definition at line 372 of file enums_POOL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::aliases = {}
Definition at line 368 of file enums_RC.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::all
template<> const std::vector<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::all
Initial value:
= {
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kva,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kaz,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kza,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kav
  }
Definition at line 358 of file enums_RC.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kva, 0.163},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kaz, 0.691},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kza, 0.119},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kav, 0.119}
  }
Definition at line 362 of file enums_RC.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::defaults_C3 = {}
Definition at line 364 of file enums_RC.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::docs
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kva, "Ruth Frommolt et a; 2001; Planta"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kaz, "Ruth Frommolt et a; 2001; Planta"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kza, "Ruth Frommolt et a; 2001; Planta"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kav, "Ruth Frommolt et a; 2001; Planta. This is not given in the paper. Therefore, teh value is really an educated guess."}
  }
Definition at line 370 of file enums_RC.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::glymaids = {}
Definition at line 366 of file enums_RC.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::names
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::names
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kva, "kva"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kaz, "kaz"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kza, "kza"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::SCOPED_ENUM_TYPE(Type)kav, "kav"}
  }
Definition at line 360 of file enums_RC.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::static_value_flags = {}
Definition at line 374 of file enums_RC.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_RC>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_RC >::value_flags = {}
Definition at line 372 of file enums_RC.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::aliases
template<> const std::map<std::string, typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::aliases = {}
Definition at line 368 of file enums_VEL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::all
template<> const std::vector<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::Type> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::all
Initial value:
= {
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vva   ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vaz   ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vza   ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vav   ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vvf   ,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vv2ABA,
    ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)VABAdg
  }
Definition at line 358 of file enums_VEL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::defaults
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::defaults
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vva   , 0.0},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vaz   , 0.0},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vza   , 0.0},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vav   , 0.0},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vvf   , 0.0},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vv2ABA, 0.0},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)VABAdg, 0.0}
  }
Definition at line 362 of file enums_VEL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::defaults_C3
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::Type, double> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::defaults_C3 = {}
Definition at line 364 of file enums_VEL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::docs
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::docs
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vva   , "The velocity of v to a conversion"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vaz   , "The rate of A to z"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vza   , "THe rate of z to a"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vav   , "The rate of A to V"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vvf   , "The rate of V formation"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vv2ABA, "The rate of conversion from v to ABA."},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)VABAdg, "The rate of ABA degradation"}
  }
Definition at line 370 of file enums_VEL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::glymaids
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::glymaids = {}
Definition at line 366 of file enums_VEL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::names
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::Type, std::string> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::names
Initial value:
= {
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vva   , "Vva"   },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vaz   , "Vaz"   },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vza   , "Vza"   },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vav   , "Vav"   },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vvf   , "Vvf"   },
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)Vv2ABA, "Vv2ABA"},
    {ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::SCOPED_ENUM_TYPE(Type)VABAdg, "VABAdg"}
  }
Definition at line 360 of file enums_VEL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::static_value_flags
template<> const std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::static_value_flags = {}
Definition at line 374 of file enums_VEL.hpp.
ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::value_flags
template<> std::map<typename ValueSetEnum<MODULE_XanCycle, PARAM_TYPE_VEL>::Type, int> ePhotosynthesis::ValueSetEnum< MODULE_XanCycle, PARAM_TYPE_VEL >::value_flags = {}
Definition at line 372 of file enums_VEL.hpp.
ValueSetStatic< T, U, ID, PT >::preinit_values
template<class T, class U, MODULE ID, PARAM_TYPE PT> std::map<typename ValueSetStatic<T, U, ID, PT>::EnumType, double> ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::preinit_values = {}
Definition at line 2866 of file ValueSet.hpp.
ValueSetStatic< T, U, ID, PT >::values
template<class T, class U, MODULE ID, PARAM_TYPE PT> std::map<typename ValueSetStatic<T, U, ID, PT>::EnumType, double*> ePhotosynthesis::ValueSetStatic< T, U, ID, PT >::values = {}
Definition at line 2862 of file ValueSet.hpp.
Referenced by report().