//This code is generated by generate_enum.py and should not be 
//modified directly
#pragma once

#include <map>
#include <string>
#include "enums/enums_RC.hpp"


const std::map<const BF_RC, const std::string>& BF_RC_names();
const std::map<const FI_RC, const std::string>& FI_RC_names();
const std::map<const PR_RC, const std::string>& PR_RC_names();
const std::map<const PS_RC, const std::string>& PS_RC_names();
const std::map<const RROEA_RC, const std::string>& RROEA_RC_names();
const std::map<const RedoxReg_RC, const std::string>& RedoxReg_RC_names();
const std::map<const RuACT_RC, const std::string>& RuACT_RC_names();
const std::map<const SUCS_RC, const std::string>& SUCS_RC_names();
const std::map<const XanCycle_RC, const std::string>& XanCycle_RC_names();
