// This code is generated by generate_enum.py and should not be
// modified directly
#pragma once

template<>
inline const std::vector<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type>& get_enum_skipped<typename ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::Type>() {
  return ValueSetEnum<MODULE_RROEA, PARAM_TYPE_KE>::skipped;
}
