// This code is generated by generate_enum.py and should not be
// modified directly
#pragma once

#include "enums/enums_RC.hpp"
#include "enums/enums_COND.hpp"
#include "enums/enums_POOL.hpp"
#include "enums/enums_KE.hpp"

enum EMPTY_ENUM {};

enum MODULE {
  MODULE_NONE,
  MODULE_BF,
  MODULE_FI,
  MODULE_PR,
  MODULE_PS,
  MODULE_RROEA,
  MODULE_RedoxReg,
  MODULE_RuACT,
  MODULE_SUCS,
  MODULE_XanCycle,
  MODULE_MAX,
};

// Code after this line will be preserved
template<MODULE T>
struct MODULE2Enum_COND {
public:
  typedef enum EMPTY_ENUM Type;
};
template<>
struct MODULE2Enum_COND<MODULE_BF> {
public:
  typedef enum BF_COND Type;
};

template<>
struct MODULE2Enum_COND<MODULE_FI> {
public:
  typedef enum FI_COND Type;
};

template<>
struct MODULE2Enum_COND<MODULE_PR> {
public:
  typedef enum PR_COND Type;
};

template<>
struct MODULE2Enum_COND<MODULE_PS> {
public:
  typedef enum PS_COND Type;
};

template<>
struct MODULE2Enum_COND<MODULE_RROEA> {
public:
  typedef enum RROEA_COND Type;
};

template<>
struct MODULE2Enum_COND<MODULE_RedoxReg> {
public:
  typedef enum RedoxReg_COND Type;
};

template<>
struct MODULE2Enum_COND<MODULE_RuACT> {
public:
  typedef enum RuACT_COND Type;
};

template<>
struct MODULE2Enum_COND<MODULE_SUCS> {
public:
  typedef enum SUCS_COND Type;
};

template<>
struct MODULE2Enum_COND<MODULE_XanCycle> {
public:
  typedef enum XanCycle_COND Type;
};

template<MODULE T>
struct MODULE2Enum_POOL {
public:
  typedef enum EMPTY_ENUM Type;
};
template<>
struct MODULE2Enum_POOL<MODULE_BF> {
public:
  typedef enum BF_POOL Type;
};

template<>
struct MODULE2Enum_POOL<MODULE_FI> {
public:
  typedef enum FI_POOL Type;
};

template<>
struct MODULE2Enum_POOL<MODULE_RROEA> {
public:
  typedef enum RROEA_POOL Type;
};

template<>
struct MODULE2Enum_POOL<MODULE_RuACT> {
public:
  typedef enum RuACT_POOL Type;
};

template<>
struct MODULE2Enum_POOL<MODULE_SUCS> {
public:
  typedef enum SUCS_POOL Type;
};

template<MODULE T>
struct MODULE2Enum_KE {
public:
  typedef enum EMPTY_ENUM Type;
};
template<>
struct MODULE2Enum_KE<MODULE_RROEA> {
public:
  typedef enum RROEA_KE Type;
};

template<MODULE T>
struct MODULE2Enum_RC {
public:
  typedef enum EMPTY_ENUM Type;
};
template<>
struct MODULE2Enum_RC<MODULE_BF> {
public:
  typedef enum BF_RC Type;
};

template<>
struct MODULE2Enum_RC<MODULE_FI> {
public:
  typedef enum FI_RC Type;
};

template<>
struct MODULE2Enum_RC<MODULE_PR> {
public:
  typedef enum PR_RC Type;
};

template<>
struct MODULE2Enum_RC<MODULE_PS> {
public:
  typedef enum PS_RC Type;
};

template<>
struct MODULE2Enum_RC<MODULE_RROEA> {
public:
  typedef enum RROEA_RC Type;
};

template<>
struct MODULE2Enum_RC<MODULE_RedoxReg> {
public:
  typedef enum RedoxReg_RC Type;
};

template<>
struct MODULE2Enum_RC<MODULE_RuACT> {
public:
  typedef enum RuACT_RC Type;
};

template<>
struct MODULE2Enum_RC<MODULE_SUCS> {
public:
  typedef enum SUCS_RC Type;
};

template<>
struct MODULE2Enum_RC<MODULE_XanCycle> {
public:
  typedef enum XanCycle_RC Type;
};

