ePhotosynthesis: ePhotosynthesis::modules::RedoxReg Class Reference
ePhotosynthesis::modules::RedoxReg Class Reference
#include <RedoxReg.hpp>
Static Private Member Functions
static void _Rate (const double t, const conditions::RedoxRegCondition *RedoxReg_Con, Variables *theVars)
static int RedoxReg_FPercent (N_Vector u, N_Vector f_val, void *user_data)
static void _reset (const bool noChildren=false)
Static Private Attributes
static EPHOTO_API double TIME = 0.
static EPHOTO_API std::size_t N = 1
Detailed Description
Class for RedoxReg related calculations and common variables
Definition at line 42 of file RedoxReg.hpp.
Member Function Documentation
_Rate()
void RedoxReg::_Rate (const double t, const conditions::RedoxRegCondition * RedoxReg_Con, Variables * theVars) static private
Calculate the Rates of the module based on the input condition.
Parameters
t The current timestamp
con Condition object giving the input parameters
theVars The global variables
Definition at line 48 of file RedoxReg_Rate.cpp.
References ePhotosynthesis::drivers::alloc_user_data(), ePhotosynthesis::conditions::FIBFCondition::BF_con, ePhotosynthesis::drivers::UserData::coeffs, DEBUG_INTERNAL, ePhotosynthesis::conditions::RACondition::EPS_con, ePhotosynthesis::conditions::EPSCondition::FIBF_con, N, ONE, ePhotosynthesis::conditions::RedoxRegCondition::RA_con, realtype, ePhotosynthesis::Variables::record, RedoxReg_FPercent(), ePhotosynthesis::Variables::RedoxReg_MP, RUN_CHECK, TIME, and ZERO.
_reset()
static void ePhotosynthesis::modules::RedoxReg::_reset (const bool noChildren = false) inline static private
Perform class specific class reset
Definition at line 55 of file RedoxReg.hpp.
References N, and TIME.
RedoxReg_FPercent()
int RedoxReg::RedoxReg_FPercent (N_Vector u, N_Vector f_val, void * user_data) static private
Definition at line 55 of file RedoxReg_MB.cpp.
References ePhotosynthesis::drivers::UserData::coeffs, and realtype.
Referenced by _Rate().
Field Documentation
N
std::size_t RedoxReg::N = 1 static private
Definition at line 69 of file RedoxReg.hpp.
Referenced by _Rate(), and _reset().
TIME
double RedoxReg::TIME = 0. static private
Definition at line 68 of file RedoxReg.hpp.
Referenced by _Rate(), and _reset().
The documentation for this class was generated from the following files:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/modules/RedoxReg.hpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/ini/RedoxReg_Ini.cpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/MB/RedoxReg_MB.cpp
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/src/rate/RedoxReg_Rate.cpp