% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = ALL_VALUES(pt, options)
    arguments
        pt (1,1) string
        options.trace (1,1) logical = 0
        options.include_calc (1,1) logical = 0
    end
    if (pt == "VARS")
        if options.trace
            error("trace not supported for VARS");
        end
        global AVR;
        global F;
        global R;
        global RT;
        global HPR;
        global TestO2;
        global CO2_cond;
        global GLight;
        global O2_cond;
        global PS12ratio;
        global PS2BF_ADP;
        global PS2BF_Pi;
        global TestATPCost;
        global TestCa;
        global TestLi_Wps;
        global TestLi;
        global PS2BF_Pi;
        global PS_PR_Param;
        global Tp;
        global alfa;
        global fc;
        global lightParam;
        global alpha1;
        global alpha2;
        global input_LHCI;
        global input_LHCII;
        global input_PSI;
        global input_PSIIcore;
        global PSIIantennaSize;
        global PSIantennaSize;
        global ProteinTotalRatio;
        if isempty(AVR)
            AVR = 0;
        end
        if isempty(F)
            F = 9.649 * 10^4;
        end
        if isempty(R)
            R = 8.314;
        end
        if isempty(RT)
            RT = 8.314 * 298;
        end
        if isempty(HPR)
            HPR = 0;
        end
        if isempty(TestO2)
            TestO2 = 0;
        end
        if isempty(CO2_cond)
            CO2_cond = 0;
        end
        if isempty(GLight)
            GLight = 0;
        end
        if isempty(O2_cond)
            O2_cond = 0;
        end
        if isempty(PS12ratio)
            PS12ratio = 0;
        end
        if isempty(PS2BF_ADP)
            PS2BF_ADP = 0;
        end
        if isempty(PS2BF_Pi)
            PS2BF_Pi = 0.0;
        end
        if isempty(TestATPCost)
            TestATPCost = 0;
        end
        if isempty(TestCa)
            TestCa = 0;
        end
        if isempty(TestLi_Wps)
            TestLi_Wps = 0;
        end
        if isempty(TestLi)
            TestLi = 0;
        end
        if isempty(PS2BF_Pi)
            PS2BF_Pi = 0.0;
        end
        if isempty(PS_PR_Param)
            PS_PR_Param = 0;
        end
        if isempty(Tp)
            Tp = 0;
        end
        if isempty(alfa)
            alfa = 0.85;
        end
        if isempty(fc)
            fc = 0.15;
        end
        if isempty(lightParam)
            lightParam = 0;
        end
        if isempty(alpha1)
            alpha1 = 1.0;
        end
        if isempty(alpha2)
            alpha2 = 1.0;
        end
        if isempty(input_LHCI)
            input_LHCI = 0;
        end
        if isempty(input_LHCII)
            input_LHCII = 0;
        end
        if isempty(input_PSI)
            input_PSI = 0;
        end
        if isempty(input_PSIIcore)
            input_PSIIcore = 0;
        end
        if isempty(PSIIantennaSize)
            PSIIantennaSize = 0;
        end
        if isempty(PSIantennaSize)
            PSIantennaSize = 0;
        end
        if isempty(ProteinTotalRatio)
            ProteinTotalRatio = 0;
        end
        out = [ ...
            AVR, ... 	% AVR
            F, ... 	% F
            R, ... 	% R
            RT, ... 	% RT
            HPR, ... 	% HPR
            TestO2, ... 	% O2
            CO2_cond, ... 	% CO2_cond
            GLight, ... 	% GLight
            O2_cond, ... 	% O2_cond
            PS12ratio, ... 	% PS12ratio
            PS2BF_ADP, ... 	% ADP
            PS2BF_Pi, ... 	% Pi
            TestATPCost, ... 	% TestATPCost
            TestCa, ... 	% CO2_in
            TestLi_Wps, ... 	% TestLi_Wps
            TestLi, ... 	% TestLi
            PS2BF_Pi, ... 	% PS2BF_Pi
            PS_PR_Param, ... 	% PS_PR_Param
            Tp, ... 	% Tp
            alfa, ... 	% alfa
            fc, ... 	% fc
            lightParam, ... 	% lightParam
            alpha1, ... 	% alpha1
            alpha2, ... 	% alpha2
            input_LHCI, ... 	% input_LHCI
            input_LHCII, ... 	% input_LHCII
            input_PSI, ... 	% input_PSI
            input_PSIIcore, ... 	% input_PSIIcore
            PSIIantennaSize, ... 	% PSIIantennaSize
            PSIantennaSize, ... 	% PSIantennaSize
            ProteinTotalRatio, ... 	% ProteinTotalRatio
        ];
        out = cat(2, out, ALL_VALUES("CTRL"));
        if options.include_calc
            out = cat(2, out, ALL_VALUES("CALC"));
        else
            names = get_names("ALL", "CALC");
            N_CALC = length(names);
            out = cat(2, out, zeros(1, N_CALC));
        end
    elseif (pt == "CTRL")
        if options.trace
            error("trace not supported for CTRL");
        end
        global record;
        global GP;
        global GRNC;
        global GRNT;
        global PAR_in_Wpm2;
        global VolRatioStCyto;
        global UseZaksNPQ;
        if isempty(record)
            record = 0;
        end
        if isempty(GP)
            GP = 0;
        end
        if isempty(GRNC)
            GRNC = 0;
        end
        if isempty(GRNT)
            GRNT = 0;
        end
        if isempty(PAR_in_Wpm2)
            PAR_in_Wpm2 = 0;
        end
        if isempty(VolRatioStCyto)
            VolRatioStCyto = 0;
        end
        if isempty(UseZaksNPQ)
            UseZaksNPQ = 0;
        end
        out = [ ...
            record, ... 	% record
            GP, ... 	% GP
            GRNC, ... 	% GRNC
            GRNT, ... 	% GRNT
            PAR_in_Wpm2, ... 	% PAR_in_Wpm2
            VolRatioStCyto, ... 	% VolRatioStCyto
            UseZaksNPQ, ... 	% UseZaksNPQ
        ];
    elseif (pt == "CALC")
        v6_1	 = get_var("RuACT::VEL::v6_1", options.trace, allow_missing=true);
        AVR	 = get_var("ALL::VARS::AVR", options.trace, allow_missing=true);
        v6_2	 = get_var("RuACT::VEL::v6_2", options.trace, allow_missing=true);
        vpga_use	 = get_var("SUCS::VEL::vpga_use", options.trace, allow_missing=true);
        v23	 = get_var("PS::VEL::v23", options.trace, allow_missing=true);
        v25	 = get_var("PS::VEL::v25", options.trace, allow_missing=true);
        vdhap_in	 = get_var("SUCS::VEL::vdhap_in", options.trace, allow_missing=true);
        v31	 = get_var("PS::VEL::v31", options.trace, allow_missing=true);
        v33	 = get_var("PS::VEL::v33", options.trace, allow_missing=true);
        v1in	 = get_var("PR::VEL::v1in", options.trace, allow_missing=true);
        v2out	 = get_var("PR::VEL::v2out", options.trace, allow_missing=true);
        vP680_d	 = get_var("FI::VEL::vP680_d", options.trace, allow_missing=true);
        Vbf11	 = get_var("BF::VEL::Vbf11", options.trace, allow_missing=true);
        v131	 = get_var("PR::VEL::v131", options.trace, allow_missing=true);
        vA_d	 = get_var("FI::VEL::vA_d", options.trace, allow_missing=true);
        vU_d	 = get_var("FI::VEL::vU_d", options.trace, allow_missing=true);
        vA_f	 = get_var("FI::VEL::vA_f", options.trace, allow_missing=true);
        vU_f	 = get_var("FI::VEL::vU_f", options.trace, allow_missing=true);
        GLight	 = get_var("ALL::VARS::GLight", options.trace, allow_missing=true);
        PHs	 = get_var("BF::COND::PHs", options.trace, allow_missing=true);
        Ks	 = get_var("BF::COND::Ks", options.trace, allow_missing=true);
        Mgs	 = get_var("BF::COND::Mgs", options.trace, allow_missing=true);
        Cls	 = get_var("BF::COND::Cls", options.trace, allow_missing=true);
        BFTs	 = get_var("BF::POOL::BFTs", options.trace, allow_missing=true);
        BFHs	 = get_var("BF::COND::BFHs", options.trace, allow_missing=true);
        RVA	 = get_var("BF::RC::RVA", options.trace, allow_missing=true);
        hill_psbs	 = get_var("NPQ::RC::hill_psbs", options.trace, allow_missing=true);
        PHl	 = get_var("BF::COND::PHl", options.trace, allow_missing=true);
        pK_psbs	 = get_var("NPQ::RC::pK_psbs", options.trace, allow_missing=true);
        vS3_S0	 = get_var("FI::VEL::vS3_S0", options.trace, allow_missing=true);
        CarbonRate 	= v6_1 .* AVR;
        CO2Release 	= v131 .* AVR;
        fluoresence 	= vA_f + vU_f;
        dissipation 	= vA_d + vU_d;
        Hfs 	= (10.^-PHs) .* 1000.;
        OHs 	= (10.^-14.) ./ (Hfs ./ 1000.) .* 1000.;
        BFs 	= BFHs - Hfs;
        BFns 	= BFTs - BFs;
        AfC 	= 6.022 .* (10.^ 23.);
        UnitCharge 	= 1.6 .* (10.^-19.);
        NetCharge 	= (Hfs + Ks + 2. .* Mgs - OHs - Cls - BFns) .* RVA .* AfC .* UnitCharge ./ 1000;
        expr_psbs 	= 10.^(hill_psbs .* (PHl - pK_psbs));
        out = [ ...
            v6_1 .* AVR, ... 	% Vc
            v6_2 .* AVR, ... 	% Vo
            vpga_use .* AVR, ... 	% VPGA
            (v23 - v25) .* AVR, ... 	% Vstarch
            vdhap_in .* AVR, ... 	% Vsucrose
            (v31 + v33) .* AVR, ... 	% VT3P
            v1in .* AVR, ... 	% Vt_glycerate
            v2out .* AVR, ... 	% Vt_glycolate
            vP680_d, ... 	% PSIIabs
            Vbf11, ... 	% PSIabs
            CarbonRate - CO2Release, ... 	% CO2AR
            dissipation, ... 	% dissipation
            fluoresence, ... 	% fluoresence
            1 - (fluoresence + dissipation) ./ (GLight .* 27.0 ./ 47.0), ... 	% fPSII
            2.0 .* NetCharge ./ 6.0 .* (10.^6), ... 	% MembranePotential
            expr_psbs, ... 	% expr_psbs
            1.0 ./ (1.0 + expr_psbs), ... 	% QH
            expr_psbs ./ (1.0 + expr_psbs), ... 	% one_minus_QH
            vS3_S0, ... 	% ROE
        ];
    else
        out = zeros(0, 0);
    end
end