% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = BF_VALUES(pt, options)
    arguments
        pt (1,1) string
        options.trace (1,1) logical = 0
        options.include_calc (1,1) logical = 0
    end
    if (pt == "COND")
        global BF_COND;
        out = BF_COND;
    elseif (pt == "MOD")
        global BF_MOD;
        out = BF_MOD;
        if options.include_calc
            out = cat(2, out, BF_VALUES("CALC"));
        else
            names = get_names("BF", "CALC");
            N_CALC = length(names);
            out = cat(2, out, zeros(1, N_CALC));
        end
    elseif (pt == "POOL")
        global BF_Pool;
        out = BF_Pool;
    elseif (pt == "RC")
        global BF_RC;
        out = BF_RC;
    elseif (pt == "VEL")
        global BF_Vel;
        out = BF_Vel;
    else
        out = zeros(0, 0);
    end
end