% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = CA_CM_NAMES(pt)
    global CA_CM_COND_START;
    CA_CM_COND_START = 1;
    if (pt == "PARAM_TYPES")
        out = [];
    elseif (pt == "CHILDREN")
        out = [];
    else
        out = strings(0, 0);
    end
end