% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = CM_VALUES(pt, options)
    arguments
        pt (1,1) string
        options.trace (1,1) logical = 0
        options.include_calc (1,1) logical = 0
    end
    if (pt == "MOD")
        global CM_MOD;
        out = CM_MOD;
        if options.include_calc
            out = cat(2, out, CM_VALUES("CALC"));
        else
            names = get_names("CM", "CALC");
            N_CALC = length(names);
            out = cat(2, out, zeros(1, N_CALC));
        end
    elseif (pt == "CTRL")
        if options.trace
            error("trace not supported for CTRL");
        end
        global TestSucPath;
        out = [ ...
            TestSucPath, ... 	% TestSucPath
        ];
    else
        out = zeros(0, 0);
    end
end