% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = DynaPS_NAMES(pt)
    global DynaPS_COND_START;
    DynaPS_COND_START = 96;
    if (pt == "PARAM_TYPES")
        out = [];
    elseif (pt == "CHILDREN")
        global UseZaksNPQ;
        if UseZaksNPQ == 0
            out = ["RA", "XanCycle"];
        else
            out = ["RA", "NPQ"];
        end
    else
        out = strings(0, 0);
    end
end