% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = FI_VALUES(pt, options)
    arguments
        pt (1,1) string
        options.trace (1,1) logical = 0
        options.include_calc (1,1) logical = 0
    end
    if (pt == "COND")
        global FI_COND;
        out = FI_COND;
    elseif (pt == "MOD")
        global FI_MOD;
        out = FI_MOD;
        if options.include_calc
            out = cat(2, out, FI_VALUES("CALC"));
        else
            names = get_names("FI", "CALC");
            N_CALC = length(names);
            out = cat(2, out, zeros(1, N_CALC));
        end
    elseif (pt == "POOL")
        global FI_Pool;
        out = FI_Pool;
    elseif (pt == "RC")
        global FI_RC;
        out = FI_RC;
    elseif (pt == "VEL")
        global FI_Vel;
        out = FI_Vel;
    else
        out = zeros(0, 0);
    end
end