% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = FIBF_VALUES(pt, options)
    arguments
        pt (1,1) string
        options.trace (1,1) logical = 0
        options.include_calc (1,1) logical = 0
    end
    if (pt == "COND")
        global FIBF_COND;
        out = FIBF_COND;
    elseif (pt == "MOD")
        global FIBF_MOD;
        out = FIBF_MOD;
        if options.include_calc
            out = cat(2, out, FIBF_VALUES("CALC"));
        else
            names = get_names("FIBF", "CALC");
            N_CALC = length(names);
            out = cat(2, out, zeros(1, N_CALC));
        end
    elseif (pt == "POOL")
        global FIBF_Pool;
        out = FIBF_Pool;
    elseif (pt == "RC")
        global FIBF_RC;
        out = FIBF_RC;
    else
        out = zeros(0, 0);
    end
end