% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = PR_VALUES(pt, options)
    arguments
        pt (1,1) string
        options.trace (1,1) logical = 0
        options.include_calc (1,1) logical = 0
    end
    if (pt == "COND")
        global PR_COND;
        out = PR_COND;
    elseif (pt == "MOD")
        global PR_MOD;
        out = PR_MOD;
        if options.include_calc
            out = cat(2, out, PR_VALUES("CALC"));
        else
            names = get_names("PR", "CALC");
            N_CALC = length(names);
            out = cat(2, out, zeros(1, N_CALC));
        end
    elseif (pt == "RC")
        global PR_RC;
        out = PR_RC;
    elseif (pt == "VEL")
        global PR_Vel;
        out = PR_Vel;
    elseif (pt == "CTRL")
        if options.trace
            error("trace not supported for CTRL");
        end
        global RUBISCOMETHOD;
        out = [ ...
            RUBISCOMETHOD, ... 	% RUBISCOMETHOD
        ];
    else
        out = zeros(0, 0);
    end
end