% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = PSPR_SUCS_NAMES(pt)
    global PSPR_SUCS_COND_START;
    PSPR_SUCS_COND_START = 1;
    if (pt == "PARAM_TYPES")
        out = [];
    elseif (pt == "CHILDREN")
        out = [];
    else
        out = strings(0, 0);
    end
end