% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = RA_NAMES(pt)
    global RA_COND_START;
    RA_COND_START = 92;
    if (pt == "PARAM_TYPES")
        out = [];
    elseif (pt == "CHILDREN")
        out = ["EPS", "RuACT"];
    else
        out = strings(0, 0);
    end
end