% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = RROEA_VALUES(pt, options)
    arguments
        pt (1,1) string
        options.trace (1,1) logical = 0
        options.include_calc (1,1) logical = 0
    end
    if (pt == "COND")
        global RROEA_COND;
        out = RROEA_COND;
    elseif (pt == "KE")
        global RROEA_KE;
        out = RROEA_KE;
    elseif (pt == "MOD")
        global RROEA_MOD;
        out = RROEA_MOD;
        if options.include_calc
            out = cat(2, out, RROEA_VALUES("CALC"));
        else
            names = get_names("RROEA", "CALC");
            N_CALC = length(names);
            out = cat(2, out, zeros(1, N_CALC));
        end
    elseif (pt == "POOL")
        global RROEA_Pool;
        out = RROEA_Pool;
    elseif (pt == "RC")
        global RROEA_RC;
        out = RROEA_RC;
    elseif (pt == "VEL")
        global RROEA_Vel;
        out = RROEA_Vel;
    else
        out = zeros(0, 0);
    end
end