% THIS FILE HAS BEEN GENERATED BY scripts/devtasks.py AND
% SHOULD NOT BE EDITED DIRECTLY
function out = RuACT_VALUES(pt, options)
    arguments
        pt (1,1) string
        options.trace (1,1) logical = 0
        options.include_calc (1,1) logical = 0
    end
    if (pt == "COND")
        global RuACT_COND;
        out = RuACT_COND;
    elseif (pt == "MOD")
        global RuACT_MOD;
        out = RuACT_MOD;
        if options.include_calc
            out = cat(2, out, RuACT_VALUES("CALC"));
        else
            names = get_names("RuACT", "CALC");
            N_CALC = length(names);
            out = cat(2, out, zeros(1, N_CALC));
        end
    elseif (pt == "POOL")
        global RuACT_Pool;
        out = RuACT_Pool;
    elseif (pt == "RC")
        global RuACT_RC;
        out = RuACT_RC;
    elseif (pt == "VEL")
        global RuACT_Vel;
        out = RuACT_Vel;
    else
        out = zeros(0, 0);
    end
end