ePhotosynthesis: ePhotosynthesis::vel::PRVel Class Reference
ePhotosynthesis::vel::PRVel Class Reference
#include <PRVel.hpp>
Public Member Functions
PRVel ()
PRVel (const PRVel &other)
PRVel & operator*= (const double val)
Friends
std::ostream & operator<< (std::ostream &out, const PRVel &in)
Detailed Description
Class for holding the result of the PR_Rate calculations
Definition at line 38 of file PRVel.hpp.
Constructor & Destructor Documentation
PRVel() [1/2]
ePhotosynthesis::vel::PRVel::PRVel () inline
Definition at line 41 of file PRVel.hpp.
References PRVel().
Referenced by operator*=(), operator<<, PRVel(), and PRVel().
PRVel() [2/2]
ePhotosynthesis::vel::PRVel::PRVel (const PRVel & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The PRVel object to copy
Definition at line 49 of file PRVel.hpp.
References PRVel().
Member Function Documentation
operator*=()
PRVel & ePhotosynthesis::vel::PRVel::operator*= (const double val) inline
Overload of the multiplication-equals operator to multiply all members of the class by a constant
Parameters
val The constant to multiply all the members by
Definition at line 69 of file PRVel.hpp.
References PRVel().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const PRVel & in) friend
Definition at line 32 of file PR_Vel_output.cpp.
References PRVel().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/vel/PRVel.hpp