ePhotosynthesis: ePhotosynthesis::RC::RuACTRC Class Reference
ePhotosynthesis::RC::RuACTRC Class Reference
#include <RuACTRC.hpp>
Public Member Functions
RuACTRC ()
RuACTRC (const RuACTRC &other)
RuACTRC & operator= (const RuACTRC &other)
Detailed Description
Class for RuACT_RC data
Definition at line 38 of file RuACTRC.hpp.
Constructor & Destructor Documentation
RuACTRC() [1/2]
ePhotosynthesis::RC::RuACTRC::RuACTRC () inline
Definition at line 41 of file RuACTRC.hpp.
References RuACTRC().
Referenced by operator=(), RuACTRC(), and RuACTRC().
RuACTRC() [2/2]
ePhotosynthesis::RC::RuACTRC::RuACTRC (const RuACTRC & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The RuACTRC object to copy
Definition at line 49 of file RuACTRC.hpp.
References RuACTRC().
Member Function Documentation
operator=()
RuACTRC & ePhotosynthesis::RC::RuACTRC::operator= (const RuACTRC & other) inline
Definition at line 53 of file RuACTRC.hpp.
References RuACTRC().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/rc/RuACTRC.hpp