ePhotosynthesis: ePhotosynthesis::vel::RuACTVel Class Reference
ePhotosynthesis::vel::RuACTVel Class Reference
#include <RuACTVel.hpp>
Public Member Functions
RuACTVel ()
RuACTVel (const RuACTVel &other)
Friends
std::ostream & operator<< (std::ostream &out, const RuACTVel &in)
Detailed Description
Class for holding the results of RuACT_Rate calculations
Definition at line 38 of file RuACTVel.hpp.
Constructor & Destructor Documentation
RuACTVel() [1/2]
ePhotosynthesis::vel::RuACTVel::RuACTVel () inline
Definition at line 41 of file RuACTVel.hpp.
References RuACTVel().
Referenced by operator<<, RuACTVel(), and RuACTVel().
RuACTVel() [2/2]
ePhotosynthesis::vel::RuACTVel::RuACTVel (const RuACTVel & other) inline
Copy constructor that makes a deep copy of the given object
Parameters
other The RuACTVel object to copy
Definition at line 49 of file RuACTVel.hpp.
References RuACTVel().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & out, const RuACTVel & in) friend
Definition at line 32 of file RuACT_Vel_output.cpp.
References RuACTVel().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/vel/RuACTVel.hpp