ePhotosynthesis: cxxopts::OptionSpecException Class Reference
cxxopts::OptionSpecException Class Reference
#include <cxxopts.hpp>
Public Member Functions
OptionSpecException (const std::string &message)
Public Member Functions inherited from cxxopts::OptionException
OptionException (std::string message)
CXXOPTS_NODISCARD const char * what () const noexcept override
Detailed Description
Definition at line 357 of file cxxopts.hpp.
Constructor & Destructor Documentation
OptionSpecException()
cxxopts::OptionSpecException::OptionSpecException (const std::string & message) inline explicit
Definition at line 361 of file cxxopts.hpp.
References cxxopts::OptionException::OptionException().
Referenced by cxxopts::invalid_option_format_error::invalid_option_format_error(), and cxxopts::option_exists_error::option_exists_error().
The documentation for this class was generated from the following file:
/home/runner/work/ePhotosynthesis_C/ePhotosynthesis_C/include/cxxopts.hpp