ePhotosynthesis: cxxopts::values Namespace Reference
cxxopts::values Namespace Reference
Namespaces
namespace detail
Data Structures
class abstract_value
class standard_value
class standard_value< bool >
struct type_is_container
struct type_is_container< std::vector< T > >
Functions
template<typename R, typename T>
void checked_negate (R &r, T &&t, const std::string &, std::true_type)
template<typename R, typename T>
void checked_negate (R &, T &&, const std::string &text, std::false_type)
template<typename T>
void integer_parser (const std::string &text, T &value)
template<typename T>
void stringstream_parser (const std::string &text, T &value)
void parse_value (const std::string &text, uint8_t &value)
void parse_value (const std::string &text, int8_t &value)
void parse_value (const std::string &text, uint16_t &value)
void parse_value (const std::string &text, int16_t &value)
void parse_value (const std::string &text, uint32_t &value)
void parse_value (const std::string &text, int32_t &value)
void parse_value (const std::string &text, uint64_t &value)
void parse_value (const std::string &text, int64_t &value)
void parse_value (const std::string &text, bool &value)
void parse_value (const std::string &text, std::string &value)
template<typename T>
void parse_value (const std::string &text, T &value)
template<typename T>
void parse_value (const std::string &text, std::vector< T > &value)
void parse_value (const std::string &text, char &c)
Function Documentation
checked_negate() [1/2]
template<typename R, typename T> void cxxopts::values::checked_negate (R & , T && , const std::string & text, std::false_type)
Definition at line 585 of file cxxopts.hpp.
References cxxopts::throw_or_mimic().
checked_negate() [2/2]
template<typename R, typename T> void cxxopts::values::checked_negate (R & r, T && t, const std::string & , std::true_type)
Definition at line 575 of file cxxopts.hpp.
Referenced by integer_parser().
integer_parser()
template<typename T> void cxxopts::values::integer_parser (const std::string & text, T & value)
Definition at line 592 of file cxxopts.hpp.
References cxxopts::values::detail::check_signed_range(), checked_negate(), cxxopts::throw_or_mimic(), and cxxopts::value().
Referenced by parse_value(), parse_value(), parse_value(), parse_value(), parse_value(), parse_value(), parse_value(), and parse_value().
parse_value() [1/13]
void cxxopts::values::parse_value (const std::string & text, bool & value) inline
Definition at line 728 of file cxxopts.hpp.
References cxxopts::throw_or_mimic(), and cxxopts::value().
parse_value() [2/13]
void cxxopts::values::parse_value (const std::string & text, char & c) inline
Definition at line 790 of file cxxopts.hpp.
References cxxopts::throw_or_mimic().
parse_value() [3/13]
void cxxopts::values::parse_value (const std::string & text, int16_t & value) inline
Definition at line 693 of file cxxopts.hpp.
References integer_parser(), and cxxopts::value().
parse_value() [4/13]
void cxxopts::values::parse_value (const std::string & text, int32_t & value) inline
Definition at line 707 of file cxxopts.hpp.
References integer_parser(), and cxxopts::value().
parse_value() [5/13]
void cxxopts::values::parse_value (const std::string & text, int64_t & value) inline
Definition at line 721 of file cxxopts.hpp.
References integer_parser(), and cxxopts::value().
parse_value() [6/13]
void cxxopts::values::parse_value (const std::string & text, int8_t & value) inline
Definition at line 679 of file cxxopts.hpp.
References integer_parser(), and cxxopts::value().
parse_value() [7/13]
void cxxopts::values::parse_value (const std::string & text, std::string & value) inline
Definition at line 751 of file cxxopts.hpp.
References cxxopts::value().
parse_value() [8/13]
template<typename T> void cxxopts::values::parse_value (const std::string & text, std::vector< T > & value)
Definition at line 767 of file cxxopts.hpp.
References CXXOPTS_VECTOR_DELIMITER, parse_value(), and cxxopts::value().
parse_value() [9/13]
template<typename T> void cxxopts::values::parse_value (const std::string & text, T & value)
Definition at line 761 of file cxxopts.hpp.
References stringstream_parser(), and cxxopts::value().
parse_value() [10/13]
void cxxopts::values::parse_value (const std::string & text, uint16_t & value) inline
Definition at line 686 of file cxxopts.hpp.
References integer_parser(), and cxxopts::value().
parse_value() [11/13]
void cxxopts::values::parse_value (const std::string & text, uint32_t & value) inline
Definition at line 700 of file cxxopts.hpp.
References integer_parser(), and cxxopts::value().
parse_value() [12/13]
void cxxopts::values::parse_value (const std::string & text, uint64_t & value) inline
Definition at line 714 of file cxxopts.hpp.
References integer_parser(), and cxxopts::value().
parse_value() [13/13]
void cxxopts::values::parse_value (const std::string & text, uint8_t & value) inline
Definition at line 672 of file cxxopts.hpp.
References integer_parser(), and cxxopts::value().
Referenced by cxxopts::KeyValue::as(), cxxopts::values::abstract_value< T >::parse(), cxxopts::values::abstract_value< T >::parse(), and parse_value().
stringstream_parser()
template<typename T> void cxxopts::values::stringstream_parser (const std::string & text, T & value)
Definition at line 661 of file cxxopts.hpp.
References cxxopts::throw_or_mimic(), and cxxopts::value().
Referenced by parse_value().