name: Test of conda recipe build
'on':
  push:
    branches-ignore:
     - gh-pages
    tags:
     - '*'
  schedule:
  - cron: 0 10 * * 1
jobs:
  build_conda_recipe:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        sundials-version: [latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true

      ###################################
      # CONDA SETUP
      ###################################
      - name: Set up MSVC Compiler on windows
        uses: ilammy/msvc-dev-cmd@v1
        if: matrix.os == 'windows-latest'
      - name: Set up miniconda test environment (W/O MPI)
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ""
          auto-activate-base: true
          auto-update-conda: true
          channels: conda-forge
          channel-priority: strict
          miniforge-variant: Miniforge3
          miniforge-version: latest
          use-mamba: true
          mamba-version: "2.0.5"
          # mamba-version: "1.5.10"
          conda-remove-defaults: true
      - name: Install conda-build
        run: |
          mamba info
          mamba list
          mamba install conda-build py-lief=0.14 cmake -y
      - name: Check mamba installation
        run: |
          mamba info
          mamba list
      - name: Build conda recipe
        run: |
          conda-build --use-local --no-anaconda-upload --output-folder ./local_channel/ recipe/
      - name: Install from local conda recipe
        run: |
          mamba install -c ./local_channel ePhotosynthesis
          mamba list

      ###################################
      # Test
      ###################################
      - name: Test ePhoto executable install by conda
        run: |
          ePhoto -d 4 --evn tests/data/InputEvn.txt --grn tests/data/InputGRNC.txt --enzyme tests/data/InputEnzyme.txt --atpcost tests/data/InputATPCost.txt --output output_conda.data
      - name: Check output from ePhoto executable install by conda
        run: |
          python scripts/devtasks.py compare-files output_conda.data --driver 4
      - name: Build example against the installed library using CMake
        run: |
          mamba list
          cd tests/external
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: Test built example executable
        run: |
          cd tests
          ./external/build/example
      - name: Check built example executable output
        run: |
          python scripts/devtasks.py compare-files tests/example_output.data --driver 4
