ePhotosynthesis: ePhotosynthesis::utils Namespace Reference
ePhotosynthesis::utils Namespace Reference
Functions
template<>
const std::map< DriverType, std::string > & get_enum_names< DriverType > ()
EPHOTO_API std::string str_toupper (const std::string &inStr)
EPHOTO_API std::string str_tolower (const std::string &inStr)
EPHOTO_API std::vector< std::string > str_split (const std::string &inStr, const char sep)
EPHOTO_API std::vector< std::string > str_split_whitespace (const std::string &inStr)
EPHOTO_API bool str_startswith (std::string const &value, std::string const &prefix)
EPHOTO_API bool str_endswith (std::string const &value, std::string const &suffix)
EPHOTO_API std::string str_getTabs (const uint tab=0)
template<typename T>
std::ostream & print_string (const std::vector< T > &x, std::ostream &out, const unsigned int tab=0)
template<typename T1, typename T2>
std::ostream & print_string (const std::map< T1, T2 > &x, std::ostream &out, const unsigned int tab=0)
template<typename T>
std::string to_string (const T &x, typename std::enable_if<!std::is_same< T, const char[]>::value >::type *=0)
std::string to_string (const std::string &x)
std::string to_string (const char *x)
template<size_t N>
std::string to_string (const char x[N])
template<typename T>
std::string to_string (const std::vector< T > &x, const unsigned int tab=0)
template<typename T1, typename T2>
std::string to_string (const std::map< T1, T2 > &x, const unsigned int tab=0)
bool values_equal (const double &a, const double &b)
double extract_value (const double &x)
double extract_value (const double *x)
template<typename T>
bool contains (const std::vector< T > &v, const T &x)
template<typename T1, typename T2>
bool contains (const std::map< T1, T2 > &v, const T1 &x)
template<typename T1, typename T2>
bool contains (const std::map< T1, T2 > &v, const T2 &x)
template<typename T1, typename T2>
void copyInto (std::map< T1, T2 > &dst, const std::map< T1, T2 > &src)
template<typename T>
const std::map< T, std::string > & get_enum_names ()
template<>
EPHOTO_API const std::map< MODULE, std::string > & get_enum_names< MODULE > ()
template<>
EPHOTO_API const std::map< PARAM_TYPE, std::string > & get_enum_names< PARAM_TYPE > ()
template<typename T1>
bool enum_key_search (const std::map< T1, std::string > map, const T1 &key, std::string &val)
template<typename T1>
bool enum_value_search (const std::map< T1, std::string > map, const std::string &val, T1 &key, bool allow_anycase=false, std::string prefix="", std::string suffix="")
template<typename T>
T enum_string2key (const std::string &val)
template<typename T>
std::string enum_key2string (const T &key)
template<typename Tenum, typename Tval>
std::map< Tenum, Tval > readEnumFile (const std::string &filename)
template<typename T1, typename T2>
T1 max_enum_value (const std::map< T1, T2 > map)
template<typename T, typename Tflag>
std::string strBitFlags (const T &flag, const std::map< Tflag, std::string > &map, const std::string &prefix="", const std::string &suffix="\n")
Function Documentation
contains() [1/3]
template<typename T1, typename T2> bool ePhotosynthesis::utils::contains (const std::map< T1, T2 > & v, const T1 & x)
Definition at line 104 of file enums_utils.hpp.
contains() [2/3]
template<typename T1, typename T2> bool ePhotosynthesis::utils::contains (const std::map< T1, T2 > & v, const T2 & x)
Definition at line 109 of file enums_utils.hpp.
contains() [3/3]
template<typename T> bool ePhotosynthesis::utils::contains (const std::vector< T > & v, const T & x)
Definition at line 96 of file enums_utils.hpp.
copyInto()
template<typename T1, typename T2> void ePhotosynthesis::utils::copyInto (std::map< T1, T2 > & dst, const std::map< T1, T2 > & src)
Definition at line 117 of file enums_utils.hpp.
enum_key2string()
template<typename T> std::string ePhotosynthesis::utils::enum_key2string (const T & key)
Definition at line 186 of file enums_utils.hpp.
References enum_key_search(), and get_enum_names().
Referenced by ePhotosynthesis::Variables::getControlDocs(), ePhotosynthesis::Variables::getControlVar(), ePhotosynthesis::Variables::getDefaultControlVar(), ePhotosynthesis::ValueSetBase< T, U, ID, PT >::getNameWithPrefix(), ePhotosynthesis::Variables::getValueSet(), ePhotosynthesis::Variables::getValueSetClass(), ePhotosynthesis::Variables::initDefaults(), ePhotosynthesis::Variables::parseVar(), ePhotosynthesis::Variables::setControlVar(), ePhotosynthesis::Variables::setDefaultControlVar(), and ePhotosynthesis::Variables::updateParam().
enum_key_search()
template<typename T1> bool ePhotosynthesis::utils::enum_key_search (const std::map< T1, std::string > map, const T1 & key, std::string & val)
Definition at line 144 of file enums_utils.hpp.
Referenced by enum_key2string().
enum_string2key()
template<typename T> T ePhotosynthesis::utils::enum_string2key (const std::string & val)
Definition at line 177 of file enums_utils.hpp.
References enum_value_search(), and get_enum_names().
Referenced by ePhotosynthesis::Variables::parseVar(), and readEnumFile().
enum_value_search()
template<typename T1> bool ePhotosynthesis::utils::enum_value_search (const std::map< T1, std::string > map, const std::string & val, T1 & key, bool allow_anycase = false, std::string prefix = "", std::string suffix = "")
Definition at line 158 of file enums_utils.hpp.
References str_toupper().
Referenced by enum_string2key().
extract_value() [1/2]
double ePhotosynthesis::utils::extract_value (const double & x)
Definition at line 91 of file enums_utils.cpp.
extract_value() [2/2]
double ePhotosynthesis::utils::extract_value (const double * x)
Definition at line 92 of file enums_utils.cpp.
get_enum_names()
template<typename T> const std::map< T, std::string > & ePhotosynthesis::utils::get_enum_names ()
Definition at line 133 of file enums_utils.hpp.
Referenced by enum_key2string(), and enum_string2key().
get_enum_names< DriverType >()
template<> const std::map< DriverType, std::string > & ePhotosynthesis::utils::get_enum_names< DriverType > () inline
Definition at line 105 of file driver.hpp.
get_enum_names< MODULE >()
template<> const std::map< MODULE, std::string > & ePhotosynthesis::utils::get_enum_names< MODULE > ()
Definition at line 98 of file enums_utils.cpp.
References ADD_MODULE, EXPAND, FOR_EACH_COMMA, and MEMBER_NAMES_COMPLETE_MODULE.
Referenced by ePhotosynthesis::drivers::DriverBase< T, M >::error_prefix(), ePhotosynthesis::ValueSetEnum< M, PT >::error_prefix(), and ePhotosynthesis::ValueSetBase< T, U, ID, PT >::field_width_value_map().
get_enum_names< PARAM_TYPE >()
template<> const std::map< PARAM_TYPE, std::string > & ePhotosynthesis::utils::get_enum_names< PARAM_TYPE > ()
Definition at line 108 of file enums_utils.cpp.
References ADD_PARAM_TYPE, EXPAND, FOR_EACH_COMMA, and MEMBER_NAMES_COMPLETE_PARAM.
Referenced by ePhotosynthesis::ValueSetEnum< M, PT >::error_prefix(), and ePhotosynthesis::ValueSetBase< T, U, ID, PT >::field_width_value_map().
max_enum_value()
template<typename T1, typename T2> T1 ePhotosynthesis::utils::max_enum_value (const std::map< T1, T2 > map)
Definition at line 224 of file enums_utils.hpp.
print_string() [1/2]
template<typename T1, typename T2> std::ostream & ePhotosynthesis::utils::print_string (const std::map< T1, T2 > & x, std::ostream & out, const unsigned int tab = 0)
Definition at line 46 of file enums_utils.hpp.
References str_getTabs().
print_string() [2/2]
template<typename T> std::ostream & ePhotosynthesis::utils::print_string (const std::vector< T > & x, std::ostream & out, const unsigned int tab = 0)
Definition at line 32 of file enums_utils.hpp.
References str_getTabs().
Referenced by ePhotosynthesis::operator<<(), ePhotosynthesis::operator<<(), to_string(), and to_string().
readEnumFile()
template<typename Tenum, typename Tval> std::map< Tenum, Tval > ePhotosynthesis::utils::readEnumFile (const std::string & filename)
Definition at line 197 of file enums_utils.hpp.
References enum_string2key(), and str_split_whitespace().
Referenced by ePhotosynthesis::ValueSetBase< T, U, ID, PT >::copy_value_map().
str_endswith()
bool ePhotosynthesis::utils::str_endswith (std::string const & value, std::string const & suffix)
Definition at line 65 of file enums_utils.cpp.
Referenced by ePhotosynthesis::Variables::updateParam().
str_getTabs()
std::string ePhotosynthesis::utils::str_getTabs (const uint tab = 0)
Definition at line 55 of file enums_utils.cpp.
Referenced by print_string(), and print_string().
str_split()
std::vector< std::string > ePhotosynthesis::utils::str_split (const std::string & inStr, const char sep)
Definition at line 23 of file enums_utils.cpp.
str_split_whitespace()
std::vector< std::string > ePhotosynthesis::utils::str_split_whitespace (const std::string & inStr)
Definition at line 34 of file enums_utils.cpp.
Referenced by readEnumFile(), ePhotosynthesis::readFile(), and ePhotosynthesis::readFile().
str_startswith()
bool ePhotosynthesis::utils::str_startswith (std::string const & value, std::string const & prefix)
Definition at line 60 of file enums_utils.cpp.
str_tolower()
std::string ePhotosynthesis::utils::str_tolower (const std::string & inStr)
Definition at line 48 of file enums_utils.cpp.
str_toupper()
std::string ePhotosynthesis::utils::str_toupper (const std::string & inStr)
Definition at line 41 of file enums_utils.cpp.
Referenced by enum_value_search().
strBitFlags()
template<typename T, typename Tflag> std::string ePhotosynthesis::utils::strBitFlags (const T & flag, const std::map< Tflag, std::string > & map, const std::string & prefix = "", const std::string & suffix = "\n")
Definition at line 230 of file enums_utils.hpp.
to_string() [1/6]
std::string ePhotosynthesis::utils::to_string (const char * x)
Definition at line 73 of file enums_utils.cpp.
to_string() [2/6]
template<size_t N> std::string ePhotosynthesis::utils::to_string (const char x[N]) inline
Definition at line 67 of file enums_utils.hpp.
to_string() [3/6]
template<typename T1, typename T2> std::string ePhotosynthesis::utils::to_string (const std::map< T1, T2 > & x, const unsigned int tab = 0)
Definition at line 78 of file enums_utils.hpp.
References print_string().
to_string() [4/6]
std::string ePhotosynthesis::utils::to_string (const std::string & x)
Definition at line 70 of file enums_utils.cpp.
to_string() [5/6]
template<typename T> std::string ePhotosynthesis::utils::to_string (const std::vector< T > & x, const unsigned int tab = 0)
Definition at line 71 of file enums_utils.hpp.
References print_string().
to_string() [6/6]
template<typename T> std::string ePhotosynthesis::utils::to_string (const T & x, typename std::enable_if<!std::is_same< T, const char[]>::value >::type * = 0)
Definition at line 58 of file enums_utils.hpp.
values_equal()
bool ePhotosynthesis::utils::values_equal (const double & a, const double & b)
Definition at line 80 of file enums_utils.cpp.
References COMPARE_ABSOLUTE_EPSILON, and COMPARE_RELATIVE_EPSILON.
Referenced by ePhotosynthesis::Value< BaseClass >::operator==, and ePhotosynthesis::Value< BaseClass >::operator==.